### ISSUE TITLE
Тесты не проходят.

### ISSUE THREAD

**Issue by aios** [LaravelRUS/SleepingOwlAdmin#1007]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/da56b14cb8c3bef98b9c9c51e9bc57c1c5f8958f/src/Display/Column/Filter/Range.php#L103

**Comment by ahurov** [comment]
Это с php 7.0
Laravel последней версии 5.8 уже требует php >= 7.1.3
Потому предлагаю и нам так сделать, travis-ci файл обновил в этом PR #1008
