### ISSUE TITLE
how to add custom js file in form

### ISSUE THREAD

**Issue by fatihcelen** [LaravelRUS/SleepingOwlAdmin#102]
previous verison i saw AssetManager but this version has not this Class.

How am i add custom js in a form page.

**Comment by butschster** [comment]
You can extend form field asset package in the file `app/Admin/bootstrap.php`

For example
```php
PackageManager::load(SleepingOwl\Admin\Form\Element\Date::class)
   ->js('custom-js', resources_url('js/custom.js'));
```

**Comment by fatihcelen** [comment]
Thanks @butschster i try this, it works. 

but i wonder how i add custom js in form which created for a table, not form element..

i have activity table and i needed some javascript code in this form for crud operations..

>  AdminForm::panel()->addBody([])->addScript('js/custom.js')

**Comment by butschster** [comment]
```php
AdminFormElement::text('title', 'Title')
     ->required()
     ->addStyle('test.css', asset('test.css'))
     ->addScript('test.js', asset('test.js'))
     ->withPackage('jquery', 'other_package_name')
```

**Comment by butschster** [comment]
```php
AdminDisplay::table()
     ->addStyle('test.css', asset('test.css'))
     ->addScript('test.js', asset('test.js'))
     ->withPackage('jquery', 'other_package_name')

AdminForm::form()
     ->addStyle('test.css', asset('test.css'))
     ->addScript('test.js', asset('test.js'))
     ->withPackage('jquery', 'other_package_name')
```

**Comment by fatihcelen** [comment]
Hi @butschster 

Thanks you for the update.

I tried your solution but I have a new problem.

I'm trying to get the SEO URLs, from the article title, like in WordPress.

I use this plugin https://github.com/riverside/friendurl to obtain the URL.

When I wrote my own JavaScript code does not see the above plug-in function. I think again of the load borne by jQuery library code added later.

Is it possible that we can provide the most recent coming in later added files

<a href="http://hizliresim.com/AJn97q"><img src="http://i.hizliresim.com/AJn97q.jpg"></a>

**Comment by butschster** [comment]
Hi, @fatihcelen

Try this solution
```php
AdminForm::form()
     ->addScript('test.js', asset('test.js'), 'admin-default')
```

**Comment by fatihcelen** [comment]
I am update composer, and try this.. but give an error.

Argument 3 passed to SleepingOwl\Admin\Form\FormDefault::addScript() must be of the type array, string given,

**Comment by butschster** [comment]
`>addScript('test.js', asset('test.js'), ['admin-default'])`

**Comment by fatihcelen** [comment]
Thanks you @butschster  it works..
