### ISSUE TITLE
required

### ISSUE THREAD

**Issue by mazhurnyy** [LaravelRUS/SleepingOwlAdmin#1037]
*ru*
## Версия в композере
dev-bs4
## Предложение
Просьба добавить к методу required() параметр true / false
по аналогии с setReadOnly(), setVisibilityCondition()

**Comment by daaner** [comment]
А чтоб не поломать обратку как ты представляешь давать значение по умолчанию?
если спасет - юзай `->setDisplayed(bool|Closure $displayed)` там булевое значение. Или покажет или спрячет

**Comment by mazhurnyy** [comment]
поставить значение по умолчанию true в методе, если не установлено (как сейчас), но с возможность передавать false
скрыть поле не проблема, 
возникла ситуация, когда по условию необходимо поле или обязательно к заполнения или нет
если сложно буду искать другие варианты, но думаю может пригодиться многим

**Comment by daaner** [comment]
Если по умолчанию труе, то если не указать - все формы будут только для чтения. Кто-то обновится и будет расставлять везде фалсе. Не целесообразно. Еще варианты есть?

**Comment by daaner** [comment]
Похоже я придумал. Я добавлю вуе валидацию прям при вводе, там будет возможность выставлять труе или  фолс, это решит твою проблему. И не поламает то, что уже у кого-то есть. Ожидай

**Comment by daaner** [comment]
с валидацией не сложилось, сообщество отговорило. Пока применение такого условия не предвидится
