### ISSUE TITLE
summernote - перекрывает поле select

### ISSUE THREAD

**Issue by mazhurnyy** [LaravelRUS/SleepingOwlAdmin#1038]
*ru*
## Версия в композере
bs4
## ошибка
toolbar summernote - перекрывает раскрытое поле select
https://user-images.githubusercontent.com/5727700/63096391-7b77b680-bf76-11e9-91f2-5a1303c30178.jpg

**Comment by daaner** [comment]
Поправлено, не забываем обновить ассеты
