### ISSUE TITLE
How to create CKeditor config settings per instance. 

### ISSUE THREAD

**Issue by 7immy** [LaravelRUS/SleepingOwlAdmin#107]
Hello all,
I wanted to ask if anyone knew how to add config settings to the CKeditor per instance. Currently I'm doing something like this:

    AdminFormElement::view('admin.ckeditor.config')
    AdminFormElement::ckeditor('page_content', 'Content')

config1.blade.php

    <script>
        // ckeditor settings are added here
    </script>

I know we can config CKeditor globally in the main sleeping_owl.php config file but I would like to customise the ckeditor differently for each instance.

**Comment by butschster** [comment]
Try to use

```php
AdminFormElement::ckeditor('page_content', 'Content')->setParameters([
   ....
])
```

**Comment by 7immy** [comment]
I tried something simple like this but nothing happened:
`AdminFormElement::ckeditor('page_content', 'Content')->setParameters(['height'=> '500px'])`

**Comment by 7immy** [comment]
For anyone wondering you need to use  `AdminFormElement::wysiwyg` NOT `AdminFormElement::wysiwyg` to ge able to use the 'setParameters' method.

    AdminFormElement::wysiwyg('page_content', 'Page Content')
        ->setParameters([
            "toolbar" => [
            "name" => "basicstyles",
            "items" => [ "Bold", "Italic", "-", "RemoveFormat" ]
    ]])

**Comment by butschster** [comment]
!

**Comment by 7immy** [comment]
Sorry. I've just realised that while I've worked out how to set parameters per instance I still can't have multiple instances of `AdminFormElement::wysiwyg` in the same form.
