### ISSUE TITLE
Searching in datatablesAsync

### ISSUE THREAD

**Issue by JShantal** [LaravelRUS/SleepingOwlAdmin#108]
When using datatables, search in item list by title (first) column works well by default, but when using datatablesAsync, there is no search results.

**Comment by 7immy** [comment]
Same here. Datatable column filters works well. DatatablesAsync column filters do not. Also the to right search box fails too. Any search I make returns zero results on the table.

**Comment by Fessnik** [comment]
+1

**Comment by bmn** [comment]
The top right search box seems to only search certain types of AdminColumn - it searches text, but not link and email.

**Comment by xcaptain** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/DisplayDatatablesAsync.php#L74
text, link, email can be searched
