### ISSUE TITLE
 There are no commands defined in the "sleepingowl" namespace.

### ISSUE THREAD

**Issue by Flancy** [LaravelRUS/SleepingOwlAdmin#111]
Устанавливаю SleepingOwl по инструкции, но на стадии команды установки 
"php artisan sleepingowl:install", выдает ошибку -
[Symfony\Component\Console\Exception\CommandNotFoundException]  
There are no commands defined in the "sleepingowl" namespace.

В config/app.php прописал в 'providers' SleepingOwl\Admin\Providers\SleepingOwlServiceProvider::class,
Laravel 5.2.30.
В чем проблема?

**Comment by Flancy** [comment]
Решил так - полное удаление папки vendor и composer update. Хотя когда ставил на чистый проект larave new blog, выдавало эту ошибку.

**Comment by Stereotip22** [comment]
еще проще - composer update

**Comment by xvladxtremal** [comment]
Никак не могу решить эту проблему, не видит namespace admin, sleepingowl. Пробовал разные версии 4.60.13, 5.1.13, 4.*@dev. Сносил vendor.

> [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "sleepingowl" namespace.
Прописал ServiceProviders

**Comment by xvladxtremal** [comment]
Решил проблему добавив в app\console\kernel.php

    protected $commands = [
        \SleepingOwl\Admin\Commands\InstallCommand::class,
        \SleepingOwl\Admin\Commands\UserManagerCommand::class,
        \SleepingOwl\Admin\Commands\SectionGenerate::class,
        \SleepingOwl\Admin\Commands\SectionMake::class,
        \SleepingOwl\Admin\Commands\SectionProvider::class,
];
