### ISSUE TITLE
Add custom JS or CSS when using own view

### ISSUE THREAD

**Issue by JShantal** [LaravelRUS/SleepingOwlAdmin#112]
Is it possible to add custom js or css to head when using 
`$view = View::make('admin.edit');
return AdminSection::view($view);`
?

**Comment by butschster** [comment]
```php
use Meta;

...

...

Meta::AddJs('customScripts', 'asset('....')', ['libraries']);
```

**Comment by JShantal** [comment]
I didn't know how to add multiple JS files using Meta or Assets. If someone will have same problem: if you use Meta::AddJs, name where 'customScripts' is placed must be unique for each Meta::AddJs.
For example: if you'll use 
`Meta::AddJs('customScripts','123.js');
Meta::AddJs('customScripts','345.js');`
as output would be last AddJs.
If you'll use
`Meta::AddJs('customScripts','123.js');
Meta::AddJs('customScripts2','345.js');`
as output would be both.
