### ISSUE TITLE
setDefaultValue() не срабатывает

### ISSUE THREAD

**Issue by Flancy** [LaravelRUS/SleepingOwlAdmin#113]
$model->onCreateAndEdit(function() {
        $url = generateUrl();
        return $form = AdminForm::panel()->addBody(
            AdminFormElement::text('email', 'Email')->required()->unique(),
            AdminFormElement::text('url', 'Url')->required()->unique()->setDefaultValue('string')
        );
        return $form;
    });
В value ничего не попадает

**Comment by NightDiRaven** [comment]
Начиная с этой версии, я писал об этом, но пока не пофиксили https://github.com/LaravelRUS/SleepingOwlAdmin/pull/103#issuecomment-218175458

**Comment by Flancy** [comment]
@NightDiRaven Благодарю :)
