### ISSUE TITLE
Validation rule 'mime:pdf' doesn't pass validation when given a file with an extension of .pdf. [Bug?]

### ISSUE THREAD

**Issue by 7immy** [LaravelRUS/SleepingOwlAdmin#115]
If I add a PDF file to the below form element sleepingOwl returns a validation error message:

> The Attachment file must be a file of type: pdf.

    AdminFormElement::file('attachment_source_url', 'Attachment file')
        ->addValidationRule('mime:pdf')

**Comment by butschster** [comment]
Unfortunately validation don't work with upload field

**Comment by butschster** [comment]
This problem with uploading process. When you attach new file, 
at first it upload by ajax on the server and the ajax request return link to file and insert it to hidden input for field.

i want to change this process

**Comment by butschster** [comment]
Use 

```php
AdminFormElement::upload('file', 'PDF')->addValidationRule('mime:pdf'),
```

**Comment by 7immy** [comment]
This is great thank you :)

**Comment by 7immy** [comment]
2 questions.
1. Is there any way to set the save path? It looks like its currently going to my server's tmp folder `/Applications/MAMP/tmp/php/php3Ib9Pj`?
2. Could you add the name of the currently uploaded file to the upload form?

Thanks

**Comment by butschster** [comment]
Try this

```php
// your model

use KodiComponents\Support\Upload;

class Post extends Model 
{
    use Upload;

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'pdf' => 'upload', //set cast for field with file - upload
    ];
}
```
