### ISSUE TITLE
AdminFormElement::image Validation

### ISSUE THREAD

**Issue by tale9** [LaravelRUS/SleepingOwlAdmin#1151]
AdminFormElement::image('image', 'Изображение')->addValidationRule('mimes:jpeg,png', 'Файл имеет неверный тип'),
![image](https://user-images.githubusercontent.com/46527876/69414297-7a97b300-0d23-11ea-9400-7ed445254bb3.png)
Выбран формат .ico
![image](https://user-images.githubusercontent.com/46527876/69414379-a61a9d80-0d23-11ea-991f-235a45af2490.png)
Выбран формат .svg
1. Пустое окно с кнопкой OK
2. sleeping_owl::validation.not_image (в файле validation.php вбито сообщение для not_image)

**Comment by daaner** [comment]
Чуть поправил, но мне все равно не нравится, как работает валидация

**Comment by daaner** [comment]
пока закрою, будут еще проблемы - откроем и поправим, просто пока не знаю куда и что править
