### ISSUE TITLE
AdminFormElement::manyToMany

### ISSUE THREAD

**Issue by alexandrmalchik** [LaravelRUS/SleepingOwlAdmin#1155]
Здравствуйте, может кто объяснить, у меня следующая ситуация.
Есть следующие модели 
Blog (id, name)

class Blog extends Model
{
    public function Images() {
        return $this->hasMany('App\Models\Image');
    }
}

Image (id, path, blog_id)

class Image extends Model
{
    public function Blogs() {
        return $this->belongsTo('App\Models\Blog');
    }
}
 
Что я хочу, при создании блога, загружать необходимое количество картинок, но при использовании hasMany 
                AdminFormElement::hasMany('Images', [
                    AdminFormElement::image('path', 'Images')
                ])
получаю следующую ошибку
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Missing required parameters for [Route: admin.form.element.image] [URI: admin/{adminModel}/image/{field}/{id?}]. (View: /application/vendor/laravelrus/sleepingowl/resources/views/default/form/element/image.blade.php)

Может кто подсказать, я что то упустил? или мне небходимо использовать 
AdminFormElement::image('image.path', 'Images')
и уже самому писать логику загрузки картинок?
Версия лары 6.6.2

**Comment by vkhokhlyuk** [comment]
Удалось решить проблему ? 
У меня такая же ошибка при попытке использовать методы image, images, file..

**Comment by xUJYx** [comment]
Откатитесь до версии ларавела 6.5 и всё заработает. Пока в слипиновле сей баг не поправлен...
