### ISSUE TITLE
Images Eloquent and ->storeAsComaSeparatedValue() method

### ISSUE THREAD

**Issue by Heisenwald** [LaravelRUS/SleepingOwlAdmin#1160]
*en*
## Version in Composer.json

"php": ">=7.0.0",
"laravel/framework": "5.5.*",
"laravelrus/sleepingowl": "dev-development",

## Steps to reproduce

1. Create some admin form and append AdminFormElement::images() element.
2. Use the Eloquent relation like hasOne (in my case) as element`s key. F.e. AdminFormElement::images('relation.field')
3. Add method ->storeAsComaSeparatedValue()

## What is expected?
1. Expected saving values like 'value.jpg1,value2.jpg,value3.jpg'

## What is actually happening?
1.  Error: implode(): Invalid arguments passed {"exception":"[object] (ErrorException(code: 0): implode(): Invalid arguments passed at vendor/laravelrus/sleepingowl/src/Form/Element/Images.php:35)
_______________________________________________________________
*ru*
## Версия в композере

"php": ">=7.0.0",
"laravel/framework": "5.5.*",
"laravelrus/sleepingowl": "dev-development",

## Что надо сделать что бы увидеть ошибку?

1. Создать админ форму с элементом AdminFormElement::images()
2. Использовать связь, например hasOne (как в моем случае), в качества ключа элемента. Пример: AdminFormElement::images('relation.field')
3. Добавить метод ->storeAsComaSeparatedValue()

## Что должно сработать?
1. Сохранение значений в виде 'value.jpg1,value2.jpg,value3.jpg'

## Что сработало?
1.  Ошибка: implode(): Invalid arguments passed {"exception":"[object] (ErrorException(code: 0): implode(): Invalid arguments passed at vendor/laravelrus/sleepingowl/src/Form/Element/Images.php:35)

**Comment by daaner** [comment]
`storeAsComaSeparatedValue()` is @deprecated in new ver.

Эта ф-ция не нужна больше, и без нее идет сохранение через запятую и с сортировкой
