### ISSUE TITLE
Template class [] not found In AdminServiceProvider.php line 92

### ISSUE THREAD

**Issue by romicaiarca** [LaravelRUS/SleepingOwlAdmin#1166]
*en*
## Version in Composer.json
"laravelrus/sleepingowl": "dev-development"
## Steps to reproduce

1. add in compose.json ``"laravelrus/sleepingowl": "dev-development"``
2. run `` ./compose.phar update`` in terminal
It is installing the packages:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
// packages are installed with success 
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In AdminServiceProvider.php line 92:
                               
  Template class [] not found  
                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

## What is expected?
1. It should finish the installation with success.

## What is actually happening?
1. It displays the following error:
```
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In AdminServiceProvider.php line 92:
                               
  Template class [] not found  
                               

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```
______________________________________________________________
I have tried to remove the package and looks like after that ``` php artsan ``` work fine. If I add back the package, the error appear again. Because of this, I cannot run any ```php artisan ``` command until I don't remove the package.

**Comment by daaner** [comment]
- go to `/bootstrap/cache` and delete all files, except `.gitignore`
- run `composer install` and `php artisan sleepingowl:install` again
