### ISSUE TITLE
В AdminFormElement::hasMany (+manyToMany) для элементов custom модель остается родительская (related не назначается)

### ISSUE THREAD

**Issue by Viacheslav1945** [LaravelRUS/SleepingOwlAdmin#1183]
1. Для всех элементов именованных внутри AdminFormElement::hasMany назначается модель нужного потомка, для элементов custom - модель остается родительская, а значит работать с текущей "записью" из него не получится, только с основной. Предположим в основной и связанной записи поля есть `text` (хотя можно еще проще - в custom выводить просто $model - вернет JSON).

            $Params = AdminFormElement::hasMany( 'params', [
                AdminFormElement::custom()->setDisplay( function ( $model ) {
                    return "<b>!!!! " . $model->text . "</b>";
                }),
                AdminFormElement::text('text', 'String/text' ),
            ]);

2. Решение возможно такое: назначать модель потомка в т.ч. на custom элементах, в коде \laravelrus\sleepingowl\src\Form\Related\Elements.php
назначение моделей идет только на NamedFormElement, на custom / html модель остается родительская

...
    protected function createGroup($attributes, $old = false, $key = null): Group
...
        $this->forEachElement($elements = $this->getNewElements(), function (NamedFormElement $el) use ($model, $key, $old) {
            // Setting default value, name and model for element with name attribute

Пока смотрю как это сделать лучше, чтобы ничего не сломать, т.к. с Laravel/SleepingOwl работаю неделю.

**Comment by Viacheslav1945** [comment]
В общем пока сделал так - все работает.

            if ( $el instanceof Custom ) {
                $el->setModel($model);
            }

Потом скину коммит, как разберусь с правилами местными, пока целиком функция 
 createGroup c этой фичей - теперь в элементах custom будет нужная зависимая модель.

Файл
\laravelrus\sleepingowl\src\Form\Related\Elements.php
...
use SleepingOwl\Admin\Form\Element\Custom;
...
    protected function createGroup($attributes, $old = false, $key = null): Group
    {
        $model = $attributes instanceof Model ? $attributes
            : $this->safeCreateModel($this->getModelClassForElements(), $attributes);
        $group = new Group($model);

        if ($this->groupLabel) {
            $group->setLabel($this->groupLabel);
        }

        if ($key) {
            $group->setPrimary($key);
        }

        $this->forEachElement($elements = $this->getNewElements(), function (NamedFormElement $el) use ($model, $key, $old) {
            // Setting default value, name and model for element with name attribute
            $el->setDefaultValue($el->prepareValue($this->getElementValue($model, $el)));
            $el->setName(sprintf('%s[%s][%s]', $this->relationName, $key ?? $model->getKey(), $this->formatElementName($el->getName())));
            $el->setModel($model);
            
            if ($old && strpos($el->getPath(), '->') === false && ! ($el instanceof HasFakeModel)) {
                // If there were old values (validation fail, etc.) each element must have different path to get the old
                // value. If we don't do it, there will be collision if two elements with same name present in main form
                // and related form. For example: we have "Company" and "Shop" models with field "name" and include HasMany
                // form with company's shops inside "Companies" section. There will be collisions of "name" if validation
                // fails, and each "shop"-form will have "company->name" value inside "name" field.
                $el->setPath($el->getName());
            }
        });

        foreach ($elements as $el) {
            if ( $el instanceof Custom ) {
                $el->setModel($model);
            }
            $group->push($el);
        }

        return $group;
    }

**Comment by Viacheslav1945** [comment]
Запушить в новую ветку коммит не удалось - нет доступа, вот дифф пока

```
diff --git a/src/Form/Related/Elements.php b/src/Form/Related/Elements.php
index f92ca849..c2747c72 100644
--- a/src/Form/Related/Elements.php
+++ b/src/Form/Related/Elements.php
@@ -20,6 +20,7 @@ use SleepingOwl\Admin\Form\Columns\Columns;
 use SleepingOwl\Admin\Form\Element\NamedFormElement;
 use SleepingOwl\Admin\Form\FormElements;
 use Throwable;
+use SleepingOwl\Admin\Form\Element\Custom;
 
 abstract class Elements extends FormElements
 {
@@ -424,6 +425,9 @@ abstract class Elements extends FormElements
         });
 
         foreach ($elements as $el) {
+            if ( $el instanceof Custom ) {
+                $el->setModel($model);
+            }
             $group->push($el);
         }
 
```

**Comment by daaner** [comment]
Принял ПР, оттести хорошо

**Comment by daaner** [comment]
Будем считать, что все проверили, раз молчат
