### ISSUE TITLE
Javascript removes file from list if press cancel 

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#1190]
Джаваскрипт удаляет файл со списка при нажатии удалить а после закрыть окно или отменить.

## Версия в композере
"laravelrus/sleepingowl": "5.6.4"

## Что надо сделать что бы увидеть ошибку?

1. Добавить поле
AdminFormElement::file('agreement_template', 'Шаблон')->required(),

2. Добавить файл 

3. Нажать на кнопку удалить и отменить файл визуально пропадает

## Что должно сработать?
1. При отмене файл не должен пропадать

## Что сработало?
1. Файл пропадает

**Comment by vkn999** [comment]
Проверил на версии SOA 7.0 - аналогичное поведение, т.е. файл визуально исчезает.

**Comment by daaner** [comment]
т.е. массив чистить только после подтверждения удаления? правильно я понял?
это только в `files`? в имейджах такое не наблюдается?
Я по свободе хотел этот компонент переписать на вуе, чтоб меньше пакетов было в коробке

**Comment by vkn999** [comment]
> т.е. массив чистить только после подтверждения удаления? правильно я понял?
> это только в `files`? в имейджах такое не наблюдается?
> Я по свободе хотел этот компонент переписать на вуе, чтоб меньше пакетов было в коробке

- Да.
- В image такого не наблюдается.
- Это было бы круто) На данный момент сам это сделать я точно не смогу.

**Comment by daaner** [comment]
в `file` такое поведение и должно быть. Такое же и в имедж
я спутал с `files`, но и там все норма. Пиши в группу в https://t.me/prtcls

**Comment by daaner** [comment]
Я понял, щас поправлю

**Comment by daaner** [comment]
Поправил)
