### ISSUE TITLE
hasMany textarea, ckeditor conrols have wrong name

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1194]
AdminFormElement::hasMany('translations', [
          AdminFormElement::text('order_notes', 'הערות למסח הזמנה'),

gives us this:

    <input class="form-control" type="text" id="order_notes" name="translations[1][order_notes]" value="">

but

    AdminFormElement::hasMany('translations', [
         AdminFormElement::textarea('order_notes', 'הערות למסח הזמנה'),

after clicking 'add row':

    <textarea class="form-control" rows="10" id="order_notes" name="order_notes"></textarea>

existing rows look like this:

    <textarea class="form-control" rows="10" id="order_notes" name="translations[1][order_notes]"></textarea>

with ckeditor it's the same: new rows have wrong name (and ckedit doesn't even start), but existing rows work fine...

**Comment by eugenem** [comment]
laravel 6.18, but I assume that issue is in JS

btw, having the same id for controls is a bad idea

**Comment by daaner** [comment]
Not sure for sure, but corrected in the DEV version. Check it

**Comment by eugenem** [comment]
how do I run DEV?

**Comment by vkn999** [comment]
> how do I run DEV?
In composer.json
"laravelrus/sleepingowl": "dev-development"

**Comment by daaner** [comment]
or `"laravelrus/sleepingowl": "~7.0"`
