### ISSUE TITLE
Кнопка выхода

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#1195]
В какой версии она наконец то появится?

**Comment by daaner** [comment]
выход откуда?

**Comment by daaner** [comment]
если ты про логаут - то учти, что это не КМС и сам пакет не знает, нужна тебе авторизация или нет. Соответственно не в курсе как тебя вылогинивать. В демке есть пример виджета. туда прикручиваешь своё кино и радуйся
![image](https://user-images.githubusercontent.com/9641698/82327826-a4d2e080-99e7-11ea-949f-e684af9c0e47.png)

**Comment by mediaceh** [comment]
Глупость говоришь.  99% пользователей используют стандартную авторизацию. М.б. одному на сотню понадобится что то колхозить и разбираться в ваших демках. А сейчас это должны делать 99 из 100. Бред полнейший.

**Comment by Butochnikov** [comment]
@mediaceh сама админка ничего не знает о подключенной тобой авторизации.
Вход осуществляется силами (шаблонами)  фреймворка. 
Следовательно, если внутри админки нужно сделать выход, то это ты делаешь самостоятельно, в нужном тебе месте. 

Другой вопрос, что можно проверять наличие авторизированного пользователя и UI для этого включить в функционал "из коробки".

**Comment by daaner** [comment]
поддерживаю. и закрываю
Будет идеи по проверке внутри - выслушаю. А так как выйти, если не знаешь как зашел)))
