### ISSUE TITLE
Need update JQuery 3.5.0 -> 3.5.1

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#1198]
Перестал работать collapse в bootstrap
подробности тут https://github.com/twbs/bootstrap/issues/30553#issuecomment-623866824
В версии 3.5.1 исправили ошибку

И можно в файле admin-app.js указывать какие версии bootstrap и jquery вставлено
Это для ускорения поиска ошибок как эта выше и для тех кто использует jquery повторно его не ассетить

**Comment by daaner** [comment]
Смотрим `package.json` в нужной ветке.
Ассеты обновил. Тестим перед релизом

**Comment by daaner** [comment]
ну и в ченджлог смотреть
```
## 2020-05-24
* [Update] NPM packages:
  - admin-lte: 3.0.4 -> 3.0.5
  - bootstrap: 4.4.1 -> 4.5.0
  - jquery: 3.5.0 -> 3.5.1
  - datatables.net: 1.10.20 -> 1.10.21
  - datatables.net-bs4: 1.10.20 -> 1.10.21
  - datatables.net-responsive: 2.2.3 -> 2.2.5
  - fullcalendar: 3.10.0 -> 3.10.2
  - i18n: 0.9.0 -> 0.9.1
  - moment: 2.24.0 -> 2.26.0
  - node-sass: 4.14.0 -> 4.14.1
  - sweetalert2: 9.10.12 -> 9.13.1
```
