### ISSUE TITLE
How to сhange authentication SleepingOwl 4?

### ISSUE THREAD

**Issue by MammutCris** [LaravelRUS/SleepingOwlAdmin#120]
Yesterday I did the move from SleepingOwl Admin 2 on this version
And there was a problem with the connection authentication Cartalyst\Sentinel
Details issue described here
https://toster.ru/q/320783

**Comment by butschster** [comment]
Ответил тебе там же

https://toster.ru/q/320783

**Comment by butschster** [comment]
Привет, ну собственно это уже не проблемы админки, а больше проблемы Laravel, я бы даже сказал не проблемы, а изменения.

В документации описан процесс изменения алгоритма авторизации:

- На русском http://laravel.su/docs/5.2/authentication#adding-custom-guards
- На английском https://laravel.com/docs/5.2/authentication#adding-custom-guards

Если кратко, то в Laravel 5.2 появились так называемые гарды, которые позволяют реализовать несколько алгоритмов авторизации и использовать их параллельно, а также выбирать гард авторизации используемый по умолчанию.

```php
'defaults' => [
     'guard'     => 'sentinel', // Используемый по умолчанию
      ....
],
...
'guards' => [
     ...
     'sentinel' => [
          'driver'   => 'session',
          'provider' => 'sentinel',
     ],
],
...
'providers' => [
     'sentinel'  => [
          'driver' => 'sentinel',
          'model' => App\User::class,
          'options' => [
                ....
          ],
     ],
],
```

```php
Auth::extend('sentinel', function($app, $name, array $config) {
      ...
});
```

Т.е. мы создаем свой провайдер для авторизации, делаем его гардом по умолчанию.

**Comment by MammutCris** [comment]
Я настраивал по этой инструкции https://cartalyst.com/manual/sentinel/2.0#laravel-5 . Аутентификация пользователей работает, а вход в админку нет, даже если подключить Middleware проверки авторизации.

Искал как прописать подключение в методе boot для sentinel, также не нашел.

Можете подсказать как это реализовать?

**Comment by Zolotov88** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/issues/217
