### ISSUE TITLE
Action ajax request has not field _id with selected rows 

### ISSUE THREAD

**Issue by oleg-tolkach** [LaravelRUS/SleepingOwlAdmin#1200]
*en*
## Version in Composer.json
"name": "laravelrus/sleepingowl", "version": "7.9",

## Steps to reproduce
1. Add new action button
$display->setActions(
            AdminColumn::action('export', 'export')
                ->setAction(route('admin.news.export'))
        );
2. Add route for this action
Route::post('/news/export.json', ['as' => 'admin.news.export', function (\Illuminate\Http\Request $request) {
    dd($request->all());
}]);
3. Select several rows and choose action export and press submit 

## What is expected?
1. $request->_id should has array with ids of selected rows 

## What is actually happening?
1. $request has not any fields 

something wrong with compiled js because it works good when I copied js directory  (\public\packages\sleepingowl\default\js\) from old project with version 
"name": "laravelrus/sleepingowl",
"version": "5.6.12",

**Comment by daaner** [comment]
Проблема была в связи с жесткой привязкой к классу `.panel` а мы этот класс убрали и заменили на `.card`. Поправил в DEV версии... Чуть позже сделаю релиз, пока можешь использовать дев ветку.
