### ISSUE TITLE
Пропала прокрутка таблиц

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#1205]
## Версия в композере
Dev (после обновления)

## Что надо сделать что бы увидеть ошибку?

1. Большая таблица с колонками

## Что должно сработать?
1. Должно добавлять горизонтальный скролл

## Что сработало?
1. Всё сжимается и выглядит немного ужасно

Пример кода:

```
   public function onDisplay()
    {
        $display=AdminDisplay::datatables();
        ...

                return  $display
                    ->with(['firm'])
                    ->setHtmlAttribute('class', 'table-primary')
                    ->setColumns([
                        AdminColumn::text('id', '#'),
                        AdminColumn::text('ref_id', 'RefID'),
                        AdminColumn::text('user_id', 'ID'),
                        AdminColumn::text('number_acc', 'Номер '),
                        AdminColumn::text('building.address', 'Адреса'),
                        AdminColumn::text('number_object', 'Номер'),
                         .... и ещё 15 полей :)
                    ])->paginate(20)
                    ->setView('admin::default.display.table');
                break;
            default:
                return back();
                break;
        }
    }
```

**Comment by daaner** [comment]
Ты про мобильную версию?
Есть максимальный размер таблицы. От горизонтальной прокрутки всегда хочется избавится.
Ты стилями можешь насильно задать минимальную ширину, если у тебя много колонок

На устройствах с узким экраном админка выглядит плохо, это известная проблема и ее до сих пор не можем нормально решать без танцев с бубном.
Самый лучший вариант - задавай для узких полей фиксированную ширину и делай `setSmall('description')` для подписей и для дополнительной информации
пример:
![image](https://user-images.githubusercontent.com/9641698/87144685-d44bee00-c2b0-11ea-9857-0ec448403160.png)

**Comment by daaner** [comment]
тут 15 видов колонок в этой таблице

**Comment by anantaramdas** [comment]
Нет я не про мобильную версию - таблица не влазит по ширине в єкран и раньше (до обновления) она показывалась с горизонтальным скроллом а теперь нет. Как это вернуть?

**Comment by anantaramdas** [comment]
Т.е. сейчас это выглядит вот так:

![image](https://user-images.githubusercontent.com/7561827/87167421-8e138080-c2ea-11ea-9bc6-7cab34cdb9ba.png)

Раньше таблица становилась шире и появлялся скролл.

**Comment by anantaramdas** [comment]
> тут 15 видов колонок в этой таблице

@daaner могли бы Вы поделиться декларацией этой таблицы для сравнения?
