### ISSUE TITLE
Убрать Dashboard и Information из меню

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#1206]
## Версия в композере
Dev 

После обновления снова появились эти два пункта меню. Подскажите как их убрать.

**Comment by daaner** [comment]
Эти пункты добавляются в navigation.php ты их можешь убрать сам.
Видимо у тебя этот файл лежит где-то в другом месте отличном от app\admin (это допустимо, все можно кастомизировать)

**Comment by anantaramdas** [comment]
Спасибо да действительно обновлися файл в app\admin\navigation.php и оттуда "выросли" эти пункты
