### ISSUE TITLE
Фильтры применяются ко всем datatables на страничке, указание нулей-фильтров в ненужных нерешает проблему.

### ISSUE THREAD

**Issue by ProtasovM** [LaravelRUS/SleepingOwlAdmin#1213]
## Версия в композере 
cова - 5.8.*

## Что надо сделать что бы увидеть ошибку?

1. в контроллере заделать несколько такого кода
$tasks = AdminSection::getModel(EmployeeTaskManager::class)->fireDisplay();
        $tasks->setApply(function($query) use($employee) {
            $query->where('employee_id', $employee->id);
            $query->orderBy('id', 'desc');
        });
        $tasks->setParameter('employee_id', $employee->id);
2.
Сами секции с datatables. Фильтры - Фильтры столбцов. Из доки.
в одной из секций дать фильтры, в остальных явно указать нули
3.
далее во вью вывести их через {!! $tasks !!} и остальные также

## Что должно сработать?
1.
фильтры только на нужной

## Что сработало?
1.
наблюдать фильтры на всех, и возможно, ошибки по кол-ву колонок

## Что кто думает?
Andrey, говорит в fireDisplay ид не выставляется. Какой я сам не знаю.

**Comment by daaner** [comment]
5,8 очень старая ветка. Лично я ее не поддерживаю уже. А тот человек кто поддерживал - давно не трогал код совы...
Проверь в дев или 8+ ветке и отпишись

**Comment by daaner** [comment]
Молчат, значит решили проблему обновлением
