### ISSUE TITLE
Editatable datatable

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#1219]
Feature Request

Is there a way to have editable datatable inside a form? The idea is to edit a belongs to many relationship inside a form, for examlpe in the demo
https://demo.sleepingowladmin.ru/admin/contacts
I wuold like to insert / edit company attributes inside contacts form. 
I believe is a common activity in all the situation where there is an "header - body (or details)" database structure, i.e. sales orders. In this case opening an order I would like to insert / edit rows in the "details" table.

Thanks,
 CS

**Comment by daaner** [comment]
```

**Comment by daaner** [comment]
or
```
$manyToMany = AdminForm::form()->addElement(
    new FormElements(
        [
            AdminFormElement::manyToMany('users', [
                AdminFormElement::text('name', 'Name'),
                AdminFormElement::select('color_id', 'Color', Colot::class)->setDisplay('name_color'),
                AdminFormElement::images('images', 'Photo'),
                AdminFormElement::checkbox('is_done', 'Checked'),
                AdminFormElement::datetime('date', 'Date payment'),
            ])->setRelatedElementDisplayName(function ($model){
                return $model->full_name;
            })
        ])
);

```

**Comment by s6carlo** [comment]
Thanks, it's a great project but not easy to use for non Russian speakers.

**Comment by daaner** [comment]
The project is free and actively supported, but the translation of the documentation is constantly delayed. If you wish, you can participate in the translation. Write me to telegram @neodaan or WhatsApp +380965775815
