### ISSUE TITLE
Has Many - multiple new items

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#1227]
As described in #1219 I'm using AdminFormElement::hasMany to insert multiple rows in a table.

Using this code to create the section

```
AdminFormElement::hasMany('tableRows',
                        [AdminFormElement::text('row_key', 'Key')->setHtmlAttribute('class', 'd-inline ml-5  w-50'),
                            AdminFormElement::text('row_value', 'Value')->setHtmlAttribute('class', 'd-inline ml-5  w-50')
                        ]
```
When I dinamically add multiple items using the "add" button they are all named 
```
tableRows[new_undefined][row_key]
tableRows[new_undefined][row_value]
```
and value are sent (POST request) as
```
tableRows[new_undefined][row_key]: key1
tableRows[new_undefined][row_value]: value1
tableRows[new_undefined][row_key]: key2
tableRows[new_undefined][row_value]: value2
```

Is it correct? The problem is that they have the same name, so only one is saved.

**Comment by s6carlo** [comment]
## Version in Composer.json
"laravel/framework": "^6.2",
"laravelrus/sleepingowl": "6.*"

Using the demo
 "laravel/framework": "5.8.*",
 "laravelrus/sleepingowl": "5.6.*",

The error does not occurs. 

It seems related to admin-app.js   in Vue.component("related-group",

**Comment by daaner** [comment]
use `dev-development`)
you can use SO last ver. Support Laravel 5.5-8

**Comment by daaner** [comment]
Old closed, no error observed
