### ISSUE TITLE
Не работает загрузка больших файлов

### ISSUE THREAD

**Issue by jofreyswb** [LaravelRUS/SleepingOwlAdmin#1235]
https://prnt.sc/vu9618 на скрине видно что все что время загрузки всегда 30 сек, на сервере стоит загрузка больше чем данное время

**Comment by vkn999** [comment]
Необходимо указать версии:
SOA
Laravel
php
какие настройки php.ini?
каков размер и формат файла?

**Comment by daaner** [comment]
еще настройки сервера нужно проверить, возможно по истечении 30 секунд нгиникс или апач рубает соединение
Пиши в чат, там подскажут. Все работает корректно, если настроить
