### ISSUE TITLE
Logout - Laravel Jetstream (replace Auth in Laravel 8.*)

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#1238]
In Laravel 8.* Authentication is provided by laravel/jetstream package

Using this package logout button is missing. Navigation header include 
```
<ul class="navbar-nav ml-auto">
	@stack('navbar.right')
</ul>
```
but this in empty. 

How to add a logout link to header (or navigation)? In Jetstream logout works only with POST method.

**Comment by Lunatig** [comment]
you can create widget 
https://sleepingowladmin.ru/#/ru/widgets

 public function toHtml()
    {
        return view('admin::widgets.logout');
    }

    /**
     * @return string|array
     */
    public function template()
    {
        return AdminTemplate::getViewPath('_partials.header');
    }

    /**
     * @return string
     */
    public function block()
    {
        return 'navbar.right';
    }

**Comment by s6carlo** [comment]
Thanks.
