### ISSUE TITLE
Action and MessagesStack

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#1246]
How to use action and MessagesStack to give a feedback onaction result?

I tried to insert
`\MessagesStack::addInfo('This is info');`
in route method, without success

Also in the demo (BS4 - datatable-actions) export has not a "feedback", actually it does not export data, the action produce a json but it is not a file to download or something else.

**Comment by s6carlo** [comment]
Is there a method to use action not as ajax request? The idea is that action method modify some data and then the datatable is loaded with new data.

**Comment by daaner** [comment]
```
Swal.fire({
    title: res.data.title,
    text: res.data.msg,
    icon: 'success'
})
```

export needs to be organized through your own logic. The package transfers an array of keys to the back. do what you want there
