### ISSUE TITLE
Selecting text inside ::files()

### ISSUE THREAD

**Issue by heiswald** [LaravelRUS/SleepingOwlAdmin#1247]
*en*
## Steps to reproduce

1. Add `AdminFormElement::files()` element into yours `onEdit` element and include title or description, or any other text field and fill it with some value.
2. Go to the UI. Try to select text inside any textarea (but not with double/tripple-click).

## What is expected?
1. Expecting selected row (highlighted)

## What is actually happening?
1. It starts to drag the card
_______________________________________________________________
*ru*
## Что надо сделать что бы увидеть ошибку?

1. Добавить `AdminFormElement::files()` в элемент `onEdit` с любым включенным текстовым полем и заполнить его данными.
2. Переходим в интерфейс и пробуем выделить любой текст внутри этого текстового поля. 

## Что должно сработать?
1. Выделение текста

## Что сработало?
1. Начинает перетаскивать карточку

**Comment by daaner** [comment]
Возможно, я потом переделаю, пока выделяй двойным кликом все или мышкой
