### ISSUE TITLE
Сортировка в datatables при работе с postgresql

### ISSUE THREAD

**Issue by isrkar** [LaravelRUS/SleepingOwlAdmin#1252]
## Что надо сделать что бы увидеть ошибку?
Проект должен работать с Postgresql базой

## Что должно сработать?
1. Сортировка по колонкам в onDisplay секции для привязанных моделей

## Что сработало?
1. Ошибка запроса

**Comment by EgorGruzdev** [comment]
Может для заворачивания использовать метод wrap из Grammar соответствующего connection

**Comment by isrkar** [comment]
Не знал о таком. Попробую тогда пр сделаю если получится :)

**Comment by isrkar** [comment]
Повесил новый пр с использованием grammar
