### ISSUE TITLE
columns inside hasMany

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1257]
Is it possible to have columns in hasMany form element? So that it would be more compact...

I've tried it like this:

```
AdminFormElement::hasMany( 'option_pizza_settings',[ AdminFormElement::columns([[
   AdminFormElement::select( 'pizza_size_id', 'גודל של פיצה', new App\Models\PizzaSize() )->setDisplay( 'name' ),
],[
   AdminFormElement::select( 'pizza_addon_size_id', 'גודל של חתיכה', new App\Models\PizzaAddonSize() )->setDisplay( 'name' ),
],[
   AdminFormElement::text('price', 'מחיר'),
],[
   AdminFormElement::text('code', 'קוד קופה'),
]])] )

```

and got this:

https://www.dropbox.com/s/por13ax81imlvty/Screen%20Shot%202021-02-02%20at%2023.59.54.png?dl=0

So just `<div class="row">` is missing there:

https://www.dropbox.com/s/ka01sq9b13zfcj8/Screen%20Shot%202021-02-03%20at%200.01.15.png?dl=0

**Comment by Aglok** [comment]
Which version of the owl?

**Comment by eugenem** [comment]
7.27

**Comment by eugenem** [comment]
will 8.2 work under laravel 6?

**Comment by Aglok** [comment]
Did you update the owl js package? Column as is to specify an ID, just give the class row div. And I also get it as indicated by the second variation.

**Comment by Aglok** [comment]
Need using branch dev. I made these edits there.

**Comment by daaner** [comment]
At the moment we maintain support for Laravel 5.5 - 8.41 (dev branch and last release)
use a newer version)
