### ISSUE TITLE
Ошибка при загрузке изображения в AdminFormElement::hasMany()

### ISSUE THREAD

**Issue by agpopov** [LaravelRUS/SleepingOwlAdmin#1259]
## Что надо сделать что бы увидеть ошибку?

1. Добавить в onEdit родительского элемента (catalog_category) два таба
2. На второй таб добавить поле для релэйшена (meta_tags) `AdminFormElement::hasMany()->setLimit(1)`
3. В hasMany добавить поле `AdminFormElement::image()`
4. В UI создавть новый элемент или открыть существующий, но без существующего релэйшена
5. Добавить mata_tag (нажать кнопку "Добавить")
6. Загрузить в поле image картинку

## Что должно сработать?
1. Картинка должна загрузиться на сервер и открыться для предпросмотра

## Что сработало?
1. Сервер на запрос загрузки возвращает 404

По сути, проблема в url, по которому грузится картинка. Должно быть что-то вроде `http://<domain>/admin/meta_tags/image/image` где meta_tags - это название релэйшена, куда должна грузиться картинка, а image - название поля. А в реальности картинка грузится по адресу `http://<domain>/admin/catalog_categories/image`. То есть, в родительский элемент catalog_categories и без указания названия поля.

**Comment by Aglok** [comment]
Какая версия совы используется? В dev ветке попробуйте. Я там много чего исправлено.

**Comment by agpopov** [comment]
> Какая версия совы используется? В dev ветке попробуйте. Я там много чего исправлено.

Переключился на dev-development, всё то же самое. 

Даже записал экран: [link](https://1drv.ms/u/s!AuSkNS4ux6OrhcZvN0KsWfuoM310uw?e=DEZrQh)
У меня с vue не очень, найти нужный код не получилось.

Вот код таба "Мета"
```private function getFormElements(): array
  {
    return [
      AdminFormElement::text('title', 'Заголовок'),
      AdminFormElement::text('h1', 'H1'),
      AdminFormElement::text('keywords', 'Ключевые слова'),
      AdminFormElement::textarea('description', 'Описание'),
      AdminFormElement::image('image', 'Изображение')
    ];
  }

**Comment by Aglok** [comment]
Fixed it in dev-development

**Comment by agpopov** [comment]
Thanks!
