### ISSUE TITLE
Call to undefined method SleepingOwl\Admin\Navigation::findActivePage()

### ISSUE THREAD

**Issue by moisespsena** [LaravelRUS/SleepingOwlAdmin#126]
I update to latest commit (9da3d6b27e4568d669a9ce18ca57de95bb18c2dc) and received this error:

`FatalErrorException in Navigation.php line 15: Call to undefined method SleepingOwl\Admin\Navigation::findActivePage()`

**Comment by butschster** [comment]
Yo should update `kodicomponents/navigation`

**Comment by moisespsena** [comment]
I update `kodicomponents/navigation` by composer and problem was be solved.
Thanks.
