### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Druget** [LaravelRUS/SleepingOwlAdmin#1263]
@aios Aios Габриелян Давид Меликович - мошенник! Кинул на $840 долларов, не выполнил работу и пропал.
Номер карты приватбанк 5218572221792372
5218 5722 2179 2372
gabrielyan david - conman! Cheated me out of $$$ 840, didn't do the job, and disappeared.

**Comment by vrusua** [comment]
@Druget Добрый день, пожалуйста, можете сообщить как с Вами связаться за дополнительной информацией на этот счет. Спасибо.
