### ISSUE TITLE
Date editor inside hasMany is broken

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1266]
Admin/models.php:
`                AdminFormElement::hasMany( 'catering_dates', [
                    AdminFormElement::date( 'date', 'Date' ),
                    AdminFormElement::text( 'details', 'Details' ),
                ]),
`

config/sleeping_owl.php
`
    'dateFormat' => 'd.m.Y',
`

2 issues:
1. When you add a new row at this section, the date picker is not initialized
2. When you save the existing date (say 1.03.2021), it crashes due to incorrect date format (checked code, and at hasMany save handler you don't account for date format)

Workaround:
changed dateFormat to 'Y-m-d'

I checked dev-development, it behaves the same way...

**Comment by daaner** [comment]
I will gladly accept PR for consideration)
Alas, I don’t deal with this functionality, maybe later.

**Comment by daaner** [comment]
use `->setPickerFormat('d-m-Y')`
