### ISSUE TITLE
AdminFormElement::select no options

### ISSUE THREAD

**Issue by zedsh** [LaravelRUS/SleepingOwlAdmin#127]
After update SleepingOwl construction AdminFormElement::select('var_id', 'Variable')->setModelForOptions('App\Variable')->setDisplay('desc') not display options in admin panel.

**Comment by zedsh** [comment]
With these dependencies it works fine .
        "laravelrus/sleepingowl": "4.36.133-beta",
        "caouecs/laravel-lang": "~3.0",
        "kodicomponents/navigation":"0.0.4"

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.37.137-beta
