### ISSUE TITLE
Ошибка валидации по уникальности поля, если primary key модели имеет название отличное от id

### ISSUE THREAD

**Issue by Pal9yni4bi** [LaravelRUS/SleepingOwlAdmin#1275]
*ru*
## Версия в композере

        "laravel/framework": "^8.40",
        "laravelrus/sleepingowl": "^8.27",

## Что надо сделать что бы увидеть ошибку?

1. Заводим модель, с $primaryKey != 'id' (пусть для примера будет $primaryKey = 'prod_id'), привязываем к таблице (для примера - products, поля title, prod_id).
2. Настраиваем редактирование модели через Sections с редактируемым полем
                                AdminFormElement::text('title', 'Уникальный заголовок')
                                    ->unique(),
3. Вносим значение в title "Товар 1" и сохраняем модель в админке

## Что должно сработать?
1. Должна отработать валидация на уникальность по полю uuid

## Что сработало?
1. Получили ошибку Column not found: 1054 **Unknown column 'id' in 'where clause'** (SQL: select count(*) as aggregate from `products` where `title` = 'Товар 1'  and `id` <> 1)

Вариант решения - в \SleepingOwl\Admin\Form\Element\NamedFormElement::getValidationRules в правиле валидации указывать не имя таблицы, а имя модели. Тогда \Illuminate\Validation\ValidationRuleParser::parse корректно извлечёт из модели и имя связанной таблицы, и имя $primaryKey. Попытка реализации https://github.com/LaravelRUS/SleepingOwlAdmin/pull/1274

**Comment by daaner** [comment]
ПР принял
