### ISSUE TITLE
Обратный порядок ссылок в меню

### ISSUE THREAD

**Issue by deniskoronets** [LaravelRUS/SleepingOwlAdmin#129]
Здравствуйте, установил dev-master версию пакета, заметил что в app/Admin/navigation.php ссылки нужно указывать в обратном порядке, для того чтобы вернуть нормальный порядок мне пришлось использовать array_reverse. Мне кажется это совершенно неинтуитивным.

**Comment by butschster** [comment]
всмысле в обратном порядке?

**Comment by deniskoronets** [comment]
я просто разкомментировал из примера, в файле они указаны в одном порядке. Выводятся в обратном

**Comment by butschster** [comment]
https://github.com/KodiComponents/Navigation посмотри примеры здесь

**Comment by EvgenyVetrov** [comment]
мне кажется проще подстроиться под обратный порядок чем делать реверс массива. не такая частая операция по добавлению туда ссылок

**Comment by butschster** [comment]
Мне кажется, что нужно просто разобраться, а не выдумывать проблему

**Comment by butschster** [comment]
@deniskoronets удалось решить проблему?

**Comment by deniskoronets** [comment]
но я не выдумывал проблему. Мне просто показалось что такой порядок ссылок не естественный и хорошо бы его поменять на нормальный, поэтому и отписал сюда. Если считаете иначе, то я не имею ничего против.

**Comment by butschster** [comment]
@deniskoronets просьба предоставить пример меню и объяснить что по твоему мнению ты считаешь не правильным порядком. Просто мне сложно дискутировать и пытаться понять проблему без примера кода.

**Comment by CrazyRedScorp** [comment]
Тоже сначала удивлялся почему в обратном порядке, потом увидел пример, все очень просто - пиши менюхи в каком угодно порядке в `navigation.php`, но главное после `'icon' => 'fa fa-example,'` добавляй строчку `'priority' => 100,` с нужной нумерацией.

**Comment by deniskoronets** [comment]
извините за долгий ответ. Да, согласен, можно просто указывать priority
