### ISSUE TITLE
<textarea> in AdminFormElement::textarea crashes

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1299]
I'm using textarea form element to edit HTML template. If I put there <textarea> tag, I get completely empty screen after trying to edit the record. This is what's rendered to page source:

```
<textarea v-pre  class="ltr form-control" rows="10" id="template" name="template">{{#if options.length}} 
<div class="option_control text  col-md-12 {{control_name}}" data-title="{{title}}"> 
<h4>{{title}}</h4> 
{{#each options}}
<textarea class="form-control" name="{{id}}" data-title="{{this.name}}" rows="3"></textarea>
{{/each}} 
</div>
{{/if}}</textarea>
```

It probably should be escaped somehow, as HTML editors also use <textarea> to store code and manage to work...

**Comment by daaner** [comment]
you can't put this there, because the tag is closed
This is logical and is not an error

**Comment by eugenem** [comment]
look at github message editor, it mamages to work with such code, and they use <textarea> as editor as well...

**Comment by eugenem** [comment]
I think the issue is only when you inject field content directly into the page. With JS it would work fine...
