### ISSUE TITLE
Is there a boilerplate

### ISSUE THREAD

**Issue by ugintl** [LaravelRUS/SleepingOwlAdmin#1318]
Is there a boilerplate or simple laravel app already using this package?

**Comment by Lunatig** [comment]
https://github.com/SleepingOwlAdmin/demo

**Comment by ugintl** [comment]
In the description, I see English 30%. What does it mean?

**Comment by Lunatig** [comment]
This means that the documentation in English is ready by 30%. You can watch Russian with a Google translator. Or ask in a telegram, they will definitely answer there.

https://t.me/prtcls
