### ISSUE TITLE
Как в класе роута подключить AdminSection?

### ISSUE THREAD

**Issue by MammutCris** [LaravelRUS/SleepingOwlAdmin#132]
У меня есть такой роут

```
Route::get('', [
			'as'   => 'admin.dashboard',
			'uses' => '\App\Http\Controllers\AdminController@index',
		]);
```

И хочу отобразить боковое меню в view, что подключить чтобы меню отображалось вместе с моим контентом?
Все работает если в самом файле роута я делаю так: 
```
Route::get('', ['as'=>'admin.dashboard', function(){
		$content = view('admin.index');
		return AdminSection::view($content, 'Information');
	}]);
```
Как в класе роута подключить AdminSection?

**Comment by butschster** [comment]
Просьба корректно задавать вопрос и хотя бы самому попробовать вникнуть в суть своего вопроса после его написания.

Как минимум объяснять что именно не получается и какие именно ошибки или проблемы возникают.

**Comment by butschster** [comment]
Если я правильно понял, то ты хочешь подключать через роут свой контроллер и выводить через него контент в админ панель.

Для этого тебе необходимо наследовать свой контроллер от `\SleepingOwl\Admin\Http\Controllers\AdminController` и использовать метод `renderContent`

```php
namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class AdminControllerextends \SleepingOwl\Admin\Http\Controllers\AdminController
{
    public function index()
    {
        return $this->renderContent(
            view('home')
        );
    }
}
```

**Comment by butschster** [comment]
Добавил пример подключения на демо сайт http://demo.sleepingowladmin.ru/admin

**Comment by MammutCris** [comment]
Большое спасибо, пример является весьма полезным когда не так много документации.
