### ISSUE TITLE
date format language

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1327]
```
                AdminColumn::datetime('date','תאריך אירוע')->setTimezone(config('app.timezone'))
                    ->setFormat('D, d.m.Y'),

```

It shows the day name in English, even though my locale is HE. Everything else seems to be using HE locale, like translations. What am I missing?

**Comment by Lunatig** [comment]
first of all you should check if you environment has needed locale.

for example how i set locale in my docker container
```
 # locales for php
    && apt-get install -y locales \
    && sed -i '/ru_RU.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen 
    
ENV LC_ALL ru_RU.UTF-8
ENV LANG ru_RU.UTF-8
ENV LANGUAGE ru_RU.UTF-8
```

**Comment by eugenem** [comment]
interesting, I've tried it at routes:

```
    Route::get('test-date', function(){
        return date('d.m.Y, D');
    });

```

and still got EN day name

I do have HE locale at server:

```
[~]# locale -a | grep he
hebrew
he_IL
he_IL.iso88598
he_IL.utf8
```

and HE locale configured at config/app.php

`	'locale' => env('APP_LOCALE', 'he'),
`

what am I missing?

**Comment by Lunatig** [comment]
> interesting, I've tried it at routes:
> 
> ```
>     Route::get('test-date', function(){
>         return date('d.m.Y, D');
>     });
> ```
> 
> and still got EN day name
> 
> I do have HE locale at server:
> 
> ```
> [~]# locale -a | grep he
> hebrew
> he_IL
> he_IL.iso88598
> he_IL.utf8
> ```
> 
> and HE locale configured at config/app.php
> 
> ` 'locale' => env('APP_LOCALE', 'he'), `
> 
> what am I missing?

Cache?
