### ISSUE TITLE
Скрыть пустые пункты меню.

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#133]
Выводится так http://joxi.ru/a2XayxGTyzVwYA
Если ставлю права доступа и пользователя нет прав,то подменю не показываются,но сам пункт меню всеже видно http://joxi.ru/4Ak0wv9SM9RoZr , как его убрать??
Как скрыть пустые пункты меню?

**Comment by butschster** [comment]
https://github.com/KodiComponents/Navigation/releases/tag/v0.4.1

run `composer update`

**Comment by Fessnik** [comment]
Всеравно пустые висят http://joxi.ru/p276eO3f0Rv7am

**Comment by butschster** [comment]
Просьба подтвердить что обновился пакет Navigation и что у данных пунктов меню `url` равен `null`

**Comment by Fessnik** [comment]
Пакет обновился ,вот допустим пункт "Категории" http://joxi.ru/Grqd6z9SNjVBEA

**Comment by butschster** [comment]
Да, мой косяк был.

**Comment by Fessnik** [comment]
Работает, большое спасибо
