### ISSUE TITLE
datatablesAsync slow

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#134]
Есть таблица с 75 000 записей,  если ставить  AdminDisplay::datatablesAsync(), то страница загружается около 20секунд, можно ли както ускорить загрузку страницы? Или единственный вариант это AdminDisplay::table() ?

**Comment by butschster** [comment]
`datatablesAsync` я так понимаю не загружают сразу все данные, а загружают только для текущей страницы

**Comment by Fessnik** [comment]
Да, оказалось там тормозит из за with , попробую переписать на чистый sql ,должно помочь.
