### ISSUE TITLE
Ищет файлы по неправильному юрлу

### ISSUE THREAD

**Issue by YouMixx** [LaravelRUS/SleepingOwlAdmin#1342]
## Ищет файлы по неправильному юрлу
P.s. не уверен, что ошибка в сове.

В .env поставил обычный http://localhost, пакеты ищутся по http://localhostpackages/sleepingowl...
Для того, чтобы работало поставил юрл http://127.0.0.1:8000/ - стало работать.
Причем если убрать слеш в конце - опять проблема.

**Comment by daaner** [comment]
кеши чистил точно? выявил проблему?

**Comment by daaner** [comment]
http://localhost/ (слеш на конце попробуй)
