### ISSUE TITLE
Поиск\фильтры при AdminDisplay::table()

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#135]
Можно ли как-то добавить поиск\фильтры при AdminDisplay::table() ?

**Comment by CrazyRedScorp** [comment]
Доброго времени суток.
Думаю вопрос аналогичен, но поясню. Подскажите как до/при формировании страницы уже иметь фильтр в наборе данных, т.е на подобии `->where('roles.id',4)`

**Comment by Fessnik** [comment]
Можешь юзать scope   $display->getScopes()->push('admin');

**Comment by CrazyRedScorp** [comment]
Дико прошу прощения, а можно на пальцах?
Допустим указываем `$display->getScopes()->push('admin');` А что прописать в модели
> public function scopeAdmin() {
> }

?

**Comment by CrazyRedScorp** [comment]
Вообще изначально требуется вывести в админке в дополнительной вкладке список пользователей с определенным идентификатором роли. Я просто создал класс с ссылкой на User, прописал в модели `return $this->belongsToMany('App\Role', 'role_user', 'user_id');` В админке `AdminColumn::lists('roles.label')->setLabel('Roles')->setWidth('200px'),` Все выходит, все работает, но в столбце **выводится весь** перечень имеющихся ролей у пользователей. А надо чтобы в список пользователей **попадали лишь те у кого** `role_id = 3`, ну и естественно сам столбец с ролями нет необходимости отображать.

**Comment by Fessnik** [comment]
public function scopeAdmin($query)
    {
        return $query->where('role_id', 3);
    }

**Comment by CrazyRedScorp** [comment]
Пробовал, скорее всего что-то надо еще указать ибо спотыкается на

> Column not found: 1054 Unknown column 'role_id' in 'where clause'
> 1. in Connection.php line 333
> 2. at PDO->prepare('select count(*) as aggregate from `users` where `role_id` = ?') in Connection.php line 333

**Comment by Fessnik** [comment]
Вы хотите вывести пользователей в админке ,в модели Role или User?
Вам пишет что в текущей таблице нет поля role_id . Попробуйте просто 
return $query->where('id', 3);

**Comment by CrazyRedScorp** [comment]
Если использовать `return $query->where('role_id', 4);`, то получим ошибку, а если прописать `return $query->where('id', 4);`, то получим единственную запись с пользователем у которого id=4.

**/app/Accountant.php**
```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Accountant extends User
{
    protected $table = 'users';

    protected $fillable = [
        'name',
        'phone',
        'email',
        'password',
        // ...
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'role_user', 'user_id');
    }

    public function scopeClients($query)
    {
        //return $query->where('role_id', 4);
        return $query->where('id', 4);
    }
}
```

**/app/Admin/Accountant.php**
```
<?php
use App\Accountant;
use SleepingOwl\Admin\Model\ModelConfiguration;
AdminSection::registerModel(Accountant::class, function (ModelConfiguration $model) {
    $model->setTitle('Accountant'); //->enableAccessCheck();
    $model->onDisplay(function () {
        $display = AdminDisplay::table()->paginate(20);
        $display->setHtmlAttribute('class', 'table-primary');
        $display->setColumns([
            AdminColumn::link('name')->setLabel('Username'),
            AdminColumn::email('email')->setLabel('Email')->setWidth('150px'),
            AdminColumn::text('phone')->setLabel('Phone')->setWidth('150px'),
            AdminColumn::lists('roles.label')->setLabel('Roles')->setWidth('200px'),
            // ToDo: Hide roles and add other columns
        ]);
        $display->getScopes()->push('Clients');
        return $display;
    });
    $model->onEdit(function() {
        return AdminForm::panel()->addBody([
            // ToDo: Add edit form
        ]);
    });
});
```

**/app/Admin/navigation.php**
```
<?php
use SleepingOwl\Admin\Navigation\Page;
return [
    [
        'title' => "Accountant",
        'icon'  => 'fa fa-credit-card',
        'pages' => [
            (new Page(\App\Accountant::class))
                ->setIcon('fa fa-fax')
                ->setPriority(0),
            (new Page(\App\Models\ClientInvoice::class))
                ->setIcon('fa fa-fax')
                ->setPriority(100),
        ]
    ],
...
```

**Comment by Fessnik** [comment]
return $query->roles->where('role_id', 4);

**Comment by CrazyRedScorp** [comment]
```
ErrorException in Accountant.php line 76:
Undefined property: Illuminate\Database\Eloquent\Builder::$roles
1. in Accountant.php line 76
2. at HandleExceptions->handleError('8', 'Undefined property: Illuminate\Database\Eloquent\Builder::$roles', '/var/www/proj/app/Accountant.php', '76', array('query' => object(Builder))) in Accountant.php line 76
3. at Accountant->scopeClients(object(Builder))
```

**Comment by CrazyRedScorp** [comment]
Попробовал сделать так:
```
return Accountant::whereHas('roles', function($query) {
    $query->where('role_id', '4');
})->get();
```
подменив поле на 'rrrole_id' словил ошибку:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rrrole_id' in 'where clause'
1. in Connection.php line 333
2. at PDO->prepare('select * from `users` where exists (select * from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = `users`.`id` and `rrrole_id` = ?)') in Connection.php line 333
3. at Connection->Illuminate\Database\{closure}(object(MySqlConnection), 'select * from `users` where exists (select * from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = `users`.`id` and `rrrole_id` = ?)', array('3')) in Connection.php line 706
```
Т.е. по логике вещей, выборка SQL должна возвращать записи с моим условием, однако такой вариант возвращает всё равно все записи =(

Закидываем в phpMyAdmin данный скрипт (с нормальным полем и числом вместо '?') и получаем нужные записи. Почему же в админку лезут все?!

**Comment by CrazyRedScorp** [comment]
Нашел, уффф... Делается оказывается вот так:
**/app/Admin/Accountant.php**
```
$display->getScopes()->push(['Clients', 4]);
```
**/app/Accountant.php**
```
public function scopeClients($query, $roleId)
{
    $query->whereHas('roles', function ($q) use ($roleId) {
        $q->where('role_id', $roleId);
    });
}
```
И все теперь нормально работает. Может кому пригодится =) Всем спасибо!
