### ISSUE TITLE
При переключении на тёмную тему цвет текста в редакторе wysiwyg становится не читаемым

### ISSUE THREAD

**Issue by vkn999** [LaravelRUS/SleepingOwlAdmin#1353]
## Что надо сделать что бы увидеть ошибку?

1. Переключиться на тёмную тему

## Что должно сработать?
1. Текст в текстовом редакторе, полагаю, не должен менять свой цвет.
Было до переключения: 
![2022-11-08 13 52 24 192 168 1 16 407e4a9c1032](https://user-images.githubusercontent.com/14319784/200547550-750dd57f-4b4d-47b7-86b7-5bdbef017f43.jpg)

## Что сработало?
1. Стало после переключения на тёмную тему:
![2022-11-08 13 52 11 192 168 1 16 042f7efe4585](https://user-images.githubusercontent.com/14319784/200547456-855afe39-0f68-49a8-be88-3b6301cbe710.jpg)
Текст стал не читаемым.

**Comment by vkn999** [comment]
Баг проявляется при использовании ckeditor 5.

**Comment by daaner** [comment]
Поправил
