### ISSUE TITLE
tinymce 4 deprecated - CDN Error

### ISSUE THREAD

**Issue by vkn999** [LaravelRUS/SleepingOwlAdmin#1354]
## Что надо сделать что бы увидеть ошибку?

1. Установить в качестве  wysiwyg редактора tinymce

## Что сработало?
1. CDN Error
![2022-11-08 15 13 22 192 168 1 16 4415b4028a91](https://user-images.githubusercontent.com/14319784/200564145-ea86fc68-b799-4d8b-a33a-344074932287.jpg)

**Comment by daaner** [comment]
Поправил и дал возможность выбирать разные версии
