### ISSUE TITLE
Не работает wysiwyg редактор summernote

### ISSUE THREAD

**Issue by vkn999** [LaravelRUS/SleepingOwlAdmin#1355]
## Что надо сделать что бы увидеть ошибку?

1.Установить в качестве wysiwyg редактора summernote

## Что сработало?
1. Не работает текстовый редактор
![2022-11-08 15 41 34 192 168 1 16 d200bb8fb85d](https://user-images.githubusercontent.com/14319784/200566668-894d8105-1fe5-4248-86aa-c8c44d9f922c.jpg)
![2022-11-08 15 38 24 192 168 1 16 8ed28c4591c8](https://user-images.githubusercontent.com/14319784/200566675-8ea10e27-5e66-427b-af8e-667a4fd70f02.jpg)

**Comment by daaner** [comment]
Я проверю все, смотрю и тини не работает уже ЦДН

**Comment by vkn999** [comment]
> Я проверю все, смотрю и тини не работает уже ЦДН

Да, точно, тини CDN не работает.

**Comment by daaner** [comment]
Увы, но summernote больше не поддерживается в сове! Помним, любим, скорбим)))
