### ISSUE TITLE
Удаление сразу нескольких элементов

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#136]
Как можно сделать удаление сразу нескольких элементов  http://joxi.ru/DmB1en0CNOQgNr   ?
В сове3  можно было сделать так http://joxi.ru/52aN08ZIGRngeA , тут как не пробывал не смог чтото подобное сделать.

**Comment by butschster** [comment]
Массовые действия были немного переделаны. Теперь выбранные ID отправляются на указанный URL 

```php
AdminDisplay::table()->setActions([
    AdminColumn::action('export', 'Export')
        ->setIcon('fa fa-share')
        ->setAction(route('admin.news.export'))
        ->useGet() // or usePost(), usePut(), useDelete()
    ])
```

Получить список ид можно в `request()->input('id')`

**Comment by Fessnik** [comment]
Спасибо,то что нужно
