### ISSUE TITLE
filter labels are missing

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1367]
I've tried to add labels to datatable filters. There is no such field, so I took placeholder and did override all filter controls. The only issue is that multi-select filter has no placeholder:

```
        if ($this->multiple) {
            $this->setHtmlAttribute('multiple', 'multiple');

            if (! in_array($this->operator, ['in', 'not_in'])) {
                $this->setOperator('in');
            }
        } else {
            $this->setHtmlAttribute('placeholder', $this->getPlaceholder());
        }

```

This is how I changed views:
```
<div {!! $width !!}>
    <label>{{@$attributesArray['placeholder']}}</label>
    <br>
  {!! Form::select('', $options, $default, $attributesArray) !!}
</div>
```

So whether placeholder should always be set, or just add labels explicitly

**Comment by eugenem** [comment]
another thing there is that for multi-select there should be no option with select title like with single select

I'm trying to make my own class for this, but it's not that simple...

**Comment by daaner** [comment]
Тебе нужен плейсхолдер при мультиселекте в фильтрах?
Простое добавление `$this->setHtmlAttribute('placeholder', $this->getPlaceholder());` в первое условие при пустом значении не достаточно?
Для фильтров ты используешь select2 или multiselect?

**Comment by eugenem** [comment]
Плейсхолдер не работает в мультиселекте, я хочу лабел. Почти получилось, но не могу понять откуда там в опциях берется имя модели. В обычном селекте это полезно (типа не выбрано). 

Вроде бы там везде селект2 стоит.

**Comment by daaner** [comment]
Я потыкаю и попробую в ближайшее время сделать. Просто если у тебя мультиселект аякс - там пишет типа "выберите" или что-то типа того. Но попробую впилить принудительно, если ты плейсхолдер указал

**Comment by daaner** [comment]
а какая версия? не могу повторить проблему, плейсхолдеры у меня вылазят везде
![image](https://user-images.githubusercontent.com/9641698/218741961-88acab1a-86c7-4284-ac1f-c6204256234b.png)
![image](https://user-images.githubusercontent.com/9641698/218742063-0cf89aec-c531-4dc7-bb3f-9a88667e6b41.png)

или ты в самом поле хотел?

**Comment by eugenem** [comment]
ну как, есть идеи что там творится?

**Comment by daaner** [comment]
Поправил и заодно стили сделал для темной и светлой темы.

**Comment by eugenem** [comment]
а как мне там на дев бранч переключиться? в релизах то его нет пока
