### ISSUE TITLE
Fatal error: Class 'Breadcrumbs' not found

### ISSUE THREAD

**Issue by maslakoff** [LaravelRUS/SleepingOwlAdmin#137]
Hello,

I get the error after the update from (**4.37.136-beta**) to (**4.40.0**):

```
FatalThrowableError in AdminController.php line 34: 
Fatal error: Class 'Breadcrumbs' not found
```

**Comment by butschster** [comment]
Update `config/sleeping_owl.php`

**Comment by maslakoff** [comment]
Thank you, it works fine. I Added breadcrumbs provider and alias to `config/sleeping_owl.php`.
