### ISSUE TITLE
default for select column filter isn't working

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#1383]
admin 9.5.1, laravel 8.83

when I use default for select filter, it's not working

```
        $display->setColumnFilters([
                null, null,
                AdminColumnFilter::select()->setPlaceholder('פעיל')
                    ->setOptions([ 1 => 'yes', 0 => 'no'])
                    ->setDefault(1),
            ]);

```

this simply sends an empty search value, even if I click 'filter' manually

the only way to fix it is to switch to another value, filter, then switch back to 1, and filter again

**Comment by ccaioadriano** [comment]
try it:

$default = AdminColumnFilter::select()->setPlaceholder('פעיל')
                    ->setOptions([ 1 => 'yes', 0 => 'no'])
                    ->setDefault(1)->get();

$display->setColumnFilters([
                null, null, $default
            ]);

**Comment by eugenem** [comment]
emm?

 Call to undefined method SleepingOwl\Admin\Display\Column\Filter\Select::get()

**Comment by daaner** [comment]
Select filters in display mode have problem for select "0"
Try this (dev brunch)
```
AdminColumnFilter::select()
                ->setOptions([
                    'false' => 'Line 0',
                    '1' => 'Line 1',
                    '2' => 'Line 2',
                    '3' => 'Line 3',
                    '4' => 'Line ...',
                ])
                ->setWidth('180px')
                ->setColumnName('line')
                ->setPlaceholder('All line'),
```
