### ISSUE TITLE
Breadcrumbs - Ошибка после обновления с 4.37 бета до 4.40

### ISSUE THREAD

**Issue by Seiger** [LaravelRUS/SleepingOwlAdmin#146]
FatalThrowableError in AdminController.php line 34:
Fatal error: Class 'Breadcrumbs' not found

**Comment by Makashov** [comment]
Проблему решил. Нужно добавить следующее строки в файл sleeping_owl.php

В массив 'providers'
`DaveJamesMiller\Breadcrumbs\ServiceProvider::class,`

В массив 'aliases'
`'Breadcrumbs' => DaveJamesMiller\Breadcrumbs\Facade::class,`

**Comment by 7immy** [comment]
Thanks @Makashov.

Are changes like this documented anywhere? It would be extremely useful for next time :)

**Comment by Seiger** [comment]
Спасибо, работает. Поддерживаю **7immy** нужно добавить в документацию.

**Comment by Makashov** [comment]
This error will not appear if you installing SleepingOwl with 
`$ php artisan sleepingowl:install`
command.
Because this command is creating sleeping_owl.php file if it's not exists.

Sorry for my english :)

**Comment by 7immy** [comment]
Oh right. I used `composer update`. Thanks for the info :)
