### ISSUE TITLE
Custom Form Elements as Independent Packages

### ISSUE THREAD

**Issue by avilaj** [LaravelRUS/SleepingOwlAdmin#154]
I have created a few custom element for previous sleeping owl admin versions.
I want to create a new composer module so I share here at github to be reusable.
Can you provide us an example on how to approach this?

Creating a custom element is related to -> https://github.com/LaravelRUS/SleepingOwlAdmin/issues/79
In advance, thank you and sorry for the troubles.

**Comment by butschster** [comment]
Hi, you should to create a new composer package with your classes and ServicePrivider class in their you need register your custom elements

```php
namespace YourNamespace\Providers;

use Illuminate\Support\ServiceProvider;

class YourNameServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
          $this->app['sleeping_owl.form.element']
              ->add('customElement', \YourNamespace\Elements\CustomFormElement::class)
              ->add('anotherCustomElement', \YourNamespace\Elements\CustomFormElement1::class)
             ....
             ;
    }
}
```

and after install package you need to include your service provider in laravel application.

Profit.

Using:

```php
AdminFormElement::customElement(...)

AdminFormElement::anotherCustomElement(...)
```
