### ISSUE TITLE
Add custom plugins to ckeditor

### ISSUE THREAD

**Issue by Badou90** [LaravelRUS/SleepingOwlAdmin#155]
Searched for this feature, but still dont know how to add custom plugins to ckeditor
I know that there is config part in `sleeping_owl.php` file, but it trying to get files from ckeditor cdn standart package, not from local folders

**Comment by butschster** [comment]
Try to add in boostrap.php

```php
PackageManager::get('ckeditor')
  ->js('ckeditor.plugin.test', asset('libs/path_to_plugin.js'), 'ckeditor')
  ->js('ckeditor.plugin.test1', asset('libs/path_to_plugin.js'), 'ckeditor')
  ->css('ckeditor.plugin.css', asset('libs/path_to_plugin.css'));
```

and then configure editor settings

sleeping_owl.php
```php
'wysiwyg' => [
        ...
        /*
         * See http://docs.ckeditor.com/#!/api/CKEDITOR.config
         */
        'ckeditor'  => [
            'height' => 200,
        ],
        ...
    ],
```

**Comment by alehkudrevich** [comment]
Hello.
I want to add own plugin to ckeditor. added

bootstrap.php
```javascript
PackageManager::get('ckeditor')->js('ckeditor.plugin.simplebox', asset('packages/sleepingowl/admin/ckeditor/plugins/simplebox/plugin.js'), 'ckeditor');
```

sleeping_owl.php
```javascript
'ckeditor' => [
            'allowedContent' => true,
            'extraPlugins' => 'simplebox',
        ],
```

As a result browser display errors.

![ckeditorerror](https://cloud.githubusercontent.com/assets/12971257/16875196/6cd613ba-4a9e-11e6-9f07-db8c8c4fd087.png)

**Comment by Badou90** [comment]
I think that first you need to ovveride default ckeditor plugin like
`PackageManager::add('ckeditor')
    ->js('ckeditor', resources_url('libs/ckeditor/ckeditor.js'), 'jquery');`

I put custom ckeditor in packages/sleepingowl/default/libs for this purpose
Now when i try to connect some plugin via config it shows me that 

`Resource name "imageuploader" was not found at "http://domain.loc/packages/sleepingowl/default/libs/ckeditor/plugins/imageuploader/plugin.js?t=G6DD".`

**Comment by butschster** [comment]
My experience:

- download ckeditor from here http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.8/ckeditor_4.4.8_standard.zip
- place files here `public/libs/ckeditor`
- replace ckeditor script path
```php
// app/Admin/bootstrap.php
PackageManager::add('ckeditor')
    ->js('ckeditor', asset('libs/ckeditor/ckeditor.js'));
```
- seeting config path
```php
// config/sleeping_owl.php

...
'wysiwyg'     => [
    'default'   => 'ckeditor',

    /*
     * See http://docs.ckeditor.com/#!/api/CKEDITOR.config
     */
    'ckeditor'  => [
        'height' => 300,
        'customConfig' => '/libs/ckeditor/config.js' // If you want use javascript config
    ],
...
```

```js
// libs/ckeditor/config.js

CKEDITOR.editorConfig = function( config ) {
      // Define changes to default configuration here.
      // For complete reference see:
      // http://docs.ckeditor.com/#!/api/CKEDITOR.config

      ...
}
```

PROFIT!

**Comment by dandarie** [comment]
For me, it worked like this:

1. add this to app/Admin/bootstrap.php:
```
WysiwygManager::register('ckeditor')
              ->js(null, '//cdn.ckeditor.com/4.5.7/standard-all/ckeditor.js', ['jquery']);
```
2. edit config/sleeping_owl.php:
```
'ckeditor'  => [
            'height'                    => 400,
            ...
            'extraPlugins'              => 'justify',
            'toolbar'                   => [
                ...
                [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ]
        ],
```

**Comment by eugenem** [comment]
It stopped working at new versions. Tried:

```
PackageManager::add('ckeditor') ->js('ckeditor', '//cdn.ckeditor.com/4.5.7/standard-all/ckeditor.js', 'jquery');

#WysiwygManager::register('ckeditor')
#    ->js(null, '//cdn.ckeditor.com/4.5.7/standard-all/ckeditor.js', ['jquery']);
```

How do I do it properly?
