### ISSUE TITLE
admin.scripts loading before admin-default.js

### ISSUE THREAD

**Issue by bryce13950** [LaravelRUS/SleepingOwlAdmin#159]
This is causing a number of issues on the current develop branch at the follow snapshot https://github.com/LaravelRUS/SleepingOwlAdmin/tree/83c3eed04775067679a98cc72bfd17eab18e23a0. The script in admin.scripts is attempting to reference window.Admin before it is created in admin-default.js. I found the issue in Safari 10, but I was also able to reproduce the issue in Firefox.

![screen shot 2016-06-14 at 10 44 49 pm](https://cloud.githubusercontent.com/assets/6487928/16067573/6bc70282-3283-11e6-942a-3b54a20f8ba0.png)

**Comment by bryce13950** [comment]
Can I get some information on this? I am still getting this error, and I am now actually getting more errors. It seems to me that the load order for all JS assets is messed up. I added a date picker to a page, and the date picker is now the second asset loaded on that page right after /admin/assets/admin.scripts. This means that jQuery is not being loaded before it.

![screen shot 2016-06-30 at 7 16 35 pm](https://cloud.githubusercontent.com/assets/6487928/16508296/447dab88-3ef7-11e6-9aef-effedabfdbcb.png)

![screen shot 2016-06-30 at 7 16 54 pm](https://cloud.githubusercontent.com/assets/6487928/16508298/489c1c36-3ef7-11e6-9857-3ce081c5eec2.png)

**Comment by butschster** [comment]
Do you have same errors if you see http://demo.sleepingowladmin.ru/admin ?

**Comment by bryce13950** [comment]
I have not found this error in the demo. Is it possible that one of the functions I am calling is changing the scripts order?
