### ISSUE TITLE
Please do not  add bower package to git

### ISSUE THREAD

**Issue by shellus** [LaravelRUS/SleepingOwlAdmin#167]
- this Git repository size is too big.

- It should allow users to install their own bower package，Otherwise there will be repeated bower package.

- bower package must have its own installation process, but can not directly use the file, which may lead to missing bower package dependencies

- Tell the users to execute this command：
```bash
bower install --save jquery bootstrap bootbox datetimepicker fontawesome moment nestable noty ckeditor Sortable select2 flow.js ekko-lightbox metisMenu datatables startbootstrap-sb-admin-2
```
Then, allowing users to configure their bower package storage path

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/tree/feature/webpack
