### ISSUE TITLE
how to make read only data?

### ISSUE THREAD

**Issue by EvgenyVetrov** [LaravelRUS/SleepingOwlAdmin#173]
### Удобная штука из yii2:
В yii2 и его генераторе админкив дополнение к удалению и редактированию записи, есть еще только чтение.
На скриншоте как раз 3 элемента (чтение / редактирование / удаление)
![image](https://cloud.githubusercontent.com/assets/15690133/16362079/276ea7ce-3bad-11e6-99d9-15a42eea4e59.png)

При чтении выходит вот что:
![image](https://cloud.githubusercontent.com/assets/15690133/16362094/a3f298dc-3bad-11e6-9b9b-61adc0dc5b5d.png)

Очень удобно. Можно продемонстрировать любую информацию системную, не боясь что кто-то нечаянно изменит то что не нужно менять. Повышается удобство и дуракастойкость.

### Как дела в сове:
В сове наблюдаю только 2 возможные позиции (или я чего-то не знаю). Предлагаю добавить возможность добавления 3ей кнопки только для чтения.

**предложение_2:**
При редактировании дать возможность сделать некоторые элементы нередактируемыми, например так:
![image](https://cloud.githubusercontent.com/assets/15690133/16362141/1ab46594-3baf-11e6-9418-f2921dfb3ac6.png)

Это может быть удобно когда нужно разрешить редактирование только части элементов, при этом что бы иметь перед глазами значения элементов, в которые не нужно совать свои шаловливые ручёнки.

**Comment by CrazyRedScorp** [comment]
По поводу просмотра не в курсе, а вот на счет "нередактируемые" я писал в #165
`AdminFormElement::text('phone', 'Phone')->setReadonly(1),`

**Comment by EvgenyVetrov** [comment]
setReadonly - да тема хорошая, спасибо.
но все таки основной посыл предложения - добавить чтение данных

**Comment by butschster** [comment]
Никто не мешает для этого использовать `AdminColumn`

```php
AdminForm::panel()
   ->addHeader(
       AdminFormElement::text('title', 'Title')->required()
  )
   ->addBody(
       AdminColumn::datetime('date'),
       ....
  )

```
