### ISSUE TITLE
When i used "Images" i have error

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#175]
ErrorException in helpers.php line 747:
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

`'insert into `product_images` (`product_id`, `filename`) values (1, ?)', 'value' => array('images/uploads/da475691e004664ae9bacc22bcaaf48b.jpg', 'images/uploads/e3d502e2e47a65b3678ffd501ca9a606.jpg')))`

I just added field Images ((

**Comment by foRsxs** [comment]
В закрытых нашел, что решает вопрос 

protected $casts = [ 'photos' => 'array' ]

**Comment by egorr-yaroslavl** [comment]
> В закрытых нашел, что решает вопрос
> protected $casts = [ 'photos' => 'array' ]

foRsxs, а можно подробнее о решении? Я ещё не очень в теме...
