### ISSUE TITLE
Multiple image

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#176]
Можно ли как сделать возможность загружать сразу несколько фоток,а не одну.
Или подскажите куда копать,что бы самому расширить стандартную загрузку изображений.

**Comment by foRsxs** [comment]
Есть загрузка нескольких Images. но она у меня не работает. В демо посмотрите

**Comment by Fessnik** [comment]
И правда есть,крутяк, спасиба)
