### ISSUE TITLE
Улучшение сортировки строк таблиц

### ISSUE THREAD

**Issue by rorc** [LaravelRUS/SleepingOwlAdmin#178]
Было бы неплохо перенести существующий механизм сортировки на стороннее готовое решение, типа http://packalyst.com/packages/package/rutorika/sortable, http://packalyst.com/packages/package/spatie/eloquent-sortable и т. п.

**Comment by butschster** [comment]
Было бы не плохо предоставить приблизительный вариант функционала и я бы его доработал.

**Comment by aios** [comment]
Внедрение дополнительных пакетов в админку отклоняется. Мы поддерживаем политику сделать так что бы вы могли подключить любой удобный вам пакет самостоятельно и не прилагать при этом больших усилий. В самой админке пакетов и так уже достаточно.

**Comment by Butochnikov** [comment]
@aios тогда поступаем как деревом? будет поддержка разных пакетов, а подключать или нет уже дело пользователя, так?
