### ISSUE TITLE
Как добавить свою страницу?

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#179]
Как можно в админке создать свою кастомную страницу?

**Comment by butschster** [comment]
На демо сайте есть пример https://github.com/SleepingOwlAdmin/demo/blob/master/app/Http/Controllers/HomeController.php

https://github.com/SleepingOwlAdmin/demo/blob/master/app/Admin/routes.php#L3

**Comment by Fessnik** [comment]
Спасибо
