### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by budeci** [LaravelRUS/SleepingOwlAdmin#19]
когда заходишь в admin NotFoundHttpException in RouteCollection.php line 161.
как это можно исправить?

Спасибо.

**Comment by butschster** [comment]
Нужно больше подробностей.

Когда установил. Каким образом устанавливал, сделал ли миграции и т.д.

**Comment by budeci** [comment]
установил laravel 5.2 
потом по инструкции установила SleepingOwlAdmin 
в migration попала только 3 таблица (migrations, users, password_resets)

**Comment by butschster** [comment]
@budeci you can use english language

**Comment by butschster** [comment]
Show me your instruction. I think, you trying to install old version.

Try to use this repo https://github.com/LaravelRUS/SleepingOwlAdminDemo to start new project.

**Comment by budeci** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin instruction

**Comment by rramel** [comment]
I Have the same problem but I downloaded a v4 version <NotFoundHttpException in RouteCollection.php line 161. Anyone has a solution ? Thanks
