### ISSUE TITLE
create/edit many related items on a parents edit page. 

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#195]
Currently its posible to set a child to belong to a parent(s) where it is apart of a database relationship. However I was wondering if it was possible to edit child records while being on a parent edit page.

I've tried this just to see if I could edit a single child from a parent's form:

```
AdminSection::registerModel(DownloadableForm::class, function (ModelConfiguration $model) {
  $model->onCreateAndEdit(function() {
          return AdminForm::panel()
            ->addBody(
               AdminFormElement::text('field_name')
                  ->setModel(DownloadableFormField::class)
            );
  })
})
```

However I get this:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_name' in 'field list' (SQL: insert into downloadable_forms  ... etc`
This is obvious as its trying to find the field in the wrong database and the id is going to be wrong too.

It would be great if we could create a repeater element like this:

```
            AdminFormElement::repeaterOneToMany('id')
                ->setManyModel(DownloadableFormField::class)
                ->setManyFields([
                    AdminFormElement::text('field_name', 'field name'),
                    AdminFormElement::text('file_extension', 'file extension'),
                    AdminFormElement::text('description', 'Description'),
                    etc..etc..
                ]),
```

**Comment by butschster** [comment]
Maybe like this:

```php
$form = AdminForm::form()->setElements([
      AdminFormElement::text('title', 'Title'),
      ...
]);

$form->addElement(
      // Set relation HasMany or ManyToMany
      AdminFormElement::relatedElements('reltion_name')
          ->setElements([
                    AdminFormElement::text('field_name', 'field name'),
                    AdminFormElement::text('file_extension', 'file extension'),
                    AdminFormElement::text('description', 'Description'),
         ])
)
```

After form render:

```html
<form>
<input name="title" />

// relation fields
<related form>
<group>
    // Attached item 
    <input name="field_name[{related_id}]" />
    <input name="file_extension[{related_id]" />
    <input name="description[{related_id]" />
    // Remove row
</group>
<group>
     // new item 
    <input name="field_name[]" />
    <input name="file_extension[]" />
    <input name="description[]" />
    // Remove row
</group>
    // Add new row
</related form>


// form buttons
</form>
```

**Comment by 7immy** [comment]
This is looking great! :D

We may want to make the input names a bit more unique though and consider what might happen if we had:
* More than one related form - how do we identify which related form is which when saving the data?
* If there is more than one related form. There may also be inputs with the same names
* The parent form could have similar input names which might get overridden when POSTing.

Also validation maybe an issue with newly un-saved groups that failed validation. There will need to be a way to re-create the un-saved related groups so the users can correct the invalid inputs.

**Comment by butschster** [comment]
`reltion_name[field_name][]` ?

**Comment by 7immy** [comment]
That would do 👍

**Comment by 7immy** [comment]
I think in lots of cases the order of the element will also need to be taken into account too.
`order[{related_id}]`. This would be updated with javascript on the front-end.

**Comment by 7immy** [comment]
See form array validation: https://laravel-news.com/2015/11/laravel-5-2-a-look-at-whats-coming/

**Comment by sergiy-lytvyn** [comment]
**error** 
BadMethodCallException in AliasBinder.php line 95: relatedElements

**Comment by aios** [comment]
@7ammer @sergiy-lytvyn WIP
