### ISSUE TITLE
files/images does not upload, internal server error

### ISSUE THREAD

**Issue by alexbeat96** [LaravelRUS/SleepingOwlAdmin#199]
Когда я пытаюсь добавить изображение или просто файл через
`AdminFormElement::image('logo', 'Логотип')`
ничего не происходит, а в консоли разработчика вылетает:
`flow.min.js:2 POST http://*домен*/admin/FormElements/image/uploadImage 500 (Internal Server Error)`
и
`VM4729:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0`
Знания Laravel еще маленькие, только начинаю его осваивать, последние 3 дня сутками сижу, но ответа пока не нашел, что делать.

----------------------------------------
When I try to add an image or a file through
`AdminFormElement::image('logo', 'Логотип')`
nothing happens, and the Developer Console is written:
`flow.min.js:2 POST http://*домен*/admin/FormElements/image/uploadImage 500 (Internal Server Error)`
и
`VM4729:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0`
What is it and what to do?

**Comment by xcaptain** [comment]
This means the upload controller didn't return json but returned a error page,  error log in `storage/logs/laravel.log` will be helpful to debug.

**Comment by butschster** [comment]
Попробуй такой вариант https://github.com/LaravelRUS/SleepingOwlAdmin-docs/blob/master/form.md#upload

**Comment by alexbeat96** [comment]
@butschster Не помогло. Теперь в админке есть просто поле, где можно выбрать файл, но он никуда не сохраняется и не отправляется. В логи тоже ничего не сыпет, ошибок нет. Просто ничего не работает)

**Comment by alexbeat96** [comment]
Простите, косяк был во мне, порылся в логах (как же их оказалось много) и понял, что ошибка была в том, что права на /public были неправильные
Поставил 777, заработало

**Comment by greabock** [comment]
По идее 755 должно быть достаточно. Если работает только c 777, это значит, что у тебя неправильно  сконфигурирован сервер, и php  исполняется не от того пользователя. В крайнем случае, даже если у тебя доступ регламентируется группой www, а не конкретным пользователем, то 775, но ни как не 777.
