### ISSUE TITLE
Замена sb-admin2 на adminlte

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#2]
Сейчас используется шаблон админ панели http://startbootstrap.com/template-overviews/sb-admin-2/
Существует альтернативная админ панель https://almsaeedstudio.com/themes/AdminLTE/index2.html

Возможно стоит мигрировать пока не поздно?!

**Comment by Big-Shark** [comment]
+

**Comment by eugene-holiday** [comment]
но оно же было https://github.com/sleeping-owl/admin-lte-template

**Comment by Big-Shark** [comment]
Ну я бы как минимум по дефолту предпочел adminLTE из за лучшей поддержки и распространенности

**Comment by Big-Shark** [comment]
@butschster пожалуйста отписывайся что ты сделал, или что закрыто по такой то причине, а то непонятно.

**Comment by butschster** [comment]
Произведена замена шаблона админ панели.
