### ISSUE TITLE
Как правильно организовать в sleeping-owl Multi-Language

### ISSUE THREAD

**Issue by budeci** [LaravelRUS/SleepingOwlAdmin#20]
Как правильно организовать в sleeping-owl, Multi-Language Content?
Я начинала это с помощью tabbed, для каждого языка отдельный таб. 
[my project](http://joxi.ru/Grqe16MUN86BVr)
---------------------------------------------------------------------------------------------------
есть tabel category_description для меняешься content и tabel prso_categories для поля которые не нужно переводить.
FormItem::text('description["name"][]', 'Category Name'),
description["..."][]
правильно такой подход?
как правильно связать эти два таблица? 
и как его правильно реализовать в sleeping-owl?

Буду рад если кто-то сможет помочь.

**Comment by butschster** [comment]
@budeci you can use english language

**Comment by budeci** [comment]
The right to be organized sleeping owl multi-languages content?
I started this with a tabbed, for each language a separate tab.
[My project](http://joxi.ru/Grqe16MUN86BVr)
-----------------------------------------------------------------
there tabel category_description for changing content and tabel prso categories for fields that do not need to be translated.
FormItem::text('description["name"][]', 'Category Name'),
description["..."][]
correctly, this approach ?
as properly associate these two table ?
и как его правильно реализовать в sleeping-owl?

P.S. Excuse me for my English

**Comment by denistorresan** [comment]
Hello @butschster ,
I'm also interested in this feature, I mean, I have a multi language website that use the dimsav/laravel-translatable plugin (but I think it's the same with others plugin).
The target is to build a CRUD with a form with all translation as described by @budeci .

Sort of this:

http://screenpresso.com/=QBdBg

thank you!

**Comment by butschster** [comment]
Gutten tag, @denistorresan :)
Können Si... oopps.

Can you create new issue and describe your feature request there?

**Comment by denistorresan** [comment]
hello @butschster , done! :-)

https://github.com/LaravelRUS/SleepingOwlAdmin/issues/36

**Comment by sergiy-lytvyn** [comment]
budeci, удалось решить данную проблему ?
