### ISSUE TITLE
Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::getModel()

### ISSUE THREAD

**Issue by MasterRO94** [LaravelRUS/SleepingOwlAdmin#201]
При создании новой сущности (New Entry) на странице с формой с использование  табов выбивает ошибку 

> 
> FatalErrorException in AdminController.php line 133:
> Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::getModel()

На демо сайте она тоже есть

http://demo.sleepingowladmin.ru/admin/contacts/v3/create

Исправте по возможности как можно быстрее

**Comment by Fessnik** [comment]
У меня точно такая же беда ,проект уже сдавать нужно и тут такая штука. 
Нужна хотябы подсказка где копать ,что бы решить проблему или костыль какойто на крайняк :)
Буду очень благодарен!!!

**Comment by Fessnik** [comment]
Спасиба
