### ISSUE TITLE
When I use the tree and tabbed,'DisplayTabbed::getRepository' etc....

### ISSUE THREAD

**Issue by osindex** [LaravelRUS/SleepingOwlAdmin#202]
I want to use the tree and table in tabbed...
When I move the tree structure
`
FatalErrorException in DisplayTree.php line 24:
Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::getRepository()
`
and i use AdminColumnEditable::checkbox in table
`
FatalErrorException in AdminController.php line 241:
Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::getColumns()
`

the packages is dev-development.
and my code like this
```php
$model->onDisplay(function () {
        $display = AdminDisplay::tabbed()->setTabs(function ($id)
        {
            $tabs = [];
            $tree = AdminDisplay::tree()
                        ->setValue('title')
                        ->setOrderField('ordering');
            $table = AdminDisplay::table()
                                ->setApply(function ($query) {
                                    $query->orderBy('ordering', 'asc');
                                })
                                ->setColumns([
                                    AdminColumn::link('title')->setLabel('CateTitle'),
                                    AdminColumn::text('type')->setLabel('CateType'),
                                    AdminColumn::custom()->setLabel('Url')->setWidth('50px')->setCallback(function ($instance) {
                                        return ($instance->slug) ? '<a href="'.config('site.cate').$instance->slug.'" target="_blank" >Go</a>' : 'Setting PL!';
                                    }),
                                    AdminColumnEditable::checkbox('display')->setLabel('Show'),
                                    AdminColumn::order()
                                    ->setLabel('order')
                                    ->setHtmlAttribute('class', 'text-center')
                                    ->setWidth('100px'),
                                    AdminColumn::custom()->setLabel('posts')->setCallback(function ($instance) {
                                        return isset($instance->slug) ? '<a href="/'.config('sleeping_owl.url_prefix').'/'.str_plural($instance->type).'?category_id='.$instance->id.'">Manager</a>('.count($instance->articles).')' : 'Setting slug!';
                                    }),
                                ])->paginate(10);
            $tabs[] = AdminDisplay::tab($tree)->setLabel('ordering')->setActive(true)->setIcon('<i class="fa fa-credit-card"></i>');
            $tabs[] = AdminDisplay::tab($table)->setLabel('setting')->setName('set')->setActive(false)->setIcon('<i class="fa fa-credit-card"></i>');
            return $tabs;
        });
        /* $display->appendTab($table,'setting');*/
        return $display;
 });
```
I will be very grateful.
This framework is very convenient。Thks.

**Comment by osindex** [comment]
I modify DisplayTree.php 21line
<pre><code>
public static function registerRoutes()
    {
        Route::post('{adminModel}/reorder', function (ModelConfigurationInterface $model) {
            if (! method_exists($model->fireDisplay(), 'getRepository')) {
                foreach ($model->fireDisplay()->gettabs() as $object) {
                    if(ends_with($object->getContent()->getView(),'tree'))
                    {
                        @$object->getContent()->getRepository()->reorder(
                            Request::input('data')
                        );
                    }
                }
            }else{
                $model->fireDisplay()->getRepository()->reorder(
                    Request::input('data')
                );
            }
            
        });
    }
</pre></code>
so,i can use the tree in tabbed.

-- The line shold writen (top question)--
`AdminColumnEditable::checkbox('display')->setLabel('Show')`

and the 2nd question about AdminColumnEditable  in tabbed

after 238 line 
<pre><code>
$display = $model->fireDisplay();
if (method_exists($display, 'getTabs')) {
            foreach ($display->gettabs() as $object) {
                if(ends_with($object->getContent()->getView(),'table'))
                {
                    $display = $object->getContent();
                }
            }
        }
</pre></code>

Maybe it's not the best way, but I hope that i can help someone who needs it.

**Comment by butschster** [comment]
Hi. Now you can overide reorder route `admin.display.tree.reorder`.

#### app/Admin/routes.php
```php
Route::post('{adminModel}/reorder', ['as' => 'admin.display.tree.reorder', function (ModelConfigurationInterface $model) {
    if ($model->getClass() == 'App\Post') {
        foreach ($model->fireDisplay()->getTabs() as $object) {
                    if(ends_with($object->getContent()->getView(),'tree'))
                    {
                        @$object->getContent()->getRepository()->reorder(
                            Request::input('data')
                        );
                    }
       }
    } else {
        $model->fireDisplay()->getRepository()->reorder(
              Request::input('data')
        );
   }
}]);
```
