### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by mr-d-orekhov** [LaravelRUS/SleepingOwlAdmin#206]
`   // Display`
`    $model->onDisplay(function () {`
`        /** @noinspection PhpParamsInspection */`
`        return AdminDisplay::table()->setColumns([`
`            AdminColumn::link('name')->setLabel('Сайт'),`
`        ])->paginate();`
`    });`

Если для дисплея не вызвать `->paginate();`, то пагинация не работает

**Comment by butschster** [comment]
Какая версия?

**Comment by mr-d-orekhov** [comment]
4.52.35 но видимо без этой инфы разобрались)
Спасибо!

**Comment by sedovolosiy** [comment]
так что с пагинацией? У меня слетает фильт и сбрасывается пагинация. Если выбрать фильтр по стране, то запрос проходит, фильтрует на 2 старницы, нажимаю на страницу 2 и фильтр сбрасывается. http://demo.sleepingowladmin.ru/admin/contacts/v3?country_id=9
