### ISSUE TITLE
Create an object from tabbed form doesn't work

### ISSUE THREAD

**Issue by myx0m0p** [LaravelRUS/SleepingOwlAdmin#207]
Saving a tabbed form doesn't work.

To reproduce use [this form](http://demo.sleepingowladmin.ru/admin/contacts/v3/create) from demo app.

Just press the 'Save' button to get error. 'Save and close' and 'Save and create' does work.

**Comment by butschster** [comment]
try `composer update`.

**Comment by myx0m0p** [comment]
that didn't update anything.
I have this version.
`"name": "laravelrus/sleepingowl",
            "version": "4.52.35",
            "source": {
                "type": "git",
                "url": "https://github.com/LaravelRUS/SleepingOwlAdmin.git",
                "reference": "1adddabd2f1d784053bbc66c701b58c7e69ae3db"
            },
`

**Comment by butschster** [comment]
Try to update. Problem with release...

**Comment by myx0m0p** [comment]
Just did an update.
  - Removing laravelrus/sleepingowl (4.52.35)
  - Installing laravelrus/sleepingowl (4.52.36)
The error is:
`
FatalErrorException in AdminController.php line 133:
Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::getModel()
`

Same error as before, should i provide more details?

**Comment by butschster** [comment]
I don't see error on this page http://demo.sleepingowladmin.ru/admin/contacts/v3/create

**Comment by myx0m0p** [comment]
Fill the data.
![0534f7dd765748dbaed9abfd2ef32c35](https://cloud.githubusercontent.com/assets/10810328/16942711/3e7453ba-4da0-11e6-87f5-507380dbffe3.png)

Hit submit button.

![2340c0186fcf4251b7bba6339b9fa044](https://cloud.githubusercontent.com/assets/10810328/16942717/422de4c6-4da0-11e6-8f70-d7963ff8815f.png)
The error.
