### ISSUE TITLE
push two items in form please help me

### ISSUE THREAD

**Issue by budeci** [LaravelRUS/SleepingOwlAdmin#21]
`$description = Admin::model(Ecommerce\Productso\Models\CategoryDescription::class)->fullEdit($editId);`

```
$description->items([
    FormItem::hidden('language_id')->defaultValue($id),
    FormItem::hidden('language_id')->defaultValue($item->language_id)
 ]);
```
`$tabs[] = AdminDisplay::tab($description)->label($item->name);`

I want to add two fields in imported form

**Comment by butschster** [comment]
Hi, which version of SleepingOwl admin are you using?

You can see examples here https://github.com/LaravelRUS/SleepingOwlAdminDemo/tree/master/app/Admin

This repository is using 4.x version.

**Comment by budeci** [comment]
I use SleepingOwl v3 
in V3 is possible such a trick?
I want to add two fields in the form imported.
