### ISSUE TITLE
Catalyst sentinel integration

### ISSUE THREAD

**Issue by vovapas** [LaravelRUS/SleepingOwlAdmin#217]
help

**Comment by SerafimArts** [comment]
God help you! :santa:

**Comment by vovapas** [comment]
<?php

namespace App\Http\Middleware;

use Closure;
use Sentinel;
use Redirect;
use SleepingOwl\Admin\Admin;
use Request;

class AdminPanel
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (Sentinel::checkt()){      
        if(Sentinel::inRole('admin')) return $next($request);
       }
        return Redirect::back();          
    }
}

Sentinel::checkt() always return false

**Comment by SerafimArts** [comment]
@vovapas its a problem of Sentinel, not Owl ;)

Is not it so?

**Comment by vovapas** [comment]
А как это можно исправить?

**Comment by SerafimArts** [comment]
@vovapas Ну смотри:
1) Ошибка никак не касается совы
2) Лично я в глаза не видел эту хрень - сентинель
3) И совершенно очевидно, даже незнающему человеку, что у функции `checkt` не существует - у тебя опечатка в названии.

Но это первый и последний раз, это не форум помощи по непонятным пакетикам, а багтрекер ошибок совы. ;)

**Comment by vovapas** [comment]
хорошо спасибо за помощь)

**Comment by Zolotov88** [comment]
Я нашел в чем дело. 
В файле app/Http/Kernel.php
```
protected $routeMiddleware = [
        ...
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'isadmin' => \App\Http\Middleware\AdminPanel::class,
    ];
```
В config/admin.php
`'middleware' => ['web', 'isadmin'],`

**Comment by vovapas** [comment]
Спасибо сработало)
только не в Admin.php а sleeping_owl.php

**Comment by Zolotov88** [comment]
А, да, точно)
