### ISSUE TITLE
Пункт Ничего не выбрано появляется дважды

### ISSUE THREAD

**Issue by nizewest** [LaravelRUS/SleepingOwlAdmin#218]
Для Radio элемента со свойством $nullable = true; пункт "Ничего не выбрано" появляется дважды.
![2016-07-22_17-59-54](https://cloud.githubusercontent.com/assets/14124337/17061239/3551d102-5036-11e6-96a8-a4826254b9f7.jpg)

**Comment by Butochnikov** [comment]
@butschster сейчас `radio` вообще не работает https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/Radio.php
