### ISSUE TITLE
Uploading images doesn't work

### ISSUE THREAD

**Issue by jokagent** [LaravelRUS/SleepingOwlAdmin#220]
Trying to follow instruction for file upload field, but images are not uploaded without showing any errors. 
When i'm debugging trait Upload in package KodiComponents, i see it failing to pass this block
`if ($model->{$key} instanceof UploadedFile) { `
So i `$model->{$key}` is not an instance of UploadedFile?
How should i configure my model to make it work?

Code here: https://gist.github.com/jokagent/64ab752ddbba2acc169e4d39f9e26c8f

**Comment by butschster** [comment]
Может стоит указать с каким типом поля ты хочешь использовать?

**Comment by jokagent** [comment]
C типом поля image
`AdminFormElement::upload('image', 'Image')`

**Comment by butschster** [comment]
что за проблема? какие ошибки?

**Comment by jokagent** [comment]
В том-то и дело, что ошибок нет, просто файл не загружается ( или не обрабатывается ).
Если о чем-то говорит, то пост приходит со статусом
`Request URL:http://glass/admin/glass_types/6/edit
Request Method:POST
Status Code:302 Found`

**Comment by butschster** [comment]
Проверь наличие в шаблоне формы `multipart/form-data`

**Comment by jokagent** [comment]
Да, его нет. После добавления через средства разработчика файл загрузился.

**Comment by butschster** [comment]
Добавь в к форме `->setHtmlAttribute('enctype', 'multipart/form-data')`

**Comment by jokagent** [comment]
Спасибо, теперь работает.

**Comment by Malezha** [comment]
Возможно элемент `upload` находится в колонке, у меня тоже был с этим небольшой затуп =)
