### ISSUE TITLE
Admin routes now have lower priority over main laravel routes.php file

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#222]
I've recently updated to the latest version of SleepingOwl and have found that /admin routes now have lower priority over the routes in my main laravel routes.php file.

Is there any way to revert this?

**Comment by butschster** [comment]
@7ammer hi, try to use temporarily
```php
app()->booted(function() {
     ....
})
````

**Comment by 7ammer** [comment]
Will do, thanks!

**Comment by worthers** [comment]
Hi @butschster can you elaborate on how to work around this?

In all my projects I like to have a route like so:

```
Route::get('/{page_slug}', [
	'uses' => 'PagesController@showPage',
	'as' => 'page'
]);
```

And this breaks with SleepingOwl as I can't change the priority order of the SleepingOwl routes. How can I solve this?

**Comment by 7ammer** [comment]
Hi @worthers, I didn't use `app()->booted(function() {...})` in the end as I wasn't sure how to place sleepingowl's 'core' routes inside the method. Instead I did something like the below:

```
$path_array = explode( "/", Request::path() );

if($path_array[0] != "admin"){
  Route::get('/{page_slug}', [
    'uses' => 'PagesController@showPage',
    'as' => 'page'
  ]);
}
```

It would be nice to know if there was a simpler solution though.

**Comment by worthers** [comment]
Cool - thanks @7ammer. 

The regular expression is a good work around.

But the other method means the route name becomes unavailable for use in the SleepingOwl: e.g. `route('page', [...])` can't be used because it isn't defined when the if statement excludes it.
