### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by denismitr** [LaravelRUS/SleepingOwlAdmin#223]
On the latest version `AdminFormElement::upload('image', 'Image')` does not automatically generate  `enctype="multipart/form-data"` for the form. And hence nothing works. Hopefully `AdminFormElement::image('image', 'Image')` does work, but this way I can't use The __Intervention Image__ library.

**Comment by butschster** [comment]
Try to add this

```php

return AdminForm::panel()
    ....
    ->setHtmlAttribute('enctype', 'multipart/form-data');
```

**Comment by denismitr** [comment]
Thanks, that works!
