### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rkorebrits** [LaravelRUS/SleepingOwlAdmin#23]
Is there any documentation? 

https://github.com/LaravelRUS/SleepingOwlAdmin documentation links to http://sleeping-owl.github.io/v4 but doesn't work; 404

http://sleeping-owl.github.io/ takes me to http://sleeping-owl.github.io/en/Getting_Started/Installation.html => V2 docs
Which links to: https://github.com/sleeping-owl/admin (old repo)

Default examples in product for users model don't work out of the box. are they supposed to?

Some documentation would be great

**Comment by butschster** [comment]
Hi, documentation is in progress.

See demo app for new version https://github.com/LaravelRUS/SleepingOwlAdminDemo/tree/master/app/Admin

**Comment by butschster** [comment]
Russian documentation here https://github.com/LaravelRUS/SleepingOwlAdmin-docs (**In progress**)
