### ISSUE TITLE
Not able to install master branch

### ISSUE THREAD

**Issue by mirzavu** [LaravelRUS/SleepingOwlAdmin#232]
Not able to install master stable branch. This command given in the doc install the development branch:

composer require laravelrus/sleepingowl:4.*@dev

**Comment by Malezha** [comment]
Master branch outdated. Try to use releases `4.52.*` or development branch `4.x-dev`.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.55.51
