### ISSUE TITLE
dependence package KodiCMS/laravel-assets error

### ISSUE THREAD

**Issue by feefk** [LaravelRUS/SleepingOwlAdmin#233]
I update sleepingOwlAdmin to lastest, I find this error when I run http://localhost/admin 
`{
"message":"Call to undefined method KodiCMS\\Assets\\Meta::getJsList()","code":1,"status_code":500,"debug":{"line":215,"file":"\/{profect_root}\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":["#0 {main}"]}}`

I find the function of getJsList had removed from KodiCMS/laravel-assets after V.0.2.0.

then what can I do for the problem?

**Comment by butschster** [comment]
Hi. This method not removed 
https://github.com/KodiCMS/laravel-assets/blob/master/src/Traits/Scripts.php#L89

Show me your version of `KodiCMS/laravel-assets`

**Comment by feefk** [comment]
Hi
kodicms/laravel-assets  version is v0.1.18。
laravelrus/sleepingowl (4.52.36) be in normal working，but laravelrus/sleepingowl (dev-development 802e266) have this problem。
![qq20160811-0](https://cloud.githubusercontent.com/assets/285585/17582536/ee378c2c-5fde-11e6-889b-6fe792332e43.png)

**Comment by butschster** [comment]
update `kodicms/laravel-assets` to version 0.2.*

**Comment by feefk** [comment]
kodicms/laravel-assets v0.2.0 requires laravel/framework 5.2.*, but my laravel is 5.1.*

**Comment by butschster** [comment]
https://github.com/KodiCMS/laravel-assets/releases/tag/v0.3.1

**Comment by feefk** [comment]
It works.

@butschster Thank you very much.
