### ISSUE TITLE
Class Admin not found

### ISSUE THREAD

**Issue by mirzavu** [LaravelRUS/SleepingOwlAdmin#234]
I have installed new version 4.52. And according to documentation I have added Model configuration in Admin/bootstrap.php as given in the below link:

http://sleeping-owl.github.io/en/Getting_Started/Model_Configuration.html

But throws this error:
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Admin' not found

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin-docs/blob/master/model_configuration.md

**Comment by mirzavu** [comment]
Bad that it is not conveyed which doc should be refered to specific version.
