### ISSUE TITLE
Buttons Settings

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#237]
hello. im using L5.2 + SleepingOwl 4 and i cant find documentation or info about the following things:

1) how to change dinamically the "New Entry" button? (i dont wanna change it in lang file, because i will need different button texts for each table)

2) how to set a new URL/route for a Cancel button (inside the create form)?

Thanks

**Comment by macedodebrito** [comment]
Hello @butschster .

thanks for the feature.

1) for my 1st question:

 im trying to use it but im missing something... i tried several ways do use that new feature...

`$display = AdminDisplay::table()->paginate(10)->setNewEntryButtonNext('Nova Entrada');`
OR
`$display->setParameter('setNewEntryButtonText', 'Nova Entrada');`

2) For my my 2nd question:

i managed to "fix" it with routes. i added a route to force a new URL.

```
Route::get('/admin/requests/cnc_history', ['as' => 'admin.requests.cnc_history', function () {
            return Redirect::to('/admin/cnc');
        }]);
```

NOTE)

After this new update, my AdminDisplay::datatables(); had an issue.

I have 2 tables in same view. 
Both had the ::datatables() instead ::table(), so i could use the default DATATABLES headers and footer (search and pagination). 
After this update, only the first table have the HEADER/FOOTER. The second table wont load it. its just loading like a normal table.

Any idea why is this happening?

Thanks

**Comment by butschster** [comment]
Yo have mistake in your code `$display = AdminDisplay::table()->paginate(10)->setNewEntryButtonNext('Nova Entrada');` NOT `setNewEntryButton !!!Next!!!`

**Comment by macedodebrito** [comment]
sorry @butschster . it was a typo.

$display = AdminDisplay::table()->paginate(10)->setNewEntryButtonText('Nova Entrada');

Yeah, its working now.

do you know why your new update had some issues with the ::datatables() header?

**Comment by butschster** [comment]
Show me code

**Comment by macedodebrito** [comment]
ok.

i have 2 tables in same view.

```
{!! AdminSection::getmodel('App\Model\CNC_open')->fireDisplay() !!}
{!! AdminSection::getmodel('App\Model\CNC_history')->fireDisplay() !!}
```

then, in App/Admin/CNC_open.php, i have:
```
$model->onDisplay(function () {
        $display = AdminDisplay::datatables();
```

Before last updates (i think last 2), i had the same code in the second table file (App/Admin/CNC_history.php):
```
 $model->onDisplay(function () {
        $display = AdminDisplay::datatables()->paginate(10);

```
Now, its the same, having AdminDisplay::datatables() or AdminDisplay::table(), i cant load the HEADERS in the second table.

atm the moment i just use this one:

```
 $model->onDisplay(function () {
        $display = AdminDisplay::table()->paginate(10)->setNewEntryButtonText('Nova Entrada');
```

I switched from 1st to 2nd, and the HEADER will load in 2nd one, if i use ::table() in 1st table.

wierd :(

**Comment by macedodebrito** [comment]
seems this is fixed. dunno if its a minimum of rows = no display but... its fixed.

if i get this probem again, i will open a new thread.

thanks @butschster .
