### ISSUE TITLE
Laravel 5.3: Undefined method Application::bindShared()

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#238]
```
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::bindShared()
in/Users/jamesisbell/Documents/Projects/webrose/vendor/laravelcollective/html/src/HtmlServiceProvider.php on line 36
```

**Comment by 7ammer** [comment]
Maybe helpful: https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-illuminatefoundationapplicationbindshared

**Comment by 7ammer** [comment]
Changing lines 36 and 49 to use `$this->app->singleton(...)` works

**Comment by butschster** [comment]
This package https://github.com/LaravelCollective/html is not support Laravel 5.3 now
