### ISSUE TITLE
Laravel 5.3: Class 'App\Providers\AdminSectionsServiceProvider' not found

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#239]
After running `php artisan sleepingowl:install` in Laravel 5.3 I get:

```
Class 'App\Providers\AdminSectionsServiceProvider' not found
```

**Comment by butschster** [comment]
Go to `app\Providers` and delete file `AdminSectionsServiceProvider.php` and then run `composer update`

**Comment by Ellrion** [comment]
see #251

**Comment by Butochnikov** [comment]
можем закрывать?
