### ISSUE TITLE
Как добавить два Badge на один пункт меню

### ISSUE THREAD

**Issue by CrazyRedScorp** [LaravelRUS/SleepingOwlAdmin#240]
Доброго времени суток.
Подскажите, как добавить два ярлыка `Badge` на пункт меню, если такое вообще возможно?

При попытке вызвать два раза подряд метод `AddBadge` - в меню будет высвечиваться только последний. А при попытке передать массив/набор получаем ошибку:
```
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: htmlentities() expects parameter 1 to be string, array given (View: /vendor/laravelrus/sleepingowl/resources/views/default/_partials/navigation/badge.blade.php)
```

**Comment by CrazyRedScorp** [comment]
А еще хотелось бы иметь возможность по разному раскрашивать ярлыки типа так:
![32c5b5689c](https://cloud.githubusercontent.com/assets/12952022/17772173/ba1cd122-6560-11e6-8f36-234d97917e47.png)

**Comment by butschster** [comment]
Метод `addBadge` на входе ожидает класс реализующий интерфейс `KodiComponents\Navigation\BadgeInterface`. Т.е. тебе необходимо создать свой класс, который реализует данный интерфейс и в нем может реализовать вывод бейджев так как тебе угодно.

**Comment by Butochnikov** [comment]
сразу в доку решения складывать или завести раздел tips and tricks

**Comment by CrazyRedScorp** [comment]
Все руки ~мозги~ не доходят сделать по уму, однако что есть.
Скажу сразу, как всегда, делалось на скорую руку _(еще в августе по совету Павла)_ и мое решение грубо говоря притянуто за уши.
Итак:
1. создал [/app/MyBadge.php](http://laravel.io/bin/Lkrme)
2. создал [/resources/views/includes/partials/badge.blade.php](http://laravel.io/bin/6LNnr)
3. изменил в админ-модели добавление беджа [/app/Http/Admin/aClient.php](http://laravel.io/bin/zjJrJ)
4. получил вот такую шляпу
![badge_01](https://cloud.githubusercontent.com/assets/12952022/21080042/8e85d250-bfc6-11e6-9368-24db08102a8c.png)
5. А все потому что не смог отцепиться от основного шаблона
`/vendor/laravelrus/sleepingowl/resources/views/default/_partials/navigation/badge.blade.php`
и пришлось его целиком заменить просто на:
`{!! $value !!}`
6. Получил почти что требовалось:
![badge_02](https://cloud.githubusercontent.com/assets/12952022/21080043/8e88f714-bfc6-11e6-9ea8-795021fa84d0.png)

Из косяков:
1. конечно же правка основного шаблона в `vendor` ~по рукам был бит и не один раз~ жескач еще тот, но, увы не знаю как отцепиться от него. Планировалось чтобы все варилось на уровне моих шаблонов из моей папки `/resources/views/`. Пробовал по разному подкладывать шаблоны в `/resources/views/vendor/sleepingowl/.....` и играться с их подключением в `$view = config('navigation.view.badge', 'navigation::badge');` и выводом через `return`, но не получилось, упорно тянет из `vendor`.
2. неудобная передача параметров, хотелось бы передавать в виде `[11, 'danger'],[22, 'info'],....`
3. при выводе 5 значений заметно что они наплывают на само название в меню, хотя и при двух значения скажем 1234 и 5678, будет тоже самое. 

Хотя если посмотреть что на выхлопе в html, то будет http://laravel.io/bin/eDz1B А хотелось бы получить вот так http://laravel.io/bin/MkaV8 Почему хотелось бы:
a. во-первых, чтобы со временем засунуть туда еще и hint всплывающий _(и передавать его третьим параметром)_
b. во-вторых, если у спана убрать `position: absolute;`
в стиле:
![badge_04](https://cloud.githubusercontent.com/assets/12952022/21080245/408196ce-bfcc-11e6-8f5f-9f0798dd79b1.png)
то получим практически что и хотелось:
![badge_03](https://cloud.githubusercontent.com/assets/12952022/21080230/06c1ea60-bfcc-11e6-849b-7058f5d92db0.png)
Хотелки юзались на прямую в браузере Chrome, до реализации на уровне своего класса - не дополз. В связи с чем, многоуважаемые гуру, может возьметесь за реализацию правильного решения или как-то докостылить/улучшить/отпимизировать это?

**Comment by sngrl** [comment]
Просто пишу сообщить, что вот эта проблема при использовании addBadge() все еще актуальна:

![](https://cloud.githubusercontent.com/assets/12952022/21080042/8e85d250-bfc6-11e6-9368-24db08102a8c.png)

В принципе решается созданием объекта бейджа, вызовом у него setHtmlAttributes и добавлением через setBadge().

**Comment by aios** [comment]
@sngrl Код пожалуйста.

**Comment by sngrl** [comment]
При вот таком коде получаем абракадабру:

`->addBadge(new Badge(123), ['class' => 'label-primary'])`

![](https://cloud.githubusercontent.com/assets/12952022/21080042/8e85d250-bfc6-11e6-9368-24db08102a8c.png)

А так все ок:

`->setBadge((new Badge(123))->setHtmlAttributes(['class' => 'label-primary']))`

**Comment by aios** [comment]
@sngrl  значит нужно выпилять - либо стандартизировать.
