### ISSUE TITLE
После обновления слетел css и js

### ISSUE THREAD

**Issue by RobVorch** [LaravelRUS/SleepingOwlAdmin#242]
После composer update панель SleepingOwl обновила пути до css и js а самих файлов нет. Как итог теперь SleepingOwl безликая страница без единого оформления. Надеюсь на исправление скорейшее!

Теперь ссылается
default/js/admin-app.js
default/css/admin-app.css

**Comment by butschster** [comment]
Смотри комментарий к последнему релизу

**Comment by RobVorch** [comment]
Спасибо!
