### ISSUE TITLE
suggestion: move admin-app.js to head

### ISSUE THREAD

**Issue by xcaptain** [LaravelRUS/SleepingOwlAdmin#243]
In [this commit](https://github.com/LaravelRUS/SleepingOwlAdmin/commit/648c71985ea37c3e71f70f670e355a31523d93cd) you added `@stack('footer-scripts')` to html footer part. I think it may be better to move this line to header part, because we can add custom js in the body which may require jquery loaded first.

**Comment by Butochnikov** [comment]
`footer-scripts` для тех скриптов, что нужны в подвале, а для остального `scripts`

**Comment by butschster** [comment]
use 
```php
Meta::addJs('custom', asset('path-to-file'), ['admin-default'])
```

```js
// customjs

// Code will run after document ready
Admin.Modules.add('module-name', function() {
     // your code here
})

```
