### ISSUE TITLE
Удаление файлов при замене

### ISSUE THREAD

**Issue by RobVorch** [LaravelRUS/SleepingOwlAdmin#245]
1)
Как поменять путь загрузки файлов. Речь не идет о постоянном пути. А хочется для каждого пункта меню свой путь сохранения файлов. Новости пускай грузят изображения в папку news / контакты в contact и так далее

Возможно ли это?

2)
Сейчас скажем при загрузке изображения к одной новости картинка загрузится в папку. А если я зашел и решил поменять картинку. Новый файл загружается а старый не удаляется. Как сделать так чтобы при обновлении картинки - старый файл удалялся. Иначе потом будет просто свалка из файлов которые и не используются даже.

**Comment by butschster** [comment]
1.
```php
AdminFormElement::image(...)->setUploadPath(function() {
    return 'news'; // полный путь будет public_path('news')
});
```

2. Это решается на уровне модели

**Comment by RobVorch** [comment]
> Это решается на уровне модели

добавил сюда

`public function onEdit($id)
    {
        return AdminForm::panel()
            ->addHeader([
                AdminFormElement::text('title', 'Title')->required(),
            ])
            ->addBody([
                AdminFormElement::date('date', 'Date')->required()->setFormat('d.m.Y'),
                AdminFormElement::checkbox('published', 'Published'),
                AdminFormElement::wysiwyg('page', 'Page', 'tinymce'),
                AdminFormElement::image('photo', 'Photo')->setUploadPath(function() {
                    return 'news'; // полный путь будет public_path('news')
                }),
            ]);
    }
`

Не работает(

**Comment by RobVorch** [comment]
в загрузке обнаружил баг = сообщил = исправили! Спасибо!

А что на счет удаления замененных фото?

**Comment by butschster** [comment]
Пока что реализация собственными силами, возможно чуть позже что нибудь придумаю

**Comment by RobVorch** [comment]
Может тогда дадите наводку где именно и как реализовать следующий сценарий

1) При открытии страницы редактирования создать пустой глобальный массив в который запишем загруженные файлы
2) при загрузке файла заносим туда имя загруженного, аналогично данным заносимым в базу
3) при нажатии СОХРАНИТЬ запись, удаляем все файлы из массива кроме того что заносится в базу
4) при нажатии ОТМЕНА, удаляем все файлы из находящиеся в массиве

**Comment by butschster** [comment]
т.е. ты хочешь удалять те файлы, которые была прикреплены к форме. но не сохраненные?

**Comment by RobVorch** [comment]
Просто сейчас ситуация такая что я захожу в форму редактирования новостей (если продолжать мою тематику) и выбираю файл изображения. Нажимаю загрузить. Файл сразу загружается в папку. Хотя я еще не нажал сохранить запись. Вот я загрузил и подумал что это изображение не подходит и нажал еще раз загрузить. Выбрал новый файл. В итоге загрузился новый файл в папку. Хотя я еще до сих пор не нажал сохранить. А в папку уже загружены 2 файла. И вот я решил что вторая не подходит и решил загрузить третью. Третью выбрал. Она погрузилась в папку. Все устраивает. Нажимаю сохранить. Она заносится в базу данных. А в папке как итог 3 файла а не 1. Хотя нужных из них только 1. Хочется чтобы те что не в базе удалялись после нажатия сохранить.

Можно конечно запустить по расписанию задание - пробежать всю БД по файлам и те что не находятся в бд - удалять. Но какой смысл если можно это реализовать сразу не отходя от кассы.

p.s. Такой принцип уже реализовывал - правда на древнем joomla в своем компоненте. Хочется такой же принцип сделать здесь.

**Comment by butschster** [comment]
Можешь тогда ради интереса потестировать ветку https://github.com/LaravelRUS/SleepingOwlAdmin/tree/feature/upload

В ней аплоад в БД происходит
После обновления на эту ветку необходимо сделать `php artisan sleepingowl:upload:table` и потом `php artisan migrate`

**Comment by RobVorch** [comment]
То есть тут файлы буду грузиться в саму базу? Это ждет в будущих обновлениях или это сторонняя разработка?

**Comment by butschster** [comment]
Work in progress

**Comment by mavsan** [comment]
Я так понимаю еще не решено, файлы безумно плодятся?

**Comment by aios** [comment]
Есть callback для сохранения файлов.

**Comment by VladislavUmrikhin** [comment]
Проблема по удалению до сих пор не решена?

**Comment by aios** [comment]
@VladislavUmrikhin уже объяснял почему удаление файлов ложится на плечи разработчиков

**Comment by VladislavUmrikhin** [comment]
@aios Есть callback для сохранения файлов.
Как это связано с тем, что не введено удаление? Что мешало сделать deleatUploadPath? Никаких претензий, просто чистый интерес, почему удаление не берет нарямую путь из базы? Даже получается без допметода.

**Comment by aios** [comment]
И так на пальцах для ленивых. 
1. Во первых админка не знает ни про какие файлы. она в принципе не знает где они лежат и зачем.
2. Во вторых Админка не может подстроится под каждый кейс - а что если картинки не в базе с моделью - а что если они  в релейшене? а что если в релейшене релейшена? - а что если картинки лежат вообще где нибудь на клауде? что тогда? брать из базы?
3. В третих - описывая кейс который работает в любой админке - как и в нашей - при создании записи - мы не можем сразу сохранить запись при загрузке файла - потому как самой модели еще нет. И тут мы делаем ход конем - мы сохраняем урлу после сохранения - это единственный момент когда админка прощупывает куда сохранить файл. она сохраняет его туда и отдает url файла. компонент загрузки - засовывает в input. Все красиво все хорошо админка сохраняет эти данные при отправке формы. 

Теперь же когда админка показывает редактирование и вы удаляете фото - компонент не удаляет фото внутри системы никак - он удаляет его из Input поля. И когда обновление модели происходит туда просто записывается новое значение - то есть единственное место соприкосновения где можно различить какой файл удален - это в этих колбеках. Да хорошо - можно добавить экшн на кнопочку удалить файл - но куда отправлять запрос? с какими данными - если у людей эти урлы файлов могут отдаваться и через мутаторы и через сервис провайдеры - или вообще браться из кеша? Конкретно я подстроится не смог. Если у кого то будет желание - то вперед и  с песней.
