### ISSUE TITLE
Validation rules

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#247]
Hello again.

im trying to make a rule for my Form.

```php
AdminFormElement::text('value', 'Quantidade')
            ->required()
            ->addValidationMessage('required', 'Campo obrigatório')
            ->addValidationRule('numeric')
            ->addValidationMessage('numeric', 'Insira um número válido')
            ->addValidationRule('min:1', 'Valor mínimo: 1')
            ->addValidationMessage('min:1', 'Valor mínimo: 1'),
```

I need to check the MAX number, i will do that with the MIN rulem but i cant understand how can i fire the function addValidationRule() (i presume this is the one i need to use)

any idea?

Thanks!

**Comment by butschster** [comment]
Can you explain what you need?

**Comment by macedodebrito** [comment]
i want to validate that "VALUE" with my database.

after i validate REQUIRED + NUMERIC + MIN:1 i need to see if the VALUE is > DB

examples:

my db total is 50. he cant be > 50. this number is not fixed so i cant add MAX:50. i need to create a new RULE to validate it.

Im sleepingowl v2 i was able to do those validations by myself, but with this v4 im not seeing how can i do it.

basically i need to check MAX < MYDB_NUMBER or he will not allow to insert into DB

DB VALUE = 50
MIN VALUE = 1

IF VALUE > 50, THROW VALIDATE ERROR
IF VALUE <=50, WILL PASS

**Comment by butschster** [comment]
https://laravel.com/docs/5.2/validation#custom-validation-rules

**Comment by macedodebrito** [comment]
Thanks.

Ok i managed to do it.

But now i cant type my own messages in any rule.

I cant customise required, min, or numeric, or my custom one...

YOU have addValidationMessage but i cant use it..

Thanks

Em 17/08/2016 17:51, "butschster" <notifications@github.com> escreveu:
