### ISSUE TITLE
Настройки без помощи директории app/Admin

### ISSUE THREAD

**Issue by manzor29** [LaravelRUS/SleepingOwlAdmin#249]
В документации указано, что использование `AdminSectionsServiceProvider` и конфигурационных классов позволяет полностью отказаться от директории `app/Admin`.

Подскажите, пожалуйста, как можно таким образом:
1. построить меню навигационной панели с вложенными пунктами;
2. скрыть мини-кнопку "удалить" либо "редактировать" в соответствующем столбце таблицы.

**Comment by Butochnikov** [comment]
1. registerNavigation()  в AdminSectionsServiceProvider 
https://github.com/LaravelRUS/SleepingOwlAdmin-docs/blob/master/model_configuration_section.md#Заключение

2. ты про запретить редактирование и удаление?
https://github.com/LaravelRUS/SleepingOwlAdmin-docs/blob/master/model_configuration_section.md#iseditable

**Comment by manzor29** [comment]
Внимательно не прочитал документацию... Спасибо за подсказку. Все получилось.
