### ISSUE TITLE
Image upload directoriy

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#250]
Is it possibile to configure different upload directory for different models? 

Something like
` AdminFormElement::image('photo', 'Photo')->uploadDirectory('/uploads/contact'),`
would be great.
In the previous version of this package I tried to face the issue using different "image" classes and changing the image/init.js file for each different directory, but this is not a flexible solution.

Thanks,
 Carlo

**Comment by butschster** [comment]
`AdminFormElement::image('photo', 'Photo')->setUploadPath('/uploads/contact'),`

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/File.php#L217
```php
AdminFormElement::image('photo', 'Photo')->setUploadPath(function() {
     return '/uploads/contact';
})
````

And for file name 

https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/File.php#L243

```php
AdminFormElement::image('photo', 'Photo')->setUploadFileName(function(\Illuminate\Http\UploadedFile $file) {
     return $file->getClientOriginalName().'.'.$file->getClientOriginalExtension();
})
```
