### ISSUE TITLE
возможно баг

### ISSUE THREAD

**Issue by axelys** [LaravelRUS/SleepingOwlAdmin#254]
приветствую!

сделал апдейт сегодня и стала вылетать ошибка

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'App\\Providers\AdminSectionsServiceProvider' not found

использовал PHP 7.0.0 и laravel v5.2.43

файл src/Providers/SleepingOwlServiceProvider.php
строка 54
`$this->app->register($this->app->getNamespace() . '\\Providers\\AdminSectionsServiceProvider');`

если убрать слеши впереди и заменить двойной слэш на одинарный то работает:

`$this->app->register($this->app->getNamespace() . 'Providers\AdminSectionsServiceProvider');`

спасибо )

**Comment by Butochnikov** [comment]
поправил.
