### ISSUE TITLE
Gallery images sometimes don't upload due to CSRF error

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#256]
I couldn't reproduce this reliably, but it definitely happens sometimes. Any ideas why?

**Comment by macedodebrito** [comment]
Hello @eugenem , nice to see you around :)

maybe session/token timeout? you saw if you were AFK for sometime? the only times i have CSRF error is when something mess with my session/token... and its always when i was AFK.

its happening randomly ?

**Comment by eugenem** [comment]
That's the catch, it happened when adding a new record. Few seconds after opening the editor. It couldn't expire in such short time...
