### ISSUE TITLE
custom datetime

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#258]
hello.

i just coded a custom datetime, to have different dates in separated tables (this could be usefull, if you have a DATE, but then you need to add or remove days/weeks/months to the setted date).

dunno if you wanna make any feature, like ->addOffset('-7 days')

```
                    AdminColumn::custom()
                    ->setLabel('date')
                    ->setWidth('160px')
                    ->setHtmlAttribute('class', 'text-center')
                    ->setCallback(function ($instance) {
                                $timestamp = strtotime('-7 days', strtotime($instance->end_at));
                                return date("d.m.Y", $timestamp);
                            }),
```

hope it was useful to anyone.

**Comment by Malezha** [comment]
[Cast](https://laravel.com/docs/5.2/eloquent-mutators#attribute-casting) field as datetime and use Carbon methods `$instance->end_at->addDays(-7)`.
