### ISSUE TITLE
function fullEdit()

### ISSUE THREAD

**Issue by budeci** [LaravelRUS/SleepingOwlAdmin#26]
use sleeping-owl V3.

I want to add two more parameters to this function `$catagory_id`, `$lang_id`:

I added these two parameters to the function, which is in `ModelConfiguration.php`.

```php
public function fullEdit($id, $catagory_id, $lang_id)
{
	$edit = $this->edit($id);
	if ($edit instanceof FormInterface)
	{
		$edit->setAction($this->updateUrl($id));
		$edit->setId($id);
	}
	return $edit;
}
```

function does not see

Error: 
`Missing argument 2 for SleepingOwl\Admin\Model\ModelConfiguration::fullEdit(), called in `

can someone help me?

**Comment by butschster** [comment]
You can add required parameters here https://github.com/sleeping-owl/admin/blob/development/src/SleepingOwl/Admin/Http/routes.php#L42

and here https://github.com/sleeping-owl/admin/blob/development/src/SleepingOwl/Admin/Http/Controllers/AdminController.php#L51

**Comment by budeci** [comment]
I want to send parameters in this model
> Admin :: model (Ecommerce \ Products \ Models \ PrsoCategory :: class)

this model

> Admin :: model (Ecommerce \ Productso \ Models \ CategoryDescription :: class)

Route:

> 		Route::get('{adminModel}/{adminModelId}/edit/{category_id?}/{lang_id?}', [
			'as'   => 'admin.model.edit',
			'uses' => 'AdminController@getEdit',
		]);

AdminController Function

> public function getEdit($model, $id, $catagory_id=null, $lang_id=null)
{
$edit = $model->fullEdit($id);
if (is_null($edit))
{
abort(404);
}
return $this->render($model->title(), $edit);
}

and nothing, something escapes me
