### ISSUE TITLE
Laravel 5.3: Call to undefined method Illuminate\Foundation\Application::bindShared()

### ISSUE THREAD

**Issue by Renesko** [LaravelRUS/SleepingOwlAdmin#260]
После выполнения php artisan sleepingowl:install получаю ошибку:
`[Symfony\Component\Debug\Exception\FatalThrowableError]                   
  Call to undefined method Illuminate\Foundation\Application::bindShared()`

На версию 5.2 устанавливается без ошибок

**Comment by AndreyElogic** [comment]
Здравствуйте,
bindShared() были заменены singleton()
Он расположен здесь: /path-to-your-project/vendor/illuminate/html/HtmlServiceProvider.php
изменение на линии пo : 36 and 49

**Comment by butschster** [comment]
Ждем обновление illuminate\html
