### ISSUE TITLE
Not working styles for select2 (for TAB)

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#261]
При использовании табов, не корректно отображаются select и multi select.
---
If used tabulation, not correct working styles for select and multiselect

**Comment by Butochnikov** [comment]
снимок экрана можно?

**Comment by foRsxs** [comment]
![screen1](https://cloud.githubusercontent.com/assets/18087400/18225030/315836c6-720b-11e6-8c55-dec53dcc1353.png)
update делал

**Comment by foRsxs** [comment]
update сделал, но ничего не изменилось,
`<span class="select2 select2-container select2-container--default" dir="ltr" style="width: 100px;">`
ширина так и стоит 100px

**Comment by butschster** [comment]
`php artisan vendor:publish --tag=assets --force`
