### ISSUE TITLE
Команда "php artisan route:list" не работает

### ISSUE THREAD

**Issue by Makashov** [LaravelRUS/SleepingOwlAdmin#263]
В терминале если набрать команду **php artisan route:list** выдает следующий _Exeption_

`[DaveJamesMiller\Breadcrumbs\Exception] 

Breadcrumb name "home" has already been registered`

В AdminController закомментировал строки 

```
Breadcrumbs::register('home', function ($breadcrumbs) {
    $breadcrumbs->push(trans('sleeping_owl::lang.dashboard'), route('admin.dashboard'));
});
```
После чего "route:list" заработал нормально.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/2a0cf360eb43c2b06b110b4e7128febfccc8444f
