### ISSUE TITLE
Как добавить image в БД

### ISSUE THREAD

**Issue by AndreyElogic** [LaravelRUS/SleepingOwlAdmin#264]
У меня есть форма с полями для добавления специалиста и поле для загрузки фотографий.Специалисты и фотографии в различных таблицях сохраняются.
Как добавить фото в БД причем в таблице "image" в поле "specialist_id" должно добавляться "id" самого специалиста, для вязки. Благодарю за помощь.

**Comment by h-zone** [comment]
например так https://github.com/h-zone/lib-immann
