### ISSUE TITLE
Возможность задавать в tree() режим collapse или expand по умолчанию для всех нод

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#265]
Сейчас по умолчанию все ноды expand, хотелось бы иметь возможность задавать этот параметр при конфигурации модели и способе отображения в виде tree().
А также добавить у tree() метод setColumns() для вывода там не только заголовка

**Comment by butschster** [comment]
Если напишешь JS код, который будет отвечать за хранение статуса дерева, то добавлю

**Comment by dronowar** [comment]
Готов написать на vue.js
За основу возьму этот пример http://vuejs.org/examples/tree-view.html и
дополню

Нужно будет чтобы backend через ajax отдавал json дерево при открытии
страницы, и методы чтобы можно было сохранить измененное дерево, создать и
обновить ноду

Vue и сам код можно просто подключить к шаблону, но лучше сразу
использовать сборщик gulp-browserify-vueify

5 сент. 2016 г. 6:51 PM пользователь "butschster" <notifications@github.com>
написал:

**Comment by Butochnikov** [comment]
@butschster, @aios 
Сделал метод setCollapsed, но для корректной работы нужно править сам `nestable.js`, он подключается из `node_modules`. В этом случае, мы отключаем его в зависимостях и используем свою измененную версию. По сути это не страшно, т.к. эта либа уже 100 лет не обновлялась.

меняем?

**Comment by aios** [comment]
@Butochnikov этот компонент подлежит полной переписи - так как тестировался на маленьких деревьях до 30-50 записей. У лунатика 500 и я охренел от того времени которое уходит на отрисовку всего дерева - а потом на обработку его сохранения. + дерево постоянно ломается. От этого мы тоже будем уходить. Nestable не подходит совсем.

**Comment by Butochnikov** [comment]
@aios у меня тоже огромные деревья + кастомный view   для каждого элемента, да, медленно, но опять-таки, работает и все пользуются. Я, например, сходу не нашел готовой альтернативы работы с деревом + d&d, даже на vue, возможно плохо искал. 
Если новое решение будет мега отличное, то старый tree можно убить, а пока нового нет предлагаю доработать.

**Comment by aios** [comment]
@Butochnikov ну я с предложением не согласен. @butschster что скажешь?

**Comment by aios** [comment]
@dronowar был добавлен метод setMaxDepth в Tree посмотри чем поможет.

**Comment by 1oginov** [comment]
Как насчёт https://www.npmjs.com/package/nestable2 ?

**Comment by dronowar** [comment]
Наконец-то это либа стала обновляться. Альтернатив ей нормальных нет, надо
брать.

12 июля 2017 г. 12:10 AM пользователь "Danila Loginov" <
notifications@github.com> написал:

**Comment by 1oginov** [comment]
Какие требования?
1. Вывести nested set в виде дерева с несколькими action кнопками
2. Expand/collapse дочерних элементов
3. Drag'n'drop элемента в любую часть дерева
4. По изменению дерева, сериализовать его и отправить на эндпоинт

Сейчас дерево рендерится на сервере, что если отдавать его Vue компоненту с указанием роутов для action кнопок, а ля:

```php
$tree = Model::getTree();
// $tree[i] = ['id' => 1, 'name' => 'Тапочки', 'children' => [...]];
```

```html
<display-tree :tree={{ json_encode($tree) }}
              reorder-url="/admin/categories/reorder"
              edit-route="/admin/categories/{id}/edit"
              delete-route="/admin/categories/{id}/delete"></display-tree>
```

Ну а Vue компонент уже хранит дерево и рекурсивно отрисовывает его, при изменении сделать JSON из дерева не составит труда. Там уже и допилить это дело под конкретные нужды можно будет, например сделать текстовый поиск по нодам.

**Comment by daaner** [comment]
Как сейчас обстоят дела с деревьями где много записей? Меняем либу?
