### ISSUE TITLE
Создание собственного элемента формы

### ISSUE THREAD

**Issue by manzor29** [LaravelRUS/SleepingOwlAdmin#267]
Попытался создать собственный элемент формы по аналогии с тем, как было показано здесь - [#79](https://github.com/LaravelRUS/SleepingOwlAdmin/issues/79). Сделал так:

Класс элемента формы 
**App\Form\Elements\PickColorFormElement.php**
```php
<?php

namespace App\Form\Elements;

use Illuminate\Database\Eloquent\Model;
use Request;
use SleepingOwl\Admin\Form\Element\Text;

class PickColorFormElement extends Text
{

}
```

Регистрация
**App\Providers\AppServiceProvider.php**
```php
<?php

namespace App\Providers;

use App\Form\Elements\PickColorFormElement;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app['sleeping_owl.form.element.text']->add('pickColor', PickColorFormElement::class);
    }
}
```

Представление элемента формы (повторяет text.blade.php)
**resources\views\vendor\sleeping_owl\default\form\element\pickcolorformelement.blade.php**
```html
<div class="form-group {{ $errors->has($name) ? 'has-error' : '' }}">
	<label for="{{ $name }}" class="control-label">
		{{ $label }}

		@if($required)
			<span class="text-danger">*</span>
		@endif
	</label>
	<input class="form-control"
		   name="{{ $name }}"
		   type="text"
		   id="{{ $name }}"
		   value="{{ $value }}"
		   @if($readonly) readonly @endif
	>
	@include(AdminTemplate::getViewPath('form.element.errors'))
</div>
```

Использование элемента
```php
...
AdminFormElement::pickColor('color', 'Цвет')
...
```

При выполнении получаю ошибку:

> ReflectionException in Container.php line 734:
> Class sleeping_owl.form.element does not exist

Подскажите, пожалуйста, в чем ошибка и как все-таки следует регистрировать класс элемента формы?

**Comment by butschster** [comment]
Используй не `boot`, а `register`

**Comment by butschster** [comment]
Ну и я так понимаю ты здесь ошибся `$this->app['sleeping_owl.form.element.text']`

**Comment by Butochnikov** [comment]
Закрываю?

**Comment by manzor29** [comment]
Да. Спасибо!
