### ISSUE TITLE
Ошибка 500 при отображении datatablesAsync со связанными полями 

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#271]
```
    $model->onDisplay(function () {
        return AdminDisplay::datatablesAsync()
            ->with('user', 'category', 'status', 'type')
            ->setColumns([
                AdminColumn::text('status.name')->setLabel('Статус'),
                AdminColumn::link('type.name')->setLabel('Тип'),

```

выдает ошибку 500:
http://joxi.ru/12MpPGEf4D8VJm

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status.name' in 'order clause' (SQL: select \* from `problems` order by `status`.`name` asc limit 25 offset 0)

этот же самый код в случае datatables() или tables() работает без проблем

**Comment by aios** [comment]
Проблема отсутствует.

**Comment by butschster** [comment]
@aios Не стоит так спешить с закрытием :)

@dronowar По поводу релейшен данных в колонках, то все три  типа таблиц используют один и тот же класс работы с колонками.

В твоем случае, он пытается отсортировать по первой колонке данные и натыкается на проблему. Попробуй указать
```php
AdminColumn::text('status.name')->setLabel('Статус')->setOrderable(false) 
```

для отключения сортировки по этому столбцу, либо указать вручную правила сортировки по данному столбцу. Вот пример:
```php
AdminColumn::text('status.name')->setLabel('Статус')->setOrderable(function($query, $direction) {
       $query->join('statuses', 'statuses.id.', '=', '...')->orderBy('statuses.name');
})
```

**Comment by aios** [comment]
@butschster Ну тут 2 выхода
Либо я закрыл issue верно - и колонка для сортировки должна быть минимум на плечах обывателя  или максимум в документации
Либо проблема есть - issue я закрыл не верно - и тогда обработка "Натыкивания на ошибку" должна быть на наших плечах.

**Comment by butschster** [comment]
@aios о данной проблеме нигде ничего не сообщается, поэтому лучше стараться разобраться в причинах ошибки и постараться учесть ее в будущих релизах.

**Comment by aios** [comment]
Так как у нас не работает пока сортировка по связанным полям (нету дефолтной логики) - то сама по себе форма что в примере работать не может - потому что сортировка если не указана setOrderable методом берется по первому столбцу - а он у нас на секундочку `status.name` отсюда и такое поведение. В скором времени я добавлю дефолтную логику по сортировке связанных полей и думаю что вы таких проблем ощущать не будете.
@dronowar
