### ISSUE TITLE
FatalErrorException when i use AdminFormElement::ckeditor

### ISSUE THREAD

**Issue by rodrigue67** [LaravelRUS/SleepingOwlAdmin#273]
Hello,

When i want use the AdminFormElement::ckeditor in my sleepingOwl project

`AdminFormElement::wysiwyg('body:'.$lang, 'Corps')->required()`
or
`AdminFormElement::ckeditor('body:'.$lang, 'Corps')->required()`

I obtain this error

FatalErrorException in Wysiwyg.php line 53:
Call to a member function getConfig() on null

My project use Laravel 5.2 and the latest developpement version of sleepingOwl.

"laravelrus/sleepingowl": "dev-development",
"laravel/framework": "5.2.*",

Can you explain me how i can use this feature without errors?

Thanks.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/5fdb3c1ad9a02b9ba3489268ec8ec327a0229e09
