### ISSUE TITLE
Перестали сохраняться файлы после обновления

### ISSUE THREAD

**Issue by FubuBy** [LaravelRUS/SleepingOwlAdmin#274]
после обновления до версии "laravelrus/sleepingowl": "^4.60" перестали сохраняться файлы, выдает ошибку:

`TokenMismatchException in VerifyCsrfToken.php line 67:`

**Comment by FubuBy** [comment]
На демо сайте та же проблема:

> POST http://demo.sleepingowladmin.ru/admin/contacts2/image/photo/7 500 (Internal Server Error)

**Comment by Butochnikov** [comment]
Не та же проблема . На демо сайте загрузка картинок запрещена. 
А ты у себя после обновления делал:
php artisan vendor:publish --tag=assets --force

**Comment by Butochnikov** [comment]
еще актуально?
