### ISSUE TITLE
Filemanager

### ISSUE THREAD

**Issue by Froxz** [LaravelRUS/SleepingOwlAdmin#275]
Is Filemanager in TODO list?

Not just as an seperate page but also as a form Input (Select Files from Filemanager)

Thanks.

**Comment by 7ammer** [comment]
This is a good one: https://github.com/UniSharp/laravel-filemanager.

**Comment by Froxz** [comment]
@7ammer 
How to include? Custom Form Items?

**Comment by 7ammer** [comment]
You'll need to create a custom element: https://github.com/LaravelRUS/SleepingOwlAdmin/issues/114

**Comment by Butochnikov** [comment]
Из коробки файл менеджер вряд ли стоит делать.
Знаю 3 штуки и все довольно быстро подключаются.
А вот в доку добавить про подключение, думаю стоит.

**Comment by aios** [comment]
@Butochnikov ну вот и займись этим.
