### ISSUE TITLE
TokenMismatchException

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#276]
На Laravel 5.3 выдает ошибку токена при использование AdminColumnEditable
http://joxi.ru/EA4ne9ZhDWG9Dm

**Comment by Butochnikov** [comment]
Какая версия совы 4.60.13 или dev?

**Comment by Fessnik** [comment]
dev

**Comment by butschster** [comment]
`php artisan vendor:publish --tag=assets --force`

**Comment by Fessnik** [comment]
Сделал, не помогло, всеравно та же ошибка
