### ISSUE TITLE
Display::table() setActions render bug?

### ISSUE THREAD

**Issue by rodrigue67** [LaravelRUS/SleepingOwlAdmin#278]
Hello,

I want create a custom actions to export my table rows.

I use LARAVEL 5.2 and SleepingOwl dev branch.

i have use the same code that the demo NEWS 5
[http://demo.sleepingowladmin.ru/admin](http://demo.sleepingowladmin.ru/admin)

but, the action form has not renderer.
```
    $model->onDisplay(function () {
        $display = AdminDisplay::table()->setActions([
                AdminColumn::action('export', 'Export')->setIcon('fa fa-share')->setAction(route('admin.news.export')),
            ])->setColumns([
                AdminColumn::checkbox(),
                AdminColumn::link('title')->setLabel('Title'),
                AdminColumn::datetime('date')->setLabel('Date')->setFormat('d.m.Y')->setWidth('150px'),
                AdminColumn::custom()->setLabel('Published')->setCallback(function ($instance) {
                    return $instance->published ? '<i class="fa fa-check"></i>' : '<i class="fa fa-minus"></i>';
                })->setWidth('50px')->setHtmlAttribute('class', 'text-center'),
            ]);

        $display->getActions()->setPlacement('panel.footer')->setHtmlAttribute('class', 'pull-right');

        return $display;
    });
```

i test to debug, the class SleepingOwl\Admin\Display\Display, the function render()
  ```
  public function render()
    {
        $view = app('sleeping_owl.template')->view($this->getView(), $this->toArray());

        $this->getExtensions()->filter(function ($extension) {
            return $extension instanceof Placable;
        })->each(function ($extension) use ($view) {
            $html = app('sleeping_owl.template')->view($extension->getView(), $extension->toArray())->render();

            if (! empty($html)) {
                $factory = $view->getFactory();

                $factory->startSection($extension->getPlacement());
                echo $html;
                $factory->stopSection(true);
            }
        });

        return $view;
    }
```
When i display `var_dump($html)`, i can see my custom form action button.

but the button has not render into the table.blade.php. Line 33

`	@yield('panel.footer', 'ko')`

I see that the bug is visible on the online demo 
[http://demo.sleepingowladmin.ru/admin/news/v5](http://demo.sleepingowladmin.ru/admin/news/v5)

Can you help me to resolve this yield bug?

Rodrigue

**Comment by rodrigue67** [comment]
Hello,

When i comment this line in DisplayTable.php Line 63

`        $this->extend('column_filters', new ColumnFilters());
`

My Table Action form is correctly renderer on the @yield('panel.footer', 'ko') in file table.blade.php

I don't understand why this "columnFilters" feature break the "actions" feature.

**Comment by butschster** [comment]
Hi, can you check?

**Comment by kambojaz** [comment]
I checked it. Everything is ok.
Thanks!
