### ISSUE TITLE
Custom datatables

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#279]
Привет, подскажите плиз. Мне нужно вывести статистику => собрать данные из нескольких таблиц и вывести их по дням. Тоесть каждая строка в таблице это отдельный день со своими данными. Как можно это сделать. В идеале бы, как-то передевать коллекцию\массив данных в datables и что бы он по ним строил таблицу, но не могу разобратся как так сделать. Или  как хотябы вывести кастомную вьюху,в доке не нашел такого.

Если плохо обьяснил, то вот таблица User http://joxi.ru/LmGqQ80HR3WM5A , только данные будут не с одной таблицы юзер ,а со многих, и вместо айдишников будут даты:
22.08
21.08
20.08

**Comment by Butochnikov** [comment]
Тебе надо:
1. делать свой роут
2. привязывать свой контроллер, который будет возвращать нужные данные во вьюху админки

ну или: 
`AdminFormElement::view('template')->setData([...])`

**Comment by Fessnik** [comment]
1. делать свой роут
2. привязывать свой контроллер, который будет возвращать нужные данные во вьюху админки

Как?
Я видел есть setControllerClass  ,пробывал его использовать, но не получилось\непонял как

**Comment by aios** [comment]
@Fessnik Читаем документацию в разделе http://sleepingowladmin.ru/docs/model_configuration#переопределение-контроллера
