### ISSUE TITLE
Routes SleepingOwlAdmin

### ISSUE THREAD

**Issue by budeci** [LaravelRUS/SleepingOwlAdmin#28]
I also add two parameters {category_id?}/{lang_id?}
if instead this route. Error 404
```
Route::get('{adminModel}/{adminModelId}/{category_id?}/{lang_id?}/edit', [
			'as'   => 'admin.model.edit',
			'uses' => 'AdminController@getEdit',
		]);
```
can someone help me?

**Comment by butschster** [comment]
Use `query string` to send data

Example
`/news/2/edit?category_id=1&lang_id=2`

**Comment by budeci** [comment]
I can not build link
He wants to send parameters of a model in another
`$description = Admin::model(Ecommerce\Productso\Models\CategoryDescription::class)->fullEdit($editId, $category_id, $item->language_id);`

**Comment by butschster** [comment]
See http://sleeping-owl.github.io/v3/en/Displays.html

Section `Set Parameters`

**Comment by budeci** [comment]
use tabs
Call to undefined method SleepingOwl\Admin\Display\DisplayTabbed::parameters()

**Comment by budeci** [comment]
```
 $description = Admin::model(Ecommerce\Productso\Models\CategoryDescription::class)->fullEdit($editId);
$description->parameters(['category_id' => $category_id, 'language_id' => $item->language_id]);
```
Error: Call to undefined method SleepingOwl\Admin\Form\FormDefault::parameters()
