### ISSUE TITLE
Cвязанные select

### ISSUE THREAD

**Issue by AndreyElogic** [LaravelRUS/SleepingOwlAdmin#281]
Как сделать связанные select через Ajax. Первый select область -> второй select город. Спасибо за ответ.

**Comment by mediaceh** [comment]
Как насчет интеграции этого решения?
https://github.com/kartik-v/dependent-dropdown

**Comment by mediaceh** [comment]
Лично у меня все заработало из коробки путем добавления пары методов к select. Если получится интегрировать клиентскую часть - серверную накачу.

**Comment by Butochnikov** [comment]
@mediaceh если сделаешь подобный элемент для админки, будет здорово

**Comment by butschster** [comment]
https://github.com/SleepingOwlAdmin/docs/blob/master/form-element.md#dependentselect

**Comment by mediaceh** [comment]
Добей тогда уж #339  раз в селекты полез. Там в has error в шаблоне нужно имя без скобок указывать.
