### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Settings' of undefined(admin-app.js:10)

### ISSUE THREAD

**Issue by feefk** [LaravelRUS/SleepingOwlAdmin#282]
When i use "laravelrus/sleepingowl": "4.*.*"(4.60.13), it work fine, but when i update it to "laravelrus/sleepingowl": "4.*@dev", it don't work. and have error below
<img width="1264" alt="qq20160920-0 2x" src="https://cloud.githubusercontent.com/assets/285585/18661333/beb7751a-7f47-11e6-94f5-4aed78ab7b3c.png">
How can i do? thank you

**Comment by feefk** [comment]
I find it conflict with [Dingo\Api](https://github.com/dingo/api) package, when i delete Dingo\Api, it also work fine with 4.\*@dev

**Comment by butschster** [comment]
`php artisan vendor:publish --tag=assets --force`

**Comment by feefk** [comment]
I use this command `php artisan vendor:publish --tag=assets --force`, but has error still:
<img width="1270" alt="qq20160920-1 2x" src="https://cloud.githubusercontent.com/assets/285585/18662452/07eb5f9e-7f4d-11e6-8db4-53d1ed1f4459.png">
