### ISSUE TITLE
Get user in middleware

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#284]
Как в Laravel 5.3 , получить пользователя в middleware, что бы решить пускать его в админку или нет?

В конфиге у меня  'middleware' => ['admin'],
В Kernel.php -  'admin'   =>  \App\Http\Middleware\Admin::class
В middleware - http://joxi.ru/bmo6Qk9fMBd71r

В 5.2 Без проблем получало юзера, в 5.3 null ,перепробывал кучу вариантов.

**Comment by butschster** [comment]
Ну во первых нужен middleware `web` перед `admin`
Во вторых middleware для авторизации я бы скопировал, например, с https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Middleware/Authenticate.php
и в строке https://github.com/laravel/framework/blob/5.3/src/Illuminate/Auth/Middleware/Authenticate.php#L42 можно получить объект пользователя как `$this->auth->user()`если я не ошибаюсь

**Comment by butschster** [comment]
либо `['web ', 'auth', 'admin']`. т.е. проверяется авторизован ли пользователь и если да, то в своем middleware `admin` ты уже делаешь дополнительные проверки

**Comment by Fessnik** [comment]
Спасибо
