### ISSUE TITLE
NamedFormElement::setHelpText($helpText) does nothing

### ISSUE THREAD

**Issue by rubix-msparis** [LaravelRUS/SleepingOwlAdmin#285]
In \SleepingOwl\Admin\Form\Element\NamedFormElement::toArray(), it returns an element options array, this array includes a key called "helpText".
But none of the Element view files uses this variable.
That means "helpText" does nothing.
I think this is a bug. Help Text related code should be put right above errors prompt code.

For example:

``` html
# vendor/laravelrus/sleepingowl/resources/views/default/form/element/text.blade.php
<div>
    <label>...</label>
    <input ... />
    /**
     * The helpText code should be put here. for example: 
     * @include(AdminTemplate::getViewPath('form.element.helptext')
     */
    @include(AdminTemplate::getViewPath('form.element.errors'))
</div>
```

**Comment by BenWoodford** [comment]
Just found this myself, it's in the wysiwyg element but nothing else:

```
@if(!empty($helpText))
        <span class="help-block">{!! $helpText !!}</span>
@endif
```

**Comment by butschster** [comment]
Thanx for the issue
