### ISSUE TITLE
Missing isReadonly in multiselect

### ISSUE THREAD

**Issue by team5ru** [LaravelRUS/SleepingOwlAdmin#293]
In file /src/Form/Element/MultiSelect.php in function toArray (line 90) missing
```
        if ($this->isReadonly()) {
            $attributes['disabled'] = 'disabled';
        }
```
as result setReadonly not working for multiselect.

**Comment by KristobalJunta** [comment]
@butschster это, судя по всему, уже надо закрыть?

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/pull/294
