### ISSUE TITLE
Sidebar - open tree to active nav element

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#298]
Now sidebar navigation is set 'active' class only to level one of the navigation.
I suggest to add 'active'/'in' classes to the full tree upto the active element.
This is useful to work with deep-nested elements of the navigation menus.

Thanks.

**Comment by Butochnikov** [comment]
Это еще актуально?

**Comment by h-zone** [comment]
уже не пользуюсь этим продуктом, если никто не исправлял, то актуально.

**Comment by Butochnikov** [comment]
@butschster, @aios что думаете по этому вопросу?

**Comment by aios** [comment]
@Butochnikov  А можно как то скрин проблемы - а то я не особо понял о чем речь. Если об этом блевке который рядом с активной кнопкой меню появляется полоска - то она как бы не нужна.
И во внутреннем меню и так понятно где мы находимся

http://icecream.me/uploads/cc633fdfe617f269cbc8a17ba4919371.png

**Comment by butschster** [comment]
Он говорит о том, что нужно помечать всех родителей активной страницы активными

**Comment by Butochnikov** [comment]
@butschster так у нас так и есть сейчас:
```html
<li class="has-child active">
    <a href="#">
        <i class="fa fa-folder-o"></i>
        <span>Родитель</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu menu-open" style="display: block;">
                   <li class="has-child active">
                        <a href="#">        
                            <span>Ребенок</span>
                            <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                           </span>
                      </a>
                    .....
               </li>
            </ul>
</li>
```
все родители активны )
