### ISSUE TITLE
Checkbox column 

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#30]
Hi, I am moving from sleeping-owl/admin to this package. I have a question, or a feature request, about the checkbox column. Is it possible to use it to **_show and modify a model attribute_**? For example in the demo there is the "news" model with a "published" attribute. In the display table ([http://demo.sleepingowladmin.ru/admin/news/v5 ](http://demo.sleepingowladmin.ru/admin/news/v5)) this attribute is a custom column, I would like to use the checkbox column to show and change this field value. I am able to change the _published _value using the checkbox column  and a custom display action, but with this approach when the table is loaded all the checkboxes are unchecked, they are not linked to a model attribute.

Thanks, Carlo

**Comment by butschster** [comment]
Hi, Carlo.

You want to show checkbox column linked with model attribute? Like this `AdminDisplay::checkbox('published', 'Published')`? And change model attribute value by changing checkbox status?

Sorry for my english :)

**Comment by s6carlo** [comment]
Yes, this request is similar to the one "Add inline column editing" but probably less complex to develop, actually the missing step is to load the checkbox status from a model attribute. The method to save changes is ready to be use.

**Comment by butschster** [comment]
Maybe something like this http://vitalets.github.io/x-editable/demo-bs3.html ?

**Comment by s6carlo** [comment]
It wuold be great, but ti start a simpler checkbox column is ok for my application. The checkbox column already exists, but is not possibile ti load the value from a database column.

**Comment by butschster** [comment]
I added new column type `AdminColumnEditable`

**Example**

```php
// Display
    $model->onDisplay(function () {
        return AdminDisplay::table()->setApply(function($query) {
            $query->orderBy('date', 'desc');
        })->setColumns([
            AdminColumn::link('title')->setLabel('Title'),
            ...
            AdminColumnEditable::checkbox('published', 'Yes', 'No')->setLabel('Published'),
            ...
        ])->paginate(5);
    });
```

**Comment by butschster** [comment]
After `composer update` you should remove assets `public\packages\sleepingowl`, config `sleeping_owl.php` and run artisan command `php artisan sleepingowl:install`
