### ISSUE TITLE
Option to hide trashed

### ISSUE THREAD

**Issue by BHEADRICK** [LaravelRUS/SleepingOwlAdmin#303]
I see that the "withtrashed" is there by default, so I'm not sure how I can optionally negate that. 

What I want to do is to hide the trashed  items in the main view and have a separate view to display only trashed.

**Comment by xcaptain** [comment]
I have a simple workaround,

```php
$display = AdminDisplay::datatablesAsync()->setApply(function ($query) {
            $query->where('deleted_at', '=', null);
        });
```
