### ISSUE TITLE
defaultUploadPath для Image

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#305]
файл /vendor/laravelrus/sleepingowl/src/Form/Element/Image.php
строка 64

В одну корзину складываем все яйца, а это не гуд.
Например для новостей, поользователей и статей необходимо динамически менять путь сохранения, однако это невозможно.

Предлагаю таки сделать возможным реагировать на ->setPath('PATH') в AdminFormElement::upload()

**Comment by h-zone** [comment]
Либо я чего-то не понимаю, однако не могу указать кастомный путь для изображения.
В любом случае сохраняет в config('sleeping_owl.imagesUploadDirectory')

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/File.php#L217
