### ISSUE TITLE
Использование AdminColumnEditable::checkbox с datatablesAsync

### ISSUE THREAD

**Issue by softlabnet** [LaravelRUS/SleepingOwlAdmin#306]
Изменение инициирует POST запрос с url /admin/{AdminModel}/async
В роутах прописан только
$router->post('{adminModel}', [
        'as'   => 'model',
        'uses' => 'AdminController@inlineEdit',
    ]);
для datatables,поэтому имеем 500 MethodNotAllowed.
Решается добавлением роута
$router->post('{adminModel}/async', [
        'as'   => 'model',
        'uses' => 'AdminController@inlineEdit',
    ]);

**Comment by aios** [comment]
#364 Close
