### ISSUE TITLE
Удаление записей

### ISSUE THREAD

**Issue by honciv** [LaravelRUS/SleepingOwlAdmin#308]
Не работает удаление записей:
- Firefox (v51.0a2 dev; v49.0.1) из формы edit. Появляется окно подтверждения, при выборе yes - окно закрывается, post не идет.
- IE 11 из формы, списка. Не появляется окно подтверждения.

В Chrome работает корректно

В Демо (http://demo.sleepingowladmin.ru/) такое же поведение

**Comment by Butochnikov** [comment]
@butschster есть идеи почему?

**Comment by Butochnikov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue которые хотелось бы закрыть](https://trello.com/c/QIqtB03o/44-issue)

**Comment by mediaceh** [comment]
Вот и у меня руки дошли. Ну что, неужели так и не решил проблему ни кто? Где ваш соревновательный дух? У меня ровно пять минут заняло решение этой проблемы. Кто быстрее?

**Comment by Butochnikov** [comment]
@mediaceh а где PR?

**Comment by Butochnikov** [comment]
@mediaceh проверял? https://github.com/LaravelRUS/SleepingOwlAdmin/issues/438

**Comment by mediaceh** [comment]
Да, оно. В хроме перестало работать последнем поэтому и дошли руки.

**Comment by s6carlo** [comment]
Same problem, in
Chrome Versione 62.0.3202.94   64 bit
message: Form submission canceled because the form is not connected

Firefox 57.0 (64 bit)
No message in console, but delete from edit form does not works.
