### ISSUE TITLE
Search text column from a related table

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#31]
Probably the capability to search text in a column coming from a related table could be useful.

The solution in 
https://github.com/sleeping-owl/admin/issues/264
could be used.

**Comment by butschster** [comment]
What about this? 

You have model `Contact` with relation `country`.

```php
$display->setFilters([
    AdminDisplayFilter::field('country.title') // Search in relation country and field title
          ->setOperator(\SleepingOwl\Admin\Display\Filter\FilterBase::CONTAINS) // Like
]);
```

And send request with query string `http://.....?country[title]=Bot`

List of operators is here https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/Filter/FilterBase.php#L13
