### ISSUE TITLE
Extra Column (L5.2)

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#314]
Hello everyone.

how can i add extra column (virtual one), to a query ?

its only for display, i wont need to "edit" it
Im using this query: 

`$query->whereIn($array);`

but i need one(or more) extra columns, basicaly they are math equations
They arent inside the database. i need to add them virtually

Any idea? 

Thanks,
- Brito

**Comment by AndreyBobrov** [comment]
If you need to filter results by additional non-existing fields, you can retrieve records and than work with collection of results, using methods like "filter" or "reject":

```
$users = App\User::where('active', 1)->get();
$users = $users->filter(function($user, $key) {
    return SomeMath($user->field) > 10;
});
```

If you need to calculate some non-existing fields and append them to resulting models, you can use Eloquent accessors.

```
function getVirtualFieldAttribute()
{
    return SomeMath($this->field);
}
```
```
dump($user->virtual_field);
```

**Comment by macedodebrito** [comment]
hum..

imagine this app\Admin\File.php

$display->setApply(function($query) {
$some_array = [];
... (code to create the array) ...
$query->whereIn('id', $some_array ['id']);
 });

i cant insert virtual columns there... and i cant understand how could i do that with your example, since this is also giving me error in filter().

i read MySQL Manual about some CASE or JOIN, even "$num AS new_clolumn_name from TABLE", but nothing is working here :\

i have a table like:

id | name

and i want: id | name | virtual_calc_1 | virtual_calc_2 | ...

dunno what to do atm.. im stuck.

Thanks,
- Brito

**Comment by macedodebrito** [comment]
solved.

thanks @AndreyBobrov :)
