### ISSUE TITLE
EN_CA и EN_US

### ISSUE THREAD

**Issue by aios** [LaravelRUS/SleepingOwlAdmin#315]
Есть одна неприятная особенность
Если использовать в Laravel язык которого нету в sleeping_owl и при этом в фолбек заюзать такой же не существующий язык - то в ней будут проблемки) 
http://prntscr.com/cytbgr

у меня это возникло в проекте у канадцев - они используют два диалекта - а не просто en.

решается отдельным мидлварем либо группой. 
Будьте бдительны)

**Comment by butschster** [comment]
Лучше такую информацию переносить в https://github.com/SleepingOwlAdmin/docs/blob/master/faq.md
