### ISSUE TITLE
Get info from the previous row (right before)

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#317]
```
                    AdminColumn::custom()
                    ->setLabel('Total (Horas)')
                    ->setWidth('100px')
                    ->setCallback(function ($instance) {
                                return $instance->total_hours;
                            }),
```

How can i get the info from the $instance->total_hours (-1), AKA the previous row.. ?

Thanks,
- Brito

**Comment by macedodebrito** [comment]
Ok im adding a image to explain my issue. its a math calc but i dunno the best way to do it (i dont know any way atm):

<img src="http://i.imgur.com/5tWhmUc.png"/>

Issue: 
B1 = A1 (its the 1st one)
B2 = B1 + A2;
C2 = C1 + B2;

Basicaly he will increment with all amount before, but always increasing, its not just the actual + the previous (or i would only SUM the A column). I should SUM all the value already SUM() BEFORE + actual line.

i dont know if i was clear :\

Thanks,
- Brito

**Comment by team5ru** [comment]
Order can be diffrent? Or same order anytime?

**Comment by macedodebrito** [comment]
this is previously ordered by DATE, and with $query->whereIn($array), so the array is already ordered.

About the "table order", this should stick the DATE, since he is increasing the DAYS by DATE.

**Comment by macedodebrito** [comment]
thanks. the global helped in this case. :)
