### ISSUE TITLE
Сохранение загруженных файлов в storage

### ISSUE THREAD

**Issue by team5ru** [LaravelRUS/SleepingOwlAdmin#322]
Сейчас используется public, хорошо бы сделать storage
`Form/Element/File.php` 89 строка
```
static::saveFile($file, public_path($path), $filename, $settings);
$value = $path.'/'.$filename;
```

Так как в документации (https://laravel.com/docs/5.3/structure#the-storage-directory) есть отличная команда `php artisan storage:link`, я думаю с чистой совестью можно сделать что то подобное
```
static::saveFile($file, storage_path('app/public/'.$path), $filename, $settings);
$value = 'storage/'.$path.'/'.$filename;
```

**Comment by team5ru** [comment]
Нашел решение)))
В конфиге прописал
```
'imagesUploadDirectory' => 'storage/images/uploads',
```
и он сохраняет и читает используя символическую ссылку.

**Comment by aios** [comment]
Я вобще registerRoutes перегружал - ибо нету взаимодействия с S3
Так же пришлось перегружать view и вообще мне кажется что этот класс нужно отдельно реализовать для взаимодействия со всеми сторейджеми.
