### ISSUE TITLE
Get datatables object

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#323]
Can i get datatables objecton client side for refresh datatablesAsync as 

`var table = $('#example').DataTable( {
    ajax: "data.json"
} );

setInterval( function () {
    table.ajax.reload();
}, 30000 );`

Is is possible or exist any way do it?

**Comment by butschster** [comment]
```php
AdminTable::datatable(....)->addScript('script-name', asset('psth/to/script.js'), 'admin-default');
```

```js
Admin.Modules.add('reload-datatable', function() {
var table = $('#example').DataTable( {
    ajax: "data.json"
} )
    setInterval( function () {
         table.ajax.reload();
   }, 30000 );`
})
```

**Comment by mediaceh** [comment]
Нет, как это сделать отдельно очевидная история.
Правильный ответ 
`$.fn.dataTable.tables({ visible: true, api: true }).ajax.reload( null, false );`
