### ISSUE TITLE
Datatables bugs

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#324]
1.  С параметром 'datatables' => ['scrollX'=>true], каленьдарь из фильтра скрывается самой таблицей. 

http://i83.fastpic.ru/big/2016/1029/c4/aa1fe7d001010f7b1b3a5e1a8f6618c4.jpg
1. С datatablesAsync не работает фильтрация по, не ищет по дате. С фильтрацией видимо дело в конвертации поле даты. Где она настраивается? Просто с  datatables фильтрация работает, поиск по дате тоже работает.
2. Дата 0000-00-00 00:00:00 выглядит в таблице как 30.11.-0001 00:00.
3. http://i83.fastpic.ru/big/2016/1029/fc/a8e4010e8cf168668d0f83a1a26525fc.jpg
   Малочь, а неприятно. Иконки друг на друга наезжают.
4. AdminColumnEditable::checkbox при открытии окно ошибка - 
  http://demo.sleepingowladmin.ru/packages/sleepingowl/default/img/loading.gif 404 (Not Found)
5. datatablesAsync и AdminColumnEditable::checkbox не работают вместе. Неправильный data-url="{{ request()->url() }}" дает на конце /async.

**Comment by mediaceh** [comment]
По второму п-ту впрос снят - https://github.com/briannesbitt/Carbon/issues/66

**Comment by Malezha** [comment]
Для поиска по полям datatablesAsync сейчас используется [костыль](https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/DisplayDatatablesAsync.php#L75). Думается мне, нужно сделать это свойство настраиваемым.

**Comment by mediaceh** [comment]
Спасибо. Это я уже накопал.

**Comment by xcaptain** [comment]
how about this fix, it works for me. https://github.com/LaravelRUS/SleepingOwlAdmin/pull/341

**Comment by aios** [comment]
@mediaceh На мой взгляд не закрытым вопрос остается только по scroll. Если это не так - создай новые issue. И впредь - делай их пожалуйста более атомарными.
