### ISSUE TITLE
Баг при повторном сохранении если поле уникальное

### ISSUE THREAD

**Issue by rorc** [LaravelRUS/SleepingOwlAdmin#326]
Если поле помечено как unique, то при сохранении всё нормально, подсвечивается ошибка, что такое название уже существует (в этот момент скрытое поле формы _redirectBack имеет неверное значение). При повторном сохранении редиректит на сам сайт а не в админку.

**Comment by Butochnikov** [comment]
@butschster сам проверял?

**Comment by aios** [comment]
@rorc 
unique правило всегда пишется через 
```php
->addValidationRule('unique:table,colum,' $id_of_model) 
```
Это правило отключает проверку на той модели которую ты на данный момент редактируешь.
Просто уник можно добавлять только на операцию Create
