### ISSUE TITLE
X-axis @ MOBILE

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#329]
Hello.

how to use the X-axis in mobile version of datatables?

if i have a table (with lets imagine, 10 columns), i cant read every column, that will depend of the resolution, and if its in IPHONE, is even worse.

how to fix this?

thanks,
- Brito

**Comment by aios** [comment]
@macedodebrito So it css fix you can use Event System to catch on datatables::draw event for implement your own CSS

In future datatables will change to some vue component with other styles - and mobile friendly.
