### ISSUE TITLE
Undefined variable: editable

### ISSUE THREAD

**Issue by mediaparkBY** [LaravelRUS/SleepingOwlAdmin#344]
В чем проблема?
`
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: editable (View: localhost/vendor/laravelrus/sleepingowl/resources/views/default/column/control.blade.php)
`

**Comment by aios** [comment]
А собственно как проявляется?

**Comment by mediaparkBY** [comment]
Проявлялось при ренденге таблицы... Точно не помню, уже снес SleepingOwlAdmin...
