### ISSUE TITLE
Цветовая дифференциация всплывающих сообщений в inner.blade.php

### ISSUE THREAD

**Issue by CrazyRedScorp** [LaravelRUS/SleepingOwlAdmin#347]
Необходимо реализовать вывод информативных блоков/всплывающих сообщений при определенных операциях разными стилями.

В частности имеется файл `/vendor/laravelrus/sleepingowl/resources/views/default/_layout/inner.blade.php`, внутри которого прописано:
```
<div class="content body">
        @if($successMessage)
        <div class="alert alert-success alert-message">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                </button>
                {!! $successMessage !!}
        </div>
        @endif

        {!! $content !!}
</div>
``` 
Именно тут надо добавить обработку еще таких ситуаций как: `Info`, `Warning`, `Danger`.

К примеру, можно через сессию передавать, а в шаблоне обрабатывать какой получен параметр. 
```
\Session::flash(
    'danger_message', trans('string.errors.empty')
);
```
Если передать `success_message` то все норм, работает, но, увы, нужен другой цвет.

Еще для примера, у меня для фронтэнда имеется файл `/resources/views/includes/partials/messages.blade.php` с обработкой подобной, в котором вот такая [текстовка](http://laravel.io/bin/Lkbxv) и он подгружается из `/resources/views/layouts/app.blade.php` в виде:
```
<div class="container" data-info="messages">
    @include('includes.partials.messages')
</div>
```

Спасибо!

**Comment by butschster** [comment]
Для добавления своего HTML в шаблон админки используй пример виджета https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Widgets/SuccessMessages.php и документацию https://github.com/LaravelRUS/SleepingOwlAdmin-docs/blob/master/widgets.md

**Comment by CrazyRedScorp** [comment]
Можно сказать почти получилось.
Во-первых, `_partials.messages` не меняет цветовую гамму. Думаю передать из виджета кроме `messages` еще и нужный `styles`. А в файле `messages.blade.php` изменить строку
```
<div class="alert alert-info alert-message">
```
на
```
<div class="alert alert-{!! $styles !!} alert-message">
```
Во-вторых, теперь у меня 2 одинаковых сообщения выходит, вместо одного. Причем стоит отключить виджет - будет 1 сообщение. Проапдейтил, кеш почистил, `php artisan vendor:publish --tag=assets --force` выполнил... Все равно два.

**Comment by CrazyRedScorp** [comment]
По второму пункту - кто-то кроме нового виджета все еще продолжает закидывать мессаги в `@yield('content.top')`.

**Comment by CrazyRedScorp** [comment]
В целом чтобы виджет изначально стал универсальным надо сделать примерно такие изменения в `/vendor/laravelrus/sleepingowl/src/Widgets/SuccessMessages.php`:
```
public function toHtml()
{
    $styles = 'primary';
    $messages = session('info_message');
    if ($messages) $styles = 'info';

    if (!$messages) {
        $messages = session('success_message');
        $styles = 'success';
    }
    if (!$messages) {
        $messages = session('warning_message');
        $styles = 'warning';
    }
    if (!$messages) {
        $messages = session('danger_message');
        $styles = 'danger';
    }

    return AdminTemplate::view('_partials.messages', [
//          'messages' => session('success_message')
        'messages' => $messages,
        'styles' => $styles
    ])->render();

}
```
и в файле  `/vendor/laravelrus/sleepingowl/resources/views/default/_partials/messages.blade.php`:
```
@if($messages)
    <div class="alert alert-{!! $styles !!} alert-message">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>

        {!! $messages !!}
    </div>
@endif
@parent
```
Теперь достаточно просто передать в сессию нужный атрибут и вуаля.
