### ISSUE TITLE
intervention/image

### ISSUE THREAD

**Issue by woren951** [LaravelRUS/SleepingOwlAdmin#358]
Когда подключаю пакет [intervention/image](http://image.intervention.io/) то перестает работать массовая загрузка фото. Как мне с этим бороться?

**Comment by aios** [comment]
Гадать на кофейной гуще никто не умеет.

**Comment by butschster** [comment]
@woren951 наверняка должны быть какие либо ошибки, например, в консоли браузера или в логах Laravel, желательно всю эту информацию собрать, проанализировать и показать, иначе не понятно чем можно помочь.

**Comment by woren951** [comment]
@butschster  та суть в том что пишет только то что не может сохранить файл в указание папки.

Intervention \ Image \ Exception \ NotWritableException
"Can't write image data to path (.../public/admin-files/images/galleries/2016/11/9d118c57d10e4fd32abebf95bd92892f.jpg)"

**Comment by butschster** [comment]
@woren951 т.е. `Intervention \ Image \ Exception \ NotWritableException` не говорит о том, что нет доступа на запись? Возможно стоит проверить права?

**Comment by woren951** [comment]
@butschster та когда я убираю с проекта [intervention/image](http://image.intervention.io/) то все дале работает и файли сохраняются.

**Comment by Butochnikov** [comment]
@woren951 а как ты делаешь массовую загрузку? куда сохраняются  картинки при отсутствии intervention/image ?

**Comment by woren951** [comment]
@Butochnikov так делается масовая загрузка:
`$currentDate = Carbon::now();`
`...`
`AdminFormElement::images('photo_files', 'Photos')
                ->setUploadPath(function() {
                    return config('sleeping_owl.imagesUploadDirectory') .'/galleries/'. $currentDate->year .'/'. $currentDate->month;
                })`

А сохраняются соответственно в ту папку которая описана в ошибке.

**Comment by Butochnikov** [comment]
@woren951 вообще странно, не думаю что для intervention/image нужны особые права, раз, как ты говоришь, без нее записывает. Но ты, все же, поиграйся с доступом и посмотри на результат.

**Comment by woren951** [comment]
@Butochnikov я работаю под Vagrant

**Comment by Butochnikov** [comment]
@woren951 там тоже консоль доступна )

**Comment by woren951** [comment]
@Butochnikov все с правами хорошо)

**Comment by woren951** [comment]
@Butochnikov я проверил права и там есть на запись, чтение и тд...

**Comment by butschster** [comment]
```php
$currentDate = Carbon::now();

AdminFormElement::images('photo_files', 'Photos')
                ->setUploadPath(function(){
                    return config('sleeping_owl.imagesUploadDirectory') .'/galleries/'. $currentDate->year .'/'. $currentDate->month;
                })
```

Может у тебя пропущен ` use($currentDate) ` при использовании `$currentDate` внутри анонимной функции. Также попробуй создать вручную директории куда должно сохраняться и проверить, т.е. создать 

`public/uploads/galleries/2016/12`

**Comment by woren951** [comment]
@butschster  после создания директории все работает значит не создает папку, но ранше без подключения intervention/image папки создавало.

**Comment by butschster** [comment]
Скорее всего нужно посмотреть алгоритм работы, может стоит сначала аплоад делать, потом редактировать и потом пересохранять.

**Comment by Butochnikov** [comment]
@butschster @woren951 да, папку надо создавать самому

**Comment by butschster** [comment]
Создал issue #382 с описание текущей проблемы, Буду рад, если появится желание помочь в исправлении данной проблемы.
