### ISSUE TITLE
Регистрация модели дважды

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#359]
Столкнулся с проблемой, что нельзя регистрировать одну модель через AdminSection::registerModel() дважды из-за того, что модель устанавливается вот так - $this->models[$class] = $model, т.е. каждый следующий вызов registerModel() перезаписывает предыдущий, если указываешь одну и ту же модель. Собственно, вопрос - есть ли возможность обойти эту проблему?

**Comment by butschster** [comment]
В демо сайте данная проблема решается через создании нового класса наследника от модели

**Comment by GotFly** [comment]
Да, это один из вариантов, но может быть есть вариант, который не предполагает создание бесполезного класса?

**Comment by butschster** [comment]
Я думал над этим, просто по названию класса происходит поиск метаданных, и получается нужна тогда либо прослойка между моделью и разделом, либо тот способ что я предложил выше

**Comment by GotFly** [comment]
Благодарю за ответы. На данном этапе решил использовать потомков, ибо с прослойками было потратил бы больше времени.
