### ISSUE TITLE
Проблема с таблицами в форме

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#361]
Приветствую.
Обнаружил такую проблему - при использовании таблиц в форме (http://sleepingowladmin.ru/docs/displays - "Использование таблицы в форме") при наличии холя бы одного элемента в этой таблице при сохранении метод реквеста устанавливается DELETE. Происходит это потому что кнопка удаления  элемента имеет поле name="_method" value="delete"  и находится в форме редактирования записи. Вижу 2 варианта решения проблемы - либо сделать кнопку удаления ссылкой, без всяких полей, либо вынести таблицу элементов за основную форму.

**Comment by aios** [comment]
Читаем документацию по методу getColumns()->getControlColumn() и настраиваем его в соответствии с документацией. У тебя получится самостоятельно сделать ссылку на удаление. Он собственно для этого и был создан.
