### ISSUE TITLE
DateTime::createFromFormat() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by skyline94** [LaravelRUS/SleepingOwlAdmin#362]
Сегодня обнаружил проблему с `AdminFormElement::date()`, при сохранении формы содержащей это поле выходит следующая ошибка:
`DateTime::createFromFormat() expects parameter 2 to be string, array given`

В метод `saveValue` класса DateTime в параметр $value приходит массив с 1 элементом содержащим значение из Javascript DateTimePicker'a.
```
public function setValue(Model $model, $attribute, $value)
{
    $value = ! empty($value) ? Carbon::createFromFormat($this->getPickerFormat(), $value)->format($this->getFormat()) : null;

    parent::setValue($model, $attribute, $value);
}
```

`Carbon::createFromFormat()` ожидает вторым параметром строку, но получает массив, что и приводит к ошибке.

**Comment by skyline94** [comment]
Как добавляю поле:
`AdminFormElement::date('published_end', 'Конец публикации')->setPickerFormat('d.m.Y H:i')`

**Comment by butschster** [comment]
Проблема не пропала?

**Comment by aios** [comment]
@skyline94 Можешь ли ты проверить наличие проблемы? Были фиксы по формату date

**Comment by skyline94** [comment]
@butschster , @aios проблема исчезла после нескольких коммитов. для себя сначала решил форком и некоторыми фиксами, потом вернул реп назад всё было хорошо. думаю можно закрывать issue.

**Comment by aios** [comment]
Паша ставь mention - так быстрее доходит до обываетелей
@butschster
