### ISSUE TITLE
Сортировка записей в таблицах форм

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#365]
На странице формы имеется таблица с дочерними элементами. Добавил в эту таблице поле AdminColumn::order(). Получилось не шибко правильно, ибо данное поле рассчитано на таблицу со всеми данными. Решил сделать собственное поле, на основе order, но возникла проблема - не смог в классе поля получить данные, которые устанавливаются в setApply() данной таблицы, для получения в totalCount() количества именно выбранных полей, а не всех в таблице. Есть ли возможность получить эти данные внутри класса поля?

**Comment by aios** [comment]
@GotFly Выложи на гит пожалуйста данные которые использовались в тот момент - если они конечно остались.

**Comment by Butochnikov** [comment]
@GotFly решил задачу?

**Comment by GotFly** [comment]
В данный момент задача эта не решена. Данные, к сожалению, не сохранились, но это можно легко воспроизвести создав, например, юзеров с разными типами (модератора и обычные юзеры, например). Для каждого типа отдельная таблица tree(). Сейчас сортировка таких данных будет работать с ошибкой, ибо поле order увеличивается на 1. Была идея менять значения поля сортировки местами с предыдущим/последующим элементом в таблице, но вышеописанная проблема не позволила этого добиться.

**Comment by aios** [comment]
@GotFly прости, но с твоим методом изложения я понял только что что то не работает. 
и про проблему #515.

**Comment by Butochnikov** [comment]
@GotFly я тоже не совсем понял проблему.

**Comment by GotFly** [comment]
Проблема в сортировке элементов через AdminColumn::order(). Если выводятся все записи таблицы, то проблем нет. Если есть какая-то особая выборка (не все записи таблицы выводятся), то сортировка работает не корректно. Собственно, в моих сообщениях выше описано что именно не работает.

**Comment by aios** [comment]
@GotFly AdminColumn::order скорее всего перепишется под компонент. или будем переделывать таблицу на таблицу с сортировкой по d&d ибо меня эти стрелочки тоже парят.

**Comment by aios** [comment]
@GotFly Произвел ресерч и думал что смогу порешать через Datatables.net-rowreorder. Ну что бы все по правильному было. Однако он требует datatables-Editor. И вот когда я уже все подключил что бы в се заработало, случилось непоправимое. Editor потребовал лицензию... =((

Так что "маемо шо маемо"))

Ссылка на пример кода есть в демке.

**Comment by GotFly** [comment]
@aios Благодарю за правки. В целом, этого хватит с головой =)

**Comment by aios** [comment]
@GotFly я очень нервничал, думал что этого не хватит - потому что в планах добавить туда интерфейс Column и метод для установки своего childs-темплейта.
