### ISSUE TITLE
AdminForm / AdminFormElement in AdminColumn? 

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#367]
Is it possible to place an AdminForm or AdminFormElement in AdminColumn?

I think this would be useful to quickly edit content.

Below is my attempt:

	$model->onDisplay(function () {
		$display = AdminDisplay::datatables();

		$display->setColumns([
			AdminColumn::link('title', 'Title'),
			AdminColumn::custom()->setLabel('Test')
				->setCallback(function ($instance) {
					return AdminForm::panel()->setElements([
                                		AdminFormElement::text('title', 'Title')
					]);
				}),
			AdminColumn::datetime('updated_at', 'Updated at')
		]);

		return $display;
	});

**Comment by butschster** [comment]
```php
AdminColumn::custom()->setLabel('Test')
			->setCallback(function ($instance) {
				return AdminForm::panel()->setModel($instance)->setElements([
                            		AdminFormElement::text('title', 'Title')
				])->initialize()->render();
			}),
```
