### ISSUE TITLE
Eloquent Events 

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#372]
Или контроль сохранеия. Столкнулся с тем, что админка не понимает действительно ли сохранен айтем.

https://laravel.com/docs/5.3/eloquent#events

Подписался на события как написано выше. Останавляваю сохранение в событии updating и благополучно получаю сообщение о том, что сохранение прошло успешно. Что есть неправда.  

Все дело в этой функции:
`    public function saveForm(ModelConfigurationInterface $modelConfiguration)
    {
        if ($modelConfiguration !== $this->getModelConfiguration()) {
            return;
        }

        parent::save();

        $this->saveBelongsToRelations();

        $loaded = $this->getModel()->exists;

        if ($modelConfiguration->fireEvent($loaded ? 'updating' : 'creating', true, $this->getModel()) === false) {
            return false;
        }

        if ($modelConfiguration->fireEvent('saving', true, $this->getModel()) === false) {
            return false;
        }

        $this->getModel()->save();

        $this->saveHasOneRelations();

        parent::afterSave();

        $modelConfiguration->fireEvent($loaded ? 'updated' : 'created', false, $this->getModel());
        $modelConfiguration->fireEvent('saved', false, $this->getModel());

        return true;
    }`
Она проверяет свое событие, но совсем не хочет узнать - сохранили мы данные на самом деле или нет. 
Но этот так, пища для размышлений. Возможно в дальнейшем следует полностью отказаться от колхоза в виде своих событий. А сейчас конечно неплохо было бы контролировать - происходит процесс сохранения на самом деле или нет.

PS: Ну и вопрос по ходу - зачем еще одно событие 'saved'?

**Comment by butschster** [comment]
Просьба показать код, как ты подписываешься на события. 

Что в твоем понимании колхоз? 

Saved срабатывает как при создании так и при обновлении

**Comment by mediaceh** [comment]
in the AppServiceProvider:
`public function boot()
    {
        \App\Model\MyModel::observe(\App\Observers\MyModelObserver::class);
    }
`
Коллективное хозяйство ) В принципе, я не уверен что они прям не нужны не нужны. Мне, например, пригодилось то, что я могу использовать события админки отдельно. Но контролировать все равно нужно, пожалуй. 
Тут, как я понимаю, достаточно проверять то, что возвращает 
`$this->getModel()->save();`

**Comment by aios** [comment]
А я вот не соглашусь c @mediaceh.

Свои эвенты нужны для того что бы мочь их прервать.  Обсерверы используются для бизнес логики - если конечно ты не собираешься ее писать в админке - допустим админ панель управляет датацентром - в ее задачи входит поднять машину - а настроить все причуды на машине я думаю что этим займется обсервер самой модели машины.
Ну да и то что ты написал 
`public function boot() { \App\Model\MyModel::observe(\App\Observers\MyModelObserver::class); }`

куда приятнее видеть это в модели
public function boot()
{
...
self::observe(new SomeObserver())
}

**Comment by butschster** [comment]
@mediaceh Модель ничего не должна знать об админке, так же как и админка никак не должна выть связана с бизнес логикой приложения. Т.е. если ты будешь одни и те же ивенты использовать, то рано или поздно ты захочешь их разделить, потому как они могут пересечься и ломать твое приложение.

**Comment by mediaceh** [comment]
Нет, вы конечно можете поспорить с документацией laravel. Ваше право. 
Модель ничего не должна. Это так. А вот те, кто работают с моделью - знать должны. И, если ты считаешь, что сохраняя модель админка ничего не должна знать о том, сохраняется модель или нет и на авось пытается создать релейшенс и выводит сообщение о том что все ок - то мне нечего добавить. 
Они уже пересекаются и ломают логику из за того, что админка генерирует свое событи и работает с моделью элементарно не зная о том сохранилась она или нет. 
К тому же Eloquent Events выполняются в любом случае. Твои события просто отрабатывают раньше и все. Так что получается тупо дублирование функционала фреймверка. 
А если я очень захочу разделить события - я сделаю отдельную модель для админки и буду с ней работать точно так же через Eloquent Events. Но, в принципе, они мне понадобались для гарантированной предобработки в независимости от способа создания модели. 
И написал я это тут для других, что бы пользовались, а не что бы стобой спорить. Но тебе видимо что то не позволяет мимо пройти.

**Comment by butschster** [comment]
@mediaceh если честно, ты уже и здесь достал. Хватит генерировать кучу бесполезного текста.

Ты либо шли PR, либо показывай код с твои решением проблем.
