### ISSUE TITLE
Image Upload in CKEditor/TinyMCE?

### ISSUE THREAD

**Issue by BenWoodford** [LaravelRUS/SleepingOwlAdmin#374]
The old version of Sleeping Owl seems to support it, is there a way to enable image uploading within the wysiwyg editors in this version? Or does anyone at least have a good solution for adding the image upload plugin to CKEditor?

**Comment by skyline94** [comment]
@BenWoodford I use this package.
https://github.com/UniSharp/laravel-filemanager
Installation guide simple and production ready.

**Comment by aios** [comment]
ну у меня через CKEditor работает drag&drop и uploadImage я правда прошел огонь и воду но работает вполне корректно.

**Comment by aios** [comment]
Скорее всего нужно просто описать этот зломучающиймозги процесс.

**Comment by Butochnikov** [comment]
описать установку пакета?

**Comment by aios** [comment]
ну ты попробуй сделать так что бы в SleepingOwl в CKEditor заработал upload через кнопку в самом редакторе и drag&drop 

![image](https://cloud.githubusercontent.com/assets/737550/22437081/4a23e526-e72f-11e6-8188-54bb90d1e65a.png)

**Comment by Butochnikov** [comment]
@aios я еще этим не занимался, было проще пакет поставить.
Если есть готовое решение, то кидай в доки, пусть пока криво, облагородим.

**Comment by aios** [comment]
@Butochnikov Ок скину завтра уже... сегодня день выдался жесть противный какой.

**Comment by Tumenbayev** [comment]
@aios Все еще не вижу image upload? У кого-нибудь получилось?)

**Comment by aios** [comment]
https://sleepingowladmin.ru/docs/image_upload

@Tumenbayev 
@BenWoodford 
@skyline94 
@Butochnikov

**Comment by antsupovsa** [comment]
@aios а для timymce нет инструкции? у меня проблемы возникли с функцией file_browser_callback как обойти не могу понять, он в качестве параметра ждет анонимную функцию, а при конфигурировании ее переводят в строку.

**Comment by aios** [comment]
@antsupovsa тут не помогу - разбирался к сожалению только с CKEditor
