### ISSUE TITLE
Using setView('view_name') on Columns Display causes $columns to not be set

### ISSUE THREAD

**Issue by BenWoodford** [LaravelRUS/SleepingOwlAdmin#375]
For some reason, setView('any_template_here') causes the render() function in Columns.php to not be called and so the view has no data passed to it.

Try it, call $display->setView('display.extensions.columns') and (for me at least) it'll say `Undefined variable: columns`

Doesn't even have to be a custom view, simply calling setView() breaks it.

**Comment by butschster** [comment]
What do you want?

You can pass view object to `setView` method

```php
->setView(view(...))
```

**Comment by BenWoodford** [comment]
```
$display = AdminDisplay::table()->setView('display.extensions.columns');
```

This will cause this error:

```
Undefined variable: columns
```

if does not get to even calling the render() method if I call setView().

So I cannot set a custom view for the table. I can override the columns.blade.php but I don't want to do that, as I want a model-specific template.

**Comment by BenWoodford** [comment]
Oh, hang on, I think I see my error now. Columns.php is an extension on top of DisplayTable.

So the question then becomes, how do I set a custom template for a Display Extension?

**Comment by butschster** [comment]
```php
$display->getColumns()->setView(view(...));
```

**Comment by butschster** [comment]
You can see examples in the documentation http://sleepingowladmin.ru/docs/displays#extension-columns
