### ISSUE TITLE
Видимость полей формы

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#377]
Добавить возможность указывать для полей формы условия видимости и редактирования.

Очень часто необходимо заблокировать редактирование полей пользователям с определенными правами и здесь есть несколько вариантов действия:

1. Полное скрытие полей.

```php
$field->setVisibilityCondition(function($model) {
    return auth()->user()->isAdmin();
});
```

Если у пользователя нет прав на видимость поля, то соответственно оно игнорируется при валидации и сохранении формы

2. Установка поля в режим только для чтения и отображение альтернативного шаблона (view).

```php
$field->setReadOnly(function($model) {
    return $model->author_id = auth()->id();
});
```

Если у пользователя нет прав на редактирование поля, то соответственно оно игнорируется при валидации и сохранении формы

**Comment by Xannn94** [comment]
Отличная идея
