### ISSUE TITLE
Form Element readOnly

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#378]
Возможно стоит поля со статусом `readOnly` игнорировать при валидации и сохранении формы, т.е. их задача - только отображение информации и полное игнорирование всех остальных действий.

Также возможно необходимо предоставить более гибкий механизм установки режима "readOnly", например передача анонимной функции

```php
$field->setReadOnly(function($model, User $user) {
     return $model->author_id != $user->id;
});
```

**Comment by mediaceh** [comment]
ReadOnly вообще то для того и предназначены, что бы отправлятся на сервер в отличии от disabled.

**Comment by butschster** [comment]
see #377
