### ISSUE TITLE
Фильтры в `onDisplay` по умолчанию не работают с null значениями

### ISSUE THREAD

**Issue by UnQuaiz** [LaravelRUS/SleepingOwlAdmin#381]
Фильтры в `onDisplay` по умолчанию не работают с `null` значениями. Нельзя отфильтровать данные по null значениям. Фильтры для таких пустых полей естественно не отображаются в ячейках.

**Comment by aios** [comment]
@UnQuaiz Добрался до этой таски. Поделись уже 5.4 - и там трейт был - может сможем решить.
