### ISSUE TITLE
Исправить логику обработки изображений.

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#382]
При загрузке изображений через элемент формы `AdminFormElement::image` на текущий момент существует проблема при наличии в приложении фасада `\Intervention\Image\Facades\Image`, т.е. наличии пакета `intervention/image`

При использовании этого пакета сохранение файлов происходит [через фасад `\Intervention\Image\Facades\Image`](https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/Image.php#L40)
и если происходит попытка сохранения файла в несуществующую директорию, то приложение выкидывает ошибку о том, что директория не существует.

Есть предложение сначала сохранять файл на диск `$file->move($path, $filename)` и после сохранения передавать в фасад путь уже загруженного изображения, таким образом мы можем решить проблему.

**Comment by pinguinjkeke** [comment]
А не лучше ли использовать стандартный Storage с кастомным драйвером?
Особенно в Laravel 5.3 UploadedFile::store('store/path').
+ проблема с автоматическим созданием директорий уйдет сама-собой

**Comment by butschster** [comment]
@pinguinjkeke ну у нас еще заявлена поддержка версии 5.2, поэтому я пока что не решаюсь использовать все возможности версии 5.3

**Comment by pinguinjkeke** [comment]
@butschster в любом случае, лучше использовать то, что уже есть из коробки. Storage - одно из них.
Мало ли, кто-то на S3 захочет хранить файлы?

**Comment by butschster** [comment]
@pinguinjkeke ну я не против работы непосредственно со storage

**Comment by aios** [comment]
Сорян но я на S3 храню) и мне тяжеловато поддерживать Кастомные контроллеры

**Comment by Butochnikov** [comment]
да, сейчас очень не хватает возможности менять место хранения изображений.
а может создать отдельный элемент для работы со Storage, с пометкой на совместимость?

**Comment by aios** [comment]
Да отдельный метод и отдельный роут мне кажется из сложного это сделать поддержку сего чада в 3 элементах - file image images

**Comment by Butochnikov** [comment]
@aios да, старые оставить для локального хранения, а новый ввести.
А ты сейчас как на S3 хранишь или ты не про админку?

**Comment by aios** [comment]
Про админку. Через кастомный контроллер
И вью

30 янв. 2017 г. 15:26 пользователь "Alexey" <notifications@github.com>
написал:

**Comment by Butochnikov** [comment]
@aios а есть где глянуть? может сразу в новый элемент переделаем?

**Comment by aios** [comment]
@Butochnikov Логику описал в #321

**Comment by aios** [comment]
ref #321

**Comment by aios** [comment]
#321
