### ISSUE TITLE
Artisan section generate

### ISSUE THREAD

**Issue by c00p3r** [LaravelRUS/SleepingOwlAdmin#385]
У меня одна проблема: когда пытаюсь добавить моделей через сервис провайдер и выполняю команду php artisan sleepingowl:section:generate, то получаю ошибку в консоли:

[Illuminate\Contracts\Filesystem\FileNotFoundException] 
File does not exist at path <path_to_project>\vendor\laravelrus\sleepingowl\src\Console\Commands/stubs/section.stub  

Помогите разобраться пожалуйста

Пакет последней версии, установлен согласно документации
Использую Laravel 5.3, PHP 5.6.23, PHPStorm 2016.2, Homestead

**Comment by c00p3r** [comment]
я рад, конечно, что помог вам
а как мне решить проблему, подскажете?

**Comment by butschster** [comment]
Просто обнови пакет через composer http://sleepingowladmin.ru/docs/update

**Comment by c00p3r** [comment]
уже)

**Comment by c00p3r** [comment]
я просто не думал что изменения сразу попадают в билд
а потом вспомнил что dev версия используется

**Comment by butschster** [comment]
@c00p3r да, с выпуском релизов - беда
