### ISSUE TITLE
Undefined variable: badge 

### ISSUE THREAD

**Issue by sharp33r** [LaravelRUS/SleepingOwlAdmin#387]
После чистой установки возникает подобная ошибка, посмотрел сорцы, есть значение $badge в
\vendor\laravelrus\sleepingowl\resources\views\default\_partials\navigation\page.blade.php
которое нигде не присваивается, в kodicms есть кусок по работе с этим, но значение в шаблон идет badgeS, а не badge, данный функционал не доделан или как заставить работать бейджи напротив раздела?

**Comment by butschster** [comment]
Я так понимаю ты используешь не dev ветку?

**Comment by sharp33r** [comment]
prefer-stable = true
        "laravelrus/sleepingowl": "^4.60",

**Comment by sharp33r** [comment]
Ну и 
    "minimum-stability": "dev",

**Comment by butschster** [comment]
Только что выпустил новый релиз, обновись и должно все заработать.

**Comment by sharp33r** [comment]
Да, все отлично, спасибо
