### ISSUE TITLE
Table Display: Заголовок (Title) Таблицы не заменяется

### ISSUE THREAD

**Issue by c00p3r** [LaravelRUS/SleepingOwlAdmin#389]
Суть:
у меня есть модель `RatingLog`,
есть класс конфигурации для нее с таким вот содержимым
```
...
public function onDisplay()
    {
        return AdminDisplay::datatables()
            ->setTitle('Votes Log')
            ->setColumns([
                ...
            ])->paginate(20);
    }
...
```
я хочу задать заголовок таблицы (вместо 'Rating Logs', которое генерируется автоматически) а получаю вот что:
![image](https://cloud.githubusercontent.com/assets/5259532/21426791/8da8d576-c859-11e6-9b1d-e15fad2df4db.png)
то есть в Breadcrumbs сработало, а в заголовке вместо замены создало еще одну строку по типу подзаголовка...

мне кажется так не должно быть... или я не прав?

**Comment by butschster** [comment]
http://sleepingowladmin.ru/docs/model_configuration

**Comment by c00p3r** [comment]
ааааа, я разобрался...
просто я использую второй вариант определения моделей: через Провайдер
неплохо было бы чтобы в документации и для него были разные примеры

нужно переопределить свойство `protected $title = 'Votes Log';`

Тогда у меня вопрос: В одном AdminDisplay может быть несколько таблиц? и метод setTitle() нужен, чтобы их разделить можно было заголовками?

**Comment by butschster** [comment]
Не понимаю почему ты не хочешь полистать документацию.

Вот пример работы с моделями через Сервис провайдер
http://sleepingowladmin.ru/docs/model_configuration_section

По поводу нескольких таблиц, думаю может. 
Навскидку можно создать свой класс, реализующий интерфейс `SleepingOwl\Admin\Contracts\DisplayInterface` и в него запихивать все свои таблицы
