### ISSUE TITLE
Model works in local, but not in server

### ISSUE THREAD

**Issue by KikoPalomares** [LaravelRUS/SleepingOwlAdmin#39]
I have implemented the latest version of Sleeping Owl Admin. In my local environment it works perfectly. But on my server there are models that do not look at the menu, and you can not see when you click on an empty space. Is there a mod php or something you have to activate?
And the menu order is reversed. (If I put the "priority" works).

My Local
![local](https://cloud.githubusercontent.com/assets/6002391/13854239/c6f252a6-ec6a-11e5-854c-4a0920e9f1fd.JPG)

My Server
![server](https://cloud.githubusercontent.com/assets/6002391/13854240/c6f2bf34-ec6a-11e5-9050-d4291847a279.JPG)

**Comment by butschster** [comment]
What versions of php and Laravel?

**Comment by KikoPalomares** [comment]
Laravel 5.2
I tried on a server with PHP 7 and works, in another with PHP 5.4 and it works. 
In the server with PHP 5.5.9 does not work...
Any ideas?

**Comment by butschster** [comment]
What version of Admin have you on the server and local?

**Comment by KikoPalomares** [comment]
The latest, updated by composer today. Local and server are the same.

**Comment by butschster** [comment]
Maybe log has errors?

**Comment by KikoPalomares** [comment]
No log. I looked in the apache logs, and Laravel logs but nothing comes out.
When I click on the empty model comes out this:

![capture](https://cloud.githubusercontent.com/assets/6002391/13871110/1ba77606-ece2-11e5-97fb-68c1c8792c4c.JPG)

**Comment by butschster** [comment]
Show me providers list from `config/app.php`

**Comment by butschster** [comment]
Do you use demo application?

**Comment by KikoPalomares** [comment]
I have not used the demo, but I have been looking to see how it works. And copy some things from there.
Here is the list:
![capture](https://cloud.githubusercontent.com/assets/6002391/13871203/2d3c64f2-ece3-11e5-920a-6c95914fd5b2.JPG)

**Comment by butschster** [comment]
Try to move `SleepingOwl\Admin\Providers\SleepingOwlServiceProvider::class` before 
`App\Providers\AppServiceProvider::class` like this

```php
...
Illuminate\View\ViewServiceProvider::class,

/*
 * SleepingOwl Service Provider
 */
SleepingOwl\Admin\Providers\SleepingOwlServiceProvider::class,

/*
 * Application Service Providers...
 */
App\Providers\AppServiceProvider::class,
...
```

**Comment by KikoPalomares** [comment]
Nothing. It does not work. The same thing happens. u.u

**Comment by butschster** [comment]
It would be great, when you send me application folder with migrations and i could test app local

**Comment by KikoPalomares** [comment]
Sorry, I can not do that, it is a very large project, with three large database, many models; and not up to me to resend. But I'll explain everything I tried and I show examples.

Some models do work and others do not. I tried to get the boss to find out the difference.
This model does work:
![works](https://cloud.githubusercontent.com/assets/6002391/13872116/41528de0-ece8-11e5-9f39-8ec0ea0ae30c.JPG)
![works_2](https://cloud.githubusercontent.com/assets/6002391/13872119/44888d02-ece8-11e5-9611-2760e400578d.JPG)

This model does not work:
![not_works](https://cloud.githubusercontent.com/assets/6002391/13872121/482dc292-ece8-11e5-9410-d4db48dd900c.JPG)
![not_works_2](https://cloud.githubusercontent.com/assets/6002391/13872124/4b64fb06-ece8-11e5-8e6e-0c9fdadd6ed6.JPG)

Like I said I have 3 different databases in mysql. I have found that the models do not work belong to both a like another. So it's no problem to have several databases.
I tried on a model that does not work to remove all dependencies from other models; but still, still does not work.
I tried to put url personalized with the "setAlias ​​()"; data and I realized that in my local environment (which does work), the URL out as I defined it. But the URL server goes as he would by default. For example, in my model "therapist" I make a setAlias ​​( "therapists / list") and local works, but the route server that appears when I click on the empty model is "therapists".
Models that work and have dependencies on other models that do not work, data models that do not work are not displayed.
I tried to remove all permissions routes in the navigation.php, but does not change anything.
I've tried other more stupid things, I know I would not do anything. But I'm desperate!

If it works in my local environment and not on the server it has to be some configuration of the server.

**Comment by butschster** [comment]
Show your `phpinfo`

**Comment by KikoPalomares** [comment]
Here it is [phpinfo()](https://dl.dropboxusercontent.com/u/43431345/phpinfo.png)

**Comment by butschster** [comment]
Try to remove `config/sleepingowl.php` and `public/packages/sleepingowl` folder and run `php artisan sleepingowl:install`

**Comment by KikoPalomares** [comment]
I tried that, but still does not work... u.u

**Comment by KikoPalomares** [comment]
News!
I upgraded from version 4.17.90-beta to 4.22.96-beta. Now the empty models can be seen in the menu; but when you try to see the list is the same problem as before. Abort in the AdminController.php (327). u.u

**Comment by KikoPalomares** [comment]
I use git. My local server is Windows. The cloud server is linux. I realized that the Linux server had two folders "admin" and "Admin". Windows is not keysensitive, and it worked. Linux only worked on some models and not all for this reason. Issue solved. u.u

**Comment by butschster** [comment]
i am glad that everything is ok!!!
