### ISSUE TITLE
Table Column type 'Email' некорректно отображает значение Null

### ISSUE THREAD

**Issue by c00p3r** [LaravelRUS/SleepingOwlAdmin#390]
есть таблица в базе с колонкой "email" где значения могут быть NULL
вывожу ее следующим образом:
```
...
public function onDisplay()
    {
        return AdminDisplay::datatables()
            ->setColumns([
                ...
                AdminColumn::email('email', 'Email'),
               ...
            ]);
    }
...
```
а на выходе получаю следующую картину:
![image](https://cloud.githubusercontent.com/assets/5259532/21427152/841c71b4-c85b-11e6-8a64-7c5db3824dec.png)

замылил адреса, но там они отображаються нормально, а вот там где значение NULL наблюдаеться очень странное поведение:
некоторые записи ничего не отображают (что есть корректным поведение)
а некоторые отображают непонятний знак...

вдоказательство прикладываю скрин таблицы БД
![image](https://cloud.githubusercontent.com/assets/5259532/21427241/103e0950-c85c-11e6-924f-b570e5f7d20b.png)

**Comment by c00p3r** [comment]
вот что код страницы дает `<a href="mailto:�">�</a>`

**Comment by c00p3r** [comment]
и еще: при каждой перезагрузке эти знаки появляются в рандомных местах...
**сортировка не меняется!**
странное поведение...
2 перезагрузка
![image](https://cloud.githubusercontent.com/assets/5259532/21427625/4b8cecae-c85e-11e6-8de0-9d4816f481d9.png)
3 перезагрузка 
![image](https://cloud.githubusercontent.com/assets/5259532/21427656/8103d3b6-c85e-11e6-886f-e4d10f9f50ee.png)

**Comment by butschster** [comment]
fixed
