### ISSUE TITLE
The default button on hitting the enter/return key is bound to "Remove Image" if there is an image in the form

### ISSUE THREAD

**Issue by BenWoodford** [LaravelRUS/SleepingOwlAdmin#392]
Go to edit any model in a form with an image upload (with uploaded image) and focus on any input box. Hit the enter/return key and it will pop up asking "Are you sure?" rather than submitting the form, as it focuses on the button to "Remove Image" rather than Save.

**Comment by Butochnikov** [comment]
@butschster что-то я не понял как это?

**Comment by aios** [comment]
@Butochnikov Автофокус срабатывает на кнопку удалить в фото компоненте)
