### ISSUE TITLE
Bug: возможность сортировки колонки Actions

### ISSUE THREAD

**Issue by c00p3r** [LaravelRUS/SleepingOwlAdmin#398]
собственно сабж
![image](https://cloud.githubusercontent.com/assets/5259532/21499904/8fd0d528-cc42-11e6-995f-cdb0c79088c1.png)

так быть, мне кажется, не должно

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/e3e098bfd848bfd4322861bcfa4e14bdc1037bf3
