### ISSUE TITLE
Feature Request: Мультиселект для фильтра по belongsToMany

### ISSUE THREAD

**Issue by aios** [LaravelRUS/SleepingOwlAdmin#399]
Логика собственно простая  - должны остаться те записи у которых выбранный набор параметров совпадает.  Желательно уметь указывать какая логика запроса - самому (для Pivot)

**Comment by butschster** [comment]
Распиши пожалуйста более подробно, желательно с примером кода, как ты себе это представляешь

**Comment by aios** [comment]
Ну у нас уже есть Select в колоночных фильтрах. Вот теперь точно такой же но мульти.
Допустим у нас есть пользователи с кучей ролей
1. Саша  - admin, realtor, backend-dev, somerole
2. Вася  - realtor, backend-dev, somerole
3. Аристарх Иванович - mech, somerole
Сейчас по селекту можно выбрать somerole и выберутся все 3 пользователя
можно выбрать realtor и выберутся Саша и Вася

Нужен мульти селект для того что бы я мог выбрать в нем admin и somerole и получить только админа или выбрать somerole и backend-dev и получить только Васю

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/e4ab5ab5dc9d114f086b8f161e644bea2f8be496
