### ISSUE TITLE
Generate slug from Form

### ISSUE THREAD

**Issue by Rubemlrm** [LaravelRUS/SleepingOwlAdmin#40]
Hi there 

I have a little question ATM i have a form working well but i need to save a slug for the slug value. But i cant fint how can i do that with this package and in a auto way.

**Comment by butschster** [comment]
Do you want to auto generate slug from other filed?

**Comment by Rubemlrm** [comment]
Yes =) in the moment that i submit the form.For instance i have a title_pt field and want generate a slug from this field on save .

**Comment by butschster** [comment]
You can use https://github.com/cviebrock/eloquent-sluggable

**Comment by Rubemlrm** [comment]
Well i've found a way to do what i want without that package. On the model just add this:

`protected static function boot(){
        parent::boot();

        static::creating(function(Model $model){
            $model->slug = str_slug($notice->field,'-');
            return $model;
        });

        static::updating(function(Model $model){
            $notice->slug = str_slug($notice->field,'-');
            return $model;
        });
    }`
