### ISSUE TITLE
Обновился и выдаёт - Undefined variable: template

### ISSUE THREAD

**Issue by kedalo** [LaravelRUS/SleepingOwlAdmin#406]
На laravel 5.2 обновил composer и после этого появилась ошибка, не находит шаблон:
Undefined variable: template (View: vendor/laravelrus/sleepingowl/resources/views/default/_partials/navigation.blade.php) 
Куда смотреть?

**Comment by butschster** [comment]
Версия админки какая?

**Comment by kedalo** [comment]
"laravelrus/sleepingowl": "4.*@dev",

**Comment by aios** [comment]
Проблема осталась?

**Comment by Butochnikov** [comment]
@kedalo еще актуально?
