### ISSUE TITLE
Add custom view form and save in separate database

### ISSUE THREAD

**Issue by wowthemes** [LaravelRUS/SleepingOwlAdmin#409]
I am trying to find out in documentation to store "custom view form" in separate table and on editing the form it should fetch that content. Is it possible

**Comment by aios** [comment]
@wowthemes can you explain what kind of separate you need?

**Comment by wowthemes** [comment]
I actually built a form through owl. I want to display to other place rather than Controllers or App/Admin but getting lot of issues and stuck with that. Can you please guide me how to display it to custom views/Constrollers
