### ISSUE TITLE
Call to a member function getScopes() on null

### ISSUE THREAD

**Issue by SergeyPish** [LaravelRUS/SleepingOwlAdmin#411]
Выдает вот такую ошибку при использовании скопа в админке, что это может быть?

$user_address = AdminSection::getModel(UserAddress::class)->fireDisplay();
        $user_address->getScopes()->push(['WithUserAddress', $id]);
        $user_address->setParameter('user_id', $id);
        $user_address->getColumns()->disableControls();

**Comment by aios** [comment]
Не правильно юзаем скоупы. 
$user_address->getScopes()->push(['**w**ithUserAddress', $id]);
$user_address->setParameter('user_id', $id);

**Comment by butschster** [comment]
Здесь проблема в том, что у него `$user_address->getScopes()` выдает `null`
Нужно смотреть код

**Comment by butschster** [comment]
Такие вещи лучше покрывать тестами

**Comment by aios** [comment]
Зачем смотреть код - если человек вызывает модель - которая скорее всего не имеет Section это как мне кажется единственный случай когда getScopes может вернуть null.

**Comment by aios** [comment]
@SergeyPish Решилась ли проблема?

**Comment by aios** [comment]
Что бы не было вопросов - перепроверил этот участок. Скорее всего человек идет в разрез документации.
