### ISSUE TITLE
Таб с формами (Несколько форм на одной странице.)

### ISSUE THREAD

**Issue by lunatig** [LaravelRUS/SleepingOwlAdmin#413]
При создании нескольких форм на одной странице
``` 
$model->onCreateAndEdit(function() {
 $tab1 =  AdminForm::form()->setElements([
            AdminFormElement::textarea('name', 'Name')->setRows(3),
            AdminFormElement::textarea('url', 'url')->setRows(3),
]);
$tab2 =  AdminForm::form()->setElements([
            AdminFormElement::textarea('kontent', 'Содержание'),        
]);
$tab3 =  AdminForm::form()->setElements([
            AdminFormElement::wysiwyg('kontent', 'Содержание'),           
]);
   $tabs = AdminDisplay::tabbed();

        $tabs->appendTab($tab1, 'Основные');
        $tabs->appendTab($tab2, 'Редактор HTML');
        $tabs->appendTab($tab3, 'Визуальный редактор');
return $tabs;
    });
```

При сохранении либо затирает поля, либо выдает ошибку. 

http://demo.sleepingowladmin.ru/admin/contacts/v3/3/edit то же наблюдается и в демке при попытке сохраниться во второй вкладке. 

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: update `the_tree` set `url` = , `name` =  , `updated_at` = 2017-01-19 17:25:30 where `id` = 3)

**Comment by butschster** [comment]
Да, проблема явно имеется и связана она скорее всего вот с этим https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Model/ModelConfiguration.php#L447

Т.е. когда происходит вызов кода страницы, то в классе таба вызывается метод `setAction`, котороый проксирует его на все элементы внутри него https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/DisplayTabbed.php#L159 

В нашем случае этим элементом является отдельный таб содержащий форму, который проксирует дальше данные https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Display/DisplayTab.php#L204 и в этом месте логичнее всего было бы добавить проверку на соответствие модели.

**Comment by aios** [comment]
@lunatig проверь пожалуйста, паша коммит сделал - а у меня нет возможности проверить на данный момент.

**Comment by lunatig** [comment]
к сожалению ничего не изменилось. по прежнему форма из второй и последующих вкладок таба не сохраняется по причине  field is required. 
но при этом форма первой вкладки прекрастно сохраняет. не трогая поля из других вкладок.

**Comment by aios** [comment]
@butschster сделай пожалуйста реверт - я попробую решить эту проблему.
@lunatig удобно будет быть на связи с погрешностью в час два - последующие пару дней для тестов ибо - сам я не воспроизведу то что у тебя.

**Comment by lunatig** [comment]
@aios да я в ближайшие два дня подряд на связи. буду мониторить сообщения..
Спасибо!

**Comment by Butochnikov** [comment]
@lunatig, @aios как у вас с этой задачей?

**Comment by lunatig** [comment]
@Butochnikov я пока это решил через вставку формы в таб через fireEdit специально созданной секции
