### ISSUE TITLE
Revision control [feature]

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#415]
Revision control might be a nice feature for sleeping Owl.

This is a nice package that lets you use make any model revision-able via a single trait:
https://github.com/VentureCraft/revisionable

Not quite sure how it could be implemented just yet. Perhaps a revision history could be shown at the bottom of the form display. On click of a revision it would reload the page with the revised values.

**Comment by Butochnikov** [comment]
@butschster, @aios надо такое?

**Comment by aios** [comment]
@Butochnikov Ну точно не в таком виде в каком реализовано в этом пакете.

**Comment by Butochnikov** [comment]
@aios а вообще оно надо?

**Comment by aios** [comment]
@Butochnikov Ну как бы кейс всегда был не плохой - если бы включался выключался одной конфигой в файле - было бы круто - что бы бац и некий интерфейс в табе - показывал ревизию и время.

**Comment by Butochnikov** [comment]
@aios а я так и не понял, как мы это можем в админке использовать.
пример привести можешь? если юзверю нужно видеть историю изменений своих моделей, то можно легко воспользоваться этим пакетом и выводить в табе. 
Даже если мы подобное и включим в админку, то все равно к событиям модели цепляться надо.. Так, что пакет подключить, что в админке конфигурить, равнозначно, нет?

**Comment by aios** [comment]
@Butochnikov Мы отходим от пакетов в админке - пакет максимально должен не зависеть от других пакетов - тем более если этот нтерфейс реализуем самостоятельно.

**Comment by Butochnikov** [comment]
@aios да я же не об этом спрашивал. а про пример и надо ли оно нам?

**Comment by butschster** [comment]
Я вообще считаю, что такие фичи должны реализовываться в отдельных модулях, которые бы подключались в админке.

**Comment by aios** [comment]
@butschster и мейнтейнить потом миллиард пакетов... спасибо - просто лары уже достаточно.

**Comment by Butochnikov** [comment]
по прошествии времени понятно, что данный функционал это, скорее, потребность отдельно взятого проекта, чем часть админки.
