### ISSUE TITLE
Customisable access checks [feature]

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#416]
Hello,
I've noticed in the `ModelConfiguration` class there is a method called `setDeletable` which can take in a boolean value.

I was wondering if we could extend on this idea for the rest of the access values: `$displayable`, `$creatable`, `$editable`.

Then we could do things like:

```
$model->setDisplayable(true)
      ->setCreatable  (auth()->user()->hasRoles(['admin','superadmin']) )
      ->setEditable   (auth()->user()->hasRoles(['editor','admin','superadmin']))
      ->setDeletable  ($model->user->id == auth()->user()->id);
```
In the above example I am able to set access depending on whether the logged in user has a specific role. The `setDeletable` method is set so it only lets an author which is related to an item delete it.

I could obviously extend `ModelConfiguration` with my own class however I think it would be nice if these methods were built in.

I know we can achieve the same thing with [polices](http://sleepingowladmin.ru/docs/model_configuration#ограничение-прав-доступа), but I think these methods make for a nicer more inclusive experience.

Cheers

**Comment by 7ammer** [comment]
Hmm I think I've been a bit short sighted here. I just noticed that `auth()->user()` doesn't actually work in registerModel? :

```
AdminSection::registerModel(User::class, function (ModelConfiguration $model) {
 dd(auth()->user()) // = null // why does this not work?
});
```

Another issue is I've realised $model doesn't return what I assumed. I can't get the ID of single items using $model. Silly mistake.

Any ideas on how this can be achieved?

Cheers

**Comment by aios** [comment]
@butschster а вещь то нужная)

**Comment by butschster** [comment]
http://sleepingowladmin.ru/docs/model_configuration#ограничение-прав-доступа

**Comment by aios** [comment]
@7ammer i maked research. Policies is a best way to solve that. Sorry for wasted time.
