### ISSUE TITLE
getModel in fireEdit

### ISSUE THREAD

**Issue by lunatig** [LaravelRUS/SleepingOwlAdmin#418]
Не правильно передается класс. 

 $Tovars = TovarCard::find($id)->tovars->All();

        $TovarSection =  AdminSection::getModel(Tovar::class);

        foreach ($Tovars as $Tovar){
            $tov_form[] = $TovarSection->fireEdit($Tovar->id);
        }
        $form = AdminForm::panel();

        $form->addBody($tov_form);

В данном случае fireEdit возвращает onEdit Tovar но данные вставляются от модели TovarCard

**Comment by aios** [comment]
Это решается через Scopes. Пример находится в Admin/Contact3.php 
И если честно то я не совсем понимаю. 

`$tov_form[] = $TovarSection->fireEdit($Tovar->id);`
Эта строчка точно возвращает форму. 

То есть мы массив форм передаем в $form->addBody?

**Comment by lunatig** [comment]
да массив форм. и передает. 
только с данными от модели текущей секции.
но форму выдает из указанной (правильной) секции. 

но стоит сделать так 
`
    /**
     * @param $id
     *
     * @return mixed|void
     */
    public function fireEdit($id)
    {
        if (! method_exists($this, 'onEdit')) {
            return;
        }

        $form = app()->call([$this, 'onEdit'], ['id' => $id]);
        if ($form instanceof DisplayInterface) {
            $form->setModelClass($this->getClass());
        }
//        $form->setModelClass('App\Model\Tovar\Tovar');
        if ($form instanceof Initializable) {
            $form->initialize();
        }

        if ($form instanceof FormInterface) {
            $form->setAction($this->getUpdateUrl($id));
            $form->setId($id);
        }

        return $form;
    }
`
то есть раскоментить и все работает как нужно.

**Comment by butschster** [comment]
@lunatig да, я уже в другом твоем issue #413  отписался. Нужно добавить проверки на соответствие моделей

**Comment by butschster** [comment]
Обновись и проверь пож все ли теперь нормально

**Comment by lunatig** [comment]
Спасибо огромное .
именно fire заработал отлично. 
но вот к сожалению 413 не совсем корректно работает.

**Comment by aios** [comment]
fix 8ecd7467aaee
