### ISSUE TITLE
При добавлении Databaseasync в колонку.

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#419]
При добавлении Databaseasync в колонку перестает работать json запрос. 

$columns = AdminFormElement::columns();

$Table = AdminDisplay::datatablesAsync()->setModelClass(TovarCard::class);
/*
...
*/
 $columns->addColumn(
            [ $Table]
);

**Comment by aios** [comment]
Весь код модели пожалуйста.

**Comment by lunatig** [comment]
<?php
namespace App\Http\Sections;

use App\Model\Tovar\TovarCard;
use PhpParser\Node\Stmt\Class_;
use SleepingOwl\Admin\Section;
use SleepingOwl\Admin\Contracts\Initializable;

use AdminForm;
use AdminColumn;
use AdminSection;
use AdminDisplay;
use FilterInterface;
use AdminFormElement;
use AdminColumnFilter;
use AdminDisplayFilter;
use AdminColumnEditable;

use Meta;


use App\Model\Vendor;
use App\Model\NestedTree;
use App\Model\Tovar\Tovar;


use SleepingOwl\Admin\Contracts\FormInterface;

class TovarSection extends Section implements Initializable
{
    /**
     * @var \App\Model\Tovar\TovarCard
     */
    protected $model = '\App\Model\Tovar\TovarCard';

    /**
     * Initialize class.
     */
    public function initialize()
    {
        // Добавление пункта меню и счетчика кол-ва записей в разделе
        $this->addToNavigation($priority = 500, function() {
            return \App\Model\Tovar\TovarCard::count();
        });

        $this->creating(function($config, \Illuminate\Database\Eloquent\Model $model) {
            //...
        });
    }

    /**
     * @var bool
     */
    protected $checkAccess = false;

    /**
     * Заголовок раздела и название пункта в меню
     * @var string
     */
    protected $title = 'Карточки товаров';

    /**
     * URL по которому будет доступен раздел
     * @var string
     */
    protected $alias = 'tovarcards';

    /**
     * @return Первичная отображаемая таблица
     */

    public function onDisplay()
    {
   $TovarCardTable = AdminDisplay::datatablesAsync()->setModelClass(TovarCard::class);

        $TovarCardTable->with('vendor','NestedTree');

        $TovarCardTable->setFilters([
            AdminDisplayFilter::field('firma')->setTitle('Category ID [:value]'),
            AdminDisplayFilter::field('razdel')->setTitle('Category ID [:value]'),
        ]);

        $TovarCardTable->setColumns([
            AdminColumn::text('id')->setLabel('#'),
            AdminColumn::text('NestedTree.descript')->setLabel('Раздел')->append(AdminColumn::filter('razdel'))->setWidth('150px'),
            AdminColumn::text('vendor.descript')->setLabel('Фирма')->append(AdminColumn::filter('firma'))->setWidth('150px'),
            AdminColumn::link('ModelName')->setLabel('Название')->setLinkAttributes(['target'=>'_blank']),
            AdminColumn::order()
                ->setLabel('Порядок')
                ->setHtmlAttribute('class', 'text-center')
                ->setWidth('100px'),
            AdminColumnEditable::checkbox('market')->setLabel('Я.М'),
            AdminColumnEditable::checkbox('nalichie')->setLabel('Нал'),
            AdminColumnEditable::checkbox('visible')->setLabel('Отбр'),
        ])->paginate(20);

        $TovarCardTable->setColumnFilters([
            null,
            AdminColumnFilter::select()->setPlaceholder('Раздел (Не выбрано)')->setModel(new NestedTree)->setDisplay('descript')->setHtmlAttribute('id','razdel_select'),
            AdminColumnFilter::select()->setPlaceholder('Фирма (Не выбрано)')->setModel(new Vendor)->setDisplay('descript')->setHtmlAttribute('id','firma_select'),

            null,
            null,
            null,

        ])->setPlacement('panel.buttons');

        return $TovarCardTable;

        $columns = AdminFormElement::columns();

        $columns->addColumn(
            [
                AdminFormElement::view('adminwidget.tree')
            ], 2
        );
        $columns->addColumn(
            [$TovarCardTable]
        );

        $form = AdminForm::panel()->setElements([$columns]);

        $form->getButtons()->setHtmlAttribute('class', 'hide');

        return $form;
    }

**Comment by butschster** [comment]
@lunatig сможешь показать url по которому таблицы пытается получить данные и вообще посмотреть ошибки в консоли браузера.

Только что посмотрел на тестовом сайте и все ок.

**Comment by lunatig** [comment]
url тот же самый что и вне колонки
http://edipanel.zedor.ru/admin/tovarcards/async?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=20&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1485435207752
Ошибка 


Symfony\Component\HttpKernel\Exception\NotFoundHttpException:  in file /var/www/lunatik/data/www/ze/edipanel.zedor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 914
