### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by rramel** [LaravelRUS/SleepingOwlAdmin#42]
I've got the same message but I downloaded a v4 version as indicated on the github site. Anyone has a solution ? Thanks

**Comment by butschster** [comment]
Did you use demo app?

**Comment by rramel** [comment]
Hi, no, I downloaded sleeping owl admin and followed the steps mentionned for installation

**Comment by rramel** [comment]
Which is not clear in the installation documentation is which adresse we have to access to see sleeping-owl : i use it in apache

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/config/sleeping_owl.php#L33

```php
    /*
    |--------------------------------------------------------------------------
    | Admin URL prefix
    |--------------------------------------------------------------------------
    */
    'url_prefix' => 'admin',
```

**Comment by rramel** [comment]
Should I verify the content of this file ?

**Comment by butschster** [comment]
Try to remove from config `'middleware' => ['web', 'auth'],` `auth` middleware.

**Comment by rramel** [comment]
I went on mysite/admin which goes to mysite/login with the error mentionned

**Comment by butschster** [comment]
By defaut admin section use `auth` middleware for authorization and you should run command `php artisan make:auth` to make authentication views and routes

**Comment by rramel** [comment]
Thanks a lot! this was the missing step. What about a database used by sleeping-owl ? Nothing mentioned in the installation ?

**Comment by rramel** [comment]
Just can't login with user 'admin@site.com' and password 'password'. Any idea ?

**Comment by butschster** [comment]
Currently admin section don`t use database

**Comment by butschster** [comment]
Best way is

**Comment by butschster** [comment]
You can run artisan command `php artisan make:auth`, return `auth` to middleware and create new user

```php
\App\User::create([
      'email' => 'admin@site.com',
      'password' => bcrypt('password')
]);
```

Profit!

**Comment by rramel** [comment]
Sorry, I'm a beginner in Laravel; i did php artisan make:auth to get the login page but I don't see how to do what you mentioned at last.

**Comment by rramel** [comment]
Are you still here ? I really don't see how to create that user. Can you help please ? You'll be a big help

**Comment by butschster** [comment]
Use https://laravel.com/docs/5.2/seeding оr `php artisan tinker` or insert code to controller, run it, after then delete code

**Comment by rramel** [comment]
I've added the code to controller. It creates the user and i can connect. Thanks a lot. 
I think I miss something : I supposed sleepingowl was a tool to create pages, users,etc.. without programming. Am I wrong ?
