### ISSUE TITLE
Laravel Breadcrumbs 3 больше не поддерживается

### ISSUE THREAD

**Issue by masterjus** [LaravelRUS/SleepingOwlAdmin#420]
Пакет davejamesmiller/laravel-breadcrumbs, который вытягивается в качестве зависимости, больше не поддерживается, поэтому когда я пытался выполнить `php artisan sleepingowl:install`, я получил ошибку 

```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::share()
```
Дело в том, что `Application::share` метод был заменен на `singleton`

**Comment by masterjus** [comment]
не помогло, так как зависимость в coposer.json все еще осталась

**Comment by butschster** [comment]
Ну зависимость в композер не привязана к конкретной версии laravel https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/composer.json#L18, проблема была исключительно в сервис провайдере, так что возможно проблема именно на твоей стороне.

**Comment by masterjus** [comment]
Так и есть, я пытаюсь добавить SleepingOwl в 5.4.
Возможно, вам стоит четко ограничить версию, на которой работает ваш пакет

**Comment by kuzaxak** [comment]
@butschster пакет с крошками больше не поддерживается для 5.4 

Сообщество предложило фикс: https://github.com/maddhatter/laravel-breadcrumbs/tree/laravel-5.4

**Comment by butschster** [comment]
@kuzaxak чуть выше я уже описал проблему и описал метод ее решения и решил ее https://github.com/LaravelRUS/SleepingOwlAdmin/commit/0992ffce6368fdc75f38eb0d4fb9b1b99288745f, в сообществе решил проблему ровно таким же способом, как и я.

Будь внимательнее!
