### ISSUE TITLE
share.  Method Removed in laravel 5.4

### ISSUE THREAD

**Issue by ivankoTut** [LaravelRUS/SleepingOwlAdmin#421]
Добрый день. 
Получаю эту ошибку 
`
[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Foundation\Application::share()
`
при выполнении команды
`
php artisan sleepingowl:install
`
https://laravel.com/docs/5.4/upgrade

Подскажите где это можно исправить?

**Comment by ivankoTut** [comment]
Это относиться к сторонним пакетам

**Comment by butschster** [comment]
fixed
