### ISSUE TITLE
order by datetime @ DatatablesAsync()

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#425]
i changed from datatables to datatablesAsync() on this table, but i cant order it.

i tried the ->setOrder() and the setApply(), without success.

any ideia ?

Thanks!

```
$model->onDisplay(function () {
        $display = AdminDisplay::datatablesAsync()
                ->paginate(25)
                ->setOrder([[0, 'desc']])
                ->setNewEntryButtonText('Nova Saída')
                ->withPackage('jquery')
                ->addScript('cnc_create.js', asset('assets/js/cnc_create.js'), ['admin-default']);

        $display->setHtmlAttribute('class', 'table-info table-hover');

        $display->with('products', 'users', 'request_pp');

        $display->setApply(function($query) {
            $query->orderBy('created_at', 'desc');
        });

        $display->setColumns([
                    AdminColumn::datetime('created_at')
                    ->setLabel('Efectuado em')
                    ->setWidth('100px')
                    ->setHtmlAttribute('class', 'text-center')
                    ->setFormat('d.m.Y H:i'),
```

**Comment by aios** [comment]
Any errs?

**Comment by macedodebrito** [comment]
no.. this just dont get ordered by date.

:(

how can i debug this? :\

**Comment by aios** [comment]
It cant happens without errors. You can use Chrome Developers Tools -> Network ->(on top of main area) All | XHR ... choose XHR. Reload page. Look for query match /async\?(.*)/.  Try sort - look in Dev Tools. 
In hear you have tab "Preview" - look at Exception and send Screen or Text for that comment with mention @aios

**Comment by macedodebrito** [comment]
ok i have a "testing area" with just a few lines of code.

i tested there and same problem. check this:

![image](https://cloud.githubusercontent.com/assets/8905347/22447701/f053e59c-e74b-11e6-8924-c7f34db13af6.png)

As you can see, everything is correct, even the ORDER BY "icon", but the date is not ORDERED by DESC but by ASC.

code:

```
use App\Model\Brito;
use App\Model\Serie;
use SleepingOwl\Admin\Model\ModelConfiguration;

AdminSection::registerModel(Brito::class, function (ModelConfiguration $model) {
    $model->setTitle('Brito (Testing Zone)')->enableAccessCheck();

    // Display
    $model->onDisplay(function () {
        $display = AdminDisplay::datatablesAsync()->setOrder([[0, 'desc']])->paginate(25);
        $display->setApply(function($query) {
            $query->orderBy('created_at', 'desc');
        });

        $display->setHtmlAttribute('class', 'table-info table-hover');

        $display->with('series');

        $display->setFilters([
            AdminDisplayFilter::related('serie_id')->setModel(Serie::class)
        ]);

        $display->setColumns([
            AdminColumn::datetime('created_at', 'Efectuado em')->setWidth('100px')->setHtmlAttribute('class', 'text-center')
                    ->setFormat('d.m.Y H:i:s'),
            AdminColumn::text('id')->setLabel('#')->setWidth('30px'),
            AdminColumn::link('name')->setLabel('Nome do Produto'),
            AdminColumn::link('code')->setLabel('Código'),
            AdminColumn::link('points')->setLabel('Pontuação'),
            AdminColumn::text('series.name')->setLabel('Série')->append(AdminColumn::filter('serie_id'))
        ]);

        //$display->getColumnFilters()->setPlacement('panel.heading');
        $display->setDatatableAttributes(['searching' => false]);

        return $display;
    });
```

im doing something wrong here?

thanks :)

**Comment by CrazyRedScorp** [comment]
Hi. In the last example, don't use `setApply`. Replace it:
```
$display->setApply(function($query) {
    $query->orderBy('created_at', 'desc');
});
```
with this:
```
$display->setOrder([[0, 'desc']]);
```

**Comment by macedodebrito** [comment]
nothing works.

i tried both ways:

1) i removed ONLY setApply
2) i removed ONLY setOrder
3) i removed BOTH, setApply and setOrder

:(

just to say that, i tried to ORDER by COLUMN #1 (its the second), and in my case its the ID, and is not ordering aswell...

you have your datatablesAsync working with order? :(

**Comment by aios** [comment]
@macedodebrito yep

**Comment by macedodebrito** [comment]
Jesus.. So what i have wrong here? :( i dont think its related with model :/

**Comment by CrazyRedScorp** [comment]
@macedodebrito Your `created_at` in this model or other related model?

**Comment by CrazyRedScorp** [comment]
Maybe 
```
AdminColumn::datetime('created_at', 'Efectuado em')->setWidth('100px')->setHtmlAttribute('class', 'text-center')
    ->setFormat('d.m.Y H:i:s')
    ->setOrderable(function($query, $direction) {
        $query->orderBy('created_at', $direction);
    }),
```
or related
```
AdminColumn::datetime('created_at', 'Efectuado em')->setWidth('100px')->setHtmlAttribute('class', 'text-center')
    ->setFormat('d.m.Y H:i:s')
    ->setOrderable(function($query, $direction) {
        $query->join('tableTwo', 'tableTwo.tableOne_id', '=', 'tableOne.id' )->orderBy('created_at', $direction);
    }),
```

**Comment by macedodebrito** [comment]
this doesnt work. :\

and the thing is: the "order by" ICON, is displayed well.. but the table is not ordered :\

created_at is from my "products" table, the model table.

**Comment by aios** [comment]
show migration of model please

**Comment by macedodebrito** [comment]
Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('serie_id');
            $table->string('code');
            $table->timestamps();
            $table->softDeletes();
        });

**Comment by aios** [comment]
@macedodebrito Version of SOA and Laravel

**Comment by butschster** [comment]
You should remove 
```php
$display->setApply(function($query) {
     $query->orderBy('created_at', 'desc');
});
```

**Comment by macedodebrito** [comment]
@aios , how can i have sure about the current versions? dunno how to check it.

@butschster , i already removed, but i still cant have the table properly ordered, even if the "icon" is saying its ORDER by DESC (datetime) or even (incremented id)

**Comment by macedodebrito** [comment]
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelrus/sleepingowl": "dev-development",

??

**Comment by butschster** [comment]
Problem is in `Baum` package in this line https://github.com/etrepat/baum/blob/master/src/Baum/Extensions/Query/Builder.php#L17

Проблема в том, что автор использует Baum пакет, который пытается запрос отсортировать в том порядке, который ему необходим и для этого он убивает все предыдущие сортировки. 

В общем это проблема связки с этим пакетом.
