### ISSUE TITLE
проблема при обновлении laravel до 5.4, приводящая к полной неработоспособности

### ISSUE THREAD

**Issue by RSivakov** [LaravelRUS/SleepingOwlAdmin#428]
приветствую.

https://laracasts.com/discuss/channels/laravel/undefined-method-illuminatefoundationapplicationshare-when-upgrading-to-laravel-54?page=1

после обновления laravel до 5.4 возникает проблема, описаная по данной ссылке.

> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                                       
  [Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()  
                                                                       

Script php artisan optimize handling the post-update-cmd event returned with error code 1

вот детальное описание проблемы:
https://laracasts.com/discuss/channels/laravel/undefined-method-illuminatefoundationapplicationshare-when-upgrading-to-laravel-54/replies/311403

https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736

**Comment by Butochnikov** [comment]
а это разве дело в сове? 

хотя для совы тоже надо issue создавать по поддержке 5.4.

**Comment by axblue** [comment]
Плюсую. Такая же проблема. 

> Unresolvable dependency resolving [Parameter #0 [ <required> $class ]] in class SleepingOwl\Admin\Model\ModelConfigurationManager

**Comment by Butochnikov** [comment]
@axblue и где же она такая же?

**Comment by Butochnikov** [comment]
@butschster закрываем?

**Comment by RSivakov** [comment]
обновил. все собирается, сова заработала.
