### ISSUE TITLE
Совместимость с Laravel 5.4

### ISSUE THREAD

**Issue by Butochnikov** [LaravelRUS/SleepingOwlAdmin#429]
Собственно сабж.

p.s.: даже не знаю какой лейбел поставить )

**Comment by butschster** [comment]
Необходимо исправить здесь https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Admin.php#L76

**Comment by Butochnikov** [comment]
@butschster собственно как я и предполагал. 😄 

p.s.: This feature typically indicates a code smell. Typically, you can always construct the object in another way that is more intuitive.

**Comment by Butochnikov** [comment]
@butschster закрываем?

**Comment by Butochnikov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue которые хотелось бы закрыть](https://trello.com/c/QIqtB03o/44-issue)

**Comment by lonesta** [comment]
Обновил до dev-feature/5.4
Сейчас lara 5.4.9

При работе с моделью выкидывает

BindingResolutionException in Container.php line 804:
Target [SleepingOwl\Admin\Contracts\ModelConfigurationInterface] is not instantiable.

**Comment by lonesta** [comment]
Обновил до dev-features\5.4
Laravel 5.4.9

При работе с моделями выкидывает ошибку:

```
BindingResolutionException in Container.php line 804:
Target [SleepingOwl\Admin\Contracts\ModelConfigurationInterface] is not instantiable.
```
![screenshot_1](https://cloud.githubusercontent.com/assets/7000388/22610300/4bd434be-ea7e-11e6-8002-2aac86c54630.png)

**Comment by Butochnikov** [comment]
@lonesta а как обновлял?

**Comment by lonesta** [comment]
@Butochnikov через composer,
Конфиг через сервис провайдер.
Ошибка вылетает когда прохожу по url.

**Comment by lonesta** [comment]
@Butochnikov 
[https://gist.github.com/lonesta/51d999f20b7c27c3295e47ff29aecb5c](url)
Да с dev.

**Comment by Butochnikov** [comment]
@lonesta 
`'App\Models\Topic' => 'App\Admin\Topic',` замени на `App\Models\Topic::class => 'App\Admin\Topic',`
плюс проверь наличие `App\Admin\Topic', неймспейс, имя файла

**Comment by butschster** [comment]
С какой версии laravel проходил?

**Comment by lonesta** [comment]
@Butochnikov 
Так тоже пробовал в провайдере объявлять.
Файл создается с помощью `php artisan sleepingowl:section:generate`

@butschster Laravel 5.4.9

**Comment by butschster** [comment]
@lonesta https://github.com/LaravelRUS/SleepingOwlAdmin/issues/307#issuecomment-252845653

**Comment by lonesta** [comment]
@butschster Спасибо помогло!

**Comment by Vuishnak** [comment]
@butschster а мне не помогло.
Подскажи, пожалуйста, по поводу:
> Необходимо исправить здесь https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Admin.php#L76

Что и как там нужно поправить?

**Comment by aios** [comment]
@Butochnikov @butschster @Vuishnak по 5.4. больше вопросов нет?

**Comment by Vuishnak** [comment]
@aios вроде все ок.
