### ISSUE TITLE
navigation.php - colors

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#431]
hello again!

i have a question: its possible to change for each "navigation link", the background-color?

```
use SleepingOwl\Admin\Navigation\Page;

return [
    [
        'title' => 'SECTION-1',
        'icon' => 'fa fa-cogs',
        'url' => '/admin/section_1',
        'priority' => 10,
    ],
    [
        'title' => 'SECTION-2',
        'icon' => 'fa fa-cubes',
        'url' => '/admin/section_2',
        'priority' => 20,
    ],
```
 
the goal was: having SECTION-1 with background-RED and SECTION-2 with background-BLUE

thanks,
- Brito

**Comment by butschster** [comment]
```php

$page1 = new \KodiComponents\Navigation\Page('SECTION-1', '/admin/section_1', null, 10, 'fa fa-cogs');
$page1->setHtmlAttribute('style', 'background: red;');

return [
    $page1,
    ....
];
```

**Comment by Butochnikov** [comment]
@butschster а в чем "help wanted"? ты же предложил решение

**Comment by macedodebrito** [comment]
ErrorException in FileViewFinder.php line 112:
No hint path defined for [navigation]. (View: vendor\laravelrus\sleepingowl\resources\views\default\_partials\navigation\navigation.blade.php) (View:

**Comment by aios** [comment]
[](http://image.prntscr.com/image/844f00c89eae437891a5af1af8b4e4a9.png)
[](http://image.prntscr.com/image/6a43cabdbf3f4273a4194b2bedd8ef93.png)
