### ISSUE TITLE
sleepingOwl + laravel 5.4 (ошибки)

### ISSUE THREAD

**Issue by Fedchishina** [LaravelRUS/SleepingOwlAdmin#433]
Добрый день. Подскажите пожалуйста, а админка корректно работает с версией Laravel 5.4? 
Установить всё получилось. Но как только начала добавлять свои модели, то сыпется ошибка:
BindingResolutionException in Container.php line 819:
Unresolvable dependency resolving [Parameter #0 [ <required> $class ]] in class SleepingOwl\Admin\Repository\BaseRepository

прилагаю скрины
![1](https://cloud.githubusercontent.com/assets/11705731/22695282/4f73bbfa-ed5b-11e6-82b1-5838e4b58826.jpg)
![2](https://cloud.githubusercontent.com/assets/11705731/22695283/4f7719d0-ed5b-11e6-988d-829376775e9f.jpg)
![3](https://cloud.githubusercontent.com/assets/11705731/22695281/4f733b26-ed5b-11e6-8f59-7efc1ed38ccd.jpg)
![4](https://cloud.githubusercontent.com/assets/11705731/22695284/4f79228e-ed5b-11e6-9500-6280164112f8.jpg)

**Comment by malyusha** [comment]
Аналогичная проблема.

**Comment by malyusha** [comment]
@Fedchishina Понял в чем проблема, в composer.json написали, что версия не может быть 5.4. Отдельным коммитом.

**Comment by lonesta** [comment]
@Fedchishina @malyusha 
Есть отдельная  [ветка](https://github.com/LaravelRUS/SleepingOwlAdmin/tree/feature/5.4) с поддержкой 5.4.
Так же есть старый [issue](https://github.com/LaravelRUS/SleepingOwlAdmin/issues/429) с возможным решением других проблем на 5.4.

**Comment by Fedchishina** [comment]
@malyusha @lonesta а что мне теперь запустить в composer, чтобы использовать эту ветку? Как решить проблему поточнее подскажите пожалуйста!)

**Comment by butschster** [comment]
Просьба смотреть старые темы, этот вопрос уже поднимался. @Fedchishina ну как минимум можно получить ответ на данный вопрос из документации по composer

**Comment by Fedchishina** [comment]
т.к. сделано было еще не много, то я решила перейти на Laravel 5.3. Ошибки уже не появляются. А открыв ссылку отдельной ветки с поддержкой 5.4 - установка та же самая, как я делала. Непонятно почему сразу не подтянулась совместимость.

**Comment by MammutAlex** [comment]
Да инструкции там еще не поменяли, вот как вам надо переключиться
`composer.json`
```
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/LaravelRUS/SleepingOwlAdmin"
        }
    ],
   "require": {
        "laravelrus/sleepingowl": "dev-feature/5.4"
    },
}
```
и команда `composer update`

**Comment by Fedchishina** [comment]
@MammutAlex, большое спасибо!) Задачу можете закрывать)

**Comment by Butochnikov** [comment]
@MammutAlex  `repositories` не обязательно указывать, ветка и так прекрасно подтягивается.
