### ISSUE TITLE
Ошибка на php 5.6

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#435]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Model/ModelConfigurationManager.php#L512 - не думаю, что такое прокатит.

**Comment by butschster** [comment]
http://php.net/manual/ru/functions.arguments.php#functions.variable-arg-list

**Comment by Makashov** [comment]
В php 7 это выдает ошибку

**Comment by Makashov** [comment]
В php 7 этот оператор урезали и теперь выдает ошибку.
**syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE)**

**Comment by aios** [comment]
Интересно как так урезали то что никто не заметил?)
