### ISSUE TITLE
form is not connected on delete

### ISSUE THREAD

**Issue by docktorrr** [LaravelRUS/SleepingOwlAdmin#438]
Hello,
Pressing the Delete button on the edit page gives "Form submission canceled because the form is not connected" js warning, and the delete request is not submitted. The problem is at least in the latest versions of Chrome and FF.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/93d34910bae22c7850476905ae29946c737e9a4d

**Comment by aios** [comment]
@butschster @Butochnikov @lunatig Как поймать этот баг?

**Comment by aios** [comment]
Баг наблюдается на старых версиях админки - более не распространяется.
`composer update && php artisan vendor:publish --tag=assets --force`
