### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by chancezeus** [LaravelRUS/SleepingOwlAdmin#44]
Hi all,

I was experimenting around with soft-deletable models and found the following issues:

1. You have to manually add `$display->setApply(function(Builder $query) { $query->withTrashed(); });`, otherwise the soft deleted records won't be visible (in my opinion this should be enabled by default when the user is allowed to restore records and the model is soft-deletable (check on withTrashed/onlyTrashed as used in BaseRepository findMany))...
2. In AdminController the postRestore function does a find on the model, but the find method in the repository doesn't include trashed records, so it always returns false (I fixed it by copying findMany and instead of whereIn use find)...
3. In BaseRepository the restore function calls $this->query() which doesn't exist (you either have to call `$this->getQuery()` or `$this->getModel()->query()` (I used the 2nd one, since the first one also includes relations in the query))...

After these fixes soft-deleting works as expected...

**Comment by butschster** [comment]
Hi, thank you for your report.

Could you test new release https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.17.90-beta ?

**Comment by chancezeus** [comment]
I can confirm it now works as expected
