### ISSUE TITLE
Добавление метода проверки fillable в NamedFormElement

### ISSUE THREAD

**Issue by malyusha** [LaravelRUS/SleepingOwlAdmin#440]
### Проблема:
У меня в модели User есть заполненный fillable массив. В админке мне нужно поле `password_confirmation`, но если оставить его, то при сохранении выбьется PDOException о том, что поля `password_confirmation` не существует. Проблема возникает из-за того, что в `NamedFormElement` в методе `setModelAttribute` никак это не проверяется. Приходится лезть в класс самой модели чтобы удалять значение при его установке.

### Предложение:
Добавить метод `isFillable` в интерфейс `FormElementInterface` , и на примере метода `isVisible` реализовать его в виде `trait`. Он будет устанавливать - нужно ли устанавливать это значение для модели или нет. Т.е. финальный код метода `setModelAttribute` будет:

```php
/**
     * @param mixed  $value
     *
     * @return void
     */
    public function setModelAttribute($value)
    {
        $model = $this->getModelByPath(
            $this->getPath()
        );

        if(!$this->isFillable()) {
            return;
        }
        
        $model->setAttribute(
            $this->getModelAttributeKey(),
            $this->prepareValue($value)
        );
    }
```

Если данное предложение будет принято я сделаю PR. Спасибо.

**Comment by butschster** [comment]
@malyusha Привет

Т.е. для у поля будет что то вроде?

```php
protected $onlyIsFillable = false;

public function setIsFillable() {
     $this->onlyIsFillable = true;
}

public function osFillable() {
     return $this->onlyIsFillable;
}
```
Хорошая идея, я помню была подобная проблема как у тебя, поэтому я буду только за

**Comment by butschster** [comment]
Второй вариант - позволить переопределять метод `save`, а еще можно не привязываться к `fillable`, т.к. не всегда поведение зависит от него, может просто 

```php
$field->skipSettingValue();
```

**Comment by malyusha** [comment]
@butschster окей, добавлю

**Comment by butschster** [comment]
Спасибо!
