### ISSUE TITLE
Замена Underscore на Lodash

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#442]
Думаю пришло время заменить [undescore](http://underscorejs.org/) на [Lodash](https://lodash.com/)

Lodash имеет более функционален, немного меньше занимает места и активно развивается.

**Comment by Butochnikov** [comment]
@butschster я за, так как Lodash и так уже автоматом в ларке https://github.com/laravel/laravel/blob/master/package.json#L14

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/tree/feature/javascript-refactoring

**Comment by butschster** [comment]
http://sleepingowladmin.ru/docs/javascript
