### ISSUE TITLE
Нужен горизонтальный скроллинг таблиц 

### ISSUE THREAD

**Issue by Visionary89** [LaravelRUS/SleepingOwlAdmin#446]
Если в любой таблице отображаемой через Datatables может оказаться слишком много столбцов для отображения на экране. В частности:
```
   /**
     * @return DisplayInterface
     */
    public function onDisplay()
    {
        $display = \AdminDisplay::datatablesAsync()
            ->setHtmlAttribute('class', 'table-primary')
            ->setColumns([
                \AdminColumn::text('id')->setLabel('id')->setWidth('100px'),
                \AdminColumn::text('email')->setLabel('Email'),
                \AdminColumn::text('last_login')->setLabel('Last Login'),
                \AdminColumn::text('first_name')->setLabel('First name'),
                \AdminColumn::text('last_name')->setLabel('Last name'),
                \AdminColumn::text('created_at')->setLabel('created_at'),
                \AdminColumn::text('updated_at')->setLabel('updated_at'),
            ]);
```

На малых экранах не видны последние поля created_at updated_at и столбец с управляющими элементами.

Нужен горизонтальный скролл таких таблиц

**Comment by aios** [comment]
@Visionary89 Таблицы ведь скроллятся таким образом.

**Comment by Visionary89** [comment]
@aios даже не знаю как тебе объяснить. Попробуй. сколлбар не появляется.

**Comment by aios** [comment]
У меня работает - давай разбираться что не работает у тебя.

**Comment by Butochnikov** [comment]
@Visionary89 для этого есть снимки экрана, покажи все будет сразу понятно

**Comment by JohnLit** [comment]
Такая же проблема, вот скриншот с демо сайта (https://demo.sleepingowladmin.ru/admin/contact4s) : https://yadi.sk/i/BocWIVjN3RNM6e
