### ISSUE TITLE
Добавление новых AdminColumnEditable

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#447]
предложение по улучшению 

**таблицы с возможностью редактирования полей.** 
AdminColumnEditable сейчас есть только checkbox. а что если бы можно было редактировать таблицу целиком и не залазить в каждую запись по отдельности.

То есть создание элементов столбцов 
AdminColumnEditable::text
AdminColumnEditable::textarea 
AdminColumnEditable::select
AdminColumnEditable::DateTime
AdminColumnEditable::image

**Comment by aios** [comment]
@lunatig Фич реквесты должны быть более атомарными

**Comment by aios** [comment]
@Lunatig Опишие пожалуйста какие именно нужны Editable что бы была предметная область в issue

**Comment by Lunatig** [comment]
AdminColumnEditable::textarea сам сделал. загружу. 

AdminColumnEditable::select нужен.

**Comment by aios** [comment]
@Lunatig что из этого сделано?

**Comment by Lunatig** [comment]
@aios
dminColumnEditable::text
AdminColumnEditable::textarea
AdminColumnEditable::select

**Comment by Butochnikov** [comment]
@Lunatig это закрываем или еще нет?

**Comment by turbosnail** [comment]
@Butochnikov тут в рамках этого тикета стоит доработать AdminColumnEditable:datetime
так как на странице редактирования элемента выводится нормальный datepicker, а в списке элементов отображается combodate
кстати combodate имеет жуткий баг
в настройках совы у меня стоит формат даты d.m.Y H:i:s
`AdminColumnEditable::datetime('end', 'По')->setFormat('d.m.Y'),`
но на самом странице выводится Y-m-D H:i:s хотя в поле value проставляется d.m.Y
```
data-format="DD.MM.YY"
data-viewformat="DD.MM.YY"
```

**Comment by daaner** [comment]
Основное сделано. Закрываем иссуе
