### ISSUE TITLE
V2 :: Custom Form Elements

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#45]
Hello.

i created some Custom Form (and Column) Elements.

When i run this at localhost everything is fine.

Problem is when i upload this. I cant get those Classes running.

I Know i should use those files outside /vendor but i cant understand the logic on those errors so im using all files inside the default FormItem and Column, @vendor/sleeping-owl

2 questions: 

1) how can i use those custom files, per example, inside /app/admin;

2) at this moment i have this Custom Form Element:

```
<?php 

namespace SleepingOwl\Admin\Models\Form\FormItem;
use SleepingOwl\Admin\Models\Form\Interfaces\FormItemInterface;
use SleepingOwl\Admin\Models\Form\FormItem\BaseFormItem;
use \Admin;

class FixedHidden extends BaseFormItem implements FormItemInterface
{
    protected $label;
    public function render()
    {
      $instance = Admin::instance()->formBuilder->getModel();
      if ($instance->exists)
      {
        return $this->formBuilder->hidden($this->name, $this->getValueFromForm(), $this->attributes);
    } else
    {
       return $this->formBuilder->hidden($this->name, $this->label, $this->attributes);
   }	
}

}
```

and @ app/admin/bootstrap.php:

`FormItem::register('FixedHidden', 'SleepingOwl\Admin\Models\Form\FormItem\FixedHidden');`

LOCALHOST is ok. online i get this error:

Class 'SleepingOwl\Admin\Models\Form\FormItem\Fixedhidden' not found

How can i fix this ?

_ Laravel 4.2 
_ Admin V2

Thanks,
- Brito

**Comment by noxify** [comment]
If I understand it correctly, you have added your custom field inside the vendor directory.
If so, did you uploaded your changes also to your remote server?


Even when I create a custom field, I add it to my own `FormItems` directory inside the `app` directory (Laravel 5).

Based on your example it should looks like this then:

FormItem File: `app/FormItems/FixedHidden.php`
```
<?php 

namespace App\FormItems;
use SleepingOwl\Admin\Models\Form\Interfaces\FormItemInterface;
use SleepingOwl\Admin\Models\Form\FormItem\BaseFormItem;
use \Admin;

class FixedHidden extends BaseFormItem implements FormItemInterface
{
    protected $label;
    public function render()
    {
      $instance = Admin::instance()->formBuilder->getModel();
      if ($instance->exists)
      {
        return $this->formBuilder->hidden($this->name, $this->getValueFromForm(), $this->attributes);
    } else
    {
       return $this->formBuilder->hidden($this->name, $this->label, $this->attributes);
   }    
}

}
```

and in your admin bootstrap you have to add this:

```
FormItem::register('FixedHidden', 'App\FormItems\FixedHidden');
```

**Comment by macedodebrito** [comment]
yes i updated my remote /vendor

i think i tested something similar, and same error occured. basicaly this wont even read the bootstrap.php, it keep giving error before that.

let me check. thanks :)

**Comment by macedodebrito** [comment]
nah, i cant get this working.

your FormItems, is inside \App ?

i dont have that, in V2 (L4.2). i just cant understand the example here:

http://sleeping-owl.github.io/en/Form_Elements/Custom_Form_Elements.html

this is working properly for localhost...

I tried to google something that used L4.2  / Sleeping-Owl.v2, but i cant find.. i would try to replicate it on my project.

Thanks

**Comment by noxify** [comment]
File is located in `<laravelroot>/app/FormItems`. 
But i don't know if it's working in laravel 4 in the same way.

But based on the documentation, it should work like described in the documentation and in my example.

**Comment by macedodebrito** [comment]
ok. the class error was case-sensitive thing.

i cant still locate those files outside vendor... dunno why :(
