### ISSUE TITLE
SleepingOwl\Admin\Display\DisplayTree Сортировка

### ISSUE THREAD

**Issue by lunatig** [LaravelRUS/SleepingOwlAdmin#450]
При сортировке дерева вылетает ошибка 

Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method SleepingOwl\Admin\Repository\BaseRepository::reorder() in file /vendor/laravelrus/sleepingowl/src/Http/Controllers/DisplayController.php on line 71
Stack trace:
  1. Symfony\Component\Debug\Exception\FatalThrowableError->() /vendor/laravelrus/sleepingowl/src/Http/Controllers/DisplayController.php:71

**Comment by butschster** [comment]
В чем была проблема и как она решилась?

**Comment by butschster** [comment]
@lunatig

**Comment by lunatig** [comment]
@butschster 
ну....
я в панель запихнул (( вот и не работало. 
самые глупые ошибки это те, которые на самом видном месте и на которые подумаешь в последний момент.
