### ISSUE TITLE
Warning в консоли при удалении модели со страницы редактирования

### ISSUE THREAD

**Issue by denis-ionov** [LaravelRUS/SleepingOwlAdmin#451]
Warning (Form submission canceled because the form is not connected) в консоли при удалении модели со страницы редактирования.
Кнопка Delete, затем Yes в диалоговом окне, в итоге, выше указанный warning в консоли и никакого удаления.

**Comment by aios** [comment]
Possible duplicate #280

**Comment by denis-ionov** [comment]
Посмотрел [#280](https://github.com/LaravelRUS/SleepingOwlAdmin/issues/280). Похоже на то, что речь идет о совершенно разных ошибках.

**Comment by aios** [comment]
Не верно сделал референс 
#438 #308
