### ISSUE TITLE
Ошибка с пунктами меню

### ISSUE THREAD

**Issue by Badou90** [LaravelRUS/SleepingOwlAdmin#456]
При создании меню в navigation.php, если используется класс `KodiComponents\Navigation\Page` и у пункта меню задан url то выкидывает исключение:
````
ErrorException in FileViewFinder.php line 112:
No hint path defined for [navigation]
````

**Comment by malyusha** [comment]
@Badou90 используйте `SleepingOwl\Admin\Navigation\Page`
