### ISSUE TITLE
Отправка данных форм посредство ALAX без перезагруки.

### ISSUE THREAD

**Issue by lunatig** [LaravelRUS/SleepingOwlAdmin#459]
Немного неудобно при работе с записями каждый раз переходить на новую страницу. 
отдельно страница создания и редактирования 

но есть замечательные методы fieEdit и fireCreate результат которых можно запихнуть в модальное окно прямо на странице просмотра записей. 

Но при отправки данных с этих форм с помьщью плагина jQuery Form
http://jquery.malsup.com/form/

запрос POST дает пустой ответ. а запрос GET дает полную страницу. 
и не получается удостовериться в успешном создании или редактировании записи.

**Comment by aios** [comment]
думаю\предполагаю что в  каком то (пока что) необозримом будущем админка будет переписываться на vue-js это означает что такое понятие как взаимодействие апи front и апи backend будет разделено, а значит что мы получим больше динамики. И по моим скудным предположениям сейчас мудрить что то на jQuery это будет жесточайший костыль как для разработчиков так и для пользователей. Потому все мудрения исключительно в индивидуальном порядке - решения сей проблемы для общей аудитории лично я не вижу.
