### ISSUE TITLE
Feature Request: Vue.js

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#46]
Мне кажется будет лучше использовать vue.js и semantic-ui

**Comment by butschster** [comment]
Готов заняться?

**Comment by dronowar** [comment]
боюсь один не потяну, но если будут единомышленники можно уделить немного сил
skype: dronowar

**Comment by butschster** [comment]
По поводу semantic ui пока не думали, но vue.js вполне хотели бы использовать. Пока что нет разработчика, который любит программировать в свое удовольствие :)

**Comment by dronowar** [comment]
вместо semantic-ui подойдет и bootstrap и позволит избежать вот таких вот
мелких неприятностей http://joxi.ru/Dr8NJ0ZIkYe4j2
На счет vue.js тут если появится возможность компенсации времени (может и
незначительной) на разработку зовите. Тк проекту это даст определенный
стимул, а сама идея выглядит очень здравой.


24 марта 2016 г., 14:13 пользователь butschster <notifications@github.com>
написал:

**Comment by Argentum88** [comment]
> если появится возможность компенсации времени

@dronowar: что ты имеешь в виду?

**Comment by dronowar** [comment]
Наверное поработать за денежное вознаграждение, возможно не значительное,
тк проект интересный.
13 июня 2016 г. 11:28 AM пользователь "Андреев Павел" <
notifications@github.com> написал:

**Comment by Argentum88** [comment]
Я конечно могу ошибаться, но в подавляющем большинстве случаев, на гитхабе за участие а проекте денег не платят. Это же не фриланс биржа.

**Comment by Argentum88** [comment]
К примеру, ты используешь этот пакет в своем коммерческом проекте и благодаря ему экономишь себе кучу времени(и денег). Потом ты интегрируешь в этот пакет vue.js делая пакет лучше, тем самым экономя себе еще больше времени. Это и будет компенсация твоего времени. Плюсом ты получаешь опыт и важную строчку в резюме

**Comment by dronowar** [comment]
Ну раз проект не коммерческий, то я согласен что денег тут брать не откуда.
Могу предложить свое участие на сколько позволит время, правда тут задачка
не самая простая, прежде чем делать фронтенд на vue.js нужно определиться с
архитектурой, workflow, и другими нюансами, какие работы уже ведутся и
каким составом и т.д. Я еще не работал над опенсурс проектами )
Кстати у самого есть одна наработка, которую изначально делал для клиента,
но обстоятельства изменились, а сейчас нет времени довести до mvp версии и
выложить как опенсурс.
13 июня 2016 г. 12:20 PM пользователь "Андреев Павел" <
notifications@github.com> написал:

**Comment by Argentum88** [comment]
@dronowar Я думаю все детали можно обсудить с основным разработчиком данного пакета, коим является @butschster
