### ISSUE TITLE
Предложение - Возможность использования элементов форм вне форм.

### ISSUE THREAD

**Issue by stranger-ru** [LaravelRUS/SleepingOwlAdmin#460]
Самый простой пример:

Есть Модель `Post` с полем `title`.
Есть секция `Post` с формой, в которой хочу вывести следующее:
```
// Create And Edit
$model->onCreateAndEdit(function() {

    $form = AdminForm::panel()->addBody(

        AdminFormElement::custom(function ($model) {
            $fmodel->title = request()->title
        })->setDisplay(function ($model) {
            return view('admin.mycolumn', [
                'model' => $model
            ]);
        })

    );

    return $form;
});
```
т.е. хочу вывести поле title во вьюшке `admin/mycolumn.blade.php` в кастомном исполнении:
```
<div class="my-div-outer">
    <div class="my-div-inner">
        <?= AdminFormElement::text('title', 'Заголовок')
            ->setValue($model->title)
            ->required() ?>
    </div>
</div>
```
но это самый простой пример, так конечно в реальности это могут быть и динамические поля по связям моделей и любые другие поля, которые хочется отобразить в виде `ImageUpload`, `Select`, `Multiselect`, `Ckeditor` и т.д.
Т.е. просто хочется в кастомных вьюшках иметь возможность выводить коробочные `AdminFormElement::select(...)`, `AdminFormElement::multiselect(...)`, `AdminFormElement::image(...)` и т.д.

Ссылки по теме из чата:
https://gitter.im/LaravelRUS/SleepingOwlAdmin?at=589324851e4d4bd962c5a74f
https://gitter.im/LaravelRUS/SleepingOwlAdmin?at=5896050f5bc3025608c7d8e3

**Comment by aios** [comment]
@stranger-ru  А какой в этом смысл?  В админке используется почти полная концепция Vue 
Компонент на то и компонент что бы он использовал только свои функции - если ему нужны другие компоненты для взаимодействия то это родительский объеденяющий два компонента компонент. На столько сложной логики в SOA Нету. Но ты можешь группировать обработку - а размещать можно элементы как угодно в какой угодно последовательности.

Теперь давай представим что твою фичу зарелизили. 
Подумай что написав такой код - твоя форма становится максимально неявной - другой человек испытает если не трудности то минимум дискомфорт работы в такой форме и в ее обработке.

**Comment by stranger-ru** [comment]
> В админке используется почти полная концепция Vue. Компонент на то и компонент что бы он использовал только свои функции

Не соглашусь, в Vue именно что компонент это отдельный элемент, который я могу вывести где угодно и обернуть в любой `html`. Например на примере, который я привел выше - в Vue я могу компонент завернуть в любой `html` - в сове нет, об этом и самый простой пример. Далее, если например у модели есть связанный денные `Many`, то в Vue в массиве я могу вывести любой компонент как интерфейс элемента этой связи, в сове нет - в сове именно что элементы жестко завязаны на форме, даже в кастомной вьюшке, которая будет выведено в пределах формы я не могу использовать эти элементы.

**Comment by aios** [comment]
Не путай пожалуйста концепцию, и реализацию.

**Comment by butschster** [comment]
@stranger-ru

**Comment by stranger-ru** [comment]
> Самый простой вариант - либо переопределять view формы стандартной и получать по ключу в шаблоне каждое поле по отдельности и вставлять его туда ,куда тебе необходимо

Т.е. если я в переопределю view формы, то в этом view я смогу по отедльности использовать  коробочные AdminFormElement::select(...), AdminFormElement::multiselect(...), AdminFormElement::image(...) и т.д., или я неправильно понял?

**Comment by aios** [comment]
Правильно но ты тогда в итоге получишь только кастомную реализацию того что уже есть и не более
@stranger-ru

**Comment by stranger-ru** [comment]
Оk, спасибо.
