### ISSUE TITLE
etrepat/baum

### ISSUE THREAD

**Issue by lunatig** [LaravelRUS/SleepingOwlAdmin#463]
https://github.com/etrepat/baum - не поддерживается с on 4 Mar 2015 
работает с ошибками.
не работает перестройка больших деревьев. 
Не работает наследование.

Замените в доках его на
https://github.com/gazsp/baum
или другое решение.

**Comment by Butochnikov** [comment]
@butschster что думаешь?

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Repositories/TreeRepository.php#L21

**Comment by lunatig** [comment]
@butschster 
Если я пользуюсь библиотекой 
https://github.com/gazsp/baum
то в ней есть изменения. 
toHierarchy - сортирует дерево без левого индекса

toSortedHierarchy - строит с учетом левого индекса. 
https://github.com/gazsp/baum/blob/master/src/Baum/Extensions/Eloquent/Collection.php#L16

В админке используется toHierarchy 
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Repositories/TreeRepository.php#L77

**Comment by butschster** [comment]
@lunatig 
Значит нужно добавить новый метод в репозиторий, который позволит добавить кастомный Callback на определение или получения дерева элементов.

Сейчас ты используешь `gazsp/baum`, а потом выйдет еще один форк или уже кто-то использует другой форк, то на каждый не напасешься методов.

**Comment by lunatig** [comment]
@butschster
а как это сделать? ((

etrepat/baum работает с ошибками ( 
а у TreeTypeKalnoy  маленький арсенал методов

**Comment by Butochnikov** [comment]
@butschster тут скорее выбор за нами какие пакеты поддерживать. Если отказаться от etrepat/baum и выбрать другую, то это уже будет как наша рекомендация.

**Comment by aios** [comment]
@Butochnikov дело немножко даже не в этом.
Мы по любому должны поддерживать работу нашего пакета - а какие средства выбирать это нам в принципе и решать. Фидбеки в этом помогают. Так что проблема больше наша чем не наша.

**Comment by butschster** [comment]
Итак, я полностью переработал сам принцип работы с различными типами репозиториев, которые используются для построения дерева.

Теперь за каждый тип дерева отвечает отдельный класс, https://github.com/LaravelRUS/SleepingOwlAdmin/tree/development/src/Display/Tree

Для поддержки своего типа дерева необходимо добавить свой класс, для удобства его можно наследовать от `SleepingOwl\Admin\Display\Tree\NestedsetType` и реализовать те методы, которые он попросит. В случае @lunatig необходимо это будет выглядить так:


```php
<?php

namespace Admin\Tree;

use Illuminate\Database\Eloquent\Model;
use SleepingOwl\Admin\Display\Tree\BaumNodeType;

/**
 * @see https://github.com/etrepat/baum
 */
class CustomBaumNodeType extends BaumNodeType
{
    /**
     * Get tree structure.
     *
     * @param \Illuminate\Database\Eloquent\Collection $collection
     *
     * @return mixed
     */
    public function getTree(\Illuminate\Database\Eloquent\Collection $collection)
    {
        return $collection->toSortedHierarchy();
    }
}
```

А дальше при инициализации `DisplayTree` мы указываем этот класс

```php
AdminDisplay::tree(\Admin\Tree\CustomBaumNodeType::class)->...
```
