### ISSUE TITLE
ControllerDispatcher::__construct() error

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#464]
Если в модели установить класс контроллера ($model->setControllerClass('controller_name')), то выдает ошибку
FatalThrowableError in ControllerDispatcher.php line 34. Type error: Argument 1 passed to Illuminate\Routing\ControllerDispatcher::__construct() must be an instance of Illuminate\Routing\Router, instance of Illuminate\Foundation\Application given, called in /www/code/local/vendor/laravelrus/sleepingowl/src/Routing/ModelRouter.php on line 83

Собственно, раньше при установки контроллера такой ошибки не возникало. Кто-нибудь сталкивался?

**Comment by butschster** [comment]
Laravel какой версии?

**Comment by GotFly** [comment]
5.2

**Comment by aios** [comment]
$model->setControllerClass работает с namespace. Так как метода получения namespace из RouteServiceProvider нету. То указывать нужно не ControllerName а `\App\Path\To\Http\Controllers\ControllerName`
Тогда все будет работать.
@GotFly

**Comment by UksusoFF** [comment]
@GotFly Получилось с namespace? У меня на L 5.2, SO 4.95.29 и namespace та же проблема.
