### ISSUE TITLE
Target [SleepingOwl\Admin\Contracts\ModelConfigurationInterface] is not instantiable

### ISSUE THREAD

**Issue by segseriy** [LaravelRUS/SleepingOwlAdmin#465]
Доброго времени суток.
Возникла проблема при обновлении laravel с 5.2 на 5.3
При входе на страницу со списком элементов модели, или на любую страницу, где модель регистрируется, получаем вот такую ошибку
`BindingResolutionException in Container.php line 763:
Target [SleepingOwl\Admin\Contracts\ModelConfigurationInterface] is not instantiable.`
Прошу о помощи в исправлении данной ошибки

**Comment by butschster** [comment]
Для решения проблемы достаточно поискать по закрытым issue
