### ISSUE TITLE
Ошибка в переводе

### ISSUE THREAD

**Issue by omak-oorzhak** [LaravelRUS/SleepingOwlAdmin#467]
Ошибка в переводе на английский в сообщении об удалении записи. Надо "Record has been deleted successfully", а не "Record deleted successfully", т.к. запись была удалена админом, а не сама запись удалила что-то.
![record](https://cloud.githubusercontent.com/assets/10987020/23448855/fdd58e18-fe85-11e6-9c0b-98054fb8a2ee.png)

**Comment by Butochnikov** [comment]
@omak-oorzhak пройдись по остальным сообщениям и сделай PR, пожалуйста
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/resources/lang/en/lang.php
