### ISSUE TITLE
переопределение Image::saveFile() 

### ISSUE THREAD

**Issue by dobrynja** [LaravelRUS/SleepingOwlAdmin#469]
добрый день

`namespace App\Form;

use SleepingOwl\Admin\Form\Element\Image as Image;

class MyCustomImage extends Image
{
    protected static function saveFile(UploadedFile $file, $path, $filename, array $settings)
    {
        if (class_exists('Intervention\Image\Facades\Image') and (bool) getimagesize($file->getRealPath())) {

            $image = \Intervention\Image\Facades\Image::make($file);
            $thumb = \Intervention\Image\Facades\Image::make($file);

            $thumb->resize(320, null, function ($constraint) {
                $constraint->aspectRatio();
            });

            foreach ($settings as $method => $args) {
                call_user_func_array([$image, $method], $args);
            }

            $thumb->save($path.'/thumb-'.$filename);
            return $image->save($path.'/'.$filename);
        }

        $file->move($path, $filename);
    }

}`

выдает мне 
Cannot make non static method SleepingOwl\Admin\Form\Element\Image::saveFile() static in class App\Form\MyCustomImage

что не так делаю?

**Comment by Makashov** [comment]
Функция **saveFIle** это **public function** вы обявили его как **protected static function**

**Comment by dobrynja** [comment]
`class MyCustomImage extends Image
{
    protected public function saveFile(UploadedFile $file, $path, $filename, array $settings)
`
а так выдает Multiple access type modifiers are not allowed

**Comment by Makashov** [comment]
Наверное потому что нельзя писать **protected public** :)

**Comment by dobrynja** [comment]
и как тогда переопределить функцию?

**Comment by Makashov** [comment]
Можете сделать как в родительском классе **Image** там он объявлен как 
`public function saveFile(UploadedFile $file, $path, $filename, array $settings)`.

Переопределяя вы должны сохранять совместимость. Можете почитать об этом в документаций.
http://php.net/manual/ru/language.oop5.basic.php#language.oop5.basic.extends

**Comment by dobrynja** [comment]
а так выдает
Declaration of App\Form\MyCustomImage::saveFile() should be compatible with SleepingOwl\Admin\Form\Element\Image::saveFile(Illuminate\Http\UploadedFile $file, $path, $filename, array $settings)

**Comment by aios** [comment]
@dobrynja мне кажется проблема в твоем не правильном восприятии перегрузки методов объекта.

**Comment by dobrynja** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/issues/330

вот код тут взял, не могу реализовать у себя, помогите）

**Comment by Makashov** [comment]
Я понял. 
Когда @butschster вот тут #330  писал свой пример метод **saveFile** была ещё protected static.

Короче поменяй 

> protected static function saveFile(UploadedFile $file, $path, $filename, array $settings)

на 

> public function saveFile(UploadedFile $file, $path, $filename, array $settings)

**Comment by dobrynja** [comment]
так тоже пробовал, вылетает ошибка
Declaration of App\Form\MyCustomImage::saveFile() should be compatible with SleepingOwl\Admin\Form\Element\Image::saveFile(Illuminate\Http\UploadedFile $file, $path, $filename, array $settings)

**Comment by dobrynja** [comment]
Как тогда по другому можно при пакетной загрузке избражений обработать их: сделать разные ресайзы, разложить по разным папкам?

**Comment by aios** [comment]
Правильно переопределить метод. И юзать свой элемент.
