### ISSUE TITLE
Is it possible to edit a relationship model with pivot?

### ISSUE THREAD

**Issue by KikoPalomares** [LaravelRUS/SleepingOwlAdmin#47]
Is it possible to edit a relationship model with pivot?

Example:
`$this->belongsToMany('App \ Role')->withPivot('column1', 'column2');`

Like this but you can edit the columns.
`AdminFormElement::multiselect()`

**Comment by butschster** [comment]
Unfortunatly, no.

Can you describe, how do you see it

**Comment by KikoPalomares** [comment]
It could be something like this:
http://formvalidation.io/examples/adding-dynamic-field/#adding-fields-with-different-names
In the first column a select field for the model.

**Comment by aios** [comment]
@KikoPalomares that component will be developed soon - now i will make some pivotal callback for pivot data. That thing will partically fix that feature.
