### ISSUE TITLE
Bug report - dependent field is not initiating when editing form

### ISSUE THREAD

**Issue by avifatal** [LaravelRUS/SleepingOwlAdmin#472]
Hi,
If you have a dependent field, and you go to the edit a row.
The target field will be stay as readonly even if the source field has value in it.
In order to overcome this, I am manually triggering the `select2:selec` evnet

```
$script = '<script>
   $(document).ready(function(){
        $("#product_id").val($("#product_id").val()).trigger(\'select2:select\')
  ;})
</script>';
$form->addBody(AdminFormElement::html($script));
```

**Comment by 1oginov** [comment]
@avifatal I've used your code with nearly-out-of-the-box SleepingOwl's configuration and it inserts this JS snippet before the initialization of jQuery (`admin-app.js` is at the bottom of the page), so it throws `$ is not defined` error. I prefer `window.onload = function () {};` instead of using `$(document).ready(function () {})`.

**Comment by 1oginov** [comment]
Относительно `dependentselect`, возможно кому-то будет полезно. У меня есть модели `Country` (страна), `State` (область) и `City` (город):

![structure](https://cloud.githubusercontent.com/assets/8770338/24334997/50d483ee-129f-11e7-824f-1f6f5500fc1c.png)

При добавлении и изменении города хотим выбирать родительскую область, фильтруя области по странам. Способ проще: вывалить все области, но это не красиво. Итак, пишем в лоб:

```php
public function onEdit($id)
{
    return AdminForm::panel()->addBody([
        AdminFormElement::select('country_id', 'Country', Country::class)->setDisplay('name')->setValueSkipped(true),
        AdminFormElement::dependentselect('state_id', 'State', ['country_id'])
            ->setModelForOptions(State::class)->setDisplay('name')
            ->setLoadOptionsQueryPreparer(function ($item, $query) {
                return $query->where('country_id', $item->getDependValue('country_id'));
            })
            ->required(),
        AdminFormElement::html($selectsInitJs),
        AdminFormElement::text('name', 'Name')->required(),
    ]);
}

public function onCreate()
{
    return $this->onEdit(null);
}
```

При таком раскладе и страна, и область будут пустые. В случае добавления нового города это не проблема, но если мы изменяем имеющийся город, то связи теряются. Как я решил:

```php
public function onEdit($id)
{
    // Get Country's ID for current City
    $countryId = $id ? City::find($id)->state->country->id : null;

    $selectsInitJs = <<<HEREDOC
<script>
    window.onload = function() {

        // Trigger #country_id to initialize #state_id update
        $('#country_id').trigger('select2:select');
        
        // Hook on successful ajax request that returns selected #state_id
        $(document).ajaxSuccess(function(event, jqXHR, ajaxOptions, data) {
            if (data.selected) {
                $('#state_id').val(data.selected).trigger('change');
            }
        });
        
    };
</script>
HEREDOC;

    return AdminForm::panel()->addBody([

        // Country field used to simplify state choosing
        AdminFormElement::select('country_id', 'Country', Country::class)->setDisplay('name')
            ->setDefaultValue($countryId)->setValueSkipped(true),

        // States select will be updated after choosing country
        AdminFormElement::dependentselect('state_id', 'State', ['country_id'])
            ->setModelForOptions(State::class)->setDisplay('name')
            ->setLoadOptionsQueryPreparer(function ($item, $query) {
                return $query->where('country_id', $item->getDependValue('country_id'));
            })
            ->required(),

        AdminFormElement::html($selectsInitJs),

        AdminFormElement::text('name', 'Name')->required(),
    ]);
}
```

Что здесь происходит: для начала получаем ID страны (если вызвана форма создания, то `null`), чтобы установить значение по умолчанию `setDefaultValue($countryId)`. Через js вызываем `$('#country_id').trigger('select2:select');`, чтобы запустить загрузку областей для выбранной страны, чуть проще, чем у @avifatal.

`dependentselect` подтягивает данные AJAX запросом, но не выбирает `selected` из ответа — баг? Чтобы исправить это, приходится сделать хак: подцепиться на успешное выполнение всех AJAX запросов. Если в ответе присутствует `selected`, то проставляем его: `$('#state_id').val(data.selected)`. Очевидно, что при использовании нескольких `dependentselect` нужно доработать обработчик.

Таким образом, при открытии формы изменения выбирается сначала страна (из текущей области) и после подтягивания областей выбирается текущая область.

**Comment by aios** [comment]
@1oginov Стукани в телеграм - нужна помощь с тестированием.

**Comment by aios** [comment]
@avifatal Get me on telegram for research that bug `@aioslike`

**Comment by aios** [comment]
`"4.*@dev"`
composer update
php artisan vendor:publish --tag=assets --force

**Comment by 3director** [comment]
@1oginov , I gave up on this framework because the support is in Russian and I am an english speaker. Sorry.

**Comment by avifatal** [comment]
@1oginov  , I gave up on this framework because the support is in Russian and I am an english speaker. Sorry...

**Comment by aios** [comment]
@avifatal Translation to english on progress - will wait for you return)))
