### ISSUE TITLE
Добавить секцию в подменю

### ISSUE THREAD

**Issue by Vuishnak** [LaravelRUS/SleepingOwlAdmin#473]
Собственно, когда юзаю ```$this->addToNavigation() ``` метод добавляет секцию в меню, но мне нужно добавить его в подменю. Собственно, если добавлять меню через navigation.php, то там понятно, а если я прям в настройках секции хочу это сделать?
Спасибо!

**Comment by ABPgroup** [comment]
Поддерживаю данный вопрос

**Comment by butschster** [comment]
Привет, ребята.

Только что добавил коммит, который упростит эту процедуру.

Коротко про принцип. Для корректного использования необходимо внести изменения в сервис провайдер, где происходит инициализация меню из файла `navigation.php` (https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Providers/AdminSectionsServiceProvider.php#L56), он должен отрабатывать раньше, чем происходит инициализация классов разделов (https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Providers/AdminSectionsServiceProvider.php#L50).

Далее в файле навигации необходимо добавить пунк меню, в который вы хотите поместить свой раздел.

Пример так:

```php
[
    'title' => 'Content',
    'id' => 'content-section'
],
...
```

Главное условие, что у этого пункта меню должен присутствовать `id`, по которому будет произведен поиск.

Ну и далее в своем разделе пишем что то типа:

```php
    /**
     * Initialize class.
     */
    public function initialize()
    {
        $page = \AdminNavigation::getPages()->findById('content-section');

        $page->addPage(
            $this->makePage(300)
        );
    }
```

**Comment by Butochnikov** [comment]
@Vuishnak  а я не совсем понял задачу.
Если в navigation был раздел, то ищем по id и добавляем пункт, получаем подпункт.
Если нет такого пункта, или подпункта, то логично, что их надо создать, прежде чем к ним что-либо добавлять.

@butschster я так понимаю @Vuishnak хотел, чтобы можно было делать `$this->addToNavigation()`, сразу указывая в какой раздел добавлять.

**Comment by Vuishnak** [comment]
@Butochnikov да.

**Comment by butschster** [comment]
@Butochnikov  именно это я и показал как сделать

**Comment by Lunatig** [comment]
@aios дока готова  в демке есть. закрывай. 
https://sleepingowladmin.ru/docs/menu_configuration#add-sub-section
https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Http/Sections/TabbedDataTablesAsync.php
