### ISSUE TITLE
Доработка selectajax

### ISSUE THREAD

**Issue by Butochnikov** [LaravelRUS/SleepingOwlAdmin#475]
@aios 
selectajax сейчас работает только с моделью, т.е. список или массив передать не получится. 
Если это так и останется, то нужно убрать 3-й параметр из доки.

и т.к.  элемент использует метод setLoadOptionsQueryPreparer, то не получается изменить запрос, т.е. поиск будет происходить по всем значениям в таблице.
а если нужно ограничить по запросу? ведь не всегда таблица содержит уникальные значения для использования в select.

Понимаю, что можно сделать свой роут и выдавать нужные значения, но все же...

**Comment by aios** [comment]
@Butochnikov исправим.
