### ISSUE TITLE
Динамическая смена полей

### ISSUE THREAD

**Issue by Vuishnak** [LaravelRUS/SleepingOwlAdmin#476]
Привет! Мне необходимо сделать селект и при изменении его значения заменять поля в форме с одного на другое.
Я делаю так:
```php
AdminForm::panel()
   ->addScript('jquery.js', asset('js/jquery.js'), ['admin'])
   ->addScript('config.js', asset('js/config.js'), ['admin']);
```
Но при загрузке страницы в консоле ошибка, что "$" не найден, хотя сначала подключается jquery, а потом уже мой кастомные скрипт.
В чем может быть проблема? Или, возможно, есть более элегантное решение такой задачи?

**Comment by Butochnikov** [comment]
это не подходит? http://sleepingowladmin.ru/docs/form-element#dependentselect

**Comment by Vuishnak** [comment]
Думаю, нет. Там же меняются селекты. А мне нужно изменять текстовые поля.
Например: у меня есть несколько типов скидок - в процентах и в сумме.
Данные передаются обычным массивом, типа: `['В процентах', 'В валюте']`
Когда через селект я выбираю первый вариант (в процентах) и должно добавится текстовое поле, для ввода значения скидки в процентах, а если выбираю второй вариант, текущее поле значения скидки убирается и заменяется на новое (в валюте).

**Comment by lunatig** [comment]
попробуй
 ->addScript('config.js', asset('js/config.js'), ['admin'],true);

**Comment by Vuishnak** [comment]
@lunatig неа(

**Comment by butschster** [comment]
@Vuishnak Jquery есть из коробки. 

```php
->addScript('config.js', asset('js/config.js'), ['admin-default'], true);
```
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Templates/TemplateDefault.php#L51

**Comment by Vuishnak** [comment]
работает, спасибо)
еще такой вопрос, а можно средствами совы элемент обернуть в div с id каким-то, чтобы я могу очистить его и затащить туда новый инпут?
