### ISSUE TITLE
Ошибка загрузки большого изображения

### ISSUE THREAD

**Issue by Xmaksss** [LaravelRUS/SleepingOwlAdmin#478]
При загрузке большой картинки (13.3М) возникает ошибка
`FatalErrorException in Image.php line 34:
Call to a member function getRealPath() on null`

Вот участок кода который выводит поле 
`AdminFormElement::image('image_main', 'Main Image')->required(),`

С маленькими изображениями проблем нет.

**Comment by ABPgroup** [comment]
Проверьте настройки PHP http://php.net/manual/ru/ini.core.php#ini.upload-max-filesize

**Comment by Xmaksss** [comment]
Да, точно, спасибо большое
