### ISSUE TITLE
Роуты с кастомные префиксом [custom routes]

### ISSUE THREAD

**Issue by Vuishnak** [LaravelRUS/SleepingOwlAdmin#484]
Есть префикс админ панели. Но у меня есть разделы, где необходимо добавить префикс.
Например: admin.example.com/ - префикс '/' в настройках.
А есть раздел, где мне нужно получить получить следующий адрес:
`admin.example.com/{prefix}/users` - где {prefix} - НЕ префикс админ-панели.
Можно ли так сделать?
И еще, какие роуты по умолчанию у CRUD операций. если брать страницу юзеров, то `users.index|users.create|etc` - не находит.

**Comment by Butochnikov** [comment]
@Vuishnak можно, почему нельзя.
список всех роутов `php artisan route:list`

**Comment by Vuishnak** [comment]
Спасибо. Закрыто.
