### ISSUE TITLE
После последнего обновления 11.03.2017 (274a82b) проблема с wrapper'ом

### ISSUE THREAD

**Issue by ABPgroup** [LaravelRUS/SleepingOwlAdmin#485]
Проблема [http://prntscr.com/eilhr6](http://prntscr.com/eilhr6)
Если убрать у wrapper position:releative [http://prntscr.com/eilih5](http://prntscr.com/eilih5)

**Comment by Butochnikov** [comment]
`php artisan vendor:publish --tag=assets --force` делал? 
`shift-f5` ? 
обновился на проекте где куча бейджей, все  работает

**Comment by ABPgroup** [comment]
Делал вот так php artisan sleepingowl:update
Помогло вот так php artisan vendor:publish --tag=assets --force

Спасибо
