### ISSUE TITLE
Неправильный путь к изображению

### ISSUE THREAD

**Issue by Xmaksss** [LaravelRUS/SleepingOwlAdmin#487]
После загрузки изображения оно не отображается, так как в response приходит неправильный путь

`path:"http://localhost:8000/D:\web\site\public\images/uploads/eb8c351ffc34a646f7c1889a93be2085.jpg"
value:"D:\web\site\public\images/uploads/eb8c351ffc34a646f7c1889a93be2085.jpg"`

Что это может быть?

**Comment by Vuishnak** [comment]
У меня, кстати, так же. Хотя вчера все нормально было...

**Comment by Butochnikov** [comment]
Исправлено в https://github.com/LaravelRUS/SleepingOwlAdmin/commit/ae0f8dc017bff506edf43ed0dacc34b32acee52e

**Comment by Vuishnak** [comment]
Обновился, у меня теперь вообще превью не работает.
Хотя... А может влиять тот факт, что я пытаюсь загрузить файл в папку, вторая является символической ссылкой? У меня просто большой проект и несколько админок и главный фронт. Я хочу туда грузить их через админку.

**Comment by ryzhykE** [comment]
Картинки не загружаются и  js ассеты не реботают

**Comment by aios** [comment]
`composer update
php artisan vendor:publish --tag=assets --force`
