### ISSUE TITLE
Symlink upload folder

### ISSUE THREAD

**Issue by Vuishnak** [LaravelRUS/SleepingOwlAdmin#489]
В общем, у меня несколько админок и 1 фронт. Мне нужно грузить картинки сразу на фронт. Решил использовать symlink. В папке `public` фронта создал папку `uploads` и сделал на нее симлинки в админках (фронт, админка1, админка2 - 3 разных проекта laravel), но при загрузке ничего не происходит и вылазит ошибка в консоли:
<img width="1280" alt="2017-03-11 18 56 26" src="https://cloud.githubusercontent.com/assets/3612580/23825119/78da7b10-068c-11e7-8513-7be224f079cf.png">
`Unable upload file to uploads/images`
Можно ли вообще так загружать? Может я делаю что-то неверно? Или есть вообще другой способ?

**Comment by lunatig** [comment]
```AdminFormElement::image('image', 'Фото')
                    ->setUploadFileName(function(\Illuminate\Http\UploadedFile $file) {
                        $filename=str_replace('.'.$file->getClientOriginalExtension(),'',$file->getClientOriginalName());
                        $slug = str_slug($filename,'-').'.'.$file->getClientOriginalExtension();
                        return str_replace('_','-',$slug);
                    })
                    ->setUploadPath(function(\Illuminate\Http\UploadedFile $file) {
                        return '../../'.env('PHOTO_LOAD_DIR'); // public/files
                    })
```

**Comment by Vuishnak** [comment]
@lunatig это прям лобовое решение. Да, так загружает, но превью не показывает...

**Comment by lunatig** [comment]
у меня показывает. в модели еще нужно. подкрутить мутаторы.
ты же получаешь путь загруженной картинки из папки фронта. 
а админка думает что из папки админки. нужно переписать этот путь. и еще в htaccess поймать и перенаправить.

**Comment by Vuishnak** [comment]
Можешь примерчик кинуть?

**Comment by lunatig** [comment]
htaccess у меня размер изображения задается через url
для front.ru/image/h_100/w_100/image.jpeg

	RewriteRule image/(h_([0-9]+))?/?(w_([0-9]+))?/?(h_([0-9]+))?/?((.*)\.(gif|jpeg|jpg|png|GIF|JPEG|JPG|PNG))$ http://www.front.ru/image.php?height=$2&width=$4&height=$6&image=$7 [NS,L]

class yourmodel extends Model
{
    use \KodiComponents\Support\Upload;
  protected $casts = [
        'imag' => 'image', // or file | upload
    ];
  public function getUploadSettings()
    {
        return [
            'image' => [
                'orientate' => [],
                'resize' => [1000, null, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                }],
            ]
        ];
    }
