### ISSUE TITLE
Как работать с полями enum через AdminFormElement::select

### ISSUE THREAD

**Issue by OlegGrizzly** [LaravelRUS/SleepingOwlAdmin#493]
Сделал так:
```
AdminFormElement::select('category', 'Категория')->setEnum(['Коммерческая', 'Некоммерческая'])->required(),
```

При создании все отлично, но вот при редактировании не выбирает нужный элемент из списка enum, точнее он просто пут как будто его не выбрало из таблицы.

**Comment by aios** [comment]
@OlegGrizzly Как проявляется ошибка?

**Comment by OlegGrizzly** [comment]
Не ошибка, не знание.
Есть таблица Objects в ней поле Category -> enum('Коммерческая', 'Некоммерческая')
Как в админ панели SleepingOwl мне их редактировать.

Таким способом 
`AdminFormElement::select('category', 'Категория')->setEnum(['Коммерческая', 'Некоммерческая'])->required()`

Он просто создает список Enum но не берет с базы какой элемент сейчас выбран.

**Comment by OlegGrizzly** [comment]
А все работает извините...

**Comment by aios** [comment]
Лол
