### ISSUE TITLE
Ошибки 

### ISSUE THREAD

**Issue by OlegGrizzly** [LaravelRUS/SleepingOwlAdmin#494]
1) Не работает:
`AdminColumnEditable::checkbox('slider', 'Слайдер'),`

Не сохраняет результат, показывает как будто изменения приняты но после перезагрузки страницы все по прежнему.

2) Не работает удаление внутри Объектов: Жмешь удалить подтверждаешь и никакой реакции

3) В шапке админки нету Logout

4) При добавлении или редактирование объекта если в нем есть дата:
`AdminFormElement::date('created_at', 'Опубликовано')->setFormat('d.m.Y')`
Выводит ошибку:

> Unexpected data found.
> Unexpected data found.
> Data missing

**Comment by aios** [comment]
php artisan vendor:publish --tag=assets --force

И проверь все пункты.

**Comment by OlegGrizzly** [comment]
@aios, тоже самое проверил в нескольких браузерах

**Comment by aios** [comment]
Логаут ты должен сам реализовать.

**Comment by OlegGrizzly** [comment]
@aios ладно а на счет остального ?

**Comment by aios** [comment]
@OlegGrizzly  Надо проверять. У меня допустим на проекте в QA человек 200 наверно сидит и каждый день пользуется - нашли бы что то - плешь проели бы.

**Comment by OlegGrizzly** [comment]
@aios кстати AdminColumnEditable::checkbox у меня с самого начала не пошел пришлось ставить костыль в 

> resources/views/default/column/editable/checkbox.blade.php 

и менять строку
`
data-url="{{ strstr(request()->url(), 'async', true) }}"`

**Comment by aios** [comment]
А до этого какая строка была?

**Comment by aios** [comment]
Очень странно.

**Comment by OlegGrizzly** [comment]
@aios 

```
<span class="exception_message">Call to a member function setAttribute() on null</span>
</h2>
<div class="block">
<ol class="traces list_exception">
<li> in <a title="W:\domains\localhost\dsk\vendor\laravelrus\sleepingowl\src\Form\Element\NamedFormElement.php line 418">NamedFormElement.php line 418</a></li>
</ol>
</div>

</div>
</body>
</html>
```

**Comment by aios** [comment]
@OlegGrizzly Последняя версия dev
все летает и без хелпера.
ищи где проблема.

**Comment by OlegGrizzly** [comment]
"laravelrus/sleepingowl": "dev-feature/5.4" ?

**Comment by aios** [comment]
"laravelrus/sleepingowl": "4.*@dev",

**Comment by OlegGrizzly** [comment]
На последней Laravel норм идет ?

**Comment by aios** [comment]
Обновляйся - понятно где у тебя прихрамывало.
ветка 5.4 давно смерджена в dev
у меня версия 5.4

**Comment by OlegGrizzly** [comment]
@aios спасибо большое шас updateнусь )
