### ISSUE TITLE
Ошибка: InvalidArgumentException in Carbon.php line 582: Data missing

### ISSUE THREAD

**Issue by OlegGrizzly** [LaravelRUS/SleepingOwlAdmin#495]
`AdminFormElement::datetime('created_at', 'Дата')->setFormat('d.m.Y H:i')->setCurrentDate()`

При сохранении выдает ошибку:

> InvalidArgumentException in Carbon.php line 582: Data missing

Думал дело в моделе добавил в нее:

```
    protected $dates = [
        'created_at',
        'updated_at',
    ];
```

Но бесполезно.

И кстати вставляю вроде **datetime** но показывается только дата без времени.

**Comment by aios** [comment]
@OlegGrizzly Имеется поправлю на днях.

**Comment by OlegGrizzly** [comment]
На будущее удалите ->setFormat('d.m.Y H:i')

**Comment by aios** [comment]
@OlegGrizzly К сожалению не можем, поле datetime может использоваться для разных целей.

**Comment by lunatig** [comment]
@OlegGrizzly зачем его удалять. нет такого setFormat('d.m.Y H:i')
есть  Y-m-d H:i:s это TIMESTAMP формат Хранения в базе. 
Если у кого-то он будет другой. то он может его установить на свой. 

Для отображения используется метод setPickerFormat
