### ISSUE TITLE
Js can not be used, select can not be used

### ISSUE THREAD

**Issue by samubra** [LaravelRUS/SleepingOwlAdmin#497]
![1](https://cloud.githubusercontent.com/assets/385368/23890290/270b847c-08cc-11e7-8565-b48371ab568c.png)
![2017-03-14 15-23-48 2](https://cloud.githubusercontent.com/assets/385368/23890291/29159294-08cc-11e7-8534-be38f0eb9ed9.png)

**Comment by butschster** [comment]
`php artisan vendor:publish --tag=assets --force`

**Comment by samubra** [comment]
Thank you, but did not solve

**Comment by samubra** [comment]
run `composer update`
see this 

> ErrorException in BoundMethod.php line 29:
call_user_func_array() expects parameter 1 to be a valid callback, array must have exactly two members

**Comment by lunatig** [comment]
та же ерунда (((
