### ISSUE TITLE
FatalErrorException in SimpleTreeType.php

### ISSUE THREAD

**Issue by UnQuaiz** [LaravelRUS/SleepingOwlAdmin#498]
Ошибка при использовании отображения tree() в laravel 5.4

FatalErrorException in SimpleTreeType.php line 38 :
Call to protected method SleepingOwl\Admin\Repositories\TreeRepository::getChildren() from context 'SleepingOwl\Admin\Display\Tree\SimpleTreeType'

**Comment by butschster** [comment]
Да, надо этот метод `SleepingOwl\Admin\Repositories\TreeRepository::getChildren` перенести из репозитория в `SleepingOwl\Admin\Display\Tree\SimpleTreeType`

**Comment by aios** [comment]
@butschster я сделаю.
