### ISSUE TITLE
FatalThrowableError in SimpleTreeType.php line 38:

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [LaravelRUS/SleepingOwlAdmin#503]
Привет
Исправьте ошибку (в master)

Call to protected method SleepingOwl\Admin\Repositories\TreeRepository::getChildren() from context 'SleepingOwl\Admin\Display\Tree\SimpleTreeType' -- без разницы какой класс, все равно ругается на TreeRepository::getChildren

> protected function getChildren($collection, $id)
на
> public function getChildren($collection, $id)

**Comment by Butochnikov** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/issues/498

**Comment by aios** [comment]
Он про master

**Comment by Butochnikov** [comment]
@aios пропустил, что master.
Да, хотфиксы для релиза надо выпускать.

@butschster ?

**Comment by aios** [comment]
CI надо настроить а у меня как назло завал по работе.
