### ISSUE TITLE
Некорректное поведение AdminFormElement::setDefaultValue для checkbox

### ISSUE THREAD

**Issue by vshining** [LaravelRUS/SleepingOwlAdmin#504]
Версия Laravel: 5.2.45
Версия SleepingOwl: 4.x-dev 359daac
Версия PHP: 5.6.29

`AdminFormElement::checkbox('сheckbox', 'Test checkbox')->setDefaultValue(true)` устанавливает значение чекбокса и при редактировании существующей записи.

**Comment by aios** [comment]
мол чекбокс не работает как нужно верно?
@vshining

**Comment by vshining** [comment]
Если модель сохранена, то значение по умолчанию не должно устанавливаться в форме, по идее. Я полагаю, false в модели он воспринимает как пустое значение.

**Comment by Butochnikov** [comment]
@vshining вот код отвечающий за это: https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/resources/views/default/form/element/checkbox.blade.php#L4

теперь смотри, что у тебя возвращается из базы

**Comment by aios** [comment]
@vshining Мы такие классные. мы такие умные. Крохи замечаем, а бревно - нет.
setDefaultValue('true')
Смотрим внимательно что запихивается в этом случае в value - а что читает функция. и вспоминаем что 'true' === 'false' === true

**Comment by Ter01an** [comment]
Использовал прошлые версии совы, там поведение default значения на checkbox работало исправно. Для таких полей у меня стояло tinyint(1) - получается значения полей 0 и 1
Старый код получения значения у поля был
```
if ($count === 1) {
    return $model->getAttribute($this->getAttribute());
}
```
Теперь стоит проверка ну пустое и значение null
```
if ($count === 1) {
    $attribute = $model->getAttribute($this->getModelAttributeKey());
    if (! empty($attribute) or is_null($value)) {
        return $attribute;
    }
}
```
Поле возвращая значение 0 или false, попадает под условие пусто, тем самым возвращает значение по default. Возможно стоит проверять длину строки strlen вместо пустого значения, либо что то подобное

**Comment by aios** [comment]
@Ter01an 

чет код найти не могу. можешь указать где значение?

**Comment by Ter01an** [comment]
\src\Form\Element\NamedFormElement.php ~ 376 строка

**Comment by aios** [comment]
ок мне жаловались на это - починим
