### ISSUE TITLE
!!!Help wanted with English!!!

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#51]
I have problem with English language and i need help with correcting `readme.md`.

**Comment by Rubemlrm** [comment]
just say what you need =)

**Comment by dannoso** [comment]
Yes please. This project if awesome but the Russian language is very limiting.
Put everything in english and an updated demo version and this project will thriving.
I don't know Russian but i think It's plenty of people here willing to help.
