### ISSUE TITLE
disableDisplay в секции

### ISSUE THREAD

**Issue by Vuishnak** [LaravelRUS/SleepingOwlAdmin#510]
Если регистрировать секцию через `AdminSection`, понятно, как отключить вывод. А если я регистрирую секцию через провайдер? Пробовал писать в `initialize - $this->disableDisplay()` - не работает.

**Comment by aios** [comment]
@Vuishnak А пробовал в onDisplay ничего не писать?

**Comment by Vuishnak** [comment]
@aios пробовал ее удалять и проверять методом `isDisplayable()` - но возвращает true. Сейчас как. Я удалил метод onDisplay, но когда захожу по адресу, чтобы посмотреть инфу открывается страница секции, просто без таблицы с инфой...

**Comment by Vuishnak** [comment]
Мне нужно, чтобы 404 возвращало при обращении на эту страницу.

**Comment by aios** [comment]
```php
public function onDisplay(){
abort(404);
}
```

**Comment by Vuishnak** [comment]
@aios спасибо) И все таки, хотелось бы иметь возможность управлять показами так, как в документации (если регидрация секции идет через провайдер).

**Comment by aios** [comment]
Ок сделаем.

**Comment by aios** [comment]
```php
    public function isDisplayable()
    {
        return false; // TODO: Change the autogenerated stub
    }
```

Так работает. 
@Vuishnak
