### ISSUE TITLE
После обработки

### ISSUE THREAD

**Issue by aios** [LaravelRUS/SleepingOwlAdmin#513]
Отправлять в активный таб после обработки форм из табов.

**Comment by Butochnikov** [comment]
@aios перестало работать, таб не устанавливается

**Comment by aios** [comment]
@Butochnikov ок посмотрю. Как давно не известно?

**Comment by aios** [comment]
@Butochnikov https://demo.sleepingowladmin.ru/admin/contact5s работает.

**Comment by Butochnikov** [comment]
@aios это ты как проверил? ты верхние табы по переключай и сохрани )
они сбрасываются.

**Comment by aios** [comment]
Вообщем тестировал я этот момент вдоль и поперек - @Butochnikov извини конечно - но он продолжает работать в штатном режиме. Если кто то может подтвердить что не работает - я отреопеню и займусь ресерчем по этому вопросу.
