### ISSUE TITLE
Проблема с SimpleTreeType.php

### ISSUE THREAD

**Issue by GotFly** [LaravelRUS/SleepingOwlAdmin#515]
\SleepingOwl\Admin\Display\Tree\SimpleTreeType.php:72 - почему тут вызывается $this->reorder() с двумя параметрами, тогда как по логике должен вызываться $this->recursiveReorder().
А так же было бы полезно во всех типах деревьев либо сделать свойство $repository protected, либо добавить геттер и сеттер для него (для доступа к нему из наследуемых типов).

**Comment by aios** [comment]
@GotFly Давай что логично или не логично решать будем мы. У вас пользователей пакета, очень часто наблюдается узкое мышление в рамках своей задачи. 

Опиши проблему, с которой ты столкнулся и попробуем придти к ее решению.

**Comment by GotFly** [comment]
@aios Проблемы тут 2:
1. Вызов reorder() вместо recursiveReorder() - ну, тут все ясно и понятно, ибо даже исходя из количества параметров вызываемого метода reorder() тут ну никак не вписывается (гляньте код).
2. По поводу типов свойств, меня устраивает SimpleTreeType, за одним исключением - мне нужно было подправить условия выборки в getTree(). Я наследовался от \SleepingOwl\Admin\Display\Tree\SimpleTreeType.php , но т.к. свойство $repository приватное я в своем классе не смог переопределить только нужный мне метод. Если бы свойство было protected, тогда никаких проблем с этим не возникло бы.

Надеюсь, я понятно изложил суть проблемы.

**Comment by aios** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/issues/505

**Comment by GotFly** [comment]
Благодарю. Это то, что нужно =)

**Comment by aios** [comment]
Стараемся...

27 марта 2017 г. 12:19 пользователь "Gotovets Alexander" <
notifications@github.com> написал:
