### ISSUE TITLE
AdminFormElement::dependentselect(...)->setModelForOptions(Model::class, $titleKey) possible bug with $titleKey

### ISSUE THREAD

**Issue by 1oginov** [LaravelRUS/SleepingOwlAdmin#517]
Доброго времени суток, огромное спасибо за потрясающий продукт!

Похоже на баг, но поправьте, если я делаю что-то не так, а реализация верная.

В `dependentselect` не отображается `$titleKey`, если использовать метод `setModelForOptions()`, как описано в доке: https://sleepingowladmin.ru/docs/form-element#dependentselect-setModelForOptions

Если не указывать `$titleKey` в `setModelForOptions()`, а задать его через `setDisplay()` (не документированный метод для `dependselect`, поэтому ссылка на `select` https://sleepingowladmin.ru/docs/form-element#select-setDisplay), то всё работает!

В вашем демо проекте также используется `setDisplay`: https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Http/Sections/Form.php#L94

```
AdminFormElement::dependentselect('city_id', 'City', ['select'])->setModelForOptions(\App\Model\Country::class)
    ->setDisplay("title")
    ->required(),
```

**Comment by aios** [comment]
Все верно - ошибка в документации...
