### ISSUE TITLE
Demo page login is broken

### ISSUE THREAD

**Issue by MurKit** [LaravelRUS/SleepingOwlAdmin#519]
I cannot log in with the given credentials. The tooltip says Please enter an email, however the admin@site.com is there.
![screenshot at 2017-03-28 13 25 54](https://cloud.githubusercontent.com/assets/13369896/24400781/59d814da-13ba-11e7-86af-1bdc3390c014.png)

**Comment by Lunatig** [comment]
delete space after the email

**Comment by MurKit** [comment]
Thanks
