### ISSUE TITLE
Select make pluck when setted modelForOptions

### ISSUE THREAD

**Issue by aios** [LaravelRUS/SleepingOwlAdmin#525]
Иногда нужно указать некий набор полей что бы было не id => value, а было что то другое. 

Дорабатываем.

**Comment by Lunatig** [comment]
@aios
AdminFormElement::select('measure', 'Мера')->setEnum(Measure::pluck('measure')->all())->setDisplay('measure'),
Так ?

**Comment by aios** [comment]
Да что то типо того - но мне хочется типо setKey -> setDisplay
