### ISSUE TITLE
Any blade template file inside app/Admin/ is visible at the top of the page

### ISSUE THREAD

**Issue by MurKit** [LaravelRUS/SleepingOwlAdmin#528]
PHP 7.0.17
laravelrus/sleepingowl 4.x-dev f81d9d7

If there is a file navbar.blade.php in app/Admin/resources/views/auth,
all the pages of web app just render this view at the top of the page.
As in any sub folders of app/Admin/.

[screenshot](http://pasteboard.co/Qtok0vUGY.png)

Is this behavior intentional? 
It is not seen in demo app.

My temporary solution is to keep views out of  app/Admin/.

**Comment by aios** [comment]
можно и на русском @MurKit

**Comment by aios** [comment]
Возьми пример из демо приложения. Там все четко расписано.

**Comment by h-zone** [comment]
у меня та же проблема.
всё перерыл - не могу понять откуда оно лезет.
