### ISSUE TITLE
select filter with array isn't working

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#529]
Select with model is working fine. Select with array doesn't return anything (or filters records with 0 value). 

There are url params. Note that 'English' is passed instead of 'en'.

draw=4
columns%5B0%5D%5Bdata%5D=0
columns%5B0%5D%5Bname%5D=
columns%5B0%5D%5Bsearchable%5D=true
columns%5B0%5D%5Borderable%5D=true
columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=
columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false
columns%5B1%5D%5Bdata%5D=1
columns%5B1%5D%5Bname%5D=
columns%5B1%5D%5Bsearchable%5D=true
columns%5B1%5D%5Borderable%5D=true
columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=English
columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false
columns%5B2%5D%5Bdata%5D=2
columns%5B2%5D%5Bname%5D=
columns%5B2%5D%5Bsearchable%5D=true
columns%5B2%5D%5Borderable%5D=true
columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=
columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false
order%5B0%5D%5Bcolumn%5D=0
order%5B0%5D%5Bdir%5D=asc
start=0
length=25
search%5Bvalue%5D=
search%5Bregex%5D=false
_=1491094614860

```
AdminSection::registerModel(\App\Models\Source::class, function (ModelConfiguration $model) {
    $model->setTitle('Sources');
    // Display
    $model->onDisplay(function () {
        $display =  AdminDisplay::datatablesAsync()
            ->with('source_type', 'categories', 'tags', 'user')
            ->setHtmlAttribute('class', 'table-primary')
            ->setColumns([
                AdminColumn::text('title')->setLabel('Title'),
                AdminColumn::text('lang')->setLabel('Lang'),
                AdminColumn::text('is_active')->setLabel('Active'),
                AdminColumn::text('source_type.name')->setLabel('Source type'),
                AdminColumn::text('summary')->setLabel('Summary'),
                AdminColumn::lists('categories.name')->setLabel('Categories'),
                AdminColumn::lists('tags.name')->setLabel('Tags'),
                AdminColumn::text('user.full_name')->setLabel('Added by'),
            ])->paginate(25);

        $display->setColumnFilters([
            AdminColumnFilter::text()->setPlaceholder('Title')->setOperator('contains'),
            AdminColumnFilter::select(['en' => 'English', 'he' => 'Hebrew'])->setPlaceholder('Lang')->setColumnName( 'lang' ),
            AdminColumnFilter::select(['1' => 'Yes', '0' => 'No'])->setPlaceholder('Active'),
            AdminColumnFilter::select(\App\Models\SourceType::class, 'name')->setPlaceholder('Type')
        ]);

        return $display;
    });
```

**Comment by aios** [comment]
columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=English

That is problem? 
@eugenem just make research for that. but value is sended. look at there please.

**Comment by eugenem** [comment]
yes, if I change it manually to 'en', it works...

**Comment by aios** [comment]
@eugenem so problem causes when you dont touching selects (no change)?

**Comment by eugenem** [comment]
No, I select 'English', and get no results. I think it's not considering 'en' => 'English' mapping...

**Comment by eugenem** [comment]
if I change value to 'en' at url, it's ok

**Comment by aios** [comment]
@eugenem ok. i will fix it soon

**Comment by eugenem** [comment]
thanks!

**Comment by aios** [comment]
@eugenem what branch you use? how you installed your sleepingowl admin?

**Comment by eugenem** [comment]
"laravelrus/sleepingowl": "4.*@dev"

this is what I've got at composer

**Comment by aios** [comment]
@eugenem i sended message to you facebook.
