### ISSUE TITLE
При загрузке изображений/файлов не блокируется submit формы.

### ISSUE THREAD

**Issue by sanct** [LaravelRUS/SleepingOwlAdmin#532]
При загрузке изображений/файлов нужно блокировать submit формы и показывать процесс загрузки. Если файлы заливаются с тормозами по каким-то причинам, то возникает ситуация, когда в интерфейсе файл вроде бы загружен, но реально его еще нет и при этом доступен сабмит формы.

**Comment by aios** [comment]
@sanct ветка какая?

**Comment by aios** [comment]
Прогресс добавить в компонент достаточно проблематично - однако сам прелоадер уже есть и работает. Был добавлен в этом коммите
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/144c3a2418a81766557e9da52a976f7dbab4707f

переключиться на 4.*@dev 
composer update && php artisan vendor:publish --tag=assets --force

@sanct
