### ISSUE TITLE
Exception Method Illuminate\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by RespectPick** [LaravelRUS/SleepingOwlAdmin#534]
Генерирую модель через сервис-провайдер

`    public function onDisplay()
    {
        return AdminDisplay::table()
            ->setHtmlAttribute('class', 'table-primary')
            ->setColumns(
                AdminColumn::lists('type.name', 'Тип чемпионата')
            )->paginate(20);
    }`

Так же имею две модели с отношением многие к одному.

Модель ChampionshipType

`    public function championship(){
        return $this->hasMany('App\Models\Championship', 'type_enum_id');
    }`

а в модели Championship

`    public function type(){
        return $this->belongsTo('App\Models\Enum\EnumChampionshipType', 'id');
    }`

При загрузке страницы ловлю исключение

FatalErrorException in 74d7252e8b7d20fd1a1f60d84c0c0621d05358d4.php line 0:
Method Illuminate\View\View::__toString() must not throw an exception

**Comment by aios** [comment]
В setColumns желательно передавать или колбек (Closure) либо массив коламнов.
@RespectPick

**Comment by RespectPick** [comment]
но я делаю как в доке

http://joxi.ru/KAgZ1Qbf46oYb2

**Comment by aios** [comment]
@RespectPick Делай как я говорю - заодно проверим баг это или нет.

**Comment by RespectPick** [comment]
а можно пример?

**Comment by RespectPick** [comment]
в доках нет такого

**Comment by aios** [comment]
```php
return AdminDisplay::table() ->setHtmlAttribute('class', 'table-primary') ->setColumns( [AdminColumn::lists('type.name', 'Тип чемпионата')] )->paginate(20);
```

**Comment by RespectPick** [comment]
то же самое

http://joxi.ru/gmv8QkLsLM5JpA

**Comment by aios** [comment]
@RespectPick У тебя type отношение belongsTo а AdminColumn::lists используется только с Many отношениями - HasMany BelongsToManyThrough BelongsToMany И тд...

**Comment by RespectPick** [comment]
у меня Types стоит hasMany

**Comment by aios** [comment]
public function type(){ return $this->belongsTo('App\Models\Enum\EnumChampionshipType', 'id'); }

где?

**Comment by RespectPick** [comment]
сама модель, в которой я пытаюсь вызвать селектбокс, имеет belongsTo, но связная с ней модель, элементы которой мне нужны в селектбоксе имеют hasMany

**Comment by RespectPick** [comment]
Модель ChampionshipType

public function championship(){ return $this->hasMany('App\Models\Championship', 'type_enum_id'); }

**Comment by RespectPick** [comment]
хорошо, как тогда вызвать селектбокс со связной моделью? К которой отношение belongsTo. В предыдущих версиях не было такой проблемы

**Comment by aios** [comment]
@RespectPick Lists Никогда не работал с отношениями belongsTo

**Comment by RespectPick** [comment]
код из другого проекта

FormItem::select('photo_type_id', 'Тип фото')->model(Type::class)->display('type_name'),

**Comment by aios** [comment]
Мы разговариваем про AdminColumn? или AdminFormElemnt - Определись уже.
@RespectPick
