### ISSUE TITLE
AdminFormElement::file() - remove callback

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#546]
Появилась необходимость в каллбеке при удалении картинки. Т.е. когда человек жмакает на удалить, чтобы вызывался какой-то метод в модели (секции).

**Comment by aios** [comment]
Мы ведь обнуляем значение поля. зачем колбек? можно поймать значения в обсервере там обработать.

**Comment by mavsan** [comment]
Я уже больше недели пытаюсь донести заказчику, что надо нажимать кнопку "Сохранить". Но кто-то там у них в фирме с длинными ресницами и когтями ни как не может въехать в это дело. Попадает почему-то мне, т.к. "я нажала удалить, а оно осталось" :(

**Comment by aios** [comment]
@mavsan Сожалею сложившейся ситуации - однако со всем уважением) это не совсем наша проблема. Загрузка изображений предполагает раннюю обработку действий - удаление  - нет.
