### ISSUE TITLE
datatablesAsync pagination is not working

### ISSUE THREAD

**Issue by pdazcom** [LaravelRUS/SleepingOwlAdmin#547]
Hi! I can't make pagination on datatablesAsync display. I do it this way:
```
$display = \AdminDisplay::datatablesAsync("project_logs")->setOrder([[0, 'desc']])->paginate(100);
$display->setHtmlAttribute('class', 'table-primary')
->setColumns(
     \AdminColumn::text('id', '#')->setWidth('30px')->setOrderable(true),
     \AdminColumn::datetime('created_at', trans('admin.columns.created_at'))->setOrderable(true),
     \AdminColumn::text('message', trans('account.projects.message'))
);
```
But this does not give an effect, I get all 300+ database records

**Comment by Daaner** [comment]
Tested on 1000+ records. All is well. Look for an error in yourself
![image](https://cloud.githubusercontent.com/assets/9641698/25127104/58702fea-243d-11e7-9583-0c5c2f5bb634.png)
