### ISSUE TITLE
Ошибка при использовании элемента radio

### ISSUE THREAD

**Issue by dessl** [LaravelRUS/SleepingOwlAdmin#548]
Ошибка следующего содержания - ErrorException: Array to string conversion. Возникает из того что в шаблоне радио элемента идет попытка прочитать массив как строку, конкретно переменная $attributes.

`<input {!! $attributes !!} value="{{ $optionValue }}" {!! ($value == $optionValue) ? 'checked' : '' !!}/>`

Branch: master
Commit: ee0bb88

**Comment by aios** [comment]
@dessl Ошибка возникает при каких обстоятельствах?

**Comment by dessl** [comment]
Создал класс, унаследовал от класса Section. в методе onCreate|onEdit вставил такой код

`AdminFormElement::radio('userInfo.gender', trans('labels.user.info.gender'))->setOptions(array('0' => trans('labels.user.info.gender_woman'), '1' => trans('labels.user.info.gender_man')))
								->required(),`

Но ошибка эта на уровне компонента, он просто не может в представлении преобразовать массив {!! $attributes !!} в строку.

**Comment by aios** [comment]
в течении часа решу.

**Comment by aios** [comment]
У меня кстати двоякое такое видени - откуда у radio метод setOptions? @dessl

**Comment by dessl** [comment]
Судя по киммиту у radio не будет ни атрибута name ни id, как в базу значение попадет? и принцип группировки полей тоже непонятен.

**Comment by aios** [comment]
@dessl сорян сорян. сча исправлю. натупил дико.

**Comment by CrazyRedScorp** [comment]
@aios кстати, в стааааарой ветке было так:

`/vendor/laravelrus/sleepingowl/resources/views/default/form/element/radio.blade.php`

```
@foreach ($options as $optionValue => $optionLabel)
    <div class="radio">
        <label>
            <input type="radio" name="{{ $name }}" value="{{ $optionValue }}" {!! ($value == $optionValue) ? 'checked' : '' !!}/>
            {{ $optionLabel }}
        </label>
    </div>
@endforeach
```

вдруг поможет... хез почему отказались от такой записи в пользу `{!! $attributes !!}`

**Comment by aios** [comment]
@dessl Все элементы автономные компоненты - по крайней мере мы к этому стремимся - нужно что бы каждому элементу можно было устанавливать свои html аттрибуты. а при таком раскладе radio у нас как бы выпадает что ли. потому его и исправили.

**Comment by CrazyRedScorp** [comment]
@aios Спасибо! Ща обновимся.

**Comment by dessl** [comment]
Спасибо. Хорошее стремление, иногда очень не хватает возможности добавить пару кастомных атрибутов.

**Comment by CrazyRedScorp** [comment]
@aios Атрибуты связанные с именем и полем откуда тянуть данные разве надо теперь задавать самому?! Смотри, имеем код, который не менялся уже год:
```
})->addColumn(function () {
    return [
        AdminFormElement::radio('userInfo.gender', trans('labels.user.info.gender'))->setOptions(array('0' => trans('labels.user.info.gender_woman'), '1' => trans('labels.user.info.gender_man')))
            ->required(),
    ];
})
```

Вот скрин результата:

![image](https://cloud.githubusercontent.com/assets/12952022/25122927/26ed6e26-2440-11e7-9032-af7be5aba53b.png)

А раньше были точечки.

**Comment by aios** [comment]
@CrazyRedScorp покажи Html который генерится.

**Comment by CrazyRedScorp** [comment]
@aios Вот

![image](https://cloud.githubusercontent.com/assets/12952022/25123342/799ee9e6-2441-11e7-8707-11cb9cc92e9c.png)

**Comment by CrazyRedScorp** [comment]
@aios А вот так выводится на стааааарых вендорах

![image](https://cloud.githubusercontent.com/assets/12952022/25125684/2878fe3c-2449-11e7-9cfb-938ddef63353.png)

**Comment by aios** [comment]
@dessl @CrazyRedScorp чекайте  - у меня вроде как все работает.

**Comment by CrazyRedScorp** [comment]
@aios Да, теперь вроде порядок, точки стоят где надо, меняются, сохраняются. Спасибо!
