### ISSUE TITLE
Ability to use auth() in navigation.php

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#549]
`auth()->user()` currently returns null in the navigation.php file. Not sure why this is.

it would be good to be able to know about the authenticated user so that we can create dynamic menu's that are dependent on the logged in user. For example:

```
if(auth()->user()->hasRole('super-admin')) {
  	$navigation [] = [
		'title' => 'Admin settings',
		'icon' => 'fa fa-admin',
		'model' => \App\Models\AdminSettings\AdminSettings::class
	],
}
```

**Comment by aios** [comment]
You can setup method display in your own policy to model - or use AccesLogic key\property in this array.

**Comment by aios** [comment]
Navigation register in ServiceProvider - if you find best way to resolve AuthServiceProvider in AdminSectionsServiceProvider - i will implement that. But now - it make hard for me. 

sorry.
