### ISSUE TITLE
two admin panel with different user role

### ISSUE THREAD

**Issue by HomaEEE** [LaravelRUS/SleepingOwlAdmin#55]
Здравствуйте, возможно ли создать 2 админки (admin и user) - где админ имеет все права, а юсер - редактирует только всю информацию?

**Comment by HomaEEE** [comment]
нужны именно /admin и /user, разделение прав не подходит

**Comment by butschster** [comment]
Привет, а в чем разница будет?

**Comment by HomaEEE** [comment]
2 разные админки по функционалу

**Comment by butschster** [comment]
Хотелось бы более подробного описания. С примерами того, что должно быть в одной админке, а что в другой
