### ISSUE TITLE
Недочеты и вопросы по datatablesAsync()

### ISSUE THREAD

**Issue by Daaner** [LaravelRUS/SleepingOwlAdmin#550]
Не передаются атрибуты в колонки в onDisplay при datatablesAsync()
AdminColumn::text('email', 'Email')->setHtmlAttribute('class', 'foo'),

Как при той же datatablesAsync() в поле поиска выключить поиск по каким-либо колонкам?
В демке на Contact (v1) при поиске SQL ошибка. Понятно что оно не ищет по смежным таблицам, это и в документации указано, но как выключить, если все же смежные поля есть?

**Comment by Daaner** [comment]
с поиском разобрался. У datatablesAsync() сортировка по полям text, url и email. Поставил custom и прошло. Неплохо было бы добавить в сборку класс типа text-unsearch, ну или как-то так

**Comment by Daaner** [comment]
и как бы для url поля тоже придумать не индексируемое поле.

**Comment by aios** [comment]
@Daaner При каком кейсе у тебя не работает сортировка - ибо этому моменту я уделил достаточно времени что бы оно работало как надо со связями.

**Comment by Daaner** [comment]
https://demo.sleepingowladmin.ru/admin/contact6s   вбей в поиск пару символов

**Comment by aios** [comment]
это общий поиск по таблице. Там выбираются все коламны и в зависимости от их нейма суют лайк по базе.

дело в том что fullName это мутатор. И на него нужно устанавливать setSearchCallback потому что дефолтной логики как не крути не будет на мутаторе.

Я разберусь с этим в демке - но такая логика ложиться на плечи разработчиков. 
@Daaner

**Comment by Daaner** [comment]
а с классами как быть?

**Comment by aios** [comment]
@Daaner классы устанавливались на колонки еще до того как я вообще начал работу по админке. проверяй что у тебя не так.

**Comment by Daaner** [comment]
Везде классы работают нормально, но именно в асинхронке они не подтягиваются. Проверял не только я.

**Comment by Daaner** [comment]
в https://demo.sleepingowladmin.ru/admin/contacts 
`$photo = AdminColumn::image('photo', 'Photo<br/><small>(image)</small>')
                ->setHtmlAttribute('class', 'hidden-sm hidden-xs')
                ->setWidth('100px'),`
А на выводе класса нет
