### ISSUE TITLE
Генерация url до сохранения в БД

### ISSUE THREAD

**Issue by Pyslar-Dmitriy** [LaravelRUS/SleepingOwlAdmin#554]
Имеется секция, `onCreate()` содержит ряд инпутов. В БД помимо этих полей, нужно записывать url который генерируется таким образом `str_slug($title)`. Пробовал в `postStore()` в `AdminController`  добавить что-то вроде `$request->merge(['url' => str_slug($request->title)]);` Но  оно само собой не работает. В `onCreate()` доступа к title нет, так как он еще не введен, как поступают в таких случаях,  когда помимо полей формы нужно сохранить другую информацию?

**Comment by aios** [comment]
Переносим [данную](https://sleepingowladmin.ru/docs/model_configuration#события) логику в секции с помощью initialize и на этапе creating делаем че хотим.
