### ISSUE TITLE
в Orderable сбой при SoftDelete

### ISSUE THREAD

**Issue by Daaner** [LaravelRUS/SleepingOwlAdmin#556]
Если указан order и запись мягко удалить:
Удаляется нормально, все значения далее смещаются
Возвращаешь назад - берется старый order и дублируется со значением, которое уже присутствует

**Comment by aios** [comment]
@Daaner А по подробнее?

**Comment by Daaner** [comment]
![image](https://cloud.githubusercontent.com/assets/9641698/25781319/1e4c985e-3341-11e7-9680-4d4ffa7ecc5e.png) софт делит, ордер остается, все остальные пересчитываются
![image](https://cloud.githubusercontent.com/assets/9641698/25781324/3d640498-3341-11e7-91d4-767d52f1bc74.png) при восстановлении записи идет дубль по ордеру

**Comment by aios** [comment]
@Daaner напиши пожалуйста в telegram (@aioslike) по поводу этой проблемы.

**Comment by Daaner** [comment]
неа! не исправил
