### ISSUE TITLE
"Складывание" параметров фильтрации столбцов

### ISSUE THREAD

**Issue by sngrl** [LaravelRUS/SleepingOwlAdmin#557]
Вывожу простую таблицу: 
```
$display = AdminDisplay::table()
```

Добавляю фильтрацию к двум полям в строке: 
```
AdminColumn::text('city')->append(AdminColumn::filter('city_id'))
AdminColumn::text('subject')->append(AdminColumn::filter('subject_id'))
```

И к самой таблице:
```
$display->setFilters(
    AdminDisplayFilter::field('city_id'),
    AdminDisplayFilter::field('subject_id')
);
```

При выводе таблицы "параметры фильтрации" почему-то складываются, т.е. на первом поле первой строки ссылка для фильтрации будет такой:
```
?city_id=1
```
А для второго поля в первой строке такой:
```
?city_id=1&subject_id=2
```
Хотя должно быть так:
```
?subject_id=2
```

Почему так происходит?

Версии пакетов такие:
```
"php": ">=5.6.4",
"laravel/framework": "5.4.*",
"laravelrus/sleepingowl": "4.*@dev",
```

**Comment by sngrl** [comment]
Определил проблему самостоятельно: параметры фильтрации, определяемые через request()->merge(...), при выводе вьюшки почему-то "накапливаются".

Решение: исправить метод getUrl() для модели Filter:

**/src/Display/Column/Filter.php**

Текущая версия:
```
    public function getUrl()
    {
        request()->merge([
            $this->getName() => $this->getValue(),
        ]);

        return app('sleeping_owl')
            ->getModel($this->getRelatedModel())
            ->getDisplayUrl(request()->all());
    }
```

Исправленная версия:

```
    public function getUrl()
    {
        $request = clone request();

        $request->merge([
            $this->getName() => $this->getValue(),
        ]);

        return app('sleeping_owl')
            ->getModel($this->getRelatedModel())
            ->getDisplayUrl($request->all());
    }
```

После этого все стало работать, как и должно.
Возможно, выглядит слишком топорно. Но найти причину, по которой при вызове request()->merge(...) возникает проблема, я не смог.
@butschster пожалуйста, добавьте это исправление в следующий коммит.

**Comment by aios** [comment]
Накапливаемые фильтры... хм.. Спасибо. Исправим в ближайшее время.
@sngrl

**Comment by sngrl** [comment]
@aios на демо-проекте видимо такая же проблема: https://demo.sleepingowladmin.ru/admin/contact3s
Для столбца Companies ссылка на фильтр формируется неверно.
https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Http/Sections/Contacts3.php#L53
