### ISSUE TITLE
Не работает фильтрация для асинхронных таблиц

### ISSUE THREAD

**Issue by sngrl** [LaravelRUS/SleepingOwlAdmin#558]
При использовании AdminDisplay::datatablesAsync() не работает фильтрация.
Пример: https://demo.sleepingowladmin.ru/admin/contacts

**Comment by aios** [comment]
@sngrl читай пожалуйста CHANGELOG, а так же сопутствующую документацию по фильтрации.

**Comment by sngrl** [comment]
@aios я изучил страницу https://sleepingowladmin.ru/docs/filters и CHANGELOG, в том числе на предмет setFilterCallback(), но так и не нашел там информации, почему при использовании datatablesAsync() ссылка на фильтрацию по полю отсылается не через ajax, а открывается как обычная ссылка.

**Comment by aios** [comment]
@sngrl мы тут на ты - пообщаемся в личке по этому поводу.
