### ISSUE TITLE
AdminFormButton фасад и кнопки

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#559]
В файле конфигурации не указан фасад AdminFormButton, из примера в [демо](https://github.com/SleepingOwlAdmin/demo/blob/master/admin/Http/Sections/Forms/FormButtons.php), зато он указан в [published](https://github.com/SleepingOwlAdmin/demo/blob/master/config/sleeping_owl.php).

Вот как пытаюсь управлять кнопками:
```
$form = AdminForm::form()
                         ->addElement($formElement)
                         ->getButtons()
                         ->replaceButtons([
                             'delete' => null,
                             'save'   => AdminFormButton::save()->setText('Сохранить'),
                             'cancel' => AdminFormButton::cancel()->setText('Отменить')
                         ]);
```
Вылетает ошибка:
![image](https://cloud.githubusercontent.com/assets/5114650/25466091/9d024658-2b49-11e7-99fb-dd0d2419612f.png)

**Comment by aios** [comment]
если кнопка Delete не нужна - то ее нужно просто удалить из массива и в твоем случае указывать не replaceButtons, а setButtons
@mavsan
