### ISSUE TITLE
Посредник ValidatePostSize

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#567]
Посредник Larave - [ValidatePostSize](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php) выполняет проверку на размер входных данных post. Если размер превышает установки в php.ini - выбрасывается исключение, которое не отлавливается ядром админки. И это понятно - оно выбрасывается еще до того, как запрос попадает в контроллер.

Т.е. уведомить пользователя, что не надо пытаться закачать такой большой файл не получается ни как, что есть в корне не верно.

Административная панель отображает это вот так:
![image](https://cloud.githubusercontent.com/assets/5114650/25644488/dfe150be-2fe9-11e7-8556-d9e3af83f13c.png)

**Comment by aios** [comment]
@mavsan покажи пожалуйста что возвращает этот самый запрос с validatePostSize.

**Comment by mavsan** [comment]
Вот, что в Response:
`{"errors":[{"id":"bd4ffe7c-2103-4152-95ac-db64a713f1d8","status":500,"title":"Internal Server Error","detail":"An error has occurred and this resource cannot be displayed."}]}`

Вот, что в логах:
`[2017-05-07 10:47:10] local.ERROR: Illuminate\Http\Exceptions\PostTooLargeException in /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:24
Stack trace:
#0 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#2 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#3 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#7 /home/mavsan/WEB/domains/etalon-laravel.app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#8 /home/mavsan/WEB/domains/etalon-laravel.app/public_html/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#9 {main} {"identification":{"id":"bd4ffe7c-2103-4152-95ac-db64a713f1d8"}}`
