### ISSUE TITLE
FormElement Number

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#568]
Объясните пожалуйста смысл вот [этого](https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/Number.php#L119) и как мне сохранить значение поля типа number, скажем -0,12, при вот такой обработке поля? В [инструкции](https://sleepingowladmin.ru/docs/form-element#number) нет ни пол слова о том, что поле может сохранять или null, или исключительно int. 

Блин, больше часа построчного дебаггинга, проверки и перепроверки таблиц бд, в которые почему-то вручную нормальное значение заносится, а через форму - нет! И в итоге такой, гхм... баг? фича? нло? Причем эта "фича" была внесена еще 02,11,16 товарищем butschster (что самое веселое - setStep() приводится к float). Неужели за это время никто не пользовался этим полем?.. Или это только у меня дробные числа бывают?..

**Comment by aios** [comment]
@mavsan бессмысленная несвязная речь))

выключай бомбеж и попробуй нормально объяснить что не так.

**Comment by mavsan** [comment]
@aios да писал уже в половине девятого вечера, голова плохо соображала после практически непрерывного 12-ти часового дня, сильно хотелось есть и пива, наверное поэтому - несвязная и бессмысленная.

Суть проста. Есть элемент формы number, в него пишут число, дробное, конкретно: -0,12. В базу попадает 0. Пишут 10,15 - в базу попадает 10. И почему-то на момент написания функционала мне в голову не пришло проверить как сохраняются данные в таблице дробные числа (а зря, весь мой опыт показывает, что проверять надо все, особенно стороннее).

Сейчас решил это элементом формы text, передавая туда нужные атрибуты посредством метода `->setHtmlAttribute('type', 'number')->->setHtmlAttribute('step', '0.01')`.

Перед тем, как делать pull request решил поинтересоваться, возможно в принудительном преобразовании чисел к целому есть какой-то сакральный смысл.

**Comment by aios** [comment]
так ты предлагаешь сделать float? @mavsan

**Comment by mavsan** [comment]
Да, поле должно принимать любые значения, ведь так? Если кому-то надо целое, можно ведь `setStep(1)` сделать.
