### ISSUE TITLE
Запрос подправить немного трейт

### ISSUE THREAD

**Issue by uacode** [LaravelRUS/SleepingOwlAdmin#578]
Надо Сову обучить менять папку размещения файла
**/vendor/kodicomponents/support/src/Upload.php**
Убрать этот хардкод
`if (! is_dir(public_path($dir = "{$destination_path}/{$this->getTable()}/{$field}/{$subFolder}"))) {`

Предлагаю сделать так:
```

    protected function getUploadFolder($filename, $field) {

        $destination_path = 'storage';

        $subFolder = substr(md5($filename), 0, 2);

        $dir = "{$destination_path}/{$this->getTable()}/{$field}/{$subFolder}";

        return $dir;
    }

    /**
     * @param string $field
     * @param UploadedFile $file
     */
    protected function attachFile($field, UploadedFile $file) {
        $filename = $this->getUploadFilename($file);

        $dir = $this->getUploadFolder($filename, $field);

        if (!is_dir(public_path($dir))) {
            File::makeDirectory(public_path($dir), 493, true);
        }

        $path = "{$dir}/{$filename}";

        if (
                class_exists('Intervention\Image\Facades\Image')
                and ( $this->hasCast($field, 'image') or $this->isImageUploadedFile($file))
        ) {
            $settings = array_get($this->getUploadSettings(), $field, []);

            $image = \Intervention\Image\Facades\Image::make($file);

            foreach ($settings as $method => $args) {
                call_user_func_array([$image, $method], $args);
            }

            $image->save(public_path($path));
        } else {
            $file->move(public_path($dir), $filename);
        }

        $this->{$field} = $path;
    }
```

**Comment by uacode** [comment]
Только вот как бы это дело обыграть, если я захочу сохранять два изображения, но не банально в
storage/news/photo/1.jpg
storage/news/thumb/1.jpg

А вот так например
storage/news/photo_1.jpg
storage/news/thumb_1.jpg

**Comment by aios** [comment]
Ты перегнул) тем более что захардкодил первый хардкод) я подумаю над этим моментом позже.

**Comment by aios** [comment]
@uacode  В ишью и в обсуждениях и помоему даже в документации указано как менять папку сохранения файлов.

**Comment by uacode** [comment]
@aios В доках сказано как заменить папку (setUploadPath), но если я хочу разбросать файлы по другим дир. то ничего не выйдет. Ну и вариант с кастомным названием файла тоже б сделать.

Подумай плиз как бы это по правильному сделать. И заранее спасибо)

**Comment by aios** [comment]
@uacode есть setSaveCallback он вызывается при каждом сохранении файла - туда можно засунуть свою логику - так что в переработке KodiComponents не нуждается - мы стремимся дать возможность сделать гибче - саму гибкость мы делать за юзеров не будем)

**Comment by uacode** [comment]
@aios Спасибо) Через setSaveCallback вышло все сделать =)
