### ISSUE TITLE
Table action buttons not working

### ISSUE THREAD

**Issue by zettich** [LaravelRUS/SleepingOwlAdmin#58]
$display->setActions(AdminColumn::action ... ) button displays properly but do nothing. Some JS issue.
P.S: Export button on Demo (http://demo.sleepingowladmin.ru/admin/news/v5) also not working.

**Comment by butschster** [comment]
Hi, you need select one or more rows and then click to button

**Comment by butschster** [comment]
Hi, try to new release https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.23.101-beta
