### ISSUE TITLE
Как правильно объявить кастомный Controller в Section?

### ISSUE THREAD

**Issue by UksusoFF** [LaravelRUS/SleepingOwlAdmin#580]
Пытаюсь делать так:
```
namespace Admin\Sections;

use Admin\Http\Controllers\AdminUserController;

class UserSection extends Section implements Initializable
{
    protected $controllerClass = AdminUserController::class;

    public function initialize()
    {
        $this->setControllerClass(AdminUserController::class);
    }
}
```
AdminUserController:

```
namespace Admin\Http\Controllers;

use SleepingOwl\Admin\Contracts\ModelConfigurationInterface;
use SleepingOwl\Admin\Http\Controllers\AdminController;

class AdminUserController extends AdminController
{
    public function getEdit(ModelConfigurationInterface $model, $id)
    {
        //
    }
}
```
Ошибка такая же как и в #464.

Чяднт?  

Laravel 5.2, SleepingOwlAdmin 4.95.29

**Comment by aios** [comment]
Так указано же как регистрировать контроллер. @UksusoFF

**Comment by UksusoFF** [comment]
@aios 
Вы про то что нужно указывать класс контроллера с namespace?
AdminUserController::class как раз же и возвращает его целиком.
В документации по секциям есть только getControllerClass, но в коде есть и setControllerClass.

**Comment by aios** [comment]
Мы тут на "ты". 
Продебаж функцию setControllerClass до момента когда этот котнтроллер вызывается. Ошибка гласит что не тот инстанс передан. Значит нужно копать что ты не так передаешь.
@UksusoFF

**Comment by UksusoFF** [comment]
В setControllerClass приходит правильный путь к контроллеру. И в runCustomController тоже.

**Comment by aios** [comment]
@UksusoFF ок гляну что не так. но на 5.2 проблем ни у кого не было.

**Comment by aios** [comment]
@UksusoFF Еле добрался до этого таска. 

В целом контроллер ты объявил правильно:
```php
namespace Admin\Sections;

use Admin\Http\Controllers\AdminUserController;

class UserSection extends Section
{
    protected $controllerClass = AdminUserController::class;
}
```
Достаточно было сделать так. Но фикс все таки потребовался.
