### ISSUE TITLE
Два пункта меню, для одной модели

### ISSUE THREAD

**Issue by Fessnik** [LaravelRUS/SleepingOwlAdmin#583]
Всем привет, подскажите пожалуйста, как сделать для одной модели, два пункта меню ?

Раньше делал так : 
` [
        'title' => 'Пользователи',
        'icon' => 'fa fa-cogs',
        'pages' => [

            (new Page(User::class))
                ->setTitle('Клиенты')
                ->setUrl('/admin/users?type=client')
                ->setPriority(510)
                ->setIcon('fa fa-exclamation')
            ,

            (new Page(User::class))
                ->setTitle('Провайдеры')
                ->setUrl('/admin/users?type=provider')
                ->setPriority(100)
                ->setIcon('fa fa-clock')
        ]
    ]`

А в модели уже фильтровал в зависимости от типа. Сейчас же выводится один пункт и все, второй не выводиться(

**Comment by aios** [comment]
Тут нет техподдержки - спрашивайте в чате..
