### ISSUE TITLE
Open first tab with validation errors

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#584]
Суть проблемы написана тут
https://github.com/sleeping-owl/admin/issues/176

Сделал так
`
    // AdminSectionsServiceProvider
    public function boot(\SleepingOwl\Admin\Admin $admin)
    {
        parent::boot($admin);
        \Meta::addJs('admin-extend', asset('js/admin-extend.js'), 'admin-default', true);
    }
    // admin-extend.js
    // open first tab with validation errors
    var id = $('.tab-pane .has-error').first().parent('.tab-pane').attr('id')
    if(id) $('.nav-tabs a[href="#'+id+'"]').tab('show')

Работает, не знаю куда сделать пул реквест

**Comment by aios** [comment]
@dronowar Таких костылей у нас своих хватает - я делаю более глобальное решение.
