### ISSUE TITLE
setDisplaySearch выдает ошибку при поиске.

### ISSUE THREAD

**Issue by Fedchishina** [LaravelRUS/SleepingOwlAdmin#585]
Добрый день.
Хочу сделать простейший поиск.
Есть 2 таблицы
users (lastName, firstName, middleName, role_id) 
roles (id, name)
В таблице высвечиваю всё вот так:
![image](https://cloud.githubusercontent.com/assets/11705731/26252941/5d3a7a68-3cba-11e7-88ec-9f3ab2c79fe6.png)
когда начинаю вводить что-то в поле поиска, выдается ошибка:
![image](https://cloud.githubusercontent.com/assets/11705731/26252994/7dcf0ea6-3cba-11e7-8e61-e82c70c8eb5d.png)
код в модели вот такой:

   $model->setTitle('Пользователи');

    $model->onDisplay(function () {
        $display = AdminDisplay::datatablesAsync()->setDisplaySearch(true)->setApply(function($query) {
            $query->whereIn('role_id', [1, 4])->with('role'); 
        });

        $display->setColumns([
            AdminColumn::link('lastName')->setLabel('фамилия'),
            AdminColumn::link('firstName')->setLabel('имя'),
            AdminColumn::link('middleName')->setLabel('отчество'),

            AdminColumn::text('email')->setLabel('email'),
            AdminColumn::text('phone')->setLabel('телефон (для связи с менеджером)'),
            AdminColumn::text('role.name')->setLabel('роль'),
        ]);

        $display->setFilters([
            AdminDisplayFilter::related('role_id')->setModel(\App\Role::class),
            AdminDisplayFilter::field('role.name') // Search in relation country and field title
                ->setOperator(\SleepingOwl\Admin\Display\Filter\FilterBase::CONTAINS) // Like
        ]);
        return $display;
    });

Подскажите пожалуйста, что не так?

**Comment by IdenGit** [comment]
Столкнулся с похожей проблемой, но только при посике по зависимостям в версии 4.95.29

Код примерно такой:
```php 
 $display = \AdminDisplay::datatablesAsync()->with(['company','category','section']);
        $display->setColumns([
           \AdminColumn::text('name')->setLabel('Продукт'),
           \AdminColumn::text('company.name')->setLabel('Компания'),
           \AdminColumn::text('category.name')->setLabel('Секция'),
           \AdminColumn::text('section.name')->setLabel('Категория'),
        ]);
```
Как я понял, при запросе через DisplayDatatablesAsync вместо DisplayDatatables DisplayDatatablesAsync пробрасывает в QueryBuilder не название ральной таблицы в бд а само название связи

> Fedchishina попробуйте вместо  ```$display = AdminDisplay::datatablesAsync()``` такой вариант 
> ``` $display = AdminDisplay::datatables()``` Для меня он помог, надеюсь и вам поможет

**Comment by aios** [comment]
@Fedchishina  SetDisplaySearch открывает поле для поиска в datatables. Поиск не происходит потому что не описано поведение для поиска по relation - role.name это relation на роли - этого поведения админка не знает - для него нужно указывать колбек setSearchCallback в колонке которая отвечает за role.name.
