### ISSUE TITLE
dates filter misbehaves 

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#587]
That's the model. 

So without setFilterCallback, it simply doesn't filter.

So I thought maybe there is something with date formatting, and tried to add setFilterCallback. But in this case it's not clear whether $search is < or > (in case of single date).

What am I missing here?

        $display = AdminDisplay::datatablesAsync()
            ->setColumns([
                AdminColumn::text('id')->setLabel('#'),
                AdminColumn::text('order.id')->setLabel('Order #'),
                AdminColumn::datetime('pick_date')->setFormat('d.m.Y')->setLabel('Date')->setFilterCallback(function($column, $query, $search){
                    if($search)
                    {

                    }
                        print_r($search); die();
                }),

        $display->setColumnFilters([
            null,
            null,
            AdminColumnFilter::range()->setFrom(
                AdminColumnFilter::date()->setPlaceholder('From Date')->setFormat('d.m.Y')
            )->setTo(
                AdminColumnFilter::date()->setPlaceholder('To Date')->setFormat('d.m.Y')
            ),

**Comment by eugenem** [comment]
Guys, any ideas?

**Comment by aios** [comment]
Will looking 4 today.

**Comment by eugenem** [comment]
btw, I've tried a trick here: filter single column using 2 filters in different columns. And it doesn't even send the regular date filters to the server:

https://www.dropbox.com/s/q74l1h2mls06x6g/Screenshot%202017-06-21%2018.25.27.jpg?dl=0

      $display = AdminDisplay::datatablesAsync()
            ->with('address_from', 'address_to', 'order', 'ride_status', 'order.transport')
            ->setHtmlAttribute('class', 'table-primary')
            ->setFilters(
                AdminDisplayFilter::field('driver_id')->setTitle(function($value) {
                    return "Driver: " . \App\Models\Driver::find($value)->name;
                }),
                AdminDisplayFilter::scope('status')->setTitle(function($value) {
                    return "סטאטוס: " . \App\Models\RideStatus::find($value)->name;
                }),
                AdminDisplayFilter::scope('period')->setTitle('Period: :value')
            )
            ->setColumns([
                AdminColumn::datetime('pick_dt')->setFormat('d.m.Y H:i')->setLabel('Pickup')->setFilterCallback(function($column, $query, $search){
                    if($search)
                    {
                        print_r($search); die();
                        $query->where('pick_dt', '>=', \Carbon\Carbon::createFromFormat('d.m.Y', $search)->format('Y-m-d'));
                    }
                }),
                AdminColumn::datetime('arrive_dt')->setFormat('d.m.Y H:i')->setLabel('Arrival')->setFilterCallback(function($column, $query, $search){
                    if($search)
                    {
                        $query->where('pick_dt', '<=', \Carbon\Carbon::createFromFormat('d.m.Y', $search)->format('Y-m-d'));
                        #print_r($search); die();
                    }
                }),
                AdminColumn::text('order.id')->setLabel('Order #'),
                AdminColumn::text('address_from.name')->setLabel('Source'),
                AdminColumn::text('address_to.name')->setLabel('Destination'),
                AdminColumn::text('order.passengers')->setLabel('Passengers'),
                AdminColumn::text('order.passengers_baby')->setLabel('Babies'),
                AdminColumn::text('order.transport.name')->setLabel('Car type')->setFilterCallback(function($column, $query, $search){
                    if($search)
                        $query->whereExists(function($q) use ($search) {
                            $q->select(DB::raw(1))
                                ->from('orders')
                                ->whereRaw('orders.id = rides.order_id')
                                ->where('transport_id', $search);
                        }) ;
                }),
                #AdminColumn::text('driver.name')->setLabel('Driver'),
                #AdminColumn::text('distance_km')->setLabel('Distance'),
                AdminColumn::text('flight')->setLabel('Flight'),
                AdminColumn::text('ride_status.name')->setLabel('Status'),
            ])->paginate(25)
            ->setOrder([[0, 'asc']]);

        $display->setColumnFilters([
            AdminColumnFilter::date()->setPlaceholder('From Date')->setFormat('d.m.Y'),
            AdminColumnFilter::date()->setPlaceholder('To Date')->setFormat('d.m.Y'),
            /*AdminColumnFilter::range()->setFrom(
                AdminColumnFilter::date()->setPlaceholder('From Date')->setFormat('d.m.Y')
            )->setTo(
                AdminColumnFilter::date()->setPlaceholder('To Date')->setFormat('d.m.Y')
            ),
            null,*/
            null,
            null,
            null,
            null,
            null,
            AdminColumnFilter::select(\App\Models\Transport::class, 'name')->setPlaceholder('Transport'),
        ])->setPlacement('table.header');`

**Comment by eugenem** [comment]
I just took the newest version and it's the same. Why wouldn't simple date() work?

**Comment by aios** [comment]
Fixed 9a1091481a8af98473483db409ab8119ec5a75f9

**Comment by eugenem** [comment]
Not working at yesterday's version :(
What am I doing wrong?

**Comment by vaiil** [comment]
@eugenem It works for me:
```
AdminColumnFilter::range()->setFrom(
                AdminColumnFilter::date()->setPlaceholder('From Date')->setPickerFormat('d.m.Y')->setFormat('Y-m-d')
            )->setTo(
                AdminColumnFilter::date()->setPlaceholder('To Date')->setPickerFormat('d.m.Y')->setFormat('Y-m-d')
            ),
```
setPickerFormat sets format for datepicker, setFormat for database searching.

**Comment by eugenem** [comment]
working now, thanks!
