### ISSUE TITLE
Vue's inline-template's are not working in custom AdminFormElement's

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#588]
I'm trying to create a custom `AdminFormElement` using Vue. Unfortunately I don't seem to be able to use `inline-template` as all data in the vue component does not render.

For example something like this: https://jsfiddle.net/pds6vxn9/ in a custom sleeping owl `AdminFormElement` does not show the 'hello world' string.

I have a feeling this is due to Vue already being instantiated on the `body`.

**Comment by mavsan** [comment]
@aios к стати, да. Я тоже с этим сталкивался. Вместо того чтобы написать компонент за 20 минут, пришлось извращаться с jQuery, т.к. я прикинул, что разбираться почему и как всё устроено -  было-бы дольше, а нужен был результат. 

Я так понимаю, что это происходит потому что `new Vue({ el: '#app' }) ` (в доке сказано, что все компоненты должны быть зарегистрированы до того, как произойдет создание экземпляра Vue)
происходит раньше, чем регистрируется мой компонент, в то-же время нельзя регистрировать компонент, пока не загружен в скриптах не загружен Vue.

Возможно есть какой-то хитрый секрет :) расскажи.

**Comment by aios** [comment]
нет хитрого секрета - сейчас буду думать как эту хрень обойти.

**Comment by aios** [comment]
@7ammer i looking for update vue in #582 - after that - i refactor some elements of admin - and give your possibility to make your own components with vue

**Comment by 7ammer** [comment]
@aios, brilliant! Looking forward to the update.
Cheers

**Comment by aios** [comment]
@7ammer  Now its possible.
