### ISSUE TITLE
New entry for the related models

### ISSUE THREAD

**Issue by maslakoff** [LaravelRUS/SleepingOwlAdmin#59]
Hello guys,

I can't add entry for the related model.
For example: http://demo.sleepingowladmin.ru/admin/contacts/v3/2/edit

If we will add a new Company from a tab "Display from Related Model (Companies)" and go back - the new Company entry will not be added for the Contacts entry.

And I think that better return to the related Contacts form when we click "Save and close" in such case. What do you think about it?

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/fef00c5e86a18d60e00acd91ba9cc3ee60a4c078

**Comment by butschster** [comment]
Try to new release https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.23.101-beta

**Comment by maslakoff** [comment]
Redirect back works nice, but new related entry still couldn't be assigned to the parent model.
