### ISSUE TITLE
levenshtein too long

### ISSUE THREAD

**Issue by nyrik8989** [LaravelRUS/SleepingOwlAdmin#591]
ErrorException in /var/www/ttm/vendor/kodicomponents/navigation/src/Navigation.php line 317:
levenshtein(): Argument string(s) too long

**Comment by nyrik8989** [comment]
PHP 7.1 NGINX
Bubuntu 
Laravel 5.4
__
Vagrant
Win8.1

**Comment by aios** [comment]
@nyrik8989 Update to dev

**Comment by aios** [comment]
Closed by https://github.com/LaravelRUS/SleepingOwlAdmin/issues/558

**Comment by mavsan** [comment]
Чё-то не совсем понятно что тут произошло. Он пишет про ливенштейна, а ты про фильтрацию таблиц. Хотя может там тоже ливеншейн используется. Но мне кажется, что он имел ввиду [вот это](https://github.com/SleepingOwlAdmin/demo/issues/34).

**Comment by aios** [comment]
@mavsan Ну собственно я ее переопределил в админке ( навигацию ) где вот эта проблема имела место.
