### ISSUE TITLE
Как в AdminFormElement::select использовать значение как value?

### ISSUE THREAD

**Issue by UksusoFF** [LaravelRUS/SleepingOwlAdmin#594]
Возможно ли как-то отрендерить вот [такой](https://github.com/tamaspap/timezones#timezone_listphp) список?
Можно было бы использовать array_flip, но там есть совпадающие значения и после они естественно теряются.

**Comment by aios** [comment]
@UksusoFF подготовка массива не задача элемента - в него должен попадать массив который он может использовать для выбора и сохранения данных.

**Comment by UksusoFF** [comment]
@aios это да, но возможность поменять их местами вполне его задача.

**Comment by aios** [comment]
@UksusoFF Его задача получить данные - отобразить и дать возможность выбрать. Предподготавливать массив можно с помощью Accessors и Collection
