### ISSUE TITLE
Поля типа JSON из PostgeSQL (решение)

### ISSUE THREAD

**Issue by xloss** [LaravelRUS/SleepingOwlAdmin#595]
О том, что с такими полями админка не работает я понял сразу. Но я пишу не о проблеме, а о её решении. Коммитить и править я сам ничего не буду по причине, что я не имею опыта публичной разработки и не знаю всех тонкостей и правил. Поэтому опишу. Имею я **Laravel 5.4** и **SleepingOwl последней версии**. По специфики проект работает на PostgreSQL и имеет важно json поле в котором грубо говоря хранится объект. Стандартный запрос из Laravel делается достаточно просто `$model->field->value1->value2`. Но например добавить в таблицу и форму админки оказалось такие поля не возможно. Конечно можно выбрать тип поля `custom`. Но тогда например уже не работает сортировка и фильтрация. А когда данных больше 20к, то это крайне не удобно. Итого я создал отдельный тип данных и подключил его согласно документации, но за основу были взяты стандартные функции с очень мелкими модификациями.

Вывод в таблице:
```php
AdminColumn::add('jsontext', JsonText::class);

$display->setColumns([
    AdminColumn::jsontext('data->name->russian', 'Name'),
]);

class JsonText extends \SleepingOwl\Admin\Display\Column\Text
{
    protected function getValueFromObject($instance, $name)
    {
        if ($name instanceof Closure) {
            return $name($instance);
        }

        $parts = explode('->', $name);
        $part = array_shift($parts);

        if (! is_null($instance)) {
            $instance = $instance->getAttribute($part);
        }

        if (! empty($parts) && ! is_null($instance)) {
            foreach ($parts as $part) {
                if (!property_exists($instance, $part)) {
                    return '';
                }

                $instance = $instance->{$part};
            }
        }

        return $instance;
    }
}
```

Поля для формы:
```php
AdminFormElement::add('jsontext', ElementJsonText::class);
return AdminForm::form()->setElements([
    AdminFormElement::jsontext('data->name->russian', 'Name'),
]);

class ElementJsonText extends \SleepingOwl\Admin\Form\Element\Text
{
    public function getValueFromModel()
    {
        if (! is_null($value = $this->getValueFromRequest(request()))) {
            return $value;
        }

        $model = $this->getModel();
        $path = $this->getPath();
        $value = $this->getDefaultValue();

        if (is_null($model) or ! $model->exists) {
            return $value;
        }

        $relations = explode('->', $path);
        $count = count($relations);
        $part = null;

        if($count > 1) {
            $part = array_shift($relations);
        }

        if(!is_null($part)) {
            $attribute = $model->getAttribute($part);

            if (! empty($relations) && !is_null($attribute)) {
                foreach ($relations as $part) {
                    if (!property_exists($attribute, $part)) {
                        return '';
                    }

                    $attribute = $attribute->{$part};
                }
            }

            return $attribute;
        }

        return $value;
    }
}
```

Данное решение было сделано на скорую руку и использовался модифицировался оригинальный код наследуемых функций с выбрасыванием лишнего когда который мне на тот момент не был нужен.
Надеюсь найдется доброволец на переноса и объединения данного кода.
**Совместимость с Laravel ниже 5.4 не проверял!**

**Comment by aios** [comment]
@xloss да круто, да супер - да спасибо за решение. Но эт оне то что нужно админке. По логике твоего решения нужно под каждый элемент делать фунцкционал json поля - а мне допустим хотелось бы что бы каждый элемент принимал в имени эти поля. 

Вот пока что занимаюсь тестированием этой лабуды.

**Comment by xloss** [comment]
@aios именно поэтому я сюда и написал. Если бы решение было бы только для одного конкретного случая, то скорей всего я бы про него не писал.

**Comment by aios** [comment]
@xloss есть ли у тебя время пообщаться на эту тему - в телеграм (@aioslike)
