### ISSUE TITLE
Using 'select' element on a 'Post' model that belongsToMany 'Categories'?

### ISSUE THREAD

**Issue by 7ammer** [LaravelRUS/SleepingOwlAdmin#596]
I'm trying to use the `select` element on an admin section called `Post`.

The `Post` model has a 'many to many' relationship with a model called `category`.

When I try to use the `select` element to connect a `category` to a `post` like so..

    AdminFormElement::select('categories', 'Category', \Worthers\LaravelBlogGenerator\Category::class)
        ->setDisplay('label')`

..It returns an error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category' in 'field list' (SQL: update `posts` set `is_active` = 1, `updated_at` = 2017-05-28 22:46:36, `category` = where `id` = 1)`

Is there any way I can use the `select` element that looks up a pivot table?

I don't want to use `multiselect` element as this will let the user select multiple `categories`. I need a 'many to many' relationship for reasons related to my project.

Regards :)

**Comment by aios** [comment]
@7ammer I am sorry - but now not have a possibility to add that feature to select element.
