### ISSUE TITLE
"There was an error during your request" is not helpful

### ISSUE THREAD

**Issue by chrisnew** [LaravelRUS/SleepingOwlAdmin#597]
Do you want to request a feature or report a bug?
More a feature request than a bug.

What is the current behavior?
Some error occurs while opening a view with data tables. Unfortunately catching the exception and just returning something else doesn’t help debugging it in production. Nothing useful is found in our logging facilities. 

What is the expected behavior?
At least log the exception or better just pass it through. Every developer should decide on their own how to handle exceptions in any situation. Laravel provides global registers to handle uncaught exceptions appropriately.

What is the motivation / use case for changing the behavior?
Faster debug errors which occur in production on an immutable infrastructure where fiddling with vendor files is nearly impossible.

Which versions of SleepingOwl and Laravel are affected by this issue?
4.95.29 on PHP 5.6

Other information (e.g. code, stacktraces, related issues, suggestions how to fix)
`SleepingOwl\Admin\Http\Controllers\DisplayController` is in `renderFindedTable` suppressing useful information by not logging it and returning an unhelpful generic response. Fix: Do not catch at all or log it atleast.

**Comment by aios** [comment]
Ty
