### ISSUE TITLE
Ошибка при загрузке фото после ошибки валидации страницы

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#599]
1. Заходом на страницу создания записи
2. Загружаем фотку
3. Не заполняем какое-то нужное поле, чтобы получить перезагрузку страницы с ошибкой валидации
4. При повторной загрузке фото получаем ошибку js в консоле 
`admin-app.js:10 Uncaught TypeError: Cannot read property 'push' of null`
http://joxi.ru/eAODPpBfxq56qr

**Comment by mavsan** [comment]
@dronowar а как ты выводишь вот эти надписи?

![image](https://cloud.githubusercontent.com/assets/5114650/26657036/12ba24e4-46a5-11e7-86f4-51b96583f26c.png)

**Comment by dronowar** [comment]
@mavsan https://sleepingowladmin.ru/docs/form-element#api-setHelpText

**Comment by aios** [comment]
@dronowar 

Захожу в демку в редактирование контактов
![image](https://user-images.githubusercontent.com/737550/27028990-39fec2a8-4f6f-11e7-84d8-e99b0a4fbd10.png)

Загружаю картинку
![image](https://user-images.githubusercontent.com/737550/27029024-5549b982-4f6f-11e7-96f1-5a0863747201.png)

Стираю поле
![image](https://user-images.githubusercontent.com/737550/27029069-78cd2cae-4f6f-11e7-87b3-55def4c24132.png)

Отправляю форму
![image](https://user-images.githubusercontent.com/737550/27029082-869f0ea6-4f6f-11e7-848c-15f403a6c5ff.png)

Загружаю фотку поверх старой
![image](https://user-images.githubusercontent.com/737550/27029112-a68a64c2-4f6f-11e7-92c9-dca26c3b1dde.png)

Собственно все тоже самое - но фотку прежде удалил что бы не поверх было.
![image](https://user-images.githubusercontent.com/737550/27029168-d818b69c-4f6f-11e7-8516-ef5fd0ad64a5.png)

Как бы извиняюсь - работает в демке - значит работает в админке)

**Comment by dronowar** [comment]
@aios Сейчас проверил в демке для поля MultiSelect не подставляются значения old input при ошибки валидации. Можно проверить на странице User поле roles

**Comment by aios** [comment]
@dronowar Ты определись - проблема с полем multiselect или с images?

**Comment by dronowar** [comment]
@aios Я же написал ранее, что images работает в демке, проблема была у меня. Но сейчас в multiselect проблема, проверял в демке

**Comment by aios** [comment]
Создай отдельный issue будем допытываться.
