### ISSUE TITLE
Хлебные крошки

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#600]
После правки #558 перестали работать хлебные крошки.

Раньше выводились так:
Dashoboard / Posts - для раздела (секции)
Dashoboard / Posts / Create record in section Posts - при создании записи
Dashoboard / Posts / Update record in section Posts - при редактировании
Dashoboard / Permissions / Users - для раздела, который в группе с другими разделами 
Dashoboard / Permissions / Users / Create record in section Users - создание
Dashoboard / Permissions / Users / Update record in section Users - изменение

Сейчас это выглядит вот так:

![image](https://cloud.githubusercontent.com/assets/5114650/26657275/3b3166de-46a6-11e7-8ef3-abe337ef0875.png)

**Comment by mavsan** [comment]
@aios частично работает:

![image](https://cloud.githubusercontent.com/assets/5114650/26766272/85f90022-49d1-11e7-8b82-f77e6b32e212.png)

![image](https://cloud.githubusercontent.com/assets/5114650/26766278/9b0af0b0-49d1-11e7-9434-dc608d98e676.png)

**Comment by mavsan** [comment]
О, нашел-таки старую, не обновленную версию админки локально. Вот как выглядели раньше хлебные крошки:

![image](https://cloud.githubusercontent.com/assets/5114650/26767004/a3d6af88-49de-11e7-915e-dac0ff790f8f.png)

**Comment by uacode** [comment]
У меня подобная проблема, кеш сбивал, но не помогло...
