### ISSUE TITLE
Связь hasOne не выбирает элемент если столбец числовой

### ISSUE THREAD

**Issue by uacode** [LaravelRUS/SleepingOwlAdmin#603]
Толи баг, толи я что-то делаю не так.
Есть у меня связь  на эту табличку
http://i.piccy.info/i9/f59289533998bedf7b56ac53d2499296/1496681068/30013/1151640/Screenshot_from_2017_06_05_19_43_58.png

```
AdminFormElement::text('details0.104', 'Модель'),
AdminFormElement::text('details0.test', 'test'),
```
details0.104 - в инпуте пусто, а details0.test достает текст с таблицы.

**Comment by aios** [comment]
В базе, в названии столбика не должно быть чистых числовых значений и начинаться с цифры тоже не должно.

**Comment by uacode** [comment]
Беда, а пофиксить как-то можно? (Хотя бы чтоб я в своей версии прописал...)
У меня очень много таких полей :(

**Comment by aios** [comment]
@uacode ну их так то в принципе быть не должно - это не прихоть админки - я где то читал статью об этом. Да и за мою долгую 8-летнюю практику никогда не видел такого.

**Comment by uacode** [comment]
@aios подобная структура юзается в OWOX, то на чем розетка.
Это ограничение Ларавел а не Совы?

**Comment by aios** [comment]
@uacode Я не знаю где ты вычитал что подобную лабуду можно использовать нормально - но мой тебе совет - переделай. И не засоряй мне issue.

**Comment by uacode** [comment]
@aios Ок, спасибо)

**Comment by mavsan** [comment]
@uacode http://www.mysql.ru/docs/man/Legal_names.html в частности:

> Имя может начинаться с любого допустимого символа, в частности, с цифры (в этом состоит отличие от правил, принятых во многих других базах данных). Однако имя не может состоять только из цифр.

**Comment by uacode** [comment]
Ага, не по феншую выходит... Буду переделовать
