### ISSUE TITLE
Нет меню выхода

### ISSUE THREAD

**Issue by shelestovas** [LaravelRUS/SleepingOwlAdmin#605]
На демо есть вот такое меню в админке http://joxi.ru/brR5j53IJR9ozA
Но после установки у меня его не было( перерыл все файлы и не могу понять почему...

**Comment by mavsan** [comment]
После установки демо нет этих виджетов? Или после установки чистой админки нету таких виджетов? 

Админка - это пластилин (местами с примесями, не дающими лепить красоту, но @aios денно и нощно их убирает, попутно внося новые), из которого лепи что хош. Если это просто установка админки, а не клонирование демо - [виджеты](https://sleepingowladmin.ru/docs/widgets).

Если виджетов нет в демке... на всё воля Летающего Макаронного Монстра.

**Comment by aios** [comment]
@shelestovas Глупости - у меня работает))

**Comment by shelestovas** [comment]
Да, до виджетов не дочитал, не сразу понял что это оно, пришлось повозиться чтобы вывести такое же меню.
Документация устаревшая...
