### ISSUE TITLE
При валидации multiselect, текст сообщения не подгружается

### ISSUE THREAD

**Issue by shelestovas** [LaravelRUS/SleepingOwlAdmin#606]
Есть multiselect:
http://joxi.ru/Y2Lkn4aS9qJE7m
и правила валидации

Но все равно сообщения не подтягиваются
http://joxi.ru/l2ZRMR7uwyJYe2

При обычном select все нормально

**Comment by aios** [comment]
Настраивайте модель - Данные берутся из атрибутов.

**Comment by shelestovas** [comment]
Подскажите ссылку с информацией о подомной настройке?

**Comment by shelestovas** [comment]
Нашел метод setPath() вы про него говорили?
только этот метод меняет имя ключа в массивах $this->getValidationRules() и $this->getValidationLabels(), а в $this->getValidationMessages() как раз там где и надо он остается неизменным
Покопался дальше и нашел кусок кода который который должен был менять  ключ
http://joxi.ru/82QqyMXTjpvnn2
то что было закомментировал и поменял на getPath() и теперь все меняет как надо, и следовательно подставляет указанные сообщения при валидации.

Только мне интересно, глупость я сделал или нет) или есть другой способ, проще...
Не нравится редактировать исходники пакета)
