### ISSUE TITLE
DisplayDatatablesAsync and render before

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#608]
Не знаю, исправлено ли в текущей версии (возможно позже посмотрю), но в своей версии обнаружился очень серьезный баг. При использовании DisplayDatatablesAsync происходит выборка всей таблицы без лимитов и условий при генерации страницы

Кусочек по которому все должно быть понятно:

`at Builder->get() in DisplayTable.php line 220
at DisplayTable->getCollection() in DisplayTable.php line 184
at DisplayTable->toArray() in DisplayDatatables.php line 152
at DisplayDatatables->toArray() in Display.php line 266
at Display->render() in AdminController.php line 2059
at AdminController->render(object(ModelConfiguration), object(DisplayDatatablesAsync)) in AdminController.php line 736`

Просто тупо выбирается вся сука таблица. Это просто трындец. 

Судя по всему, в текущией версии это не исправлено. За такое по хорошему нужно руки отрывать. А то и ноги.

**Comment by aios** [comment]
@mediaceh Ну вот сначала протестируй пожалуйста последнюю версию - а потом создавай ишью. Мы как бы в ногу со временем.

**Comment by mediaceh** [comment]
А что мне тестировать когда я в коде аналогичную проблему вижу?

**Comment by aios** [comment]
@mediaceh Я же говорю - ты сначала протестируй - а потом пиши issue - если ты используешь старые релизы - это не наши проблемы.  Как я и говорил админка используется на проектах с миллионными данными. И там работают DatatablesAsync - если бы твоя проблема (не была исправлена 2 релизами ранее) существует - то мы бы испытывали дискомфорт.
