### ISSUE TITLE
CSV export for DataTablesAsync

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#610]
Any easy way to do this?

**Comment by eugenem** [comment]
https://datatables.net/extensions/buttons/examples/initialisation/export.html

They have something, but it requires lots of JS. How can I add all these scripts?

**Comment by aios** [comment]
So you can use custom actions

**Comment by eugenem** [comment]
I want something generic, that will consider current filters.

**Comment by aios** [comment]
We have added some events to confirm dialog. And added confirm dialog to mass actions - you can catch confirm dialog "cancel or confirm" and can change formData to send of your own controller.
Look CHANGELOG.md
