### ISSUE TITLE
Не работает view при добавлении виджета в админку

### ISSUE THREAD

**Issue by zheselevko** [LaravelRUS/SleepingOwlAdmin#611]
Делал все по примеру как в документации. виджет в нужную позицию не ставится. так же появляется код вверху страницы. вместе с блейдовскими переменными

*Note: for support questions, please use gitter: https://gitter.im/LaravelRUS/SleepingOwlAdmin

Read this before asking (Прочитай, прежде чем задавать вопросы):

 - http://programmers.stackexchange.com/help/how-to-ask
 - https://www.propublica.org/nerds/item/how-to-ask-programming-questions
 - https://habrahabr.ru/post/127967/
 - https://mkdev.me/posts/kak-zadavat-voprosy-mentoru-ili-starshemu-razrabotchiku

Do you want to request a feature or report a bug?

What is the current behavior?
If the current behavior is a bug, please provide the steps to reproduce and if possible show log error for this bug.

What is the expected behavior?

What is the motivation / use case for changing the behavior?

Which versions of SleepingOwl and Laravel are affected by this issue?

Other information (e.g. code, stacktraces, related issues, suggestions how to fix)

**Comment by aios** [comment]
Есть демо - если в демо работает - значит в админке тоже работает.

**Comment by zheselevko** [comment]
взял поставил с демо все. и вот как оно сейчас выглядит http://joxi.ru/RmzqNRdI0Q43Yr
