### ISSUE TITLE
MultiSelect - не подставляются значения old input при ошибке валидации

### ISSUE THREAD

**Issue by dronowar** [LaravelRUS/SleepingOwlAdmin#612]
В демке для поля MultiSelect не подставляются значения old input при ошибке валидации. Можно проверить на странице User - поле roles

- Добавляем роли к пользователю
- Стираем данные в обязательном поле
- Сохраняем
- Наблюдаем что данные для роли стерлись

В сессии в массиве _old_input данные присутствуют.

**Comment by aios** [comment]
@dronowar прошу проверить данный таск
