### ISSUE TITLE
AdminFormElement::images - не удаляются изображения

### ISSUE THREAD

**Issue by nyrik8989** [LaravelRUS/SleepingOwlAdmin#613]
AdminFormElement::images('img', 'Изображения на странице новости'),
В секции.
Упало после обновления пакета,
  - Removing laravelrus/sleepingowl (dev-development 6e2a68e)
  - Installing laravelrus/sleepingowl (dev-development 4dee0b7): Downloading (100%)

![screenshot_4](https://user-images.githubusercontent.com/22983913/27170784-ceb33966-51b7-11e7-8bb6-5bde19f1260f.png)

**Comment by nyrik8989** [comment]
AdminFormElement::image('overview_img', 'Изображение виджета')
Так же и на методе "image"

**Comment by aios** [comment]
php artisan vendor:publish --tag=assets --force?

**Comment by nyrik8989** [comment]
да опубликовал

**Comment by nyrik8989** [comment]
Демо в той же версии?

**Comment by aios** [comment]
еще нет.
