### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#615]
Обновился до последней версии, есть элемент формы Image

![image](https://user-images.githubusercontent.com/5114650/27374735-3a1787a0-56b0-11e7-92f9-7ce73c7e9584.png)

Жмакаем "сохранить", получаем:

![image](https://user-images.githubusercontent.com/5114650/27374808-7a516994-56b0-11e7-96a7-ee7db62a1b5a.png)

**Comment by mavsan** [comment]
`php artisan sleepingowl:update` сделал, кеш почистил, ctrl+f5 нажал

**Comment by mavsan** [comment]
![image](https://user-images.githubusercontent.com/5114650/27379351-33bdcd52-56be-11e7-91f5-e30c6fc48b92.png)

Оба этих файла есть, я редактирую запись, которая была создана до того, как обновил сову, и просто нажимаю - сохранить. Vue инспектор показывает, что в обоих компонентах value заполнено, а ничего не отправляется, ппц.

**Comment by mavsan** [comment]
Компонент:

```
data () {
        return {
            errors: [],
            uploading: false,
            val: '',
        }
    },
```

тут val есть, инспектор vue (или как он называется):

![image](https://user-images.githubusercontent.com/5114650/27380398-3e5fd602-56c2-11e7-8e85-6da227ee0737.png)

Если в шаблоне компонента:

`<input :name="name" type="hidden" :value="val">`

заменить на:

`<input :name="name" type="hidden" :value="value">`

все начинает работать:

![image](https://user-images.githubusercontent.com/5114650/27380522-ca9be1c4-56c2-11e7-8337-034145984d2c.png)

что-за фигня?

**Comment by mavsan** [comment]
вот, что в admin-app.js:

![image](https://user-images.githubusercontent.com/5114650/27380661-6224daf0-56c3-11e7-83de-8c3e3acd6eec.png)

это типа webpack так оптимизировал? или это я после 12 часов работы уже туплю?..

**Comment by mavsan** [comment]
Блин, все-таки наверное 12 часов сказываются. Оказывается `php artisan sleepingowl:update` не обновил `admin-app.js`, а просто докопировал `modules.js` и `vue.js`, оно-то меня похоже и успокоило.

Бля, столько времени потрачено зря.

**Comment by Lunatig** [comment]
composer.json 
"post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize",
            "php artisan vendor:publish --tag=assets --force"
        ]

**Comment by aios** [comment]
Эх читаешь монологи и охиреваешь сколько ты проспал)
