### ISSUE TITLE
Валидация картинок

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#616]
В последней версии совы не отображаются ошибки валидации картинок. Ранее отображались только оранжевые полоски, текста не было. После обновления не отображаются даже они, как мне кажется проблема вот в [этом](https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/resources/assets/js/admin/form/image.js#L51): `self.$set(self.errors, response.errors);`, т.к. если сделать просто `self.errors = response.errors`  - все начинает работать (в коде еще есть конструкции `self.$set`). 

`errors` же и так реактивно, зачем использовать `self.$set`? К тому-же [дока](https://ru.vuejs.org/v2/api/#vm-set) говорит, что там должен быть третий параметр.

**Comment by aios** [comment]
Версия Images Была старая и написана по старому - не доглядел.

**Comment by mavsan** [comment]
И надо кнопкам удалить поставить атрибут `type=button`, иначе если нажать enter на каком-то поле появляется вопрос "Вы уверены", но в чем уверены не спрашивает (хочет картинку удалить).
