### ISSUE TITLE
Pagination в DatatablesAsync не отображается контрол переключения

### ISSUE THREAD

**Issue by dessl** [LaravelRUS/SleepingOwlAdmin#618]
При создании таблицы типа DatatablesAsync не отображается переключатель количества записей на страницу.
И в футере со стилями проблема, кривовато как то отображается именно в DatatablesAsync.

Laravel - 5.4
SleepingOwlAdmin - dev-development, 39bc5fdec09b17f8977eea372f64f127c09e8580

**Comment by aios** [comment]
@dessl Для того что бы он отображался - есть метод.
