### ISSUE TITLE
Problem using enableAccessCheck

### ISSUE THREAD

**Issue by Nickbloor** [LaravelRUS/SleepingOwlAdmin#620]
I have created 2 Auths.
One for users, one for admin_users. 
I am using admin_users with sleeping owl. All successful. 
I have created an admin user policy, to handle authorisation. 
I have set all methods to true and have used the auth service provider to map them. 
However, under app/Admin/adminusers.php I am trying to use $model->enableAccessCheck(); 
Even though all methods in policy return true, I cannot access within Sleepingowl. 

Can anyone give advise please?

**Comment by aios** [comment]
you should use Section for better profit with policies. 
If you go to AdminSectionServiceProvider (on demo github)- you can look at registerPolicies method
It use Name of Section As "Some + SectionAdminPolicy" = "SomeSectionAdminPolicy"
If you want use another name = look to protected $policies = [
         "Admin\Sections\SomeAsSampleNamespaceOfSection" => "Admin\Policies\SomePolicy"
]

Have a nice day)

**Comment by Nickbloor** [comment]
Managed to get to the bottom of the problem. We were using 2 Auths, but not using the default for SleepingOwl. Laravel uses Method, resolveUser() using default auth. Because the default was 'user', it returned false. We can fix this by either making admin_user the default in config/auth.php or we could use Auth::shouldUse('admin'); added to the admin/bootstrap.php. Thanks for your help.
