### ISSUE TITLE
Не сохраняются изображения в базе

### ISSUE THREAD

**Issue by stasoft91** [LaravelRUS/SleepingOwlAdmin#626]
Что делаю:
1. Загружаю изображение в AdminFormElement::image('source', 'Карта')
2. Нажимаю сохранить

Что хочу: чтоб путь к изображению записался в соответствующее поле

Что имею: изображение сохраняется в папке, но после нажатия на кнопку Сохранить POSTом в поле source отправляется '' (пустота)

**Comment by aios** [comment]
У всех сохраняются у вас не сохраняются. 
Вывод? 
composer update
php artisan vendor:publish --tag=assets --force
