### ISSUE TITLE
AdminFormElement::date после обновления не работает (всегда пытается вставить 0)

### ISSUE THREAD

**Issue by martelev** [LaravelRUS/SleepingOwlAdmin#632]
Не смотря на то, что в нем выбрана дата, всегда вставляет в базу 0 (именно 0).
Вот пример ошибки:
`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '0' for column 'date' at row 1 (SQL: insert into 'posts' ('header', 'date', 'time', 'image', 'description', 'lead', 'content', 'published', 'prorogued', 'author', 'updated_at', 'created_at') values (Lorem ipsum!, 0, 11:40:00, images/uploads/5e702d0a892b1b2e466f2e568ceb8ed2.jpg, Curabitur convallis vitae...`

**Comment by aios** [comment]
Нужно выставлять формат даты setFormat и формат для отображения setPickerFormat

**Comment by martelev** [comment]
Нет, все равно не работает, это вообще не помогает, что логично.
Вот код:
`AdminFormElement::date('date', 'Дата добавления')->setFormat('Y-m-d')->setPickerFormat('d.m.Y')->required(),`

**Comment by aios** [comment]
Значит поле в базе не соответствует date или оно есть timestamp. У других все работает.

**Comment by martelev** [comment]
Нет, поле формата date. На локалке все работает. 
Вот код: 
`Schema::table('posts', function (Blueprint $table) {
            $table->date('date');`

**Comment by aios** [comment]
Я объяснил уже если бы такая проблема была у всех - меня бы сожрали с потрохами - в первую очередь некоторые из моих сотрудников.
