### ISSUE TITLE
new AdminFormElement::select

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#633]
Выглядит здорово. но на маленьких размерах очень странно.
![untitled-2 fw](https://user-images.githubusercontent.com/3226171/27969220-b3a2ab28-6352-11e7-8f71-53fca972e065.png)

Работает медленнее, чем старые select2

**Comment by aios** [comment]
Первое можно поправить - а второе звиняй - select2 не дают возможностей что дает этот компонент 
так что разбирайся с 600 селектами как то сам. 600 селектов сама по себе проблема я уже говорил.

**Comment by Butochnikov** [comment]
@Lunatig медленнее? а в чем это выражается?

**Comment by aios** [comment]
@Butochnikov У него 600 селектов на странице
