### ISSUE TITLE
value of image field passed to model is null

### ISSUE THREAD

**Issue by tekhoi** [LaravelRUS/SleepingOwlAdmin#635]
Edit form like this
```
    public function onEdit($id)
    {

        return AdminForm::panel()->addBody(
            AdminFormElement::text('title', 'Title'),
            AdminFormElement::image('image', 'Image'),
            AdminFormElement::textarea('intro', 'Intro'),
            AdminFormElement::wysiwyg('body', 'Body')
        );

    }
```

Can upload image fine and have checked AJAX returns path
![image](https://user-images.githubusercontent.com/1024657/27996947-63e32bc8-64e5-11e7-95ef-74cc1d34c29a.png)

Then when the form is saved the image field is null

To check what value is passed I printed value of $request from 
AdminController - postUpdate

![image](https://user-images.githubusercontent.com/1024657/27996967-bb69acc8-64e5-11e7-927e-b1b482c0280d.png)

**Comment by aios** [comment]
@tekhoi 
That causes after save?
If yes - you can try to use setAfterSaveCallback()
in changelog.md you can find info about them

that probally resolve your problem before i find that bug and fix it.

**Comment by tekhoi** [comment]
Yes, that's after using save button, I'll try  setAfterSaveCallback

**Comment by aios** [comment]
@tekhoi let feedback here please with mention on me - i will read this ASAP.

**Comment by aios** [comment]
@tekhoi Fresh installed demo from github - can't repro problem
