### ISSUE TITLE
Getting errors with select & radio fields

### ISSUE THREAD

**Issue by tekhoi** [LaravelRUS/SleepingOwlAdmin#636]
Trying to use either select or radio but get error with both.

`AdminFormElement::radio('media_type_id', 'Type')->setOptions(['0' => 'Test 1', '1' => 'Test 2']),`

With this I get error 
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: htmlspecialchars() expects parameter 1 to be string, array given (View: \vendor\laravelrus\sleepingowl\resources\views\default\form\element\radio.blade.php)

I have also tried select as an alternative
`AdminFormElement::select('media_type_id', 'Type')->setOptions(['0' => 'Test 1', '1' => 'Test 2']),`

With this the select is not rendered - I also notice in the browser console there are 404 errors for multiselect.css, maybe thats related? (can't find any files with this name)

**Comment by aios** [comment]
"post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan optimize",
            `"php artisan vendor:publish --tag=assets --force"`
        ]

@tekhoi look at that command - that need to execute after every update of sleeping_owl

**Comment by tekhoi** [comment]
Thanks.

Don't get 404 any more but other issues still same :(

**Comment by aios** [comment]
Can find me in telegram (@aioslike)?

**Comment by aios** [comment]
Try to update and command php artisan vendor:publish --tag=assets --force
and when you are on admin page try to CTRL+F5 or same keyboard combination for your OS and clean browser cache

**Comment by aios** [comment]
I have added your same select on my own admin - and it works
![image](https://user-images.githubusercontent.com/737550/28019970-65b5a772-658b-11e7-916d-ae742c12f121.png)

P.S. After fix radio

![image](https://user-images.githubusercontent.com/737550/28020742-146d41ce-658e-11e7-8f78-d5cdc6b9ae93.png)
