### ISSUE TITLE
Cancel after Save

### ISSUE THREAD

**Issue by Daaner** [LaravelRUS/SleepingOwlAdmin#638]
При редактировании, если ткнуть сохранить и после сохранения кнопка отмены перестает выводить из onEdit. И при такой ситуации кнопка SaveAndClose выкидывает на '/'
Легко проверить в демке на новостях, к примеру.

**Comment by aios** [comment]
Помоему Кнопка Отмена нужна для того что бы выйти из формы - а не для того что бы отменять ее отправку. Если бы на кнопке было написано "Назад" стало бы понятно зачем она нужна.

**Comment by Daaner** [comment]
так не выходит же из формы, когда она была сохранена уже просто кнопкой Save

**Comment by aios** [comment]
Ну у меня чистая установка - только обновляю сову. У меня проходит.

**Comment by Daaner** [comment]
просто тыкается, если что-то сохранить в форме - потом уже не тыкается

**Comment by Daaner** [comment]
в демке тож так
и еще у одного чела в чате

**Comment by Butochnikov** [comment]
Подтверждаю, после save, кнопка "отменить" не работает.

**Comment by Daaner** [comment]
С "отмена" все норма. Но еще один маленький нюанс. Открыть -> изменить -> сохранить ->сохранить и закрыть  -- выкидывает в корень сайта (даже не в корень админки)

**Comment by aios** [comment]
Это пока никого не беспокоит....
