### ISSUE TITLE
select, multiselect and JS

### ISSUE THREAD

**Issue by macedodebrito** [LaravelRUS/SleepingOwlAdmin#641]
Hello!

before this multiselect update, i had my JS code being used with things like this: 

`$('#request_id').on('change', function () {`

Now this is not working, 
How can i use this kind of feature again?

for elements like this one per example: 

`AdminFormElement::select('request_id', 'Pedido de Produção')`

Thanks.

- Brito

**Comment by macedodebrito** [comment]
i still have problems here. the multiselect INPUT doesnt have name/id aswell. it is supposed to be like that ?

i cant use JS without pointing to an ID :D

thanks

**Comment by aios** [comment]
can you make request on telegram (@aioslike) its be fastest.

**Comment by macedodebrito** [comment]
what ? telegram? im not following you... what is telegram? the messenger thing? :D

**Comment by Daaner** [comment]
https://telegram.org/

**Comment by aios** [comment]
@macedodebrito if i haven't your data for test your problem - find solution for your problem will be slow and booooring. I haven't time for research. 

You do not follow me and it's your right. But the communication channel by which the solution to your problem can be accelerated, I leave the right to choose myself.

**Comment by macedodebrito** [comment]
You misunderstood me. I said I did not know TELEGRAM, and I did not understand what you meant by "telegram."

Obviously I will always use the channels themselves to streamline the solution to the problems, namely GITTER, GITHUB and TELEGRAM (now I have installed it).

Thank you for your help.
