### ISSUE TITLE
При использовании табов ломается верстка всей админки

### ISSUE THREAD

**Issue by zerolimitss** [LaravelRUS/SleepingOwlAdmin#642]
When I use tabs, the layout of the entire admin dashboard breaks down.
```
$tabs = AdminDisplay::tabbed();
$tabs->setTabs(function ($id) {...
```

The reason  - AdminFormElement::image()
If you use only text fields(without ::image, only ::text()), tabs are normally displayed.
How fix it?

**Comment by Daaner** [comment]
![image](https://user-images.githubusercontent.com/9641698/28088194-9c460c8e-668d-11e7-82b2-00e0101b2f06.png)
Maybe you somehow not so use?

**Comment by zerolimitss** [comment]
Maybe. Could you show example of your code?

**Comment by zerolimitss** [comment]
I have exception
"Method Illuminate\View\View::__toString() must not throw an exception"

**Comment by aios** [comment]
![image](https://user-images.githubusercontent.com/737550/28202941-41545cbe-6880-11e7-8772-e650e2e60661.png)
Tabs working.

Please dont add issue marked Design Questions. If questions not marked UX or not related to Business Logic -> permanently closed
