### ISSUE TITLE
Select empty array

### ISSUE THREAD

**Issue by Daaner** [LaravelRUS/SleepingOwlAdmin#657]
Eсли элементов не находит не показывает надпись "No elements found. Consider changing the search query.", а тупо не раскрывается

ЗЫ: если чутка поколдовать в стилях и поубирать дисплей:ноне то надпись увидеть можно

![view](https://user-images.githubusercontent.com/9641698/28498630-51481a8a-6faa-11e7-9a28-28be9eb2cf09.png)
![emptyselect](https://user-images.githubusercontent.com/9641698/28498629-5144257e-6faa-11e7-9b90-2868d17e6492.png)

**Comment by aios** [comment]
Собственно я изучил этот момент - эта штуковина появляется только когда вводишь что то в поле поиска - и нету результатов. Потому и не отображается при открытии - так то селект пустой. Нужно будет при проверке опшнов просто менять подпись на Нет элементов.
