### ISSUE TITLE
Слетел дизайн админки

### ISSUE THREAD

**Issue by lor08** [LaravelRUS/SleepingOwlAdmin#661]
Здравствуйте, после последнего обновления у админки слетел диз
http://i.prntscr.com/dmWMdcKCRMW2F9JE7P9MRA.png
В чем может быть причина?
laravel 5.4

**Comment by Daaner** [comment]
ты что-то начудил или не форсанул. Читал реадми? все сделал с  php artisan sleepingowl:update?
![image](https://user-images.githubusercontent.com/9641698/28671149-48b8fa1e-72e4-11e7-99a5-e2cdcd40f84e.png)

**Comment by lor08** [comment]
Нашел уже проблему, почему-то ресурсы в папке 
public/packages/sleepingowl не обновились, или они не должны там обновляться, после команды sleepingowl:update?

**Comment by aios** [comment]
Читаем README.md
