### ISSUE TITLE
Запрос фишки - цветовая индикация строк таблиц

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#670]
Во время отображения данных в таблице, некоторые заказчики требуют цветовую дифференциацию строк.
Для совсем чёткого понимания: чтобы например softDeleted строки были другого цвета/вида, чтобы в зависимости от данных в строке, программист мог определить свой css-класс для назначения всей строке.
Если бы кто-то взялся написать новый метод для всех таблиц, то было бы просто волшебно.
Примеры есть у jqGrid / jqWidgets <= это повсеместно в црм/ерп используемые инструменты, настолько нужные, что также стоило бы их внедрить в сову.

**Comment by aios** [comment]
Кстати недавно сделал для такой задачи костыль. 
<span class="model_deleted">

Перехватывал datatables::draw и просто делал столбику другой стиль. но это так просто костыль.

**Comment by h-zone** [comment]
Чёрт прям даже не знаю. Костыли в бизнесе ни алё...
Есть же смысл делать свою работу правильно и хорошо, - неужели задача не возбуждает?

**Comment by aios** [comment]
Ну что бы получить то что ты хочешь - нужно переписать datatables. Я планирую сделать это на vue. Но это не решается щелчком пальца. Это будет в 5 версии.. Для начала хочу позакрывать все ишью и создать майлстон на 5.0. Потому тебе придется потерпеть. Я категорически против jQuery На фронте. только со стороны клиента.

**Comment by h-zone** [comment]
Забей на datatables это вообще не серьёзный инструмент. Ни-ра-зу!
Смотри на jqGrid, я не от праздного или хотелки этого говорю. Я с ним работал и как минимум с десяток црм поднял на нём. Да, мега сложный, но реально закроет все хотелки до 18 версии совы. Повторяю, - я не шучу.
Нужна помощь по jqGrid - обращайся, контакты дам, например в гиттере.

**Comment by h-zone** [comment]
> Я категорически против jQuery На фронте. только со стороны клиента.
поподробнее, а то звучит сумбурно/двояко

**Comment by aios** [comment]
На странице Readme Есть список компонентов - все что есть - и у всех у кого есть зависимость от jQuery будут либо уничтожены и заменены на vue аналоги - либо переписаны в ручную. jQuery останется на фронте как клиентский поток. не больше.

**Comment by aios** [comment]
@h-zone не пасибо - jQgrid как и все остальные jQuery плагины порождают свою базу рамок в которые мне придется себя засунуть. А я хочу что бы у пользователей в последствии была возможность кастомизировать все - вплоть до того что они сами могли бы подключить jQgrid.
так что "Интим" не предлагать. Но спасибо за заботу. Пока времени на крупные разработки все равно нет.

**Comment by aios** [comment]
@h-zone да нет - я работал с ним. И я знаю его возможности. Именно по этому и не хочу. Я уверен что у меня получиться гараздо легче - гараздо компактнее и гараздо кастомизабельнее с помощью vue. Ну не лежит у меня душа к jQuery. Не обессудь. Проект не мой. Но я поддерживаю и постоянно слушаю пользователей. Стараюсь максимально быстро внедрять то что они просят. Сейчас сова требует изменений. И они будут - в гараздо лучшую сторону чем с jQGrid. 

Посмотри на гигантов. Orchid, Backpack, Pyro, Voyager. Если jQgrid такое офигеть не встать какое решение. Почему его в этих пакетах нет? то то же. 

И все же если ты считаешь что "МЫ" ( в лице сообщества совы ) не правы - и тебе корпит доказать обратное. Тебя за ногу никто не держит. У тебя всегда есть все версии совы и ее репозиторий. Сделай форк -  сделай ветку - сделай пулреквест - потрать на это время - пойми каким трудом это дается - а пользователи оценят и начнут теребить гуру что бы они его приняли. Это если ты думаешь что проблема в том что я не хочу. То у тебя есть все шансы доказать дееспособность jQGrid. Если же ты просто ждешь что кто то сделает это за тебя - сорян мужик - тут это так не работает.

**Comment by h-zone** [comment]
> Посмотри на гигантов. Orchid, Backpack, Pyro, Voyager. Если jQgrid такое офигеть не встать какое решение. Почему его в этих пакетах нет? то то же.

ни разу не аргумент.
админка в первую очередь инструмент управления, и зачастую не просто сайтом, а бизнес-элементами. удобство должно быть выше нежелания использовать устаревшую библиотеку.

> И все же если ты считаешь что

Мне, если прямо говорить, сова не импонирует. использую потому что
а) лень писать свой инструмент
б) удобство развёртывания. тот же voyager - плоский геморрой.

С точки зрения форка - увольте. Я помогу кому-то своим участием, советами и другими делами, помогу решить вопрос "как", а вот писать не буду. старый уже.

**Comment by aios** [comment]
@h-zone Ну если используешь значит уже чем то привлекла. 
По поводу посылов ниже этого высказывания. Со всем уважением к твоему возрасту\опыту\знаниям - это твои проблемы. Опен сорс делается не на управленческой основе и не в менторном ключе. А исключительно исходя из желания\времени, которое лично ты можешь на это уделить. Нету ни того ни другого? сорян. тогда двигай по своему пути и не высказывай свое мнение "Абы\Лижбы". Если это ничем не подкреплено - это не опенсорс. А просто твоя позиция. А просто у твоей позиции есть одно очень крутое свойство - тебя с ней могут просто послать далеко и на долго) Спасибо что уделил время.
