### ISSUE TITLE
AdminColumn::datetime меняет время

### ISSUE THREAD

**Issue by lor08** [LaravelRUS/SleepingOwlAdmin#677]
Когда вывожу дату при помощь AdminColumn::datetime
время уходит на 3 часа назад, в чем может быть дело?
При AdminColumn::text все нормально,внизу пример
слево все норм, справа трабла (
Такое чуство, что где-то часовой пояс в админке меняется...
http://i.prntscr.com/W6P6UJKNQgmgFSC9pfaWcg.png

**Comment by xloss** [comment]
Всё ниже указанное всего лишь предположения, но:
- есть настройки таймзоны в config/app.php
- настройки сервера на котором расположена база данных, я например люблю использовать GMT+0 на сервере, а временем балансирую через php.

**Comment by lor08** [comment]
настройки таймзоны в config/app.php стоит Москва как и нужно.
На сервере тоже стоит Москва в php.ini так же Москва
Именно при выводе мне кажется что-то не так происходит, в самое панели есть где-нибудь установка зоны для AdminColumn::datetime?

**Comment by aios** [comment]
@lor08 Такое дело 
`src/Display/Column/DateTime.php`
```php
    /**
     * @return string
     */
    public function getTimezone()
    {
        if (is_null($this->timezone)) {
            $this->timezone = config('sleeping_owl.timezone');
        }

        return $this->timezone;
    }
```

**Comment by Daaner** [comment]
Есть настройки таймзоны в конфиге совы. Сам мучался. Пока не нашел в новой версии. При обновлении в конфиг не прилетают параметры. Тут только ручками вставлять и все будет ок
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/config/sleeping_owl.php#L105
