### ISSUE TITLE
Запрос функционала - события для всех таблиц

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#678]
Нужны события для отрисовки всех таблиц:
tableBeforeShow - перед началом отрисовки таблицы
tableShown - непосредственно сразу после отрисовки талицы
tableAfterShow - после отрисовки таблицы и всех данных (строк)
rowShown - после каждой строки (итерация)

Для корректной работы и распознавания строк предлагаю каждой row назначать data-row-id="" равный либо ключу (если указано) таблицы либо сквозному номеру, а лучше сделать настраиваемым.
То же самое для каждой ячейки - data-cell-id="{row-id}-{cell-num}"

В целом, оглядываясь на jqGrid это нужный функционал, позволит что-то делать с таблицей.

Например внедрить цветовую дифференциацию строк, что просто must have в бизнес-приложениях...
Оперировать с ячейками строки в зависимости от данных в других ячейках этой или уже отрисованных строк.

Очень прошу не закрывать этот топик, а хотя бы обсудить возможность решения этой задачи.

Как вариант могу помочь (через пару месяцев) с внедрением jqGrid со всеми недокументированными его фичами... Но после того как у самого с работой будет полегче...

**Comment by aios** [comment]
Возможно в будущем.
