### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by alex-shamshurin** [LaravelRUS/SleepingOwlAdmin#68]
The provided docs are not sufficient to get it work. Please write some additional steps to launch it. After I did step 3) "/admin" route returns an empty page with no hints about reasons. Also, some example models needed for that must be created by default.

**Comment by artemiydeveloper** [comment]
+

**Comment by codydh** [comment]
Not only that, but the documentation itself suggests installing v2.* (http://sleeping-owl.github.io/en/Getting_Started/Installation.html), whereas the repo is on 4.*@dev. Documentation is hard to work through unless you know what you're doing.

**Comment by 7immy** [comment]
Since version 2 methods names have changed, installation steps have changed, new features have been added, some methods have been removed and coding style is a different too.

I'm currently having looking up the src files and guessing how to use each method :(

**Comment by followtheart** [comment]
+1

**Comment by butschster** [comment]
You can also view release comments, for example about custom wysiwyg editor https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.21.94-beta
I want to move all code examples to docs. if you want, you can help/

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin-docs
