### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by dontTryThisAtHome** [LaravelRUS/SleepingOwlAdmin#685]
при попытки установки возникает следующее исключение

$ php artisan sleepingowl:install
Copied File [\vendor\laravelrus\sleepingowl\config\sleeping_owl.php] To [\config
\sleeping_owl.php]
Publishing complete.

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to SleepingOwl\Admin\Console\Commands\Install
  Command::SleepingOwl\Admin\Console\Commands\{closure}() must be an instance
   of SleepingOwl\Admin\Contracts\Console\InstallatorInterface, string given

**Comment by aios** [comment]
Проверим решим. Ожидайте.
