### ISSUE TITLE
AdminColumnEditable::text

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#689]
## Версия в композере
"laravelrus/sleepingowl": "4.*@dev"
[вот эта версия, если быть точным](https://github.com/LaravelRUS/SleepingOwlAdmin/commit/8ab75dbf098802789a1b3401b206dccf35d9b36e)
## Что надо сделать что бы увидеть ошибку?

1. В секции `$display = AdminDisplay::datatables();`
2. Где-то в описании столбцов `AdminColumnEditable::text('column', 'Label'),`

## Что должно сработать?
1. В таблице в соответствующем поле при клике по значению должен появиться блок с возможностью изменить значение.

## Что сработало?
1. Выглядит вот так:
![image](https://user-images.githubusercontent.com/5114650/29056321-74ccf6b8-7c45-11e7-857f-dcb7de1ea2c8.png)

2. При клике по полю иногда выглядит вот так (иногда только 1 блок появляется):
![image](https://user-images.githubusercontent.com/5114650/29056455-7728ef1a-7c46-11e7-9f1f-3ff05c9ca459.png)

## Что не сработало?
1. В базу новое значение не было сохранено.

## Каким богам были принесены жертвы?
1. Увы, до этого не дошло, достаточно таблицу определить вот так: `AdminDisplay::datatablesAsync()`. С другими типами не пробовал, только `AdminDisplay::datatables()` (не работает) и `AdminDisplay::datatablesAsync()`.

**Comment by aios** [comment]
@mavsan расписывай как добавляешь - лунатик на всех браузерах потестил - все ок.

**Comment by mavsan** [comment]
Ubuntu chrome, более нигде не тестировал. `composer update`, обновление ассетов прописано в composer.json, на всякий случай вручную запустил (после того, как увидел это дело). Нажал Ctrl+F5, результат тот-же. После этого полез в демо, там работает. Скачал, посмотрел исходники, там `AdminDisplay::datatablesAsync()`, а у меня - `AdminDisplay::datatables()`, поменял - все стало отлично. Вот и создал issue.

**Comment by mavsan** [comment]
Вот, сейчас опять сделал `AdminDisplay::datatables()` и потестил на Opera и Mozilla (все для linux)
Mozilla:
![image](https://user-images.githubusercontent.com/5114650/29149164-9c9b2e1e-7db5-11e7-991f-a5476498685f.png)
Еще бывает так:
![image](https://user-images.githubusercontent.com/5114650/29149172-af51c400-7db5-11e7-8f35-63483886b540.png)

Opera:
![image](https://user-images.githubusercontent.com/5114650/29149178-c0ee636c-7db5-11e7-84e1-4f9d0a27b390.png)

![image](https://user-images.githubusercontent.com/5114650/29149186-ccb17e96-7db5-11e7-8555-356474fc402b.png)

**Comment by mavsan** [comment]
Вот так - не верно работает:

```php
public function onDisplay()
    {
        $display = AdminDisplay::datatables();

        $display->setColumns([
            AdminColumn::link('title', 'Заголовок'),
            AdminColumn::custom('Раздел',
                function (\Illuminate\Database\Eloquent\Model $model) {

                    switch ($model->position) {
                        case 'about':
                            $data = 'О нас';
                            break;

                        case 'buyers':
                            $data = 'Покупателям';
                            break;

                        default:
                            $data = 'ошибка';
                    }

                    return $data;
                }),
            AdminColumnEditable::text('sort',
                'Сортировка вывода в пределах раздела'),
            AdminColumn::text('uri', 'Ссылка'),
        ]);

        return $display;
    }
```

А вот так - верно:
```php
public function onDisplay()
    {
        $display = AdminDisplay::datatablesAsync();

        $display->setColumns([
            AdminColumn::link('title', 'Заголовок'),
            AdminColumn::custom('Раздел',
                function (\Illuminate\Database\Eloquent\Model $model) {

                    switch ($model->position) {
                        case 'about':
                            $data = 'О нас';
                            break;

                        case 'buyers':
                            $data = 'Покупателям';
                            break;

                        default:
                            $data = 'ошибка';
                    }

                    return $data;
                }),
            AdminColumnEditable::text('sort',
                'Сортировка вывода в пределах раздела'),
            AdminColumn::text('uri', 'Ссылка'),
        ]);

        return $display;
    }
```

![image](https://user-images.githubusercontent.com/5114650/29149249-44769da8-7db6-11e7-9e9b-8eb57ea0d10f.png)

**Comment by mavsan** [comment]
На всякий случай исходник в браузере:
![image](https://user-images.githubusercontent.com/5114650/29154703-b2b0ee54-7dd9-11e7-9b84-d61d5d4e9168.png)

**Comment by Lunatig** [comment]
опа. так откуда на td нападает класс editable. вот и причина засора

**Comment by mavsan** [comment]
@Lunatig, я не добавлял, оно само! :)

**Comment by Lunatig** [comment]
не. эт мой косяк. я поправлю.

**Comment by Lunatig** [comment]
@mavsan
то есть учитывая что сейчас datatables алиас datatablesAsync проблема больше не появляется ?

**Comment by aios** [comment]
d5767d29c82c5272efbb временно пофиксили вот этим коммитом.

**Comment by mavsan** [comment]
Прикольно: "временно пофиксили", т.е. когда решат вернуть datatables - кто-то тоже отловится?.. Ну да ладно, хозяин-барин, хотя я такого не понимаю.

**Comment by aios** [comment]
@mavsan я думаю что datatables простые - не вернутся уже никогда.
