### ISSUE TITLE
Не работает AdminFormElement::select()

### ISSUE THREAD

**Issue by Ivnkara** [LaravelRUS/SleepingOwlAdmin#690]
## Версия в композере
"laravel/framework": "5.3.*",
"laravelrus/sleepingowl": "4.*@dev",

## Что надо сделать что бы увидеть ошибку?
1. В любом пункте меню создать элемент формы AdminFormElement::select()

## Что должно сработать?
1. Появится выпадающий список

## Что сработало?
1. Селекты пропали во всей админке. Отображается просто label заголовок, а самого выпадающего списка нет. Кажись, обновления всё поломали. Не есть хорошо -=(((

**Comment by vkn999** [comment]
+1 Вчера заметил. "laravel/framework": "5.4."

**Comment by aios** [comment]
@Ivnkara @vkn999 
Сделайте так:
`cd vendor/laravelrus/sleepingowl && npm install && npm i -g gulp && gulp`

Вы должны увидеть лог сборки фронта.

Откройте вторую вкладку терминала в этом проекте и скомандуйте 
`php artisan vendor:publish --tag=assets --force`

Зайдите в админку на неработающий селект и сделайте CTRL+F5 
и покажите мне гребаную консоль Chrome или другого браузера. Хочу понять ошибку которая у вас происходит.

**Comment by xloss** [comment]
Достаточно просто `php artisan vendor:publish --tag=assets --force` набрать в консоли.
