### ISSUE TITLE
Ссылки в админке по типу /admin/section/:param1/:param2

### ISSUE THREAD

**Issue by Letoile** [LaravelRUS/SleepingOwlAdmin#691]
## Версия в композере
"4.*@dev"

## Что надо сделать ~~что бы увидеть ошибку~~?

1. Для секций добавить возможность в случае указания ссылок с параметрами (/admin/some_section/:param1/:param2 и т.п.) настроить фильтр по указанным параметрам
2. При добавлении таких ссылок в навигацию - корректно выделять активную
3. Корректно отображать хлебные крошки

**Comment by daaner** [comment]
Гет параметры (немного не так как хочешь ты, но все же) уже давно можно прокидывать в секцию и получать динамический фильтр.
Тем более относительно давно добавилось сохранение положения фильтров, что тоже закрывает часть ишью
