### ISSUE TITLE
AdminColumnFilter::select, setUsageKey и object

### ISSUE THREAD

**Issue by xloss** [LaravelRUS/SleepingOwlAdmin#692]
Это дополнение к #673
Отловил баг. Если в setFetchColumns указать поле object и в качестве ключа использовать свойство объекта, то будет ошибка. Получается так, что если не указать setFetchColumns, то указание ключа нужно делать через вид:
```php
->setUsageKey('object.key'),
```
Я предлагаю добавить:
```php
$key = str_replace('->', '.', $key);
```
в файле `Traits/SelectOptionsFromModel.php` после строки `239`
а вызов ключа уже будет по формату
```php
->setUsageKey('object->key'),
```
и тогда ошибки не будет с setFetchColumns и без его использования.

**Comment by aios** [comment]
@xloss Зачем это требуется?

**Comment by xloss** [comment]
@aios как обычно, что бы в качестве ключа использовать значения из поля с cast = object

**Comment by aios** [comment]
@xloss попробуй поставить эту строку и протестировать остальные селекты. потому что для меня это выглядит как костыль.
