### ISSUE TITLE
Помогите новичку!

### ISSUE THREAD

**Issue by Jlomaka** [LaravelRUS/SleepingOwlAdmin#697]
Доброе вам время суток, хотелось бы узнать есть ли у вас возможно какое видео по обучению либо примеры хотя бы пару готовых вкладок, так как документации мало, и хотелось бы хотя бы чуть чуть визуального восприятие всего, сам начинаю только программировать на laravel 5.4, все что нашел в youtube вообще не информационно или просто набор фраз а не объяснений как с ней работать или мануал по установке. Буду очень благодарен за пример что бы в живую оценить хотя бы некоторые возможности вашей админки.

**Comment by aios** [comment]
И так поехали.
Самое самое первое это laracasts нужно посмотреть все видосы - а лучше по 2 раза. что бы понимать о чем речь. 

Дальше нужно почитать документацию laravel. Сначала бегло - второй раз вдумчивей. Это все для индексации информации, которая в последствии поможет тебе решить буквальные ситуации с фреймворком.

Дальше читаешь этот файл: https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/README.md

Устанавливаешь все как написано

Далее лезешь на сайт http://sleepingowl.ru

Там вся интересующая тебя инфа + демо + гитхаб на демо.

С ув. Команда SO
