### ISSUE TITLE
AdminColumnFilter::select

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#698]
## Версия в композере
"laravelrus/sleepingowl": "4.*@dev"

## Что надо сделать что бы увидеть ошибку?
1. Поле, по которому идет поиск должно иметь значение 0 (ноль)
2. Создать фильтр столбцов `AdminColumnFilter::select([...])`

## Что должно сработать?
1. При выборе значения из выпадающего списка фильтра с ключом 0 (ноль) и нажатия на кнопку "фильтр" значения в таблице должны отфильтроваться и отобразиться только те записи из БД, значения поля по которому происходит фильтрация = 0

## Что сработало?
1. Отображаются все записи из бд, как будто никто ничего не фильтровал. 
2. Если выбрать какое-то другое значение из базы выпадающего списка (ключ у которого != нулю), то фильтр работает исправно.

**Comment by marmildev** [comment]
I have a problem with select field after last update
these lines don't show field in admin , only label.

AdminFormElement::select('country_id', 'Zemlja')->setModelForOptions(Country::class, 'title'),
AdminFormElement::select('structure_id', 'Strukture', Structure::class)->setDisplay('title')->required(),

Somebody has same problem? Any solution?

**Comment by aios** [comment]
@marmildev what kind of problem? can you screen what happened?

**Comment by marmildev** [comment]
![select_problem_1](https://user-images.githubusercontent.com/10978080/29386518-8dd7c29e-82dc-11e7-9a08-b95d1f7a0c92.png)
![select_problem_2](https://user-images.githubusercontent.com/10978080/29386519-8dd8c2d4-82dc-11e7-82ac-cc5ab922e565.png)

lines which I paste above showing only label in admin panel without select (drop-down) field

**Comment by aios** [comment]
@marmildev Look on Readme.md
and put php artisan sleepingowl:update on his place in composer.json

just for solve your problem now please command php artisan vendor:publish --tag=assets --force

**Comment by marmildev** [comment]
It works now. Thank you very much @aios

**Comment by aios** [comment]
@marmildev you can try to connect on our telegramgroup and here we can fast resolve some problems
http://t.me/sleeping_owl

**Comment by marmildev** [comment]
ok I'm in. tnx
