### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by butschster** [LaravelRUS/SleepingOwlAdmin#7]
Необходимо дать возможность настраивать  Policy для каждого раздела

**Comment by butschster** [comment]
Добавлена проверка прав доступа на работу с разделом.

По умолчанию проверка прав отключена и доступ к разделам можно отключать посредством методов

```
$model->disableDisplay();
$model->disableCreating();
$model->disableEditing();
$model->disableDeleting();
$model->disableRestoring();
```

Также можно включить проверку прав с помощью Policies
Для этого необходимо включить ее

```
$model->enableAccessCheck();
```

После чего создать для модели Policy класс для модели, которая используется в текущем разделе https://laravel.com/docs/5.2/authorization#policies

И в класс Policy добавить методы 

```
public function display(User $user, Model $model);
public function create(User $user, Model $model);
public function edit(User $user, Model $model);
public function restore(User $user, Model $model);
public function delete(User $user, Model $model);
```

После чего проверка прав будет дополнительно осуществляться на его основе

**Comment by shachneff** [comment]
> По умолчанию проверка прав отключена и доступ к разделам можно отключать посредством методов

$model->disableDisplay();
$model->disableCreating();
$model->disableEditing();
$model->disableDeleting();
$model->disableRestoring();

Куда это пихать?? Где взять модель??
Покажите на своей демке!!!
