### ISSUE TITLE
Естественное упорядочение элементов Select ($options)

### ISSUE THREAD

**Issue by ZAZmaster** [LaravelRUS/SleepingOwlAdmin#701]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/4463c620045f1e7a3066fdda36ed600283a4b00c/src/Form/Element/Select.php#L70

Предлагаю добавить SORT_NATURAL к данной сортировке.

**Comment by ZAZmaster** [comment]
Ну или возможность указывать этот параметр без правки исходников.

**Comment by aios** [comment]
`setSortable(false)`
