### ISSUE TITLE
Дополнительные опции Vue в multiselect

### ISSUE THREAD

**Issue by ZAZmaster** [LaravelRUS/SleepingOwlAdmin#702]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/4463c620045f1e7a3066fdda36ed600283a4b00c/resources/views/default/form/element/multiselect.blade.php#L14

Было бы неплохо реализовать возможность добавлять/изменять опции Vue мультиселекта http://monterail.github.io/vue-multiselect/#sub-props

**Comment by aios** [comment]
@ZAZmaster Это к сожалению никому не нужно. Если есть такая потребность то есть возможность переопределить шаблон select и указать там все нужные переменные.
