### ISSUE TITLE
Динамическое добавление полей

### ISSUE THREAD

**Issue by Jazz-Man** [LaravelRUS/SleepingOwlAdmin#703]
Как реализовать динамическое добавление полей в формы?
Например, есть список различных атрибутов и опций для товара, и нужно в карточке товара их динамически добавлять:

- цвет:синий 

- размер:большой, и т.д.

**Comment by aios** [comment]
Как Ты себе это видишь?

**Comment by Jazz-Man** [comment]
Поскольку laravel я только изучаю, поэтому опишу теорию, как я это вижу

### Атрибуты

Атрибуты могут иметь любой тип - строка, число, цвет (могут быть и другие). В карточке товара можно будет присваивать любое количество этих атрибутов, выбирая из уже существующих. В зависимости от типа атрибута при воборе его в форму карточки товара добавляется соответствующее типу поле.

### Опции

Опции тоже добавляются заранее и их назначение - изменения цены товара в зависимости от выбранных опций. В них тоже есть определенные типы - чекбокс, селект, радибаттон, изображения (могут быть и другие). В карточке товара выбор опций может быть такой же, как в атрибутах с той разницей, что для опций добавляется поле "цена" за опцию.


### Основная задача:
добавление этих полей динамически через ajax.

### вопрос:

можно ли это реализовать штатным способом или пилить свой какой-то компонент

**Comment by aios** [comment]
@Jazz-Man скорее всего придется пилить самостоятельно. У меня есть в планах сделать Related-Edit компонент - но охватить все кейсы у меня к сожалению не выйдет. Потому до этого еще нужно дойти.

**Comment by daaner** [comment]
На данный момент появились элементы `hasMany` и прочие. Они покрывают это иссуе. Закрываю
