### ISSUE TITLE
Бага в BreadCrumbs при создание

### ISSUE THREAD

**Issue by Pingvi** [LaravelRUS/SleepingOwlAdmin#705]
При создание новой записи в BreadCrumbs отображается не полный путь. 

![default](https://user-images.githubusercontent.com/6401810/29350548-68f8787e-8278-11e7-8dd8-3ed9b86a6fef.png)

В итоге есть проблемы с навигацией в меню (пункт не отображается как активный).

**Comment by aios** [comment]
@Pingvi сяп - буду смотреть.
