### ISSUE TITLE
I do not see the menu to logout

### ISSUE THREAD

**Issue by KikoPalomares** [LaravelRUS/SleepingOwlAdmin#71]
I do not see the menu to logout. Do I have to do something to make it look ?; The auth do everything right.

**Comment by butschster** [comment]
Hi. I removed `auth` middleware from sleepingowl config.

**Comment by artemiydeveloper** [comment]
@butschster удалили? а в документации сказано, что нужно использовать middleware. Или я не так понял?

**Comment by KikoPalomares** [comment]
But I have put back... so?

`'middleware' => ['web', 'auth'],`

**Comment by butschster** [comment]
Yes

**Comment by KikoPalomares** [comment]
But I still do not see the logout menu.

**Comment by butschster** [comment]
show me code.

**Comment by KikoPalomares** [comment]
What part of it?

**Comment by fedcba98** [comment]
+1 
Тоже не появился логаут. Вижу в хедере админки (resources/views/default/_partials/header.blade.php) такое:
`
 <ul class="nav navbar-nav">
     @yield('navbar')
 </ul>
 
 <ul class="nav navbar-nav navbar-right">
 	@yield('navbar.right')
 </ul>
`

**Comment by butschster** [comment]
@fedcba98, @KikoPalomares 

see example with adding navigation profile link https://github.com/SleepingOwlAdmin/demo/blob/master/app/Providers/AuthServiceProvider.php#L42
https://github.com/SleepingOwlAdmin/demo/blob/master/resources/views/auth/partials/navbar.blade.php

or

https://github.com/butschster/SimpleSite/blob/master/resources/views/auth/partials/navbar.blade.php

**Comment by fedcba98** [comment]
Да, я раскопал в принципе чуть позже. Спасибо за подсказку.
