### ISSUE TITLE
Над AdminColumnEditable::checkbox появляется попап с текстовым полем

### ISSUE THREAD

**Issue by 1oginov** [LaravelRUS/SleepingOwlAdmin#712]
## Версия в композере
^4.95 (4.99.99)

## Что надо сделать что бы увидеть ошибку?
1. Зайти на https://demo.sleepingowladmin.ru/admin/news
2. Нажать на AdminColumnEditable::checkbox

**Comment by Lunatig** [comment]
это для AdminDisplay::table();

если поменять на AdminDisplay::datatables(); там все работает. 

ошибка возникает из-за двойных html атрибутов. которые для 
AdminDisplay::table(); вешаются и на ячейку и на элемент ColumnEditable::checkbox

хотелось бы чтобы можно было задавать атрибуты для ячейки и для элемента по отдельности. т.к. библиотека x-editable позволяет расширять возможности за счет добавления атрибутов data-

**Comment by aios** [comment]
https://demo.sleepingowladmin.ru/admin/news
Пофиксили.
