### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#714]
*en*
## Version in Composer.json
 4.99.99
## Steps to reproduce

1. Add params to config/app
2. php artisan sleepingowl:install
3.

## What is expected?
1. Succefull install

## What is actually happening?
1. Error: Call to undefined method Illuminate\Foundation\Application::bindShared()
_______________________________________________________________
*ru*
## Версия в композере
 4.99.99
## Что надо сделать что бы увидеть ошибку?

1. По мануалу добавить строки в config/app
2. Запустить  php artisan sleepingowl:install
3.

## Что должно сработать?
1. Установка админки

## Что сработало?
1. Call to undefined method Illuminate\Foundation\Application::bindShared()

********************************************
Версия Laravel 5.5
php composer.phar update делал

**Comment by aios** [comment]
@foRsxs ого не думал что ее кто то на 5.5 ставить будет. 5.5 конечно стабильная - но я бы рекомендовал подождать релиза и потом копать что же не так будет с нашим пакетом)

**Comment by foRsxs** [comment]
Я погуглил про bindShared(), пишут что давно его заменили на что-то другое

**Comment by altpoint** [comment]
бутсрап директорию проверяйте при обновлении, там структура файловая меняется с крайними версиями ругулярно, стурктуры кеша и скомпиленных списков тоже меняются

**Comment by kaizer666** [comment]
Так же столкнулся с данной проблемой. Установка на 5.5 ни в какую не хочет заводиться. Залез глубоко в код и всё равно не заработала. 2 часа мучений впустую.

**Comment by kaizer666** [comment]
@aios чистый 5.5, с нуля поставленный на чистой машине (виртуалка).

**Comment by aios** [comment]
@kaizer666 такие вы интересные. Сказано же, ждем релиза. До релиза мучайтесь сколько влезет.
