### ISSUE TITLE
для 5. Три точки входа в приложение

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#716]
1) точка входа - морда. только статика и "необходимый минимум" и "информация"
2) точка входа в приложение только для возвращаемых данных. только "данные"
в запросе к точке должно быть:
"тип возвращаемых данных": json/xml/csv/xls/txt
"требуемое": модель/секция, то, что вренёт данные
"параметры требуемого" в виде вложенного массива
3) точка входа в приложение только для внешнего взаимодействия через встроенный oauth2 сервер

возможно 3я точка не нужна, но лучше её иметь, и сделать наследником точки входа 2, но работающую от oauth2

**Comment by Butochnikov** [comment]
1. это то, что и было в 4
2. это описывается короткой аббревиатурой  API
3. точно не нужна, ибо ставим нужные пакеты и получаем то, что хотим

**Comment by h-zone** [comment]
Butochnikov, это писалось простым языком специально.
Да и API не есть точка входа в приложение. Погугли матчасть.
А вот 3-й пункт и есть API и он нужен, но не сразу.

разруливая приложение от точек входа, можно легче масштабировать это приложение.

**Comment by Butochnikov** [comment]
@h-zone простым языком для кого?
не знаю чего я там должен гугилить, но раз ты писал простым языком,  то должен был пояснить про СВОИ "точки входа".
как по мне, то 2-й пункт полностью подходит как часть API (читаем [википедию](https://ru.wikipedia.org/wiki/API). и он не обязательно должен быть только внешним или внутренним.

**Comment by daaner** [comment]
Все эти точки входа не нужны для круда. Кому надо - напишет свои
