### ISSUE TITLE
для 5. Админка от репозитория

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#717]
бытует мнение, что стоит иметь голое ядро, которое могло бы догружать "откуда-то" функциональные модули.
* например display-потомков (таблицы/деревья) итд итп.
- быть возможным настроить эти модули из активной админки. например путём одноразовой страницы настроек, которая по save выплюнет config.php в директорию конфигов.
- быть возможным управлять любыми настроками _отображения_ из админки, будь то выбор поля таблицы для отображения в дереве или создание мутаторов для вывода (только показа), но работы с полями модели в нормальном режиме
* например form-элементы
* например догружать необходимые js-ассеты по мере их востребованности. например модуль/секция требует bootstrap - выгрузим 1 раз к нам локально и работаем от локальной версии.

= это позволило бы не нагружать админку неиспользуемыми элементами (не забываем про автолоад)

**Comment by daaner** [comment]
Сова весьма тяжелая. Если сайт какой-то хайлоадный - ее лучше посадить на субдомен со своей ларой или вооще на другой сервер. Надо админка - заходим в приложение и работаем с базой. Ну а если у тебя мелкий бложек - тебя это особо не нагрузит.

**Comment by daaner** [comment]
Однако, Если ты заморочишься и накидаешь ПРов - некто в тебя тапками кидать не будет. Проверим, затестим, примем ПР.
