### ISSUE TITLE
для 5. callbackи и eventы

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#718]
Очень хотелось бы из php *секции) пробрасывать js-каллбэки в таблицы и в другие модули. для этого необходим апи.
Очень нужны (в ключе калбэков) js-события:
- до отрисовки
- отрисовка поэлементно
- после отрисовки
Это позволит мутировать view где это необходимо.
Например подкрасить строки таблиц, поменять находу 1/0/true/false на иконку чекбокса, что в разы улучшит востребованность пакета.

**Comment by Butochnikov** [comment]
а разве не проще будет использовать кастомные элементы? или менять шаблон, если нужен иной вид.
или если это js, то юзать vue компоненты, ведь надеюсь в 5-ке vue будет больше 

допуская, что возможно я не понял чего-либо, но тогда нужен пример, зачем калбэк до отрисовки? что должен менять js до отрисовки шаблона?

**Comment by h-zone** [comment]
тут над архитектурой нао сидеть, а зачастую понять решение можно только его потрогав. займёт время поиск лучшего решения.

поясняю непонятое...
например до отрисовки калбеком можно что-то проверить, и опять же, не дать отрисовать.
или от условий проверки нарисовать другое. вариантов масса.

**Comment by Butochnikov** [comment]
Без подробного примера все равно сложно понять. Если будешь описывать пример, то постарайся привести реальный, пожалуйста.

**Comment by h-zone** [comment]
Реальный пример, к сожалению, лежит в 2007 году, и под нда.
Суть. Кастомный ФВ, где "секция", а по сути - страница, описывала всё, от полей и дозволительных методов (небыло тогда в продакшенах вразумительного abstract и factory вообще), до объявления js калбеков, кои писались вручную и лежали (а фиг вам, неймспейсов тоже лебыло!)) в определённом js файле, внутри переменной, и содержали соответственно вызываемый каллбэк.
По сути, повторю, js каллбэк тогда объявлялся как JSFile::method(), дальше парсилось by php.
Сейчас можно такое решить архитектурно лучше, используя современные технологии. Да тот же jsonp или туподёргать бэкэнд за вьюшкой (совсем по простому), содержащей нужный код, который исполнится немедленно при каком-нить заумном условии.
Вам, уважаемые городить, а со мной, Butochnikov, ты даже говорить (через Костю) не стал (где-то в августе-сенябре). Обидело.

**Comment by Butochnikov** [comment]
@h-zone когда и о чем говорить, что ты до сих пор в обиде 2 года? как тогда, так и сейчас я плотно совой не занимаюсь, по причине занятости. Что вдруг ты эту тему вспомнил? Хочешь помочь, помогай.

**Comment by daaner** [comment]
Возможно потом, если прям очень будет необходимо. Закрою иссуе, чтоб не таскать по версиям
