### ISSUE TITLE
для 5. Диалоги и консоль ошибок

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#719]
Нужна консоль ошибок, которая бы перехватывала ошибки запросов к серверу (ajax) и соответственно бы рисовала там хоть что-то вразумительное вместо страницы с ошибкой wooops.

Нужны диалоги при редактировании данных, формирующиеся от рнр-секции со всеми полями, условиями, калбэками.
При этом при удачном сохранении данных (isDirty()?) обновлять ту часть данных, где расположен редактируемый объект:
- у таблиц - текущую страницу таблицы
- у дерева - перерисовывать дерево полностью
итп

**Comment by h-zone** [comment]
не любимый всеми jQuery пример https://indev.h-zone.ru/lib-appjs-v4/

**Comment by daaner** [comment]
С переходом на полное АПИ можно логировать любые знаачения будет и этот иссуе отпадет. На данный момент такое делать не целесообразно
