### ISSUE TITLE
Optional relations fix

### ISSUE THREAD

**Issue by RodionMun** [LaravelRUS/SleepingOwlAdmin#72]
Fixes optional relation of the model:

In \src\Form\FormDefault.php

change
`
$model->{$name}() instanceof BelongsTo
`
`
$model->{$name}() instanceof HasOneOrMany
`

to:

`
$model->{$name}() instanceof BelongsTo && !is_null($relation)
`
`
$model->{$name}() instanceof HasOneOrMany && !is_null($relation)
`

**Comment by butschster** [comment]
Hi. Can you create pull request?
