### ISSUE TITLE
для 5. Заведомо мультиязычный сайт от админки

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#720]
хотел предложить решение
https://github.com/in-the-beam/laravel-locale-selector
что-то подобное.
и на сайте и в админке можно было бы переключать локаль.

а там уже выходим на 2 опции работы с контентом.
* Контент от локали
* Локаль только меняет названия кнопок, интерфейса

**Comment by Butochnikov** [comment]
да, мультиязычность было бы хорошо иметь "из коробки"

**Comment by Daaner** [comment]
а разве щас ее нет? Я поставил пакет https://laravel.ru/docs/v5/localization, подключил виджет и имею мультиязычный интерфейс в админке. Правда в секциях все через транс надо. И как бы из коробки. В чем проблема?

**Comment by h-zone** [comment]
daaner, там возможность использовать мультиязычность, но не сама мультиязычность.
мультиязычность не только набор переменных на твоём языке(х), но и UI, перехватчики (мидлвари), безопасность, троттлинг от кирпича на Ф5.

**Comment by daaner** [comment]
Давай более детально. Ну или еще раз ткни в пакет / сайт, а то ссылка с топика уже 404

**Comment by daaner** [comment]
закрываю, с мультиязычностью проблем не наблюдаю
