### ISSUE TITLE
для 5. Запуск

### ISSUE THREAD

**Issue by mavsan** [LaravelRUS/SleepingOwlAdmin#722]
Сейчас при запуске сайта в сервис провайдере совы происходит полный подъем всего, что связано с совой. Даже если сова вовсе не нужна (открывается фортэнд, к примеру).

Сова должна инициализировать модели, секции, политики и прочее, что ей нужно только тогда, когда нужна именно сова.

**Comment by Butochnikov** [comment]
@mavsan а как это вообще сделать? есть примеры?

я просто вешаю админку на поддомен отдельным приложением, ибо сайт сайтом, а админка админкой.

**Comment by mavsan** [comment]
@Butochnikov, в контроллере, если прошли все проверки и попали в контроллер административной панели, то тут уже и надо поднимать все это дело.

**Comment by Butochnikov** [comment]
@mavsan это написать легко. ты видел подобное в каком-нибудь пакете?

**Comment by aios** [comment]
@Butochnikov в целом он прав. Если в секции ошибка - сайт падать не должен. по сути он говорит о том что роуты должны подгружаться первыми. А если резолв падает в админку - значит подтягиваем то что нужно.

**Comment by mavsan** [comment]
@Butochnikov да, я так делал, пока не начал пользоваться совой. В конструктор контроллера просто прописал все, что необходимо для подъема админки. Правда у меня не было столько всего много, абстракций минимум (ибо цели не было сделать одно для всего, писалось в лоб). Но все-равно, кони отдельно, люди отдельно.

В сове создать отдельный класс "SleepingOWL::eatMe()", который все, что надо зарегистрирует (алиасы, поднимет ядро админки, а роуты естественно в сервис провайдере должны регистрироваться) и вызывать его в каждом нужном контроллере, в т.ч. в контроллере пользователя, если ему нужен для чего-то свой контроллер.

**Comment by mavsan** [comment]
Я просто не знаю другого способа определить, что хотят именно админку, только контроллер, т.е. сервис провайдер отпадает.

**Comment by Butochnikov** [comment]
@aios я же не про прав или нет. я то как раз за то, чтобы не грузить админку когда не надо. Вопрос был как это грамотно реализовать. 
Естественно провайдер должен регить роуты (основные точки входа, как минимум), а вот дальше запускать все остальное, при обращении.

**Comment by daaner** [comment]
Сомневаюсь что это все же в ближайшем будущем будет реализовано без полного рефактора кода.
Нынче есть выход простой - вставляй админу у на субдомен. Тогда и овцы сыты и волки целы)
