### ISSUE TITLE
The search box is missing

### ISSUE THREAD

**Issue by KikoPalomares** [LaravelRUS/SleepingOwlAdmin#724]
*en*
## Version in Composer.json
"laravelrus/sleepingowl": "4.*@dev",
## Steps to reproduce

After update to the last version the search box is missing.

## What is expected?
![1](https://user-images.githubusercontent.com/6002391/29717598-0d605970-89b0-11e7-9b7a-d135fdc9e02c.jpg)

## What is actually happening?
![2](https://user-images.githubusercontent.com/6002391/29717605-12bb3778-89b0-11e7-84f0-4035d35859a9.jpg)

**Comment by Daaner** [comment]
datatables => datatablesAcync

**Comment by aios** [comment]
@KikoPalomares AdminDisplay::datatablesAsync()->setDisplaySearch(true);
