### ISSUE TITLE
Как отобразить свой blade с jQuery логикой?

### ISSUE THREAD

**Issue by UksusoFF** [LaravelRUS/SleepingOwlAdmin#731]
Раньше jQuery скрипты просто лежали внутри custom_view и она отдавалась как написано в доке ```AdminSection::view(view('admin.custom_view'))```.

Теперь если я правильно понимаю ее нужно вытащить в ```@stack('footer-scripts')```. Но как?

Я попробовал из контроллера возвращать ```view('block.custom_view')``` который ```@extends('sleeping_owl::default._layout.base')```
Но такой вариант ругается что нет $template.

**Comment by UksusoFF** [comment]
Как подключать кастомный js я нашел в https://github.com/LaravelRUS/SleepingOwlAdmin/issues/243

Но вопрос можно ли экстендить base blade остался.

**Comment by aios** [comment]
Можно - нужно положить в resources/views/vendor/sleepingowl/default и там как по структуре в вендоре. И у тебя переопределиться baseblade с твоего ресурса.
@UksusoFF

**Comment by UksusoFF** [comment]
@aios я немного не про то.

Но вообщем получил что хотел так:
```
<?php

namespace App\Admin\Http\Controllers;

use SleepingOwl\Admin\Http\Controllers\AdminController as Controller;

class AdminController extends Controller
{
    public function test()
    {
        return $this->admin->template()->view('test', [
            'title' => '',
            'content' => '',
            'breadcrumbKey' => '',
        ]);
    }
}
```
и шаблон положить в `resources/views/vendor/sleeping_owl/default/test.blade.php`:
```
@extends(AdminTemplate::getViewPath('_layout.inner'))

@push('content.top')
    ///
@endpush

@push('footer-scripts')
<script>
    ///
</script>
@endpush
```

**Comment by UksusoFF** [comment]
Было бы неплохо кстати если можно было бы не передавать в inner title и content:
```
{!! $content or '' !!}
```
