### ISSUE TITLE
Laravel 5.5 не работает команда php artisan sleepingowl:section:generate

### ISSUE THREAD

**Issue by hitman249** [LaravelRUS/SleepingOwlAdmin#735]
## Версия в композере
Laravel 5.5  
`"laravelrus/sleepingowl": "4.*@dev"`

## Что надо сделать что бы увидеть ошибку?

    php artisan sleepingowl:section:generate

## Что сработало?
    [ReflectionException]                                                               
    Method SleepingOwl\Admin\Console\Commands\SectionGenerate::handle() does not exist

# Также не знаю это баг или нет

## Что надо сделать что бы увидеть ошибку?

    php artisan sleepingowl:update

## Что сработало?
    Copied Directory [/vendor/laravelrus/sleepingowl/public] To [/public/packages/sleepingowl]
    Publishing complete.
    Exception: Class assets does not exist
    Skipping \KodiCMS\Assets\Facades\Assets.
    Exception: Class assets does not exist
    Skipping \KodiCMS\Assets\Facades\Assets.
    SleepingOwl Framework successfully updated.

**Comment by Ognestraz** [comment]
`composer dumpautoload`
или на крайний случай
`composer update`
Должно помочь

**Comment by hitman249** [comment]
вопрос с `php artisan sleepingowl:section:generate` решился такой командой  

    composer update && php artisan sleepingowl:update && php artisan view:clear && composer dump-autoload --optimize && php artisan optimize && php artisan ide-helper:generate && php artisan ide-helper:meta

но `php artisan sleepingowl:update` ещё не находит все классы

**Comment by aios** [comment]
Как бы и не должна.. Мы используем зависимости от KodiComponents И к сожалению на этапе рефлексии Ассеты теряются.
