### ISSUE TITLE
Exception on logout

### ISSUE THREAD

**Issue by pakhomovps** [LaravelRUS/SleepingOwlAdmin#736]
*en*
## Version in Composer.json
"4.*@dev"

## Steps to reproduce

1. login as admin
2. try to logout 

## What is expected?
1. logout

## What is actually happening?
1. MethodNotAllowedHttpException in RouteCollection.php (line 251)
_______________________________________________________________
*ru*
## Версия в композере
"4.*@dev"

## Что надо сделать что бы увидеть ошибку?

1. Залогиниться
2. Разлогиниться

## Что должно сработать?
1. должен разлогиниться

## Что сработало?
1. MethodNotAllowedHttpException in RouteCollection.php (line 251)

Solution: 
vendor\laravel\framework\src\Illuminate\Routing\Router.php line 1013
change from 
$this->post('logout', 'Auth\LoginController@logout')->name('logout');
to 
$this->get('logout', 'Auth\LoginController@logout')->name('logout');

**Comment by pakhomovps** [comment]
Solution:
vendor\laravel\framework\src\Illuminate\Routing\Router.php line 1013
change from
$this->post('logout', 'Auth\LoginController@logout')->name('logout');
to
$this->get('logout', 'Auth\LoginController@logout')->name('logout');

**Comment by Daaner** [comment]
как бы нехорошо в вендоре ковыряться, особенно если он тейлоровский. может ты ему иссуху создашь?

**Comment by aios** [comment]
@pakhomovps c get на post было переделано еще в 5.3 - так что в вендоре там точно править ничего не нужно.
