### ISSUE TITLE
Problem with AdminFormElement::select

### ISSUE THREAD

**Issue by pakhomovps** [LaravelRUS/SleepingOwlAdmin#737]
*en*
## Steps to reproduce

1. use setHtmlAttributes()

## What is expected?
1. new attributes are added to the element

## What is actually happening?
1. no new attributes
_______________________________________________________________
*ru*
## Что надо сделать что бы увидеть ошибку?

1. Использовать setHtmlAttributes() к селекту

## Что должно сработать?
1. должны появиться атрибуты при рендеринге

## Что сработало?
1. ни чего не появилось

**Comment by pakhomovps** [comment]
**Step 1**
vendor\laravelrus\sleepingowl\resources\views\default\form\element\select.blade.php line 35
<input type="hidden" {!! $attributes !!}
**Step 2**
vendor\laravelrus\sleepingowl\src\Form\Element\Select.php line 233
return ['attributes' => $this->htmlAttributesToString()] + parent::toArray() + [

**Comment by Daaner** [comment]
Почему бы не пулреквестнуть?
