### ISSUE TITLE
How to enable new value at multiselect?

### ISSUE THREAD

**Issue by fendy3002** [LaravelRUS/SleepingOwlAdmin#74]
I see that this admin using select2 components. In select2 multiselect, it can enable tag support, where you can insert new value if not exists: [https://select2.github.io/examples.html#tags](https://select2.github.io/examples.html#tags). How can I enable this?

**Comment by butschster** [comment]
Hi, i added tags support for multiselect form element.

```php
AdminFormElement::multiselect('tags', trans('core.poll.field.answers'), new \App\PollAnswer())
  ->taggable()
  ->setDisplay('title')
```
