### ISSUE TITLE
Input-select в Табах

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#741]
*ru*
## Версия в композере
 4.x-dev a332d5f
## Что надо сделать что бы увидеть ошибку?

1. Добавить во втором, третьем табе input-select
2.
3.

## Что должно сработать?
1. input-select должен разворачиваться на col-md-4

## Что сработало?
1. input-select разворачивается в 2,3 раза короче. Если убрать из класса input-select и оставить только form-control то отображается нормально, но уже без поиска а просто селект

**Comment by Butochnikov** [comment]
на актуально для новой версии
