### ISSUE TITLE
WYSIWYG в кастомном варианте

### ISSUE THREAD

**Issue by foRsxs** [LaravelRUS/SleepingOwlAdmin#742]
*en*
## Version in Composer.json
 4.x-dev a332d5f
## Steps to reproduce

1. Create custom controller and view
2. Add textarea
3.

## What is expected?
1. SimpleMDE is supposed to be work

## What is actually happening?
1. Css and js not loaded for SimpleMDE 
_______________________________________________________________
*ru*
## Версия в композере
 4.x-dev a332d5f
## Что надо сделать что бы увидеть ошибку?

1. Создать кастомный контроллер и вью
2.
3.

## Что должно сработать?
1. SimpleMDE должен работать как в обычной модели

## Что сработало?
1. Ничего просто textarea

p.s. при принудительном добавлении и запуска simpleMde, все запускается но почему-то в режиме readonly т.е. ничего нельзя изменить хотя в самом SimpleMDE нет такой опции ридонли.

**Comment by foRsxs** [comment]
Вообщем сделал так
в контроллере 
`Meta::loadPackage(['simplemde']);
 Meta::addJs('custom','/js/adsense/customMde.js',['simplemde']);`

В самом скрипте 
`$(function() {
    var simplemde = new SimpleMDE();
});`

**Comment by aios** [comment]
@foRsxs Одичалые теперь самостоятельные)))
