### ISSUE TITLE
AdminFormElement::files

### ISSUE THREAD

**Issue by opi-dopi** [LaravelRUS/SleepingOwlAdmin#743]
Было бы неплохо иметь элемент AdminFormElement::files , так как часто возникает возможность грузить не только картинки а файлы, разных форматов.
не всегда все хотят запихивать все в архив и его прикреплять, это не очень удобно постоянно его разархивировтаь.

**Comment by Butochnikov** [comment]
https://sleepingowladmin.ru/docs/form-element#file

**Comment by opi-dopi** [comment]
@Butochnikov это понятно, но мне нужен элемент на подобии imageS  где можно грузить много файлов, а не 1
скажем нужен AdminFormElement::images  но без валидации

**Comment by aios** [comment]
Будет - завтра или после завтра. запарили вы меня с ним.

**Comment by opi-dopi** [comment]
@aios привет, есть что по этому вопросу?)

**Comment by Butochnikov** [comment]
Работа с файлами будет переработана в новой версии
