### ISSUE TITLE
Invalid argument supplied for foreach(), Laravel 5.1

### ISSUE THREAD

**Issue by AratKruglik** [LaravelRUS/SleepingOwlAdmin#744]
## Версия в композере
4.*@dev

## Что надо сделать что бы увидеть ошибку?

1. Установил через `composer require "laravelrus/sleepingowl":"4.*@dev"`
2. `config\app.php` - перед `AppServiceProvider::class` прописано `SleepingOwl\Admin\Providers\SleepingOwlServiceProvider::class`
3. При `php artisan sleepingowl:install` получаю ошибку в консоли `Invalid argument supplied for foreach()`

Версия Laravel 5.1, PHP 7.1.1

Как можно побороть проблему или установить пакет?

**Comment by aios** [comment]
Обновить лару. Мы к сожалению не можем поддерживать такое колличество версий.
