### ISSUE TITLE
Incorrect pagination when setOrderCallback() with join is used

### ISSUE THREAD

**Issue by pakhomovps** [LaravelRUS/SleepingOwlAdmin#748]
*en*
## Version in Composer.json
"4.*@dev"
## Steps to reproduce

1. Add function setOrderCallback() to AdminColumn with join
```
AdminColumn::count('schedules', trans('admin.Schedule'))
           ->setOrderCallback(function (TableColumn $column, Builder $query, $order) {
                $query->select([DB::raw('count(schedules.id) as num'), 'events.*'])
                    ->join('schedules', 'events.id', '=', 'schedules.event_id', 'left' )
                    ->groupBy('events.id')
                    ->orderBy('num', $order);
            }),
```
2. try to sort this column

## What is expected?
1. Pagination is the same as before 

> Showing 1 to 10 of 14 entries

## What is actually happening?
1. Pagination is changed

> Showing 1 to 8 of 8 entries (filtered from 14 total entries)
_______________________________________________________________
*ru*
## Версия в композере
"4.*@dev"
## Что надо сделать что бы увидеть ошибку?

1. Добавить функцию setOrderCallback() к AdminColumn с join
```
AdminColumn::count('schedules', trans('admin.Schedule'))
           ->setOrderCallback(function (TableColumn $column, Builder $query, $order) {
                $query->select([DB::raw('count(schedules.id) as num'), 'events.*'])
                    ->join('schedules', 'events.id', '=', 'schedules.event_id', 'left' )
                    ->groupBy('events.id')
                    ->orderBy('num', $order);
            }),
```
2. Сортируем эту колонку в табличке

## Что должно сработать?
1. Пагинация выглядит так же как и раньше

> Showing 1 to 10 of 14 entries

## Что сработало?
1. Пагинация изменилась

> Showing 1 to 8 of 8 entries (filtered from 14 total entries)

**Comment by pakhomovps** [comment]
Возможное решение:

заменить строку:
SleepingOwlAdmin\src\Display\DisplayDatatablesAsync.php 217
на
```
if(!is_null($countQuery->getQuery()->joins)) {
                $filteredCount = DB::table(DB::raw("(" . $countQuery->toSql() . ') as t'))->count('t.id');
            } else {
                $filteredCount = $countQuery->count();
            }
```

и добавить в начале файла:
`use Illuminate\Support\Facades\DB;`

**Comment by aios** [comment]
@pakhomovps А собственно с чего ради? - Ты изменяешь мейн запрос - добавляешь туда Order логику в нее пихаешь Джоин - указываешь что он left это означает что он выберет записи по принципу whereHas - и переживаешь что у тебя пагинация сломалась? Мы строим 1 запрос - его потом каунтим - и строим пагинацию - так пагинация работала всегда - я не понимаю как у тебя можно получить два разных запроса на пагинацию и на данные.

**Comment by pakhomovps** [comment]
> я не понимаю как у тебя можно получить два разных запроса на пагинацию и на данные.

Для построения навигации, к главному запросу применяется ->count(). И выходит, когда мы сортируем таблицу по любому другому полю запрос такой:
```
select count(*)
from events
```
> 14

а когда по партнерам такой:
```
select count(*)
from events
left join partners on partners.event_id = events.id
```
>21

Вот и получается 2 разных запроса для построения навигации на одной и той же странице

а когда мы применяем еще и group_by то вообще получается несколько записей

```
select count(*)
from events
left join partners on partners.event_id = events.id
group by partners.event_id
```

> 8
5
4

и для навигации берется первое число "8". Вот и получается - при сортировке по этому полю навигация одна, а по любому другому другая.

**Comment by aios** [comment]
@pakhomovps Ладно попробую что то придумать...

**Comment by Butochnikov** [comment]
@pakhomovps этот вопрос был решен?

**Comment by daaner** [comment]
Год без ответа, да и ветки уже далеко убежали. Закрываем
