### ISSUE TITLE
Very slow datatables

### ISSUE THREAD

**Issue by fedcba98** [LaravelRUS/SleepingOwlAdmin#75]
Установил SleepingOwlAdmin, сделал CRUD для таблицы с 3000 записей.
В итоге все получилось, но таблица рисуется с AdminDisplay::datatables() 30 секунд.
Как бы многовато... Debugbar показывает  16K отрисовок вьюшек. Видимо, затык именно в этом.

datatablesAsync() работать отказались. Что-то с этим бы сделать...

**Comment by butschster** [comment]
Всмысле отказались?

**Comment by fedcba98** [comment]
А вот так:
Меняю 
`$display = AdminDisplay::datatables()` 
на 
`$display = AdminDisplay::datatablesAsync()`
Получаю: 
FatalErrorException in Display.php line 252:
Call to a member function has() on null

**Comment by enotys** [comment]
А вот так:
Меняю 
$display = AdminDisplay::datatables() 
на 
$display = AdminDisplay::datatablesAsync()
Получаю: 
FatalErrorException in Display.php line 252:
Call to a member function has() on null

Такая же фигня, не работает AdminDisplay::datatablesAsync(). Php 7.0.5, а $display = AdminDisplay::datatables()  же при овер 100 записей работает слишком медленно.

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/commit/570b004f29c78fcab0e5167d39f94b9c9d201689

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.23.106-beta

**Comment by enotys** [comment]
Теперь при загрузке крутится лоадер. а в консоле ошибка подгрузки данных. если попытаться пройти по урлу то получаем такую ошибку.

FatalThrowableError in Arr.php line 231:
Fatal error: Cannot use object of type SleepingOwl\Admin\Display\Extension\Columns as array

**Comment by enotys** [comment]
классы вот такие

use App\Cost;
use SleepingOwl\Admin\Model\ModelConfiguration;


AdminSection::registerModel(Cost::class, function (ModelConfiguration $model) {

    $model->setTitle('Расходы');
    $model->onDisplay(function () {
        $display = AdminDisplay::datatablesAsync();
        $display->setHtmlAttribute('class', 'table-primary');

        $display->setColumnFilters([
            AdminColumnFilter::date()->setFormat('Y-m-d'),
            AdminColumnFilter::text()->setPlaceholder('Источник'),
            AdminColumnFilter::text()->setPlaceholder('РК'),
            AdminColumnFilter::text()->setPlaceholder('CRM ID'),
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ]);

        $display->setColumns([
            AdminColumn::datetime('date')->setFormat('Y-m-d')->setLabel('Дата'),
            AdminColumn::text('system')->setLabel('Источник'),
            AdminColumn::text('campaign_id')->setLabel('РК'),
            AdminColumn::text('crm_id')->setLabel('CRM ID'),
            AdminColumn::custom()->setLabel('Потрачено')->setCallback(function ($instance) {
                $money = $instance->cost / 1000000;
                return $instance->cost ? sprintf("%01.2f", $money) : 0;
            }),
            AdminColumn::text('shows')->setLabel('Показов'),
            AdminColumn::text('clicks')->setLabel('Кликов'),
            AdminColumn::text('profit')->setLabel('Наценка в %'),
            AdminColumn::custom()->setLabel('Наценка в рублях')->setCallback(function ($instance) {
                $money = ($instance->profit_in_currency / 1000000);
                return $instance->profit_in_currency ? sprintf("%01.2f", $money) : 0;
            }),
            AdminColumn::custom()->setLabel('Итоговая стоимость')->setCallback(function ($instance) {
                $money = ($instance->result_cost / 1000000);
                return $instance->result_cost ? sprintf("%01.2f", $money) : 0;
            }),
            AdminColumn::datetime('updated_at')->setFormat('Y-m-d H:i:s')->setLabel('Обновлено')
        ]);
        return $display;
    });
});

и сам Cost:

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cost extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'cost';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'date',
        'crm_id',
        'system',
        'campaign_id',
        'cost',
        'shows',
        'clicks',
        'profit',
        'profit_in_currency',
        'result_cost'
    ];
}

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.23.107-beta

**Comment by enotys** [comment]
Чуть дальше ушло :)

FatalThrowableError in DisplayDatatablesAsync.php line 231:
Fatal error: Call to a member function get() on array

**Comment by enotys** [comment]
с последним фиксом DisplayDatatablesAsync.php line 231 =>  где заменен $columnFilter = array_get($this->getColumnFilters()->all(), $index);  Тест на 2995 записях, полет нормальный.

**Comment by enotys** [comment]
на ветке
https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.24.108-beta

таблица грузится, но фильтры не работают. :(

**Comment by butschster** [comment]
Есть навыки самому попробовать разобраться?

**Comment by enotys** [comment]
Попробую, не вникал еще во внутренности админки.

**Comment by enotys** [comment]
Эх. Не получается разобраться :(

**Comment by fedcba98** [comment]
Получилось раздебажить.
Поиск по всем полям заработал послле того, как в DisplayDatatablesAsync.php в методе 
`protected function applySearch(Builder $query)`
поменял строчку
`$search = Request::get('search.value');`
на 
`$search = Request::input('search.value');`

**Comment by enotys** [comment]
Ага заработал полный поиск. По калонкам поиск работает, но только при полном соответствии:

Например: тектсовое поле содержит "ya" или "yandex" если в фильтр ввести "y" То будет пустой результат, если "ya" - то все записи где "ya" но НЕ "yandex"

**Comment by enotys** [comment]
Подозреваю, что где то в недрах, где формируется запрос в БД используется field=search.value, вместо field like %search.value%

**Comment by enotys** [comment]
Ну как и подозревал если в строчке добавить 'like' то все работает как надо, просто по умолчанию, там именно строгое соответствие, и плохо что это не настраивается при создании фильтра, хотя задел на это есть:
` $columnFilter->apply($this->repository, $column, $query, $search, $fullSearch, 'like');`

**Comment by enotys** [comment]
Резюмируя если в DisplayDatatablesAsync.php методы выглядят так:

` /**
     * Apply search to the query.
     *
     * @param Builder $query
     */
    protected function applySearch(Builder $query)
    {
        $search = Request::input('search.value');
        if (is_null($search)) {
            return;
        }

        $query->where(function ($query) use ($search) {
            $columns = $this->getColumns()->all();
            foreach ($columns as $column) {
                if ($column instanceof Text) {
                    $name = $column->getName();
                    if ($this->repository->hasColumn($name)) {
                        $query->orWhere($name, 'like', '%'.$search.'%');
                    }
                }
            }
        });
    }

    /**
     * @param Builder $query
     */
    protected function applyColumnSearch(Builder $query)
    {
        $queryColumns = Request::get('columns', []);

        foreach ($queryColumns as $index => $queryColumn) {
            $search = array_get($queryColumn, 'search.value');
            $fullSearch = array_get($queryColumn, 'search');
            $column =  array_get($this->getColumns()->all(), $index);
            /** @var ColumnFilters $columnFilter */
            $columnFilter = array_get($this->getColumnFilters()->all(), $index);
            if (! is_null($columnFilter)) {
                $columnFilter->apply($this->repository, $column, $query, $search, $fullSearch, 'like');
            }
        }
    }`

То все хорошо работает и поиск и фильтры по колонкам

**Comment by butschster** [comment]
Привет, немного доработал я фильтры.
Добавил возможность указывать тип оператора используемый при поиске

```php
AdminColumnFilter::text()
    ->setPlaceholder('Источник')
    ->setOperator(\SleepingOwl\Admin\Contracts\FilterInterface::CONTAINS)
```

Список всех операторов 
```php
    const EQUAL = 'equal';
    const NOT_EQUAL = 'not_equal';
    const LESS = 'less';
    const LESS_OR_EQUAL = 'less_or_equal';
    const GREATER = 'greater';
    const GREATER_OR_EQUAL = 'greater_or_equal';
    const BEGINS_WITH = 'begins_with';
    const NOT_BEGINS_WITH = 'not_begins_with';
    const CONTAINS = 'contains';
    const NOT_CONTAINS = 'not_contains';
    const ENDS_WITH = 'ends_with';
    const NOT_ENDS_WITH = 'not_ends_with';
    const IS_EMPTY = 'is_empty';
    const IS_NOT_EMPTY = 'is_not_empty';
    const IS_NULL = 'is_null';
    const IS_NOT_NULL = 'is_not_null';
    const BETWEEN = 'between';
    const NOT_BETWEEN = 'not_between';
    const IN = 'in';
    const NOT_IN = 'not_in';
```
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Contracts/FilterInterface.php

https://github.com/LaravelRUS/SleepingOwlAdmin/commit/d354ab8aebfb3fb77935ca538e5228d3b057b1d5

**Comment by enotys** [comment]
Ага, вижу, круто. Сейчас попробуем.

**Comment by enotys** [comment]
Сорри, я наверное нуб в composer. Пытаюсь выкачать ревизию в композере вместо:
"laravelrus/sleepingowl": "4.*@dev",

записываю:
"laravelrus/sleepingowl": "dev-master#d354ab8"

Но, что то видимо я не то делаю, так как сильно много он переустанавливает и потом Admin Provider теряет, подскажите как мне конкретно эту ревизию можно правильно выкачать ?

**Comment by butschster** [comment]
`dev-development`

**Comment by enotys** [comment]
Ага, работает. Только еще бы измениния что товарищ предложил. А то полный поиск без них не работает:

> Получилось раздебажить.
> Поиск по всем полям заработал послле того, как в DisplayDatatablesAsync.php в методе 
> protected function applySearch(Builder $query)
> поменял строчку
> $search = Request::get('search.value');
> на 
> $search = Request::input('search.value');

**Comment by enotys** [comment]
Пока проверял несколько вещей заметил: 
1) не всем типам фильтров можно любой оператор задать. Например, если по дате фильтр и Contain. То отвалится с ошибкой в SQL.
2) Если в таблице 11 колонок и скажем по 4-м из них задать фильтры, то т.к. фильтры здоровые, последняя колонка просто изчезает. Может можно как то ширину фильтров задавать ?

**Comment by aios** [comment]
@enotys Ну так баг уже поправлен) с шириной я думаю сами разберетесь.

**Comment by fedcba98** [comment]
Баг с поиском (Request::get() -> Request::input()) остался.
