### ISSUE TITLE
Кнопка сброса фильтра убивает submit формы фильтров.

### ISSUE THREAD

**Issue by AratKruglik** [LaravelRUS/SleepingOwlAdmin#754]
Кнопка сброса фильтра убивает submit формы фильтров. После нажатия на сброс фильтров таблица оставляет только отфильтрованные данные и не реагирует на фильтры дальше на нажатие кнопки "Filter".

## Версия в композере
4.*@dev

## Что надо сделать что бы увидеть ошибку?

1. Набрать в фильтрах таблиц секции некий текст для поиска.
2. Нажать на кнопку сброса фильтров: http://i.prntscr.com/1kCocIA-SsykWY9mF-IXRA.png

## Что должно сработать?
1. Таблица должна принять результаты данных, которые были загружены изначально, без применения фильтров.

**Comment by aios** [comment]
Possible duplicate #740
