### ISSUE TITLE
Возможность сброса ранее выбранного значения в SelectAjax

### ISSUE THREAD

**Issue by galo4kin** [LaravelRUS/SleepingOwlAdmin#760]
## Версия в композере
"4.*@dev"

## Что надо сделать что бы увидеть ошибку?

1. При редактировании записи используется AdminFormElement::selectajax()
2. Нет возможности сбросить ранее выбранное значение на "пустое"

## Что должно сработать?
1. Рядом с выбранным ранее элементом ожидается "крестик" для сброса значения на "пусто": https://select2.org/selections#clearable-selections

**Comment by Butochnikov** [comment]
уже не актуально для новой версии
