### ISSUE TITLE
В MultiSelectAjax не отображается ранее выбранные значения

### ISSUE THREAD

**Issue by galo4kin** [LaravelRUS/SleepingOwlAdmin#763]
## Версия в композере
"4.*@dev" (4.99.99)

## Что надо сделать что бы увидеть ошибку?
1. При редактировании записи использую AdminFormElement::multiselectajax()
2. Через ->setLoadOptionsQueryPreparer() указываю предустановленные значения из БД
3. При рендеринге страницы, если смотреть html код, то внутри <select> есть предустановленные <option>, а вот визуально их нет.

## Что должно сработать?
1. Ожидается такое отображение https://qsnapnet.com/snaps/drrt2gfduudz33d

## Что сработало?
1. На данный момент такое https://qsnapnet.com/snaps/37ya7zsphc9pb9 и https://cloud.mail.ru/public/2UJy/wLSSmKxBK

**Comment by Butochnikov** [comment]
уже не актуально

**Comment by galo4kin** [comment]
А в такой версии поправлено поведение?

**Comment by Butochnikov** [comment]
@galo4kin в dev и new ветках должно работать
