### ISSUE TITLE
cancel button

### ISSUE THREAD

**Issue by astrogin** [LaravelRUS/SleepingOwlAdmin#764]
*en*
## Steps to reproduce

1.
2.
3.

## What is expected?
1.

## What is actually happening?
1.
_______________________________________________________________
*ru*
## Версия в композере
4.*@dev обновилось до версии 4.99.99
## Что надо сделать что бы увидеть ошибку?

1.AdminFormElement::select('is_recommended', 'Recommended',
                array("Not recommended","Recommended"))->required()
2.
3.

## Что должно сработать?
1.Обычный селект. До composer-update все работало

## Что сработало?
1.Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Array to string conversion (View: /var/www/resources/views/vendor/sleeping_owl/default/form/element/select.blade.php)

**Comment by astrogin** [comment]
Нашел причину. Шаблон select.blade.php был опубликован, а в вендоре новая версия этого шаблона лежала.

**Comment by Limych** [comment]
@astrogin
Название кнопки система тянет из языковый файлов.
Посмотрите на содержимое файла `vendor/laravelrus/sleepingowl/resources/lang/ru/lang.php` — по идее, у вас там должно отсутствовать запись для `button.cancel`.

**Comment by astrogin** [comment]
кнопка заработала. Незнаю почему :)
Делал composer update и снес почти все опубликованные шаблоны. Спасибо за помощь!

**Comment by Limych** [comment]
Рад был помочь. Приятного использования.
