### ISSUE TITLE
Удаление hardcoded CSS-styles

### ISSUE THREAD

**Issue by Limych** [LaravelRUS/SleepingOwlAdmin#765]
Сейчас занимаюсь портированием под SO админки CoreUI, которая написана на Bootstrap 4. А из-за различия в названиях стилей по сравнению с Bootstrap 3 постоянно приходится придумывать «костыли» для нормального отображения таких элементов как, например, счётчики объектов в пунктах меню или ControlColumn в таблицах. Во всех этих случаях названия стилей жёстко зашиты в код движка, что не есть правильно.

Прошу учитывать этот нюанс в будущих версиях и программировать так, чтобы основа никак не зависела от конкретного CSS-фреймворка. Либо, чтобы все объекты, отвечающие за формирование внешнего вида страниц можно было заменить на свои через конфиги или какие-либо ещё переопределения.

Спасибо.

**Comment by aios** [comment]
Ок пожелание учтем.
