### ISSUE TITLE
для 5. Работа с полиморфами при редактировании данных

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#767]
Вариант на том что уже сейчас есть:

1) Select натравливается на "*able_type"-field.
2) DependentSelect есть "*able_id"-field. Он должен принимать для setModelForOptions указанное в 1м селекте и соответственно грузить данные, согласно выбранной модели.

= это плоский механизм без прогнозируемого развития.

В идеале требуется нормальный механизм, позволяющий работать с реляциями выбранной модели динамически, например через if/else в каком-то, абстрактно, методе 2го селекта указывать, какие ->with() / ->scope() грузить, что даст возможность депендить данные дальше.

А ещё нужно:
- внедрить везде события!
  - до отрисовки элемента
  - до инициализации модели
  - после отрисовки элемента
  - после инициализации модели
  - каждый элемент списка, до отрисовки
  - каждый элемент списка, после отрисовки
- дать возможность писать свои методы элементам, дабы их дёргать когда и где необходимо
- дать доступ к данным элементов! чтобы не городить тонны говнокода для тупого извлечения списков для re-use в других частях кода.
- $model (для onEdit) опубликовать как protected-свойство
- для onEdit дать возможность указывать with()/scope(), чтобы можно было более гибко работать с записями (например делать проверки после получения данных и дёргать соответствующие события)

**Comment by daaner** [comment]
Частично сделано, остальное или не сильно востребовано и решается в пределах проекта или вооще не оправдано по трудозатратам. Сорян! До обновления Бутстрапа 5, выпиливания джейквери и перевода совы на вуй компоненты такой ф-ционал никто не будет делать, потом посмотрим, может будет все намного проще
