### ISSUE TITLE
для 5. динамические табы

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#768]
Интересная мысль в ключе ишью https://github.com/LaravelRUS/SleepingOwlAdmin/issues/767

В зависимости от выбранной полиморфной записи и подгруженных реляций этой модельки, динамически рисовать таб с данными

Например (высосано из пальца)

Тренинг <= Корпоративные договор <= Слушатели
Тренинг <= Групповые договор <= Слушатели

При этом оба вида договоров - разные таблицы с разной архитектурой

При выборе полиморфа-договора грузить соответственно слушателей этого типа договора. Например у слушателя есть свойство корпора или нет.

Пример снят с неба, но мысль вроде ясна...

**Comment by daaner** [comment]
Возможно потом, если прям очень будет необходимо. Закрою иссуе, чтоб не таскать по версиям
