### ISSUE TITLE
для 5. Политики секций

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#770]
*ru*

## Политики секций

Политики секций позволяют только отключать показ страницы целиком. 

Но не позволяют показать страницу редактирования с запретом на редактирование. 

Особенно интересно иметь возможность при попытке сохранения указать причину отказа
Например:
           abort('403','Этот пост имеет комментарии и по этому не может быть удален или отредактирован.  ');

Конечно можно решить через события. но уже не так красиво и удобно.

**Comment by daaner** [comment]
Это же реализовано. Если четко настроить политики то в редактирование не пустит.
Добавились методы на отображение данных, чтоб даже не показывать то, что нельзя. Вместе с методом реадонли можно добиться желаемого результата.
Если не прав - поправьте. На данный момент вопрос исчерпан
