### ISSUE TITLE
AdminColumnEditable::datetime years are limited

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#771]
Years are limited by 1970-2015, and there is no time at all. I've checked x-editable, and years are limited there as well. So it looks not usable in this form...

**Comment by aios** [comment]
@eugenem take some example for not working policy

**Comment by Butochnikov** [comment]
@aios Либа x-editable в nmp не обновлялась, но есть новая версия где это поправили.
Если планируешь обновлять ассеты, то склонируй новый x-edit.
