### ISSUE TITLE
Syntax error or access violation: 1066 Not unique table/alias

### ISSUE THREAD

**Issue by zerolimitss** [LaravelRUS/SleepingOwlAdmin#772]
I have a  self related model: 

```
 class People extends Model
{
    public function parent()
    {
        return $this->belongsTo('App\People', 'parent_id', 'id');
    }
}
```

This is my admin model config of onDisplay method:
```
    $model->onDisplay(function () {
        $display = AdminDisplay::datatablesAsync()->setColumns([
            AdminColumn::text('id')->setLabel('id'),
            AdminColumn::link('name')->setLabel('Name'),
            AdminColumn::text('parent.name', 'Parent'),
        ]);
        $display->paginate(15);
        return $display;
    });
```

The error occurs when I want to sort table by parent column and click on "Parent" name. How to fix it?

> SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'peoples' (SQL: select count(*) as aggregate from `peoples` left join `peoples` on `peoples`.`id` = `peoples`.`parent_id`)

![screenshot_8](https://user-images.githubusercontent.com/17233797/32000574-cbdef19e-b99f-11e7-8ef1-7fe885263809.png)

**Comment by aios** [comment]
@zerolimitss upgrade your admin files to Sections
https://sleepingowladmin.ru/docs/model_configuration_section
