### ISSUE TITLE
multiselect multitile

### ISSUE THREAD

**Issue by tomastovt** [LaravelRUS/SleepingOwlAdmin#773]
Здравствуйте. Есть некий код модели 

```php

use App\City;
use App\Client;
use App\Port;
use SleepingOwl\Admin\Model\ModelConfiguration;
AdminSection::registerModel(Client::class, function (ModelConfiguration $model) {
    $model->setTitle('Список Клиентов');
    $model->onDisplay(function () {
        return AdminDisplay::table()
			->setHtmlAttribute('class', 'table-primary')
			->setColumns([
				AdminColumn::checkbox(),
                AdminColumn::text('id')->setLabel('#'),
                AdminColumn::link('fio')->setLabel('ФИО'),
                AdminColumn::text('city.name')->setLabel('Город'),
				AdminColumn::datetime('created_at')->setLabel('Created'),
				AdminColumn::datetime('updated_at')->setLabel('Updated'),
			])->paginate(20);
		});
    $model->onCreateAndEdit(function() {
        return AdminForm::panel()->addBody([
            AdminFormElement::text('fio', 'Фамилия Имя Отчество')->required(),
            AdminFormElement::text('passport', 'Серия № Паспорта')->required(),
            AdminFormElement::select('city_id', 'Город')->setModelForOptions(new City)->setDisplay('name')->nullable()->required(),
			AdminFormElement::multiselect('port','Задействованные порты', Port::class)->setDisplay('name')->nullable(),
			AdminFormElement::file('contract', 'Дополнительные файлы'),
			AdminFormElement::textarea('description', 'Описание')
        ]);
    });
});
```

Элемент формы port выбирается с модели Ports
`AdminFormElement::multiselect('port','Задействованные порты', Port::class)->setDisplay('name')->nullable(),`

В свою очередь порт относится к Devices по device_id. Довольно неудобно выбирать по названию порта. Возникла идея но не вьехал пока как реализовать. Хочется выбирать по названию Устройства + название порта. Тоесть как-то так  
`AdminFormElement::multiselect('port','Задействованные порты', Port::class)->setDisplay('port.device.name' .  ' - ' . 'name')->nullable(),`

**Comment by zlodes** [comment]
@tomastovt tsya.ru. Больно же.

**Comment by anmmat** [comment]
Тоже интересует данный вопрос, уже несколько раз натыкался. Решения пока не нашел.

**Comment by tomastovt** [comment]
Здравствуйте покопался немножко в старых сообщениях - наткнулся на https://github.com/sleeping-owl/admin/issues/50. Вопрос решился
В модель Port добавляем метод аццесора и соединяем требуемые нам строки:
```
public function getTitleAttribute(){
		return "{$this->device->model} - {$this->name}";
	}
```
В модели Sleeping Owl выводим с помощью метода setDisplay: `AdminFormElement::multiselect('ports','Задействованные порты', Port::class)->setDisplay('title'),`
