### ISSUE TITLE
косяк с getValue от select'а

### ISSUE THREAD

**Issue by h-zone** [LaravelRUS/SleepingOwlAdmin#774]
пример колонки для onEdit
```
$r = AdminFormElement::radio( 'modelable_type', 'MODELS' ) )
    ->setOptions( [
        Model1::class => 'Model-1',
        Model2::class => 'Model-2',
    ] )
```
$r->getValue() всегда null

Как бы обязан вернуть валуй выбранной модели, если она предварительно выбрана и хранится в бд, нет?

Да и хотелось бы в коде хоть как-то взаимодействовать с выбранным значением. смысл наличия dependentselect начинает создавать сомнения.

**Comment by h-zone** [comment]
ну и далее, развивая мысль, - я пытаюсь писать костыль для работы с полиморфами...

**Comment by h-zone** [comment]
PSS: для dependentselect стоит дать либо новый метод либо изменить существующий setModelForOptions()
Дабы можно было так же динамически менять ему модель для данных.

это вообще решит проблему работы с полиморфами

**Comment by aios** [comment]
@h-zone дай пример где ты пытаешься достать это значение.

**Comment by h-zone** [comment]
в первом посте же пример

**Comment by aios** [comment]
@h-zone Где? и Что? это два разные вопроса.

**Comment by h-zone** [comment]
какая разница "где" !?
в onEdit положи мой пример и попытайся после объявления колонок что-то вынуть из примера (при условии что что-то задано заранее, например в бд)

что не понятного я пишу ?

**Comment by aios** [comment]
@h-zone Ну это не заработает. Инициализация элемента и  его внутренняя обработка никак не связаны между собой. На момент инициализации элемента и запихивание данной в переменную - инициализации самой секции еще нет. по сему и траблы.

**Comment by h-zone** [comment]
а в jqGrid изначально небыло подобных проблем :)
ахахахах!!!

**Comment by aios** [comment]
@h-zone jQGrid тут не причем. Это работа самой системы. Обработка на беке. Тебе любую дырку jQGridoм закрыть бы.
