### ISSUE TITLE
Вызов callback'а раньше сохранения модели в AdminFormElement::view

### ISSUE THREAD

**Issue by FlashWS** [LaravelRUS/SleepingOwlAdmin#775]
## Что надо сделать что бы увидеть ошибку?

https://sleepingowl.ru/docs/form-element#view

1. AdminFormElement::view(string $view, array $data = [], Closure $callback = null): static
2. Открыть модель для редактирования
3. Увидеть вызванный callback до сохранения модели

## Что должно сработать?
1. Callback должен вызваться после нажатия кнопки Сохранить

## Что сработало?
1. Callback вызывается при отображении формы редактирования модели

**Comment by aios** [comment]
@FlashWS честно говоря не совсем понимаю зачем этот колбек вообще нужен - если есть кастом - но в том ключе в котором он выполняется - он более логично размещен именно в этом месте. 

Для действий с моделью после сохранения или до есть events
