### ISSUE TITLE
Редирект при сохранении модели в fireEdit

### ISSUE THREAD

**Issue by FlashWS** [LaravelRUS/SleepingOwlAdmin#778]
Документация функционала https://sleepingowl.ru/docs/model_configuration#переопределение-редиректа

В случае если дочерняя модель добавляется или редактируется через fireEdit, редирект отправляет не в родительскую модель, а на общую страницу, которая не должна существовать.

**Comment by aios** [comment]
@FlashWS Больше подробностей...
