### ISSUE TITLE
I can not upload a file RAR

### ISSUE THREAD

**Issue by KikoPalomares** [LaravelRUS/SleepingOwlAdmin#78]
I can not upload a file RAR or ZIP.
`AdminFormElement::file('file_url', 'File')`
why?

**Comment by butschster** [comment]
OMG
it is probably my mistake.

https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/src/Form/Element/Image.php#L23

**Comment by butschster** [comment]
`File` form element exdends `Image`, but `image` checks files for image type
