### ISSUE TITLE
После переноса пропали стили в админке.

### ISSUE THREAD

**Issue by Ivnkara** [LaravelRUS/SleepingOwlAdmin#780]
_______________________________________________________________
*ru*
## Версия в композере
"laravelrus/sleepingowl": "4.*@dev",

## Что надо сделать что бы увидеть ошибку?
1. Перенести на другой сервер))
2. И прикрутить HTTPS сертификат

## Что должно сработать?
1. JS и CSS файлы должны нормально подключиться.

## Что сработало?
1. Не подключились стили и скрипты. В консоли сказано, типа приложение юзает https-сертификат, а файлы запрашивает по обычному HTTP. 

Как поправить?

**Comment by PhpNet** [comment]
composer dump попробуй, ну и глянь что в конфиге прописано - может там путь приложения где то с http:// захардкожен

**Comment by Ivnkara** [comment]
Странно, оно как-то само поправилось))

**Comment by kefzce** [comment]
same problem
