### ISSUE TITLE
Admin on subdomain

### ISSUE THREAD

**Issue by weijinnx** [LaravelRUS/SleepingOwlAdmin#782]
Is it possible to configure admin not on prefix, but on subdomain?
If yes, please, give me an example. Thanks!

**Comment by aios** [comment]
@weijinnx  You need to add key for config/sleeping_owl.php named 'domain' => 'admin.yourdomain.com'
Just approve link your server to that A-row in DNS and linked server (nginx, caddy, or smthg) for listen that name. Don't forget for url_prefix key.
