### ISSUE TITLE
Route name метод

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#785]
## Что надо сделать что бы увидеть ошибку?
Для роутов прописанных в админке не работает метод name

Route::get('/process/show/',   'Admin\Http\Controllers\Process\Controller@show')  
 ->name('process.show');

то есть имя роута хоть и будет светиться в списке роутов 
php artisan route:list
но будет выдаваться ошибка при попытке обращения 

## Что должно сработать?
должен работать хелпер route('process.show') 

## Что сработало?

Если роут сделать старым способом 

Route::get('/process/show/',  ['as' => 'process.show',  'uses' => 'Admin\Http\Controllers\Process\Controller@show']);
 То все прекрасно работает.

**Comment by Butochnikov** [comment]
проверял на проекте где laravel 5.5 и сова из ветки new, работает
