### ISSUE TITLE
Unknown column 'some_column' in field list

### ISSUE THREAD

**Issue by weijinnx** [LaravelRUS/SleepingOwlAdmin#787]
Собственно, при загрузку картинки, она сохраняется, но поле, которое я для этого использую, нет в базе данных (потому что я хранение всех изображений вынес в отдельную таблицу). Получаю такую ошибку:
<img width="370" alt="2017-11-23 17 22 44" src="https://user-images.githubusercontent.com/3612580/33179693-00f23e2e-d073-11e7-87ab-51df0615f817.png">
Да, все верно, поля не существует в базе, но мне же нужно указать какой-то атрибут в инпуте, а я не хочу заводить поле в таблице, чтобы оно было пустым постоянно...

**Comment by doroshenko-misha-90** [comment]
@weijinnx https://sleepingowladmin.ru/docs/form-element#api-setValueSkipped
