### ISSUE TITLE
Как сделать чтобы ide-helper видел кастомные поля?

### ISSUE THREAD

**Issue by UksusoFF** [LaravelRUS/SleepingOwlAdmin#788]
Добавил несколько кастомных полей в сервис-провайдере:
```
        $this->app['sleeping_owl.table.column']->add('datetime', DateTimeTableColumn::class);
        $this->app['sleeping_owl.table.column']->add('number', NumberTableColumn::class);
```
Как можно сделать чтобы `sleepingowl:ide:generate` их тоже увидел?

**Comment by aios** [comment]
К сожалению динамические поля не участвуют в списке генерируемых файлов - потому как нигде не подтягиваются. Интерфейсы докблоков для них не прописываются. по сему и генерация их не обрабатывает. Рефлекшны для меня пока еще чуть чуть темный лес - но думаю что это со временем решится.

**Comment by UksusoFF** [comment]
Понятно, спасибо за ответ.
