### ISSUE TITLE
JSON поля в отношениях в onEdit

### ISSUE THREAD

**Issue by PhpNet** [LaravelRUS/SleepingOwlAdmin#789]
## Версия в композере
`"laravelrus/sleepingowl": "4.*@dev"`
## Что надо сделать что бы увидеть ошибку?

1. Создать модель с отношением hasOne
2. В модели сделать JSON-поле
3. В onCreate сделать что то вроде: `AdminColumn::text('relation_name.field->json')`
4. В onEdit сделать такое же поле
## Что должно сработать?
1. В onEdit должно подставиться значение из json-поля

## Что сработало?
1. в onCreate все правильно, данные сохраняются
2. в onEdit поле не заполняется, даже с помощью setValue/setDefaultValue

**Comment by aios** [comment]
@PhpNet Поля отношений не будут редактироваться ни в json формате ни в обычном. Для этого дела подключается отдельно таб с листингом принадлежащих записей и редактируется уже из таба - и там в редактировании можно указать любое поле принадлежащее этой модели.
