### ISSUE TITLE
AdminColumn::link->setLinkAttributes() renders incorrectly

### ISSUE THREAD

**Issue by Acerbic** [LaravelRUS/SleepingOwlAdmin#793]
## Version in Composer.json
"laravelrus/sleepingowl": "4.*@dev"
(actual - 4.99.99)

## Steps to reproduce

1. Add a section with a DisplayDatatables display with a column type 'link'
2. Set custom attributes to the link like this:
 ->setLinkAttributes(['class' => 'btn btn-xs'])

## What is expected?
1. 
```html
<a class="btn btn-xs">
```

## What is actually happening?
1. 
```html
<a class=&quot;btn btn-xs&quot;>
```
The template file "default.column.link" should use {!! !!} instead of {{ }} for attributes. It is safe, since attributes builder class already uses htmlentities().

**Comment by Butochnikov** [comment]
works on branches  `dev` and `new`
