### ISSUE TITLE
Хотелось бы добавить возможность игнорировать GlobalScopes в админке.

### ISSUE THREAD

**Issue by razersergey** [LaravelRUS/SleepingOwlAdmin#794]
У себя решил проблему путем копирования класса BaseRepository в область админки и редактирования функции 
public function getQuery()
    {
        return $this->getModel()
            ->query()**->withoutGlobalScope(PublishScope::class)**
            ->with(
                $this->getWith()
            );
    }
Думаю можно написать в BaseRepository функцию setQuery или setApply и изменить немного AdminController, которую можно было бы вызывать из секции. Или добавлением в модель какой нибудь переменной в которой бы хранились названия классов глобальных скоупов, которые в админке следовало бы игнорировать.

**Comment by Butochnikov** [comment]
@razersergey а зачем тога создавать глобальный скоуп, чтобы его потом отменять?
может это неудачная архитектура приложения?

**Comment by mediaceh** [comment]
А зачем тогда в Laravel есть withoutGlobalScopes? Допустим на фронте мне нужны только опубликованные записи или записи за последний месяц. Допустим у меня эти записи привязаны к нескольким другим записям через отношения. И сколько мне всего придется дополнительно наворотить вместо того, что бы применить глобальный скоп и забыть об этом? 
Вообще, это было бы очевидно, что бы в админке не работали глобальные скопы по умолчанию. Так как я не вижу варианта при котором они могут понадобится в админке и вижу кучу вариантов почему они нужны на фронте.  А сейчас просто отрезается возможность использовать глобальные скопы.
@Butochnikov, у вас тут архитектура мозга неудачная скорее всего.  Нормальные ишу закрываете, а хуйню какую то бесползную оставляете.
