### ISSUE TITLE
After installing got public folder in context being pushed by url()

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#797]
*en*
## Version in Composer.json
        "laravelrus/sleepingowl": "4.*@dev",

Hi,

Could you help me resolve following issue (or explain it at least) - after enabling sleepingowl I've being redirected to /public context in my url. I mean that href being generated correctly (like http://some-domain/explorer/path) however I'm hitting context which contains public as a beginning of whole context (i.e. http://some-domain/public/explorer) and as result URL string being changed. Still site is working however it is not good in sense of SEO.

Could you please advice how to fix it or point me where I did something wrong.

Thank you!

**Comment by Butochnikov** [comment]
Это скорее всего к настройкам сервера, а не к админке вопрос. Хотя, я не совсем понял, что у тебя происходит.
