### ISSUE TITLE
[Laravel 5.5] Install command fails

### ISSUE THREAD

**Issue by weijinnx** [LaravelRUS/SleepingOwlAdmin#799]
*en*
## Steps to reproduce

1. Install admin via composer
2. Run `php artisan sleepingowl:install`
3.

## What is expected?
1. Successful install

## What is actually happening?
1. Method SleepingOwl\Admin\Commands\InstallCommand::handle() does not exist

Я заметил, что в команда хендлиться методом fire, если его поменять на handle - работает.

**Comment by 7immer** [comment]
I'm getting this too with version 4.99.99. Is this fixed in the dev version?
Why was this closed?
