### ISSUE TITLE
Error in view form/panel (last release)

### ISSUE THREAD

**Issue by fedcba98** [LaravelRUS/SleepingOwlAdmin#80]
После обновления до последней версии (https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/4.30.110-beta) все попадало вот здесь: https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/resources/views/default/form/panel.blade.php#L6

Говорит, мол, undefined index "header" у массива $items

**Comment by butschster** [comment]
Хм, странно, а можно пример того что в Form::panel()

**Comment by fedcba98** [comment]
Во-первых, сразу после обновления пришлось вместо setItems написать addBody
вот код:

    $model->onCreateAndEdit(function($id = null) {
        $form = AdminForm::panel();
        $form->addBody(
            AdminFormElement::columns()
                ->addColumn(function() {
                    return [
                        AdminFormElement::text('surname', 'Фамилия')->required(),
                        AdminFormElement::text('name', 'Имя')->required(),
                        AdminFormElement::text('father', 'Отчество'),
                        AdminFormElement::text('country', 'Страна'),
                    ];
                })->addColumn(function() {
                    return [
                        AdminFormElement::date('birthdate', 'Дата рождения')->setFormat('d.m.Y'),
                        AdminFormElement::select('amplua_id', 'Амплуа')
                            ->setModelForOptions(new Amplua)
                            ->setDisplay('amplua'),
                        AdminFormElement::text('height', 'Рост'),
                        AdminFormElement::text('weight', 'Вес'),
                        //AdminFormElement::hidden('user_id')->setDefaultValue(auth()->user()->id),
                    ];
                })
        );
        $form
            ->getButtons()
            ->setSaveButtonText('Сохранить данные')
            ->hideCancelButton();
        return $form;
    });

**Comment by butschster** [comment]
А версия php?

**Comment by fedcba98** [comment]
5.6.19

**Comment by fedcba98** [comment]
Да, немного странно, на домашнем компе сделал все то же самое, что ранее на рабочем - все завелось с "addBody" и после удаления закешированной вьюхи. Непонятно... Тут версия PHP 7.0.4, но как-то вряд ли наверно это с версией связано.
