### ISSUE TITLE
Ошибка при редактировании записи, в форме которой присутствут табы и выводится список записей из связанной модели.

### ISSUE THREAD

**Issue by protectedfor** [LaravelRUS/SleepingOwlAdmin#803]
Конфигурация модели может быть найдена по ссылке:
https://gist.github.com/anonymous/2e21a4c35b21ad0b0781a7ed82a4f19e

Задача:
Вывести в форме редактирования табы и в одном из табов должен отображаться список связанных моделей (родительская модель имеет связь: `hasMany`), по мимо элементов формы, таких как `text`, `image` ну и т.д.
Задача выполнена успешно, выводится все как надо.

Проблема:
При сохранении записи вылетает ошибка:
```
MethodNotAllowedHttpException in RouteCollection.php line 218:
```
Запрос идет правильным методом - `POST` и по правильному адресу. Но почему вылетает эта ошибка не понятно.
Если не выводить связанные записи в форме редактирования, то все работает. Или же если выводить форму без табов, тоже все работает.
Может кто-либо сталкивался с такой проблемой или же сам разработчик знает как ее обойти.
За любые подсказки буду очень благодарен. Так как сроки сдачи проекта горят. Заранее огромное спасибо!

**Comment by Butochnikov** [comment]
@protectedfor решил?

**Comment by vladislavtkachenko** [comment]
работает, сохраняет
