### ISSUE TITLE
Argument 1 passed to SleepingOwl\Admin\Navigation::SleepingOwl\Admin\{closure}() must implement interface SleepingOwl\Admin\Contracts\Navigation\PageInterface, instance of KodiComponents\Navigation\Page given

### ISSUE THREAD

**Issue by xadjek** [LaravelRUS/SleepingOwlAdmin#805]
*en*
## Version in Composer.json
SleepingOwl: 4.99.944
Laravel: 5.6/5.4
PHP: 7.2.2

## Steps to reproduce

1. go to /admin page

## What is expected?
1. admin page

## What is actually happening?
1. We see error: Argument 1 passed to SleepingOwl\Admin\Navigation::SleepingOwl\Admin\{closure}() must implement interface SleepingOwl\Admin\Contracts\Navigation\PageInterface, instance of KodiComponents\Navigation\Page given
_______________________________________________________________
*ru*
## Версия в композере
4.99.99
## Что надо сделать что бы увидеть ошибку?

1. Попытаться перейти в админ панель

## Что должно сработать?
1. Открыться админ панель

## Что сработало?
1. Отображается laravel ошибка: Argument 1 passed to SleepingOwl\Admin\Navigation::SleepingOwl\Admin\{closure}() must implement interface SleepingOwl\Admin\Contracts\Navigation\PageInterface, instance of KodiComponents\Navigation\Page given
Screenshot: https://ibb.co/ni0z6S

**Comment by Butochnikov** [comment]
@xadjek dev версию пробовал?

**Comment by xadjek** [comment]
@Butochnikov да, пробовал несколько версий

**Comment by Butochnikov** [comment]
@xadjek 
как мне попасть на эту ошибку?
проверил на демке, проверил на laravel 5.5-5.6, php 7.2.4

**Comment by aios** [comment]
"dev-development" там этой ошибки нет.
