### ISSUE TITLE
setSearchCallback not working with AdminColumn::custom()?

### ISSUE THREAD

**Issue by 7immer** [LaravelRUS/SleepingOwlAdmin#806]
*en*
## Version in Composer.json
4.99.99
## Steps to reproduce

1.

```
       $display->setColumns([
            AdminColumn::custom()
                 ->setLabel('Full name')
                 ->setCallback(function ($instance) {
                      return "<a href='/admin/teams/" . $instance->id . "/edit'>" . $instance->full_name . "</a>";
                })
	        ->setSearchCallback(function($column, $query, $search) {
	             $query->where('first_name', 'like', "%$search%")
                                    ->orWhere('last_name', 'like', "%$search%");
	       })
     ]);
```

2. search for either first_name or last_name in the table

## What is expected?
1. table is filtered

## What is actually happening?
1. table is not filtered
2.query shows 'first_name' and 'last_name' have not been added:
```
[
    "query" => "select * from `teams` where (`type` like ? or `job_title` like ? or `order` like ?) limit 25 offset 0"
    "bindings" => array:3 [
      0 => "%davies%"
      1 => "%davies%"
      2 => "%davies%"
    ]
```
3. Does the `if` statement on line 260 in DisplayDatatablesAsync.php account for `AdminColumn::custom()`?

**Comment by 7immer** [comment]
The method `$this->searchableColumns` on Line 260 in DisplayDatatablesAsync.php does not include AdminColumn::custom().

This should be included.

**Comment by 7immer** [comment]
Hello :)
Anyone have any thoughts on this issue?

**Comment by vAlfred88** [comment]
@7immer I can't repeat the error, I have everything working

**Comment by Butochnikov** [comment]
use `dev` or `new` version
