### ISSUE TITLE
Ошибка с элементом формы Date/Datetime при редактировании записи

### ISSUE THREAD

**Issue by deadddie** [LaravelRUS/SleepingOwlAdmin#809]
## Версия в композере
dev-development

## Что надо сделать что бы увидеть ошибку?

```php
  /**
   * @param int $id
   * @return FormInterface
   */
  public function onEdit($id)
  {
    return AdminForm::panel()->addBody([
      AdminFormElement::date('year', 'Год выпуска')
        ->setFormat('Y')
        ->setPickerFormat('Y')
        ->required(),
    ]);
  }
```
## Что должно сработать?
Должен появляться год, сохраненный в БД, например, 2016.

## Что сработало?
При вызове редактирования записи в поле вставляется текущий год. Приходится заново выбирать, иначе сохраняется это текущее значение.

![2018-03-18_02-31-30](https://user-images.githubusercontent.com/10388841/37560995-65e03ba2-2a54-11e8-8c38-8aea52af2c9f.png)

**Comment by vAlfred88** [comment]
@deadddie я не смог повторить ошибку, проверь пожалуйста, может у тебя акцессоры настроены или что-то подобное возвращает текущую дату

**Comment by deadddie** [comment]
@vAlfred88 всё обрыл.. Никаких сторонних "влияний" нет. Может подскажешь как отловить?
Заметил, что баг воспроизводится, если поле в таблице БД имеет тип YEAR(4). На TIMESTAMP всё нормально. Надеюсь, эта информация поможет.

**Comment by Butochnikov** [comment]
@deadddie удалось решить проблему?

**Comment by aios** [comment]
Ошибку к сожалению не поправить. Так как strtotime не понимает только год. Carbon::parse('2016') вернет дату с годом 2018
strtotime('2016') вернет таймстемп сегодня. Потому и не сохраняется год. Поле должно быть TimeStamp.
