### ISSUE TITLE
Сайдбар не складывается влево, не разворачиваются группы в сайдбаре

### ISSUE THREAD

**Issue by NikitaNikulin** [LaravelRUS/SleepingOwlAdmin#814]
После последнего мёржа коммита https://github.com/LaravelRUS/SleepingOwlAdmin/commit/a62182a83328878c338addc86230d4ff7e22a0b1 сайдбар перестал реагировать на клики по кнопкам

## Версия в композере
"laravelrus/sleepingowl": "dev-development",

## Что должно сработать?
1. Сайдбар складывается влево при нажатии на сендвич
2. При клике на группу в сайдбаре она разворачивается и отображается содержимое 

## Что сработало?
1. Событие по клику не срабатывает

**Comment by serh1o** [comment]
Подтверждаю, версия админки та же. Сайдбар не сворачивался с самого начала использования.

**Comment by Butochnikov** [comment]
В dev ветке вернули обратно, а так можно уже начинать пользоваться веткой new.
