### ISSUE TITLE
Error when saving with a HasOne related model

### ISSUE THREAD

**Issue by chancezeus** [LaravelRUS/SleepingOwlAdmin#82]
I came across an error whilst trying to save a related HasOne model (using text, but the problem is in NamedFormElement, so it probably affects more elements)...

On line 424:

```
$relatedModel = $relationObject->create();
$model->{$relation} = $relatedModel;
```

Tries to create the related model but (in Laravel 5) the HasOneOrMany create function required an array of attributes. Since create also automatically saves the model, this isn't going to work if any of the columns cannot be NULL and have no default value. Trying to fix it I replaced `$relatedModel = $relationObject->create();` with `$relatedModel = $relationObject->getRelated()->newInstance();`. This did fix the error generated by the create statement, but generated a problem saving the model, since the assignement actually creates a (non existing) column attribute (relationship fields are "read-only", so an assignment actually assigns it to a column). Removing the assignment generates an error in FormDefault->saveHasOneRelations, since the related row isn't actually linked to the model. Looking at the sources for Model/HasOneOrMany gave me a nice solution to the whole problem.

```
$relatedModel = $relationObject->getRelated()->newInstance();
$relatedModel->setAttribute($relationObject->getPlainForeignKey(), $relationObject->getParentKey());
$previousModel->setRelation($relation, $relatedModel);
```

The first line generates a new instance (without saving it, to make sure there are no database errors related to NULL columns)
The second line sets the ID attribute (which probably gets set anyway in the FormDefault->saveHasOneRelations, but I wanted to be sure)
The last line links the relation into the relationships array of the model.

This should work for first level relationships, I haven't actually tested it for multilevel relationships (since I have no need for it), but I suspect (with a few tweaks to FormDefault->saveHasOneRelations) they should also work as expected.

**Comment by Butochnikov** [comment]
@butschster какое решение по этому будет?

**Comment by aios** [comment]
@Butochnikov Я суть проблемы не понял - объясни пожалуйста.
