### ISSUE TITLE
Не работает меню [dev ветка]

### ISSUE THREAD

**Issue by Butochnikov** [LaravelRUS/SleepingOwlAdmin#823]
@aios 
В последних коммитах ты снова загрузил admin-app.js, который ломает работу меню.
В ветке dev мы стараемся держать актуальную и рабочую версию, т.к. множество проектов обновляется из этой ветки.

Прошу тестировать перед публикацией и постарайся исправить как можно быстрее.

**Comment by aios** [comment]
@Butochnikov  Снова это когда? на сколько давно? потому что я конкретно не работал в колобрейте уже наверно с пол года.

**Comment by Butochnikov** [comment]
@aios 5 апреля заливали уже не рабочий скрипт.
https://github.com/LaravelRUS/SleepingOwlAdmin/commits/7a4de648f94a5fdd4fcd77e6bcd3b333f5863670/public/default/js/admin-app.js

как править будем?

**Comment by Butochnikov** [comment]
close d8e7b5a649c190fbde5ffcba1bb76228146df3e3
