### ISSUE TITLE
Get rid of "filtered from __ total entries" in custom filter

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#825]
I'm trying to get following funcitonality in SleepingOwl: customer need to see only orderds which he/she made. Obviously there is customer_id in order table but when I'm using `setApply()` or `setScope()` to filter it out I'm getting following `(filtered from 11 total entries)` which are number of all orders in system. How can I get rid of it?

**Comment by aios** [comment]
@anantaramdas give please an example of section where do you want retrieve this counters

**Comment by anantaramdas** [comment]
@aios Thanks for your answer. 
I do not want to retreave - I need remove it completely.
**Use case:**
I have different customers with orders and single screen with order list. If I use above mentioned methods I'm receiving "Записи починаючи з 1 до 12 із 12 (відфільтровано з 13 записів)" (Ukrainian). I do not want user to see which is total number of orders it filtered out from.

**Comment by aios** [comment]
@anantaramdas общайся на русском - и добавься в телеграм @aioslike там опишешь мне что ты хочешь.

**Comment by aios** [comment]
```php
AdminDisplay::datatablesAsync()->setDatatableAttributes(['bInfo' => false])
```

**Comment by anantaramdas** [comment]
@aios  thanks that worked
