### ISSUE TITLE
ReflectionException  : Method SleepingOwl\Admin\Console\Commands\InstallCommand::handle() does not exist

### ISSUE THREAD

**Issue by HarmlessEvil** [LaravelRUS/SleepingOwlAdmin#827]
*en*
## Version in Composer.json
^4.99

## Steps to reproduce

1. Install Laravel 5.6
2. Run `composer require laravelrus/sleepingowl`
3. Run `php artisan sleepingowl:install`

## What is expected?
1. Sleepingowl is installed succesfully

## What is actually happening?
1. Exception is thrown: ` ReflectionException  : Method SleepingOwl\Admin\Console\Commands\InstallCommand::handle() does not exist`
_______________________________________________________________
*ru*
## Версия в композере
^4.99

## Что надо сделать что бы увидеть ошибку?

1. Установить Laravel 5.6
2. Выполнить команду `composer require laravelrus/sleepingowl`
3. Выполнить команду `php artisan sleepingowl:install`

## Что должно сработать?
1. Sleepingowl должен установиться

## Что сработало?
1. Появляется сообщение об ошибке: ` ReflectionException  : Method SleepingOwl\Admin\Console\Commands\InstallCommand::handle() does not exist`

Если я не ошибаюсь, с какой-то версии Laravel метод `fire` должен быть переименован в `handle`

**Comment by Ko3bIpb** [comment]
Добавь в composer.json вместо 4*dev строку 'dev-development', и опять composer update
