### ISSUE TITLE
Невозможность удалить первую запись при display:tree в Табах

### ISSUE THREAD

**Issue by Ko3bIpb** [LaravelRUS/SleepingOwlAdmin#828]
Создал табы в модели:
Модель товаров
    public function onEdit($id)
    {   

        $formPrimory = AdminForm::panel()->addBody([
         AdminFormElement::text('name','Название')->required(),
                AdminFormElement::number('price','Цена')->required(),
                AdminFormElement::number('oldprice','Старая цена'),
                ---Тут еще куча полей---
        ]);

        $tabs = AdminDisplay::tabbed();

        $tabs->appendTab($formPrimory, 'Товар');

        if($id){
            $instruct = AdminForm::panel()->addBody([
                AdminSection::getModel(\App\InstructProduct::class)
                             ->fireDisplay(['params' => ['Products' => $id]])
                             ->setParameter('product_id', $id)
            ]);

            $characteristics = AdminForm::panel()->addBody([
                AdminSection::getModel(\App\Charvalue::class)
                             ->fireDisplay(['params' => ['Products' => $id]])
                             ->setParameter('product_id', $id)
            ]);

            $tabs->appendTab($characteristics, 'Характеристики');
            $tabs->appendTab($instruct, 'Инструкции');
        }

        
        

        return $tabs;
    }
Модель Инструкций(Модель характеристик аналогична)
public function onDisplay($params = null)
    {
        $display = AdminDisplay::tree(OrderTreeType::class)->setValue('instruct');

        if($params){
            if (!empty($params['Products'])) {
                $display->setScopes(['Products' , $params['Products']]);
            }
        }

        return $display;
    }

Когда тыкаю на delete первой записи инструкции вылетает NoMessage. Хотя другие удаляются прекрасно.
Если зайдем в консоль то видим, что по какой то причине первая запись не имеет формы удаления:
![default](https://user-images.githubusercontent.com/26626453/39807200-a6e0d784-53b6-11e8-98ae-6f1630f06025.png)
_____________________________________________________________________________________________
Кто сталкивался с таким, или в чем может быть проблема?

**Comment by aios** [comment]
@Ko3bIpb исправим

**Comment by aios** [comment]
@Ko3bIpb Единственное о чем попрошу - используя данные демо, мог бы ты запулить пример сего действа в саму демку - дабы остался для людей кто с этим столкнется?

**Comment by HarmlessEvil** [comment]
Такая же ошибка и с `AdminDisplay::table()` при использовании её в табах

**Comment by HarmlessEvil** [comment]
@aios я воспроизвёл баг (если нужно) вот здесь https://github.com/HarmlessEvil/demo

**Comment by aios** [comment]
@HarmlessEvil можешь сделать PR в демо совы?

**Comment by Lunatig** [comment]
на следующей неделе выделю денек и обновлю демо совы до dev-new ветки и 5.6 лары.

**Comment by aios** [comment]
@Lunatig не утруждай себя
я сам это сделаю.

**Comment by HarmlessEvil** [comment]
@aios я вижу, вы за меня PR уже сделали)

**Comment by aios** [comment]
@HarmlessEvil мы на "ты")

**Comment by aios** [comment]
@Ko3bIpb @HarmlessEvil Проблема оказалась банально проста. Все что находится в onEdit оборачивается в форму редактирования. Потому первая форма не рендерится, то есть проблема чисто V8 - она не хочет рендерить доп форму внутри формы. 

Что делать с этим я к сожалению пока не знаю) Так что надо будет отложить до лучших времен.

**Comment by daaner** [comment]
![image](https://user-images.githubusercontent.com/9641698/62944743-07a6a400-bde6-11e9-8b23-3a656e77d767.png)
Проблема не замечена
