### ISSUE TITLE
How to update a pivot with custom column

### ISSUE THREAD

**Issue by xcaptain** [LaravelRUS/SleepingOwlAdmin#83]
```php
AdminFormElement::multiselect('companies', 'Companies')->setModelForOptions(new Company)->setDisplay('title'),
```
This line will update the `company_contact` table, How can I add a custom column in `company_contact` and set the value every time I submit the multiselect form, thanks.

**Comment by de-raaf-media** [comment]
I'm looking for this as well. This would require another way of adding multiple items in the front-end. Vers usefull.

**Comment by PatricB** [comment]
I archived this by defining [Accessors & Mutators](https://laravel.com/docs/5.2/eloquent-mutators) to the Model. 
You would add to your Company Model something like:
```
public function getSourceAttribute()
    {
        return $this->contact->pivot->source;
    }
```
this for belongsTo relations. For others you have go may be through all related models.

Know the **Mutator**. There you can act simlliar:

```
public function setSourceAttribute($sources)
    {
        $this->sources()->detach();
        if ( ! $sources) return;
        if ( ! $this->exists) $this->save();

        $this->sources()->attach($sources);
    }
```

Know you can access the pivot column as attribute of the company model and get or set the attribute related to the company model.

Hope this is helpfull.

**Comment by de-raaf-media** [comment]
I don't think this should be closed yet. How would you do edit the custom column from the admin?

**Comment by PatricB** [comment]
You should handle it like a normal attribute. In this case it would would be called "source" 
set[name]Attribute($x) 
get[name]Attribute()
