### ISSUE TITLE
Move IDE Helper Generator to dev dependency

### ISSUE THREAD

**Issue by UksusoFF** [LaravelRUS/SleepingOwlAdmin#832]
Он совершенно не нужен на production. В документации этого пакета его предлагается реквайрить как dev зависимость:
```composer require --dev barryvdh/laravel-ide-helper```

**Comment by zlodes** [comment]
Ага, только вот есть класс
`SleepingOwl\Admin\Console\Generator`, который наследуется от `Barryvdh\LaravelIdeHelper\Generator`.

Зачем так было сделано — не ясно.

**Comment by UksusoFF** [comment]
@aios ну идехелпер тоже не нужен на проде же.

**Comment by zlodes** [comment]
@aios, возможно, стоит генератор вынести в отдельный пакет и подключать как dev-dependency.
А он уже будет зависеть от оригинального ide-helper.

**Comment by UksusoFF** [comment]
Можно просто вот тут не регистрировать команду с ним: https://github.com/LaravelRUS/SleepingOwlAdmin/blob/ba4ae1363fa063c529ad9c8bb4957104db5a6dbe/src/Providers/SleepingOwlServiceProvider.php#L82
Если ```!class_exists(\Barryvdh\LaravelIdeHelper\Generator::class)```

**Comment by daaner** [comment]
Это уже поправлено https://github.com/LaravelRUS/SleepingOwlAdmin/blob/ba4ae1363fa063c529ad9c8bb4957104db5a6dbe/src/Providers/SleepingOwlServiceProvider.php#L67

**Comment by UksusoFF** [comment]
@daaner только вот он все еще в require:
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/composer.json#L46
