### ISSUE TITLE
getView setView getPlacement setPlacement как trait

### ISSUE THREAD

**Issue by Lunatig** [LaravelRUS/SleepingOwlAdmin#835]
Создал 2 трейта

ElementViewTrait и ElementPositionTrait и их повесил на namespace 

SleepingOwl\Admin\Display\Extension\ColumnsTotal 

https://github.com/LaravelRUS/SleepingOwlAdmin/commit/28cdbb3ebc47ebddfa61e6675711920a8e80d514

**Comment by aios** [comment]
Понял - норм тема.
@Lunatig опишешь что там у тебя с плейсментами не получилось?

**Comment by Lunatig** [comment]
@aios 
Берем стандартную дататаблу.

$table =  AdminDisplay::datatablesAsync()

Добавляем Total строку
$table->setColumnsTotal([
            'Total: ',
            '<income_total>', 'labuda', 10
        ],
            $table->getColumns()->all()->count() +1
        );

//Перемещаем ее в подвал. по умолчанию она в header.
$table->getColumnsTotal()->setPlacement('table.footer');

в результате она пустая. 

Если в подвал не переносить все нормально.

**Comment by vladislavtkachenko** [comment]
fixed
