### ISSUE TITLE
Display Tree

### ISSUE THREAD

**Issue by bulba-man** [LaravelRUS/SleepingOwlAdmin#84]
Не работает перетаскивание при использовании такого отображения
делал как тут http://demo.sleepingowladmin.ru/admin/pages
установил Baum, заполнил таблицу как положено.

таблица такая же, как и миграция на демо сайте, модель админки для админки так же соответствует демо сайту.

похоже, что чего-то не хватает. т.к. в демо репозитории лежит совсем не то, что есть на сайте

**Comment by Baster** [comment]
Та же проблема. Устанавливал пару дней назад работало перетаскивание, сейчас пишет: 
```
Uncaught TypeError: Cannot read property 'fn' of undefined jquery.nestable.js:462 
Uncaught TypeError: $(...).nestable is not a function categories:98
```

**Comment by butschster** [comment]
Попробуйте удалить папку `public/packages/sleepingowl` и выполнить `php artisan sleepingowl:install`

**Comment by goodmove** [comment]
мне не помогло
может быть дело в том что nestable.js подключается раньше всех? и где поменять очередь или зависимость очереди?

<script src="http://services.loc/packages/sleepingowl/default/libs/nestable/js/jquery.nestable.js"></script>
<script src="http://services.loc/packages/sleepingowl/default/js/libraries.js"></script>

**Comment by goodmove** [comment]
Это помогло, правда пришлось править в папке vendor, дописал зависимость от libraries

`PackageManager::add('nestable')
    ->css(null, resources_url('libs/nestable/css/jquery.nestable.css'))
    ->js(null, resources_url('libs/nestable/js/jquery.nestable.js'), ['jquery', 'libraries']);`

**Comment by bulba-man** [comment]
спасибо, это помогло
но это плохое решение:)

**Comment by butschster** [comment]
@bulba-man что именно плохое решение? Периодически происходит обновление css и js и при обновлении система не обновляет эти файлы и их нужно вручную обновлять

**Comment by bulba-man** [comment]
@butschster  я про то, что при обновлении затерётся  assets.php

**Comment by butschster** [comment]
А он затерся?

**Comment by goodmove** [comment]
@butschster Ошибка была в том, что nestable.js подключался перед libraries.js, можно было не обновлять а просто в вендоре в assets.php добавить зависимость от libraries, поэтому @bulba-man  и говорит, что не хорошо вендор править

**Comment by butschster** [comment]
Не совсем понимаю ошибку, на демо сайте стоит последняя версия и также локально, проблема не воспроизводится

**Comment by goodmove** [comment]
я так понимаю jquery находиться в файле libraries.js

а в assets.php зависимость от jquery

`PackageManager::add('nestable')
    ->css(null, resources_url('libs/nestable/css/jquery.nestable.css'))
    ->js(null, resources_url('libs/nestable/js/jquery.nestable.js'), ['jquery']);`

поэтому nestable.js у нас подключался в документе выше файла libraries.js, у вас в демо он как положено подключен ниже libraries.js

и в консоле мы видели типичную ошибку
`Uncaught TypeError: Cannot read property 'fn' of undefined jquery.nestable.js:462 
Uncaught TypeError: $(...).nestable is not a function categories:98`

поэтому я предложил прописать зависимость от libraries
