### ISSUE TITLE
Не работает setScopes|push

### ISSUE THREAD

**Issue by TheArdent** [LaravelRUS/SleepingOwlAdmin#847]
*ru*
## Версия в композере
dev-development ac98f91
## Что надо сделать что бы увидеть ошибку?

1.Передаем скоуп

```
$skins = \AdminSection::getModel(ChestSkin::class)
                        ->fireDisplay(['scopes' => ['withChest' => $id]]);

$skins->setParameter('chest_id', $id);
$tabs[] = AdminDisplay::tab($skins)->setLabel('Скины');
```

2.Принимаем скоуп в другой секции
```
public function onDisplay($scopes = [])
    {
        $table = AdminDisplay::datatablesAsync();
        if ($scopes) {
//              Оба варианта не работаю
//              $table->setScopes($scopes);
//              $table->getScopes($scopes)->push($scopes);
        }

        $table->setColumns([
            AdminColumn::text('chest.name_ru', 'Сундук'),
            AdminColumn::text('skin.name', 'Скин'),
            AdminColumn::text('percent', 'Шанс выпадения(%)')->setWidth(150),
        ]);

        return $table;
    }

```
## Что должно сработать?
Скоуп

## Что сработало?
Ошибка - 

> Method ...Builder::1 does not exist

**Comment by Lunatig** [comment]
Красота. Теперь вместо скоупов вставляетcя WHERE по полю имени скоупа. 

AdminSection::getModel(Log::class)->fireDisplay(['scopes' => ['inDocument' , $id]])

....

 public function onDisplay($scopes = [])
    {
        if($scopes){
            $table->setScopes($scopes);
        }


Получаем ошибку
 Column not found: 1054 Unknown column 'inDocument'
