### ISSUE TITLE
Новые типы отображения данных. (Вопрос)

### ISSUE THREAD

**Issue by DJZT** [LaravelRUS/SleepingOwlAdmin#866]
Планируется ли добавление новых типов отображения данных помимо таблиц и дерева? К примеру: календарь, список (Не таблица (Правда не знаю зачем :-))). Больше интересует календарь.
Есть некоторые наоработки по календарю но с зависимостями.
https://fullcalendar.io/
https://github.com/maddhatter/laravel-fullcalendar

**Comment by daaner** [comment]
А нужно ли такое на постоянной основе?
Ели бы хотя бы 10% пользователей совы нуждались бы в этом сильно - запилили бы уже давно

**Comment by aios** [comment]
@daaner К сожалению нужно. И такое будет.
