### ISSUE TITLE
Создание формы в форме

### ISSUE THREAD

**Issue by buchkovsky** [LaravelRUS/SleepingOwlAdmin#867]
Есть задача, управление morphTo релейшеном внутри модели, т.е. нужно создавать, удалять и редактировать связь из дочерней модели, возможно ли это реализвать? Я у уже подумывал сделать форму в форме, и кастом элемент с коллекцией форм ( т.е. список релейшенов представленных в виде форм). Возможно ли сделать аякс отправку и валидацию формы? Конечно все это можно реализовать кастомно, но не очень хотелось бы городить лишние методы

**Comment by Lunatig** [comment]
Аяксом не сложно сделать отправку, но вот валидацию, только на кастомном контроллере. 

Есть без аякса. 
https://www.youtube.com/watch?v=BeM8UDJjlXc 

или можно таблицей просто из дочерней секции и использовать Editable Columns

**Comment by buchkovsky** [comment]
да, я тоже так думал сделать, но тогда остается вопрос добавление новой связи, т.е. с редактированием можно решить проблему. Просто добавить таблицу в форму и использовать инлайн редактирование, но вот создать новую связь аяксом я так понимаю нельзя

**Comment by buchkovsky** [comment]
спасибо, сейчас более детально изучу

**Comment by Lunatig** [comment]
ну я например использую для этого написаный компонент vue 

<template>

    <div :id='this.id' class="modal fade bs-example-modal-lg"  role="dialog" >
        <div class="modal-dialog modal-lg" role="document" :style="css">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{{ title }}</h4>
                </div>
                <div class="modal-body">
                    <slot></slot>
                </div>
            </div>
        </div>
    </div>

</template>

<script>
    export default {

        props:[ 'id', 'title', 'css' ],          

    }
</script>

**Comment by buchkovsky** [comment]
ага, ну т.е. кастом. Я тоже уже сел делать кастом, думал мало ли просмотрел какой функционал.

**Comment by Lunatig** [comment]
1) сделать компонент модального окна бутстрапа.
2) передать туда fireCreate(); $tabContent[] = '<modal id=myid>'.AdminSection::getModel(Property::class)->fireCreate.'</modal>'
3) вызывать можно стандартной кнопкой 
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
ее можно запихнуть перед таблицей $tabContent[] или внутрь таблицы заменив вид или вместо экшенов. 
4) отправка данных. тут поможет jquery-form ajaxSubmit/
Но валидации не будет.

**Comment by buchkovsky** [comment]
да, так и думал, впринципе он же при создании модели в любом случае будет валидировать, соответвенно можно расшириться и при аякс реквесте переопределить дисплей для выдачи ошибок в json , ну и уже исходя из ответа проставить их
