### ISSUE TITLE
Image Cropping and Resizing

### ISSUE THREAD

**Issue by Baster** [LaravelRUS/SleepingOwlAdmin#87]
Как переопределить стандартную массовую загрузку изображений? И вопрос еще, при редактировании или добавлении если нажать remove на картинке, то она исчезнет, но вот физически останется, это нормальное поведение?

**Comment by butschster** [comment]
Привет, массовую ты имеешь виду хранение в одном поле через запятую?

**Comment by Baster** [comment]
Да именно, просто я только начал пользоваться этой админкой, а в документации не нашел.

**Comment by butschster** [comment]
Ну вообще не очень удачно реализована работа с файлами, я думал немного ее переделать

**Comment by Baster** [comment]
Я в старой документации нашел " добавить метод setImage() в модель", этот способ еще работает?

**Comment by butschster** [comment]
Нет, это ни на что не повлияет. Вообще работа с файлами не совсем правильно организована и при удалении файла сама модель ничего ни делает. Удаление файлов можно организовать через мутаторы

**Comment by NobleKayHara** [comment]
Same question but i only know english :(

**Comment by NobleKayHara** [comment]
Oh i used a translator, seems like uploading and resizing hasn't been implemented? If not, can you point me in the right direction to implement cropping and resizing of images @butschster

**Comment by butschster** [comment]
Hi. I'm working now with this feature

**Comment by NobleKayHara** [comment]
Okay, thanks. Waiting patiently :D

**Comment by Baster** [comment]
А не подскажите где поменять стандартное название папки public при сохранении файла, а то на хостинге это имя домена.

**Comment by butschster** [comment]
@Baster попробуй https://laracasts.com/discuss/channels/general-discussion/where-do-you-set-public-directory-laravel-5

**Comment by goodmove** [comment]
@butschster 

> Удаление файлов можно организовать через мутаторы

Как через мутатор организовать ресайз понятно, а вот удаление так корректно сделать?

`public function setImageAttribute($image)
    {
       if($image){
            $this->attributes['image'] = $image;
            $img = Image::make($image);
            $img->resize(320, 240);
            $arr = explode('.', $image);
            $img->save($arr[0].'320x240.'.$arr[1]);
       }else{
           if($this->image){
               unlink($this->image);
               $this->attributes['image'] = null;
               $this->update($this->attributes);
           }
       }

    }`

**Comment by butschster** [comment]
Попробуй использовать мой трейт https://github.com/butschster/SimpleSite/blob/master/app/Traits/Upload.php

Вот пример указания полей, которые он будет воспринимать (`file` для файлов, `image` для изображений)
https://github.com/butschster/SimpleSite/blob/master/app/Photo.php#L53

Если тип изображение, то можно указать правила для ресайза https://github.com/butschster/SimpleSite/blob/master/app/Photo.php#L61

Ну и все, передаешь в поле `$request->file('field_name')`, ну или проще говоря `Illuminate\Http\UploadedFile` и дальше все само разрулится

**Comment by goodmove** [comment]
спасибо, удаление файла происходит, а нарезка нет, причем ошибок не выдает никаких

**Comment by butschster** [comment]
Пакет `intervention/image`  установлен?

**Comment by goodmove** [comment]
да, и сделал все, как в примерах выше

**Comment by goodmove** [comment]
ошибку нашел, upload_file надо было указать как поле в админ модели, но теперь ошибка

Type error: Argument 1 passed to App\Models\Service::setUploadFileAttribute() must be an instance of Illuminate\Http\UploadedFile, string given
