### ISSUE TITLE
Запоминание фильтров в AdminDisplay::datatables

### ISSUE THREAD

**Issue by kundius** [LaravelRUS/SleepingOwlAdmin#874]
*ru*
## Версия в композере
4.*@dev

## Что надо сделать что бы увидеть ошибку?

1. Добавить фильтр в AdminDisplay::datatables
2. Отфильтровать результат на странице
3. Обновить страницу

## Что должно сработать?

После обновления состояние фильтрации должно либо остаться, либо сброситься.

## Что сработало?

Сейчас сами фильтры сбрасываются, но данные в таблице отображаются с последней фильтрации.

**Comment by NikitaNikulin** [comment]
Тоже наталкивался на такую проблему. Приходится принудительно через js при подгрузке таблицы сбрасывать фильтры. Идеально было бы оставлять значения в фильтрах и фильтрацию при обновлении страницы, чтобы было видно по каким параметрам отфильтровано

**Comment by aios** [comment]
@kundius @NikitaNikulin ок пофикшу.

**Comment by daaner** [comment]
спасибо, канеш, за `localStorage.clear();` нужно чуть по другому
