### ISSUE TITLE
Ошибка при загрузке большого изображения в элементе Image

### ISSUE THREAD

**Issue by ignorantic** [LaravelRUS/SleepingOwlAdmin#875]
## Версия в композере
4.*@dev
## Что надо сделать что бы увидеть ошибку?
1. При редактировании записи в элементе Image попытаться загрузить изображение размером более 1.2 М.

## Что должно сработать?
1. Изображение должно успешно загрузиться.

## Что сработало?
1. Сервер возвращает ошибку 500.
2. В логах появляется запись:
[2018-06-16 19:51:26] local.ERROR: ErrorException: getimagesize(): Read error! in /home/user/project//vendor/laravelrus/sleepingowl/src/Form/Element/Image.php:44

**Comment by vladislavtkachenko** [comment]
Такая ошибка была на хостинге, так и не разобрался с чем связано. На локалке все ок
