### ISSUE TITLE
Кастомизация групповой обработки данных с помощью Action

### ISSUE THREAD

**Issue by FlashWS** [LaravelRUS/SleepingOwlAdmin#884]
## Необходима групповая обработка данных с помощью Action
[https://sleepingowladmin.ru/docs/columns#action](https://sleepingowladmin.ru/docs/columns#action)

На данный момент action передает список id'ков без дополнительных параметров.

1. Необходимо кастомизировать диалоговое окно перед отправкой данных:
1.1. Заменять текст вопроса перед отправкой
1.2. Добавлять кастомные поля в диалоговое окно и передавать их вместе c ID'ками
2. Делать релоад таблицы после успешной обработки или возвращать ошибку, если таковая произошла.

**Comment by Lunatig** [comment]
создавай вуй компонент. запихивай тег в нужное тебе место в таблице. 
![image](https://user-images.githubusercontent.com/3226171/42514772-d9494b2a-8462-11e8-8aa7-82daa66dfc3f.png)
