### ISSUE TITLE
Неправильные namespace

### ISSUE THREAD

**Issue by Nakuro** [LaravelRUS/SleepingOwlAdmin#892]
## Что надо сделать что бы увидеть ошибку?

Внутри файла src/Display/Column/Order.php на 33 и 44 строчке неправильно указан неймспейс!

Вместо 'SleepingOwl\Admin\Http\Controllers\DisplayColumnController'
Должно быть!
'SleepingOwl\Admin\Http\Controllers'

**Comment by aios** [comment]
Обновись на dev-new
