### ISSUE TITLE
Пропадает секция с фильтрами в табах, если туда же добавить кнопки (Actions)

### ISSUE THREAD

**Issue by NikitaNikulin** [LaravelRUS/SleepingOwlAdmin#895]
## Версия в композере
dev-new
## Что надо сделать что бы увидеть ошибку?

1. Создать форму с табами
2. Добавить в таб в форме одной модели секцию другой модели 
(используя AdminSection::getModel(Test::class)->fireDisplay(['scopes' => ['test_id' => $id ]))
3. В секцию модели Test добавить фильтрацию по колонкам (AdminColumnFilter::text()) и кнопки Actions ($display->getActions()->setView())

## Что должно сработать?
1. В форме первой модели в текущем табе должна отобразиться секция модели Test с фильтрацией и кнопками Actions в хедере

## Что сработало?
1. Отображаются только кнопки Actions, блока фильтраций нет

**Comment by daaner** [comment]
Думаю ты напутал вьюшки
![image](https://user-images.githubusercontent.com/9641698/73301920-69d05580-421c-11ea-9cb1-f00308f21e9f.png)
![image](https://user-images.githubusercontent.com/9641698/73302041-9f753e80-421c-11ea-9468-421f744415d0.png)

**Comment by daaner** [comment]
Хотя я не использовал файр. Скинешь код - проверю и поправлю

**Comment by daaner** [comment]
с файр тоже работает норма
![image](https://user-images.githubusercontent.com/9641698/73302405-44901700-421d-11ea-8948-a38a5ddc316e.png)
