### ISSUE TITLE
Не устанавливается значение поля в JSON полях

### ISSUE THREAD

**Issue by net0** [LaravelRUS/SleepingOwlAdmin#898]
## Что надо сделать что бы увидеть ошибку?

1. AdminFormElement::text('options->test');
2. Записываем значение, сохраняем
3. Поле пустое
4. Идем в базу - там все хохранилось, т.е. не выводится

Если записать так:
AdminFormElement::text('options->test')->setDefaultValue('');
Опппа, появилось сохраненное значение

**Comment by aios** [comment]
@net0 запуль пожалуйста в демку свой пример - я посмотрю что не так.
