### ISSUE TITLE
AdminDisplay::tree + alias bug

### ISSUE THREAD

**Issue by pinguinjkeke** [LaravelRUS/SleepingOwlAdmin#90]
If I'm using nested $model alias, than reorder not working
`AdminSection::registerModel(ProductCategory::class, function (ModelConfiguration $model) {
    $model->setTitle('Категории')
          ->setAlias('catalog/categories');`

http://sitename/admin/catalog/categories/reorder 404 Not found

And it's working with `$model->setAlias('categories')`

**Comment by butschster** [comment]
Fixed
