### ISSUE TITLE
'{{ }}' breaks AdminFormElement::textarea

### ISSUE THREAD

**Issue by eugenem** [LaravelRUS/SleepingOwlAdmin#900]
version: latest 4.*@dev

I simply added this:

`            AdminFormElement::textarea('template', 'Template'),
`

field value is:

` {{hi}}
`

When try to open it in editor, I see it for a short moment, and then screen is completely cleared.

I've tried with 'hi' value, and it works fine.

So it looks like any '{{ }}' breaks the editor completely...

There are no errors at console unfortunately.

It works fine with ::text editor, but my real values are too long (handlebars html templates). And ckeditor isn't suitable, as I need raw html there.

**Comment by aios** [comment]
@eugenem try please it on the latest stable version ([5.6.4](https://github.com/LaravelRUS/SleepingOwlAdmin/releases/tag/5.6.4) on that time)

**Comment by eugenem** [comment]
seems to work the same

**Comment by vkn999** [comment]
баг актуален для ветки bs4

**Comment by daaner** [comment]
в девке поправлено, в мастер переедет коммит после тестов
