### ISSUE TITLE
Multiselect very slow, what about using ajax?

### ISSUE THREAD

**Issue by s6carlo** [LaravelRUS/SleepingOwlAdmin#91]
In my application, using sleeping-owl/admin package, multiselect is very slow because the option element has something like 20000 items. Is it a common problem? I think it could be solved using ajax and jquery to dynamically load options when the user start typing. 
Has someone else the same problem?

**Comment by s6carlo** [comment]
Any update about this feature? I am switching from sleeping-owl/admin v3 to this new project, but the main problem is always related to Multiselect forms.
The issue is related to #69

**Comment by aios** [comment]
Already has MultiselectAjax and SelecAjax Elements

**Comment by s6carlo** [comment]
Is there an example of using MultiselectAjax and SelecAjax ?

**Comment by aios** [comment]
@s6carlo has in docs but only russian 
thats like main multiselect
```php
AdminFormElement::multiselectajax('somefield', 'SomeLabel')
                    ->setModelForOptions(Somemodel::class)
                    ->setDisplay('path_name'),
```
