### ISSUE TITLE
Версия 5.6 не совместима с php 7.1, 7.2

### ISSUE THREAD

**Issue by vkn999** [LaravelRUS/SleepingOwlAdmin#919]
*ru*
## Версия в композере
composer require laravelrus/sleepingowl:5.6

laravel 5.6.33
php 7.2.8
## Что надо сделать что бы увидеть ошибку?

1. Начать процесс установки: composer require laravelrus/sleepingowl:5.6

## Что должно сработать?
1. Инициализация процесса установки пакета

## Что сработало?
1. [InvalidArgumentException]                                                                                        
  Package laravelrus/sleepingowl at version 5.6 has a PHP requirement incompatible with your PHP version (7.2.8.0)  

До этого было протестировано с версией PHP 7.1* - результат тот же.
Установка производится на чистую лару (установлен только debugbar v. 3.1.5)&

**Comment by aios** [comment]
к сожалению тестировал и на 7.2 и на 7.1 становится нормально.
@Lunatig @Butochnikov или кто то может подтвердить?

**Comment by aios** [comment]
https://travis-ci.org/LaravelRUS/SleepingOwlAdmin/builds/415086777

**Comment by Butochnikov** [comment]
@aios я 5.6 не тестировал, но версия 4.9 у меня, везде, на 7.1 пашет. На 7.2 не знаю, так как нет смысла поднимать выше чем версия самой низкой, поддерживаемого фреймворка.

**Comment by aios** [comment]
@vkn999 весь лог ошибки скинь плиз.
