### ISSUE TITLE
Не показывает заголовок для кастомной колонки

### ISSUE THREAD

**Issue by anantaramdas** [LaravelRUS/SleepingOwlAdmin#926]
*ru*
## Версия в композере
5.6.4
## Что надо сделать что бы увидеть ошибку?

1. Делаем кастомное поле
2. Ставим лейбл
3. В таблице заголовка нет

## Что должно сработать?
1. Показаться заголовок

## Что сработало?
Смотрю что в конструкторе Custom.php некорректный вызов родительского конструктора NamedColumn.php:

В Custom.php:
public function __construct($label = null, Closure $callback = null)
    {
        parent::__construct($label);
        if (! is_null($callback)) {
            $this->setCallback($callback);
        }
    }

В NamedColumn.php:
    public function __construct($name, $label = null, $small = null)

**Comment by daaner** [comment]
Пул ждем
Кстати, ты ж тоже мог бы ПР сделать? Что помешало?
