### ISSUE TITLE
There are no commands defined in the "admin" namespace. 

### ISSUE THREAD

**Issue by Gorchel** [LaravelRUS/SleepingOwlAdmin#94]
Hello.

When i run commands: php artisan admin:administrators or php artisan admin:install, i get an error
There are no commands defined in the "admin" namespace.  

Help me!

**Comment by butschster** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin#installation

**Comment by Gorchel** [comment]
i add all providers,facades and install adminpanel with the command php artisan sleepingowl:install.
and how can I use commands 
$ php artisan admin:administrators
Create new administrator:

$ php artisan admin:administrators --new
Change password for administrator:

$ php artisan admin:administrators --password
Delete existing administrator:

$ php artisan admin:administrators --delete

Тhanks!

**Comment by bedanadt** [comment]
I have this same problem, it's with the "laravelrus/sleepingowl": "4.*@dev".

**Comment by butschster** [comment]
Use new console command `php artisan sleepingowl:user`.

```
Usage:
  sleepingowl:user [options]

Options:
  -c, --create          Create new user.
  -d, --delete          Delete user.
  -p, --password        Change user password.
```
