### ISSUE TITLE
Переключение табов

### ISSUE THREAD

**Issue by VardanNersesyan** [LaravelRUS/SleepingOwlAdmin#941]
## Версия в композере
5.6.*
## Хочу задать вопрос
Предположим что у меня 3 таба, в каждом из них возможность добавить медиа разного типа
1. images stored as json
2. iframe для 3d тура
3. iframe для vimeo плеера
Вопросы:
1) Есть ли возможность при редактировании одного из item'ов переключить на тот таб в котором поле не пустое? - как реализовать?

**Comment by sngrl** [comment]
Прикручивать свой js-код только:

1. Добавить в пакетный менеджер свой js-файл (в bootstrap.php):
```
PackageManager::add('selectTab')
    ->js('st', asset('js/selectTab.custom.js'), ['admin-default'], true)
;
```

2. Подключить пакет с js-файлом в onEdit секции:
```
Meta::loadPackage(['selectTab']);
```

Аналогичный пример в демке: https://demo.sleepingowladmin.ru/admin/StopPageRefresh
