### ISSUE TITLE
Можно ли добавить страницу просмотра элемента?

### ISSUE THREAD

**Issue by VardanNersesyan** [LaravelRUS/SleepingOwlAdmin#942]
Можно ли добавить страницу просмотра элемента?
допустим в таблице нажал на кнопку и перешел в страницу детализации данного элемента?
Если да то как?

**Comment by sngrl** [comment]
Что подразумевается под страницей просмотра элемента? Каждая сущность может иметь свое назначение, набор полей, и как это все отображать - сова не знает, если ей не сказать ;) Поэтому можно сделать так:

1. В routes.php сделать свой именованный роут под конкретную сущность, например:

`Route::get('company/{$id}/preview', ['as' => 'admin.company.preview', function ($id) {
    $company = \App\Company::find($id);
    $content = view('admin.company_preview', compact('company'));
    return AdminSection::view($content, 'Company preview');
}]);`

2. Добавить кнопку со ссылкой в ControlColumn:

`$display = AdminDisplay::datatablesAsync();
//..........
$button = (new ControlLink(function ($model) {
    return route('admin.company.preview', [$model->id]);
}, '', 100))
    ->setTitle('Предварительный просмотр')
    ->setIcon('fa fa-eye')
    ->setHtmlAttribute('class', 'btn-warning')
    ->setCondition(function () {
        return true;
    })
;
$display->getColumns()->getControlColumn()
    ->addButton($button)
    ->setHtmlAttribute('style', 'white-space:nowrap')
;`
