### ISSUE TITLE
При валидации multiselect - текст сообщения ошибки не подгружается

### ISSUE THREAD

**Issue by BytCoder** [LaravelRUS/SleepingOwlAdmin#961]
Обновил laravel до 5.7
Перестали отображаться сообщения ошибки , при валидации multiselect.

Решение похожей проблемы https://github.com/LaravelRUS/SleepingOwlAdmin/issues/606 не работает.

**Comment by sngrl** [comment]
Предоставьте полный код секции и модели (через gist)

**Comment by BytCoder** [comment]
[multiselect_errors.zip](https://github.com/LaravelRUS/SleepingOwlAdmin/files/2762979/multiselect_errors.zip)

**Comment by BytCoder** [comment]
[multiselect_errors.zip](https://github.com/LaravelRUS/SleepingOwlAdmin/files/2762984/multiselect_errors.zip)

**Comment by BytCoder** [comment]
Переопределили на custom teplate
