### ISSUE TITLE
AdminColumnEditable::checkbox работает не корректно

### ISSUE THREAD

**Issue by Davidnadejdin** [LaravelRUS/SleepingOwlAdmin#963]
*ru*
## Что надо сделать что бы увидеть ошибку?

1.Применить \AdminColumnEditable::checkbox

## Что должно сработать?
1. Должен был появится столбец-чекбокс доступный для редактирования

## Что сработало?
1. Отображает описание просто как текст в зависимости от значения назначего столбца в таблице(true/false)

**Comment by Davidnadejdin** [comment]
Если в секцию добавить
```
public function onEdit($id)
    {
        return false;
    }
```
то начинает работать правильно

**Comment by Davidnadejdin** [comment]
Также для любых других _\AdminColumnEditable_ не создается post роут при отсутствии  метода _onEdit_

**Comment by daaner** [comment]
https://demo.sleepingowladmin.ru/admin/editable-columns

Проблема решена
