### ISSUE TITLE
А воз и ныне там (с)

### ISSUE THREAD

**Issue by mediaceh** [LaravelRUS/SleepingOwlAdmin#965]
Не выводятся ошибки валидации для мультиселекта. Не выводится класс has-error для мультиселекта (Нахерачили местами в шаблоне почти правильно. Вместо того, что бы передать сразу имя без скобок три раза стр реплейс делать надо. На олимпиаде неудачников можно было взять первое место).

При сохранении существующей записи с ошибками валидации в пустых полях оказываются старые значения (надо проверять существование ключа в запросе, а не значение, но с селектом и чекбоксом это проблему не решит). 
Мультиселект своих значений так же не сохраняет при ошибках валидации (на новых записях тоже). На существующей все просто сбрасывается. Видимо эта проблема за два года так и не была решена. Мило (кавычки). 
Это просто гениально - 

         public function getValueFromModel()
         {
            $value = parent::getValueFromModel();
            if (is_array($value)) {
                foreach ($value as $key => $val) {
                    $value[$key] = $val;
                }
            }
    .....
Я считаю это достойно быть в резюме того человека, который это написал.

Куда дели строку поиска у datatables? 

Почему datatables выводит datatablesAsync? Это вообще удивительно. 

PS: Зачем была впендюрена дебильная кнопка для фильтров в datatables, когда и без нее все работало?

**Comment by aios** [comment]
@mediaceh Это OS. У нас не принято высказывать свое мнение по поводу работы, тем более в такой грубой форме. Ты не платишь за этот "продукт" аж ничего.  Проект писался на коленке и не одним разработчиком. Я не думаю что это нуждается в каких то осуждениях или оправданиях. Уверен что если покопаться в твоем белье - то пара грязных шмоток тоже найдется. Мне лично плевать что и в чье резюме ты бы засунул, потому что мне плевать на твое мнение. Не плевать на баг-репорт с твоей стороны и что ты все же пытаешься уделить время, за что спасибо. 

По всему остальному если есть вопросы ты можешь высказать их в телеграм канале. Либо здесь, но без лишней воды и по-пунктно. Я отвечу на каждый правильно заданный вопрос.

**Comment by mediaceh** [comment]
Так и напиши об этом в документации большими буквами - ошибки не исправляются, а только добавляются, документация в актуальном состоянии не поддерживается ,делаю для себе, переименовываю методы на досуге. Не позорься. Чисто русский подход - делать на отъебись, а потом еще в грудь себя бить - да я, да я за бесплатно. Много что бесплатно и одновременно хорошо работает. А если руки кривые - оставь и не трогай. Кому нужно ошибки пофиксят и будут пользоваться.

**Comment by aios** [comment]
@mediaceh Документация, Код, Поддержка таких вот кадров как ты. Все это требует времени. Опенсорс это не работа которая кормит, то есть делается на досуге, а значит еще раз повторю для особо одаренных что не нуждается в осуждении или оправдании. Все очень просто - не нравится не юзай. А раз у тебя руки из правильного места растут - так возьми и все что перечислил сделай - найди время выдели,исправь,а потом разглагольствуй на право и на лево у кого руки не из того места растут. В противном случае просто проходи мимо.
