### ISSUE TITLE
Laravel 5.8 Breadcrumbs::setView does not exist

### ISSUE THREAD

**Issue by stasoft91** [LaravelRUS/SleepingOwlAdmin#969]
## Версия в композере
Сова 5.6.8
Лара 5.8.4

## Что надо сделать что бы увидеть ошибку?
Попытаться открыть любую страницу совы

## Что увидим
Method SleepingOwl\Admin\Templates\Breadcrumbs::setView does not exist. (View: /home/stasoft/www/goodplaces/vendor/laravelrus/sleepingowl/resources/views/default/_layout/inner.blade.php)

Проблема видимо где то около vendor/laravelrus/sleepingowl/src/Templates/Template.php:175

**Comment by RSivakov** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/issues/827#issuecomment-387394209

привет. мне, походу, вот сейчас помогла смена версии по рекомендации по ссылке. (Парус чем-то лет назад была такая же проблема с одной из предыдущих первий лары, хех, пошел завести таску на эту тему и нашел свою таску, почти слово в слово повторяющую то, что хотел написать =)
