### ISSUE TITLE
Laravel\Lumen\Routing\UrlGenerator::__construct() error when unit testing

### ISSUE THREAD

**Issue by fendy3002** [LaravelRUS/SleepingOwlAdmin#97]
I tried to do unit testing a project with sleepingowl. However the test unit does not have any connection anyway. I'm using laravel 5.2, in windows development.

I get the following error:

PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
There was 1 error:

1) Tests\Export\ImageLinksToDbReaderTest::test
ErrorException: Argument 1 passed to Laravel\Lumen\Routing\UrlGenerator::__construct() must be an instance of Laravel\Lumen\Application, instance of Illuminate\Foundation\Application given, called in C:\Users\_\AppData\Roaming\Composer\vendor\laravel\lumen-framework\src\helpers.php:281 and defined

C:\Users\_\AppData\Roaming\Composer\vendor\laravel\lumen-framework\src\Routing\UrlGenerator.php:44
C:\Users\_\AppData\Roaming\Composer\vendor\laravel\lumen-framework\src\helpers.php:281
_\app\Admin\navigation.php:28
_\vendor\laravelrus\sleepingowl\src\Providers\AdminServiceProvider.php:67
_\vendor\laravel\framework\src\Illuminate\Container\Container.php:507
_\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:757
_\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:740
_\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:741
_\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php:17
_\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:203
_\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:219
_\tests\TestCase.php:21
_\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestCase.php:86
_\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestCase.php:65
C:\Users\_\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:154
C:\Users\_\AppData\Roaming\Composer\vendor\phpunit\phpunit\src\TextUI\Command.php:105

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
Complete.

**Comment by butschster** [comment]
refs #131
