### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by Igor5005** [LaravelRUS/SleepingOwlAdmin#973]
Не могу побороть эту ошибку,в чем проблема,подскажите?
1/1) FatalErrorExceptionDeclaration of SleepingOwl\Admin\Navigation\Badge::render() must be compatible with KodiComponents\Navigation\Badge::render($view = NULL)
in Badge.php (line 5)
Сайт на хостинге работает,все ок, перенес на локалку-такая штука появляется.

**Comment by PhpNet** [comment]
окружение совпадает? версии пыхи, лары, пакетов, etc
