### ISSUE TITLE
xss уязвимость

### ISSUE THREAD

**Issue by Krispian** [LaravelRUS/SleepingOwlAdmin#983]
Всем привет!
Если в админке вбить в любое поле 
> <script>alert("XSS");</script>
То оно сработает как миниум в AdminColumn::text и AdminColumn::link, пример можно посмотреть в вашей [демке](https://demo.sleepingowladmin.ru/admin/contacts/10/edit)
На последней dev версии также не закрыта

**Comment by aios** [comment]
Понял - уберем.

**Comment by stasoft91** [comment]
Серьезно? Я уже полтора года думаю, что вы просто за самостоятельную фильтрацию...

**Comment by aios** [comment]
@stasoft91 я просто чет завтыкал с этим когда то давно.

**Comment by daaner** [comment]
Основные убрал, но в кастоме можно продолжать стрелять себе в ногу.
Все не изолируешь

**Comment by daaner** [comment]
Кстати, патч только в ветке БС4
