### ISSUE TITLE
Хлебные крошки, пункты меню

### ISSUE THREAD

**Issue by ifad6** [LaravelRUS/SleepingOwlAdmin#996]
## Что надо сделать что бы увидеть ошибку?

1. Открыть демо
2. Посмотреть как ведут себя хлебные крошки и активный пункт меню в разделах:
— Dashboard \ Content \ News
— Dashboard \ Content \ News 2

## Что должно сработать?
1. Должны отображаться хлебные крошки и активный пункт меню

**Comment by daaner** [comment]
Там слегка запутана система. Это давняя проблема и если все строить правильно - все нормально работает.
Я обновлю пакет, который используется, может такое поведение в нем уже поправлено.
К сожалению это будет только в новой ветке.
В любом случае, если правильно строить навигацию - все отображается нормально

**Comment by daaner** [comment]
![image](https://user-images.githubusercontent.com/9641698/62947030-78e85600-bdea-11e9-875c-a1ea3632b9af.png)
![image](https://user-images.githubusercontent.com/9641698/62947082-91f10700-bdea-11e9-836c-a568a53ad3d0.png)
